const {randomUUID}=require('node:crypto');
const {fail}=require('../../../server/http');
const {text}=require('./validation');
function events({repo,store}){const sql=repo.sql;return ({resource,id,action,method,b,ctx,json})=>{
 if(resource!=='events')return false;const {user,samajId,sec}=ctx;
 const visible=e=>e.samaj_id===samajId&&(e.family_id?sec.can('family.view',repo.get('family',e.family_id,samajId)):sec.grants.some(g=>g.permission==='directory.search'));
 if(method==='GET'&&!id){const items=sql.prepare('SELECT * FROM samaj_events WHERE samaj_id=? ORDER BY starts_at,id LIMIT 500').all(samajId).filter(visible).map(e=>({...e,response:sql.prepare('SELECT response FROM samaj_event_rsvps WHERE event_id=? AND user_id=?').get(e.id,user.id)?.response||'',going:sql.prepare("SELECT count(*) AS n FROM samaj_event_rsvps WHERE event_id=? AND response='Going'").get(e.id).n}));json(200,{items});return true;}
 if(method==='POST'&&!id){sec.require('announcement.create');const title=text(b.title,'Title',120,true),location=text(b.location,'Location',200,true),description=text(b.description,'Description',2000),starts=text(b.startsAt,'Event time',16,true);if(!/^\d{4}-\d{2}-\d{2}T([01]\d|2[0-3]):[0-5]\d$/.test(starts)||!Number.isFinite(Date.parse(starts+'+05:30'))||new Date(starts.slice(0,10)).toISOString().slice(0,10)!==starts.slice(0,10))fail(400,'Enter a valid event time in IST');const family=b.familyId||null;if(family)sec.require('family.view',repo.get('family',family,samajId));const eid=randomUUID();store.transaction(()=>{sql.prepare('INSERT INTO samaj_events(id,samaj_id,title,starts_at,location,description,family_id,created_by) VALUES(?,?,?,?,?,?,?,?)').run(eid,samajId,title,starts,location,description,family,user.id);repo.audit(user,samajId,'event.create',eid,null,{title,starts,family});});json(201,{id:eid});return true;}
 const event=sql.prepare('SELECT * FROM samaj_events WHERE id=? AND samaj_id=?').get(id,samajId);if(!event||!visible(event))fail(404,'Event not found');
 if(method==='POST'&&action==='rsvp'){if(event.cancelled)fail(409,'This event is cancelled');if(!['Going','Maybe','Not going','Clear'].includes(b.response))fail(400,'Choose a valid response');store.transaction(()=>{if(b.response==='Clear')sql.prepare('DELETE FROM samaj_event_rsvps WHERE event_id=? AND user_id=?').run(id,user.id);else sql.prepare('INSERT INTO samaj_event_rsvps VALUES(?,?,?) ON CONFLICT(event_id,user_id) DO UPDATE SET response=excluded.response').run(id,user.id,b.response);});json(200,{ok:true});return true;}
 if(method==='POST'&&action==='cancel'){sec.require('announcement.create');store.transaction(()=>{sql.prepare('UPDATE samaj_events SET cancelled=1 WHERE id=? AND samaj_id=?').run(id,samajId);repo.audit(user,samajId,'event.cancel',id,null,{cancelled:true});});json(200,{ok:true});return true;}fail(405,'Method not allowed');
};}module.exports={events};
