import {scenes,createScene,strike,caption,drawScene} from './scenes.mjs';
import {breathState} from './engine.mjs';
const $=s=>document.querySelector(s),media=matchMedia('(prefers-color-scheme: dark)');$('#theme').outerHTML=SynapseTheme.control('id="theme"');function theme(){const p=SynapseTheme.read();document.documentElement.dataset.theme=p==='system'?(media.matches?'dark':'light'):p;paint();if(currentScene)renderScene();}$('#theme').addEventListener('change',theme);media.addEventListener('change',theme);
let currentScene=null,sceneAnimation=null;const sceneStates=new Map();
let popped=0,sound=false,audio=null,timer=null,started=0,strokes=[],stroke=null,ripples=0;const canvas=$('#garden'),ctx=canvas.getContext('2d');
const quiltNames=['Sky','Leaf','Honey','Lavender','Rose','Sea'];
const chooser=document.createElement('div');chooser.className='actions';chooser.setAttribute('role','group');chooser.setAttribute('aria-label','Choose a break by mood');for(const [label,modes]of [['I want calm',['breathe','sand']],['I want to create',['quilt','sand']],['I want to let it out',['computer','tv','plates','shred','pop']]]){const button=document.createElement('button');button.textContent=label;button.type='button';button.onclick=()=>{const mode=modes[crypto.getRandomValues(new Uint32Array(1))[0]%modes.length];document.querySelector('.modes [data-mode="'+mode+'"]').click();$('#'+(scenes[mode]?'scene':mode)).scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};chooser.append(button);}$('.modes').before(chooser);
let quilt=Array(25).fill(-1),quiltColour=0,quiltHistory=[];
function paintQuilt(){
  $('#quilt-grid').querySelectorAll('button').forEach((tile,i)=>{
    tile.style.background=quilt[i]<0?'var(--surface)':'var(--team-'+quilt[i]+')';
    tile.dataset.colour=String(quilt[i]);
    tile.setAttribute('aria-label','Tile '+(i+1)+': '+(quilt[i]<0?'blank':quiltNames[quilt[i]]));
    tile.textContent=quilt[i]<0?'·':['○','❧','☀','✧','♡','≈'][quilt[i]];
  });
  $('#quilt-undo').disabled=!quiltHistory.length;
}
function rememberQuilt(){quiltHistory.push([...quilt]);if(quiltHistory.length>50)quiltHistory.shift();}
$('#quilt-colours').replaceChildren(...quiltNames.map((name,i)=>{
  const button=document.createElement('button');button.textContent=name;
  button.style.background='var(--team-'+i+')';button.setAttribute('aria-pressed',String(i===quiltColour));
  button.onclick=()=>{quiltColour=i;$('#quilt-colours').querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));$('#quilt-status').textContent=name+' selected. Tap any tile to paint.';};return button;
}));
$('#quilt-grid').replaceChildren(...quilt.map((_,i)=>{
  const tile=document.createElement('button');tile.onclick=()=>{if(quilt[i]===quiltColour)return;rememberQuilt();quilt[i]=quiltColour;paintQuilt();tone();$('#quilt-status').textContent='Tile '+(i+1)+' painted '+quiltNames[quiltColour]+'. Make it your own.';};return tile;
}));
$('#quilt-surprise').onclick=()=>{rememberQuilt();const offset=(quilt.find(x=>x>=0)??-1)+1;quilt=quilt.map((_,i)=>(Math.floor(i/5)+i%5+offset)%6);paintQuilt();$('#quilt-status').textContent='A new woven pattern. Change any tile to make it yours.';};
$('#quilt-undo').onclick=()=>{if(!quiltHistory.length)return;quilt=quiltHistory.pop();paintQuilt();$('#quilt-status').textContent='Last change undone.';};
$('#quilt-clear').onclick=()=>{if(quilt.some(x=>x>=0)){rememberQuilt();quilt.fill(-1);paintQuilt();}$('#quilt-status').textContent='A blank quilt. Ready for your colours.';};paintQuilt();
const quiltExport=document.createElement('button');quiltExport.type='button';quiltExport.id='quilt-export';quiltExport.textContent='Download my quilt';$('#quilt .actions').append(quiltExport);quiltExport.onclick=async()=>{quiltExport.disabled=true;const snapshot=[...quilt];try{const logo=new Image();logo.src='/logo-adaptive-192.png';await logo.decode();const canvas=document.createElement('canvas');canvas.width=600;canvas.height=720;const ctx=canvas.getContext('2d'),styles=getComputedStyle(document.documentElement),colour=token=>styles.getPropertyValue(token).trim();ctx.fillStyle=colour('--surface')||getComputedStyle(document.body).backgroundColor;ctx.fillRect(0,0,600,720);ctx.fillStyle=getComputedStyle(document.body).color;ctx.font='bold 28px sans-serif';ctx.fillText('My little colour quilt',40,52);for(let i=0;i<25;i++){ctx.fillStyle=snapshot[i]<0?colour('--surface'):colour('--team-'+snapshot[i]);ctx.fillRect(40+(i%5)*104,82+Math.floor(i/5)*104,96,96);ctx.strokeStyle=getComputedStyle(document.body).color;ctx.lineWidth=1;ctx.strokeRect(40+(i%5)*104,82+Math.floor(i/5)*104,96,96);ctx.fillStyle=getComputedStyle(document.body).color;ctx.font='32px sans-serif';ctx.textAlign='center';ctx.fillText(snapshot[i]<0?'·':['○','❧','☀','✧','♡','≈'][snapshot[i]],88+(i%5)*104,142+Math.floor(i/5)*104);}ctx.textAlign='left';ctx.drawImage(logo,40,634,42,42);ctx.font='bold 20px sans-serif';ctx.fillText('Sushant Synapse · Pocket Pause',94,652);ctx.font='14px sans-serif';ctx.fillText(location.origin+'/pocket-pause',94,678);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Image export unavailable');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pocket-pause-quilt.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('#quilt-status').textContent='Your branded quilt image is ready.';}catch(error){$('#quilt-status').textContent='Could not export: '+error.message;}finally{quiltExport.disabled=false;}};
$('#sand-undo').onclick=()=>{stroke=null;strokes.pop();paint();$('#status').textContent='Last stroke undone.';};
function tone(){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type='sine';o.frequency.setValueAtTime(420,t);o.frequency.exponentialRampToValueAtTime(120,t+.09);g.gain.setValueAtTime(.08,t);g.gain.exponentialRampToValueAtTime(.001,t+.1);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.11);o.onended=()=>{o.disconnect();g.disconnect();};}catch{sound=false;$('#sound').textContent='Sound unavailable';$('#sound').setAttribute('aria-pressed','false');}}
function pop(b){if(!b?.classList.contains('bubble')||b.getAttribute('aria-pressed')==='true')return;b.setAttribute('aria-pressed','true');b.setAttribute('aria-label',b.dataset.label+' popped');popped++;tone();if(popped===36)$('#status').textContent='Sheet complete. A good moment to return to your day, or choose a fresh sheet.';}
function fresh(){popped=0;$('#bubbles').replaceChildren(...Array.from({length:36},(_,i)=>{const b=document.createElement('button');b.className='bubble';b.dataset.label='Bubble '+(i+1);b.setAttribute('aria-label',b.dataset.label);b.setAttribute('aria-pressed','false');b.onclick=()=>pop(b);return b;}));$('#status').textContent='A fresh sheet is ready.';}$('#fresh').onclick=fresh;$('#bubbles').addEventListener('pointerdown',e=>pop(e.target));$('#bubbles').addEventListener('pointermove',e=>{if(e.buttons===1)pop(document.elementFromPoint(e.clientX,e.clientY));});$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',String(sound));if(sound)tone();else audio?.suspend().catch(()=>{});};
function paint(){$('#sand-undo').disabled=!strokes.length;const css=getComputedStyle(document.documentElement);ctx.fillStyle=css.getPropertyValue('--team-2');ctx.fillRect(0,0,900,540);ctx.strokeStyle=css.getPropertyValue('--muted');ctx.lineWidth=3;ctx.lineCap='round';for(const points of strokes){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));if(points.length===1){ctx.lineTo(points[0][0]+.1,points[0][1]+.1);}ctx.stroke();}}
function point(e){const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(900,(e.clientX-r.left)*900/r.width)),Math.max(0,Math.min(540,(e.clientY-r.top)*540/r.height))];}canvas.onpointerdown=e=>{if(e.button!==0||stroke)return;canvas.setPointerCapture(e.pointerId);stroke=[point(e)];strokes.push(stroke);if(strokes.length>150)strokes.shift();paint();};canvas.onpointermove=e=>{if(!stroke||!canvas.hasPointerCapture(e.pointerId))return;if(stroke.length>=1000)return;const next=point(e),last=stroke[stroke.length-1];if(Math.hypot(next[0]-last[0],next[1]-last[1])<2)return;stroke.push(next);ctx.beginPath();ctx.moveTo(...last);ctx.lineTo(...next);ctx.stroke();};function end(){stroke=null;}canvas.onpointerup=end;canvas.onpointercancel=end;canvas.onlostpointercapture=end;$('#clear').onclick=()=>{strokes=[];stroke=null;ripples=0;paint();$('#status').textContent='A clean patch of sand. Nothing to keep up with.';};$('#ripple').onclick=()=>{for(let ring=1;ring<=5;ring++){const pts=[];for(let a=0;a<=Math.PI*2+.05;a+=.05)pts.push([450+Math.cos(a)*ring*35,270+Math.sin(a)*ring*35]);strokes.push(pts);}strokes=strokes.slice(-150);ripples++;paint();$('#status').textContent='A ripple in the sand. Smooth it whenever you like.';};
function stop(message='Paused. Take the rest of your break your way.'){clearInterval(timer);timer=null;$('#start').disabled=false;$('#stop').disabled=true;$('#circle').classList.remove('expanded');$('#cue').textContent='Ready when you are';$('#remaining').textContent='No breath holds. No targets.';$('#status').textContent=message;}function tick(){const state=breathState(performance.now()-started);if(state.done){stop('One minute complete. A good moment to return to your day.');$('#cue').textContent=state.cue;$('#remaining').textContent='Break complete.';return;}$('#cue').textContent=state.cue;$('#circle').classList.toggle('expanded',state.expanded);$('#remaining').textContent=state.remaining+' seconds remaining';}$('#start').onclick=()=>{stop();started=performance.now();$('#start').disabled=true;$('#stop').disabled=false;$('#status').textContent='A gentle minute. Stop whenever you like.';tick();timer=setInterval(tick,250);};$('#stop').onclick=()=>stop();document.addEventListener('visibilitychange',()=>{if(document.hidden){if(timer)stop('Paused while this tab is away. Start again whenever you like.');audio?.suspend().catch(()=>{});}});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(timer)stop();stroke=null;const selected=b.dataset.mode;for(const mode of ['pop','sand','breathe','quilt'])$('#'+mode).hidden=mode!==selected;$('#scene').hidden=!scenes[selected];if(scenes[selected]){currentScene=sceneStates.get(selected)||createScene(selected);renderScene();}else currentScene=null;$('#pieces').replaceChildren();sceneAnimation?.cancel();document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#status').textContent=b.dataset.mode==='pop'?(popped===36?'Sheet complete. Choose a fresh sheet when you want.':'Pop at your own pace.'):b.dataset.mode==='sand'?'Draw without a goal.':b.dataset.mode==='quilt'?'Choose a colour and tap a tile.':'Ready when you are.';if(currentScene)$('#status').textContent='Fictional props. Tap or use Space to play.';paint();});
function renderScene(){const s=currentScene;drawScene($('#scene-canvas'),s);$('#scene-title').textContent=scenes[s.kind].title;$('#scene-hint').textContent=scenes[s.kind].hint;$('#scene-caption').textContent=caption(s);$('#scene-target').setAttribute('aria-label',scenes[s.kind].verb);$('#scene-target').disabled=s.hits===scenes[s.kind].limit;$('#repair').textContent=s.kind==='shred'?'More pretend memos':s.kind==='plates'?'Restock the shelf':'Rebuild '+(s.kind==='tv'?'TV':'computer');$('#channel').hidden=s.kind!=='tv';sceneStates.set(s.kind,s);}
function burst(x,y){const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)return;$('#pieces').replaceChildren();for(let i=0;i<14;i++){const p=document.createElement('span');p.className='fragment';p.style.left=x*100+'%';p.style.top=y*100+'%';$('#pieces').append(p);const a=i*Math.PI*2/14;const anim=p.animate([{transform:'translate(0,0) rotate(0deg)',opacity:1},{transform:'translate('+Math.cos(a)*90+'px,'+(Math.sin(a)*80+80)+'px) rotate('+i*80+'deg)',opacity:0}],{duration:550,easing:'ease-out'});anim.finished.catch(()=>{}).finally(()=>p.remove());}sceneAnimation?.cancel();sceneAnimation=$('#scene-canvas').animate([{transform:'translateX(0)'},{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],{duration:160});}
$('#scene-target').onclick=e=>{if(!currentScene)return;const r=$('#scene-target').getBoundingClientRect(),keyboard=e.detail===0,x=keyboard ? 0.5 :(e.clientX-r.left)/r.width,y=keyboard ? 0.5 :(e.clientY-r.top)/r.height;const next=strike(currentScene,x,y,keyboard);if(next===currentScene)return;currentScene=next;renderScene();tone();burst(x,y);$('#status').textContent=currentScene.hits===scenes[currentScene.kind].limit?'Scene complete. Rebuild when you want, or take your break back to the day.':caption(currentScene);};$('#repair').onclick=()=>{currentScene=createScene(currentScene.kind);$('#pieces').replaceChildren();sceneAnimation?.cancel();renderScene();$('#status').textContent='Fresh imaginary props. Ready when you are.';};$('#channel').onclick=()=>{if(!currentScene||currentScene.kind!=='tv')return;currentScene={...currentScene,channel:(currentScene.channel+1)%4};renderScene();tone();$('#status').textContent=caption(currentScene);};theme();fresh();
