export const scenes={computer:{name:'Computer meltdown',limit:8,verb:'Bonk the computer',title:'This meeting could have been a bonk.',hint:'Tap the fictional computer. Watch the error messages get increasingly silly.'},tv:{name:'Retro TV tantrum',limit:6,verb:'Bonk the TV',title:'Tonight on absolutely nothing.',hint:'Change the channel, or give this cartoon TV a dramatic send-off.'},plates:{name:'Crockery crash',limit:6,verb:'Break a plate',title:'The dishes can wait. These cannot.',hint:'Tap a plate to turn it into colourful pieces. Space breaks the next plate.'},shred:{name:'Inbox shredder',limit:5,verb:'Shred a pretend memo',title:'Please find attached: confetti.',hint:'Five fictional office memos. Feed them to the shredder, one at a time.'}};
export const memos=['URGENT: another meeting','Kindly do the needful','Quick call? 90 minutes','Reply all: noted, thanks','Final_FINAL_v27.doc'];
export const channels=['BREAKING: cat takes a nap','Weather: 100% chance of chai','LIVE: a plant growing slowly','SPORT: competitive sofa sitting'];
export function createScene(kind){if(!scenes[kind])throw new Error('Unknown scene');return {kind,hits:0,marks:[],broken:[],channel:0};}
export function strike(state,x=.5,y=.5,keyboard=false){if(!scenes[state.kind]||!Number.isFinite(x)||!Number.isFinite(y))throw new Error('Invalid scene input');const limit=scenes[state.kind].limit;if(state.hits>=limit)return state;let index=Math.max(0,Math.min(5,Math.floor(x*6)));if(state.kind==='plates'){if(keyboard)index=Array.from({length:6},(_,i)=>i).find(i=>!state.broken.includes(i));if(state.broken.includes(index))return state;}return {...state,hits:state.hits+1,marks:[...state.marks,{x:Math.max(.05,Math.min(.95,x)),y:Math.max(.08,Math.min(.88,y))}],broken:state.kind==='plates'?[...state.broken,index]:state.broken};}
export function caption(s){if(s.hits>=scenes[s.kind].limit)return s.kind==='shred'?'Inbox zero. Confetti achieved.':s.kind==='plates'?'Every plate is now modern art.':'Spectacularly out of service.';if(s.kind==='computer')return ['Loading your patience...','Error 404: motivation not found','Update scheduled for yesterday','Too many tabs. Same.','Have you tried turning meetings off?','Keyboard has left the chat','Please contact the imaginary IT desk','One last bonk?'][s.hits];if(s.kind==='tv')return channels[s.channel%channels.length];if(s.kind==='shred')return memos[s.hits];return 'A tiny, colourful crash.';}
export function drawScene(canvas,s){const c=canvas.getContext('2d'),style=getComputedStyle(document.documentElement),color=n=>style.getPropertyValue(n).trim();const palette=[color('--team-0'),color('--team-1'),color('--team-3'),color('--team-4')];const box=(x,y,w,h,r,fill)=>{c.fillStyle=fill;c.beginPath();c.roundRect(x,y,w,h,r);c.fill();};const text=(t,x,y,size=24)=>{c.fillStyle=color('--text');c.font='600 '+size+'px Segoe UI,Arial,sans-serif';c.textAlign='center';c.fillText(t,x,y,820);};c.clearRect(0,0,900,540);box(0,0,900,540,20,color('--soft'));c.strokeStyle=color('--line');c.lineWidth=2;for(let y=440;y<540;y+=22){c.beginPath();c.moveTo(0,y);c.lineTo(900,y);c.stroke();}
if(s.kind==='computer'){box(145,50,610,350,22,color('--muted'));box(165,70,570,305,12,color('--team-0'));box(420,400,60,45,8,color('--muted'));box(330,439,240,18,8,color('--muted'));box(220,470,460,42,10,color('--surface'));for(let k=0;k<18;k++)box(232+k*24,480,17,15,3,color('--line'));text(s.hits===8?'OFFLINE / FINALLY':'SYNAPSE OS / VERY TIRED',450,130,21);text(caption(s),450,230,25);text(s.hits===8?'Your cartoon computer has clocked out.':'Click anywhere. Absolutely imaginary hardware.',450,307,17);}
if(s.kind==='tv'){c.strokeStyle=color('--muted');c.lineWidth=8;c.beginPath();c.moveTo(450,80);c.lineTo(350,20);c.moveTo(450,80);c.lineTo(550,20);c.stroke();box(130,90,640,360,36,color('--muted'));box(155,115,510,305,35,palette[s.channel%4]);for(let i=0;i<5;i++)box(175+i*94,130,80,48,4,palette[(i+s.channel)%4]);box(685,150,55,55,28,color('--surface'));box(685,235,55,55,28,color('--surface'));text(s.hits===6?'END OF BROADCAST':'CHANNEL '+(s.channel+1),405,223,25);text(caption(s),405,280,19);box(180,450,65,28,6,color('--muted'));box(655,450,65,28,6,color('--muted'));}
if(s.kind==='plates'){for(let i=0;i<6;i++){const x=75+i*150;box(x-68,352,136,15,4,color('--muted'));if(!s.broken.includes(i)){c.fillStyle=palette[i%4];c.beginPath();c.ellipse(x,246,60,94,0,0,Math.PI*2);c.fill();c.strokeStyle=color('--accent');c.lineWidth=3;c.beginPath();c.ellipse(x,246,42,73,0,0,Math.PI*2);c.stroke();text(String(i+1),x,253,24);}else{for(let j=0;j<6;j++){c.fillStyle=palette[i%4];c.beginPath();c.moveTo(x-58+j*20,410+j%2*20);c.lineTo(x-40+j*20,435+j%2*20);c.lineTo(x-64+j*20,447+j%2*20);c.fill();}}}text('THE TOTALLY REPLACEABLE COLLECTION',450,75,20);text(caption(s),450,505,22);}
if(s.kind==='shred'){box(230,280,440,190,20,color('--muted'));box(250,300,400,20,6,color('--text'));box(330,85,240,218,8,color('--surface'));text('OFFICE MEMO',450,130,20);text(s.hits===5?'ALL DONE':memos[s.hits],450,200,18);for(let i=0;i<9;i++){box(285+i*38,340,17,65+(i%3)*15,3,palette[(i+s.hits)%4]);}text(s.hits===5?'INBOX ZERO':'SHRED / REPEAT IF YOU LIKE',450,510,21);}
if(s.kind==='computer'||s.kind==='tv'){c.strokeStyle=color('--text');c.lineWidth=2;for(const [i,m] of s.marks.entries()){const x=155+m.x*500,y=110+m.y*260;for(let j=0;j<5;j++){const a=j*Math.PI*2/5+i;c.beginPath();c.moveTo(x,y);c.lineTo(x+Math.cos(a)*35,y+Math.sin(a)*35);c.lineTo(x+Math.cos(a+.2)*58,y+Math.sin(a+.2)*58);c.stroke();}}}if(s.hits===scenes[s.kind].limit){box(275,15,350,42,12,color('--surface'));text('BREAK COMPLETE / YOUR CALL',450,44,18);}}
