import {setTheme} from '../../../tests/browser-theme.js';
import {test,expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
let child,base,dir;
test('help and sample downloads preserve work; complete browser state survives reopening and backup restore',async({page,context})=>{
 page.on('dialog',d=>d.accept());await page.goto(base+'/timetable-lite');
 await page.getByLabel('Institute name',{exact:true}).fill('My retained institute');await page.getByRole('button',{name:'Save institute & days'}).click();
 const before=await page.evaluate(()=>localStorage.getItem('synapse-timetable-lite-v1'));
 await page.locator('#help summary').click();
 let event=page.waitForEvent('download');await page.locator('#help-download').click();const guide=await event;expect(fs.readFileSync(await guide.path(),'utf8')).toContain('Unsubmitted form entries');
 event=page.waitForEvent('download');await page.locator('#sample-download').click();const sample=await event;const bytes=fs.readFileSync(await sample.path());const setup=JSON.parse(bytes);
 expect(await page.evaluate(()=>localStorage.getItem('synapse-timetable-lite-v1'))).toBe(before);
 const {validateEntries}=await import('../frontend/engine.js');expect(validateEntries(setup,setup.entries)).toEqual([]);expect(setup.entries).toHaveLength(20);
 setup.holidays=[{id:'h1',date:'2026-10-02',name:'Sample holiday'}];setup.institute.logo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
 await page.locator('#import').setInputFiles({name:'sample.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(setup))});await expect(page.locator('#message')).toContainText('Backup imported');
 await page.close();const reopened=await context.newPage();await reopened.goto(base+'/timetable-lite');
 expect(await reopened.evaluate(()=>JSON.parse(localStorage.getItem('synapse-timetable-lite-v1')))).toEqual(setup);
 await expect(reopened.getByLabel('Institute name',{exact:true})).toHaveValue('Sample Academy');await expect(reopened.locator('#workspace')).toContainText('Short break');
 await reopened.locator('#steps [data-step="1"]').click();await expect(reopened.locator('#workspace')).toContainText('Class 7');await reopened.locator('#steps [data-step="5"]').click();await expect(reopened.locator('.timetable')).toBeVisible();
 event=reopened.waitForEvent('download');await reopened.locator('#backup').click();const backup=await event;expect(JSON.parse(fs.readFileSync(await backup.path(),'utf8'))).toEqual(setup);
 await reopened.locator('#help summary').click();await reopened.setViewportSize({width:320,height:850});expect(await reopened.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('corrupt storage is preserved and quota failure leaves an exportable setup',async({page})=>{
 await page.goto(base+'/timetable-lite');await page.evaluate(()=>localStorage.setItem('synapse-timetable-lite-v1','broken JSON'));await page.reload();await expect(page.locator('#message')).toContainText('has not been overwritten');
 await page.getByLabel('Institute name',{exact:true}).fill('Recovery');await page.getByRole('button',{name:'Save institute & days'}).click();expect(await page.evaluate(()=>localStorage.getItem('synapse-timetable-lite-v1'))).toBe('broken JSON');await expect(page.locator('#save-status')).toContainText('Saving paused');
 await page.evaluate(()=>localStorage.removeItem('synapse-timetable-lite-v1'));await page.reload();await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError');};});
 await page.getByLabel('Institute name',{exact:true}).fill('Unsaved but recoverable');await page.getByRole('button',{name:'Save institute & days'}).click();await expect(page.locator('#save-status')).toContainText('Not saved');
 const event=page.waitForEvent('download');await page.locator('#backup').click();const backup=await event;expect(JSON.parse(fs.readFileSync(await backup.path(),'utf8')).institute.name).toBe('Unsaved but recoverable');
});
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-timetable-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timeout')),15000);child.stdout.on('data',c=>{out+=c;const m=out.match(/localhost:(\d+)/);if(m){base='http://127.0.0.1:'+m[1];clearTimeout(timer);resolve();}});child.once('error',reject);});});
test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});
test('complete anonymous setup, real generation, editing, persistence, exports and responsive views',async({page})=>{
 const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));page.on('dialog',d=>d.accept());await page.goto(base+'/timetable-lite');
 await page.getByLabel('Institute name',{exact:true}).fill('Synapse Academy');await page.getByRole('button',{name:'Save institute & days'}).click();await page.getByRole('button',{name:'Build periods',exact:true}).click();await expect(page.locator('tbody tr')).toHaveCount(9);
 await page.getByRole('button',{name:'Continue to Classes'}).click();for(const name of ['Class 6','Class 7']){await page.getByLabel('Class / batch name').fill(name);await page.getByLabel('Section (optional)').fill('A');await page.getByRole('button',{name:'Add class',exact:true}).click();}
 await page.getByRole('button',{name:'Continue to Subjects'}).click();for(const name of ['Mathematics','English']){await page.getByLabel('Subject name').fill(name);await page.getByRole('button',{name:'Add subject',exact:true}).click();}
 await page.getByRole('button',{name:'Continue to Teachers'}).click();for(const [name,sub] of [['Mr. Shah','Mathematics'],['Mrs. Patel','English']]){await page.getByLabel('Teacher name').fill(name);await page.getByLabel(sub,{exact:true}).check();await page.getByRole('button',{name:'Add teacher',exact:true}).click();}
 await page.getByRole('button',{name:'Continue to Allocation'}).click();for(const cls of ['Class 6 · A','Class 7 · A'])for(const sub of ['Mathematics','English']){await page.getByLabel('Class / batch',{exact:true}).selectOption({label:cls});await page.getByLabel('Subject',{exact:true}).selectOption({label:sub});await page.getByLabel('Teacher',{exact:true}).selectOption({label:sub==='Mathematics'?'Mr. Shah':'Mrs. Patel'});await page.getByRole('button',{name:'Add allocation',exact:true}).click();}
 await page.getByRole('button',{name:'Continue to Generate'}).click();await page.getByRole('button',{name:'Generate timetable',exact:true}).click();await expect(page.locator('#message')).toContainText('Timetable generated',{timeout:20000});await expect(page.locator('.timetable')).toBeVisible();
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('synapse-timetable-lite-v1')));expect(saved.entries).toHaveLength(20);await page.locator('[data-cell][draggable]').first().click();await page.locator('[data-cell].selected').click();await expect(page.locator('#message')).toContainText('All constraints still pass');await page.getByRole('button',{name:'Undo last adjustment'}).click();
 for(const mode of ['teacher','master','class']){await page.locator('#view').selectOption(mode);if(mode==='master')await page.locator('#workspace details summary').first().click();await expect(page.locator('.timetable').first()).toBeVisible();}
 await page.getByLabel('Calendar week').fill('2026-09-28');for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await setTheme(page,'light');await page.screenshot({path:'test-results/timetable-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await setTheme(page,'dark');await page.screenshot({path:'test-results/timetable-mobile.png',fullPage:true});
 for(const [button,ext] of [['Download PDF','pdf'],['Download image','png'],['Export backup','json']]){const promise=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const dl=await promise;await dl.saveAs('test-results/timetable.'+ext);const bytes=fs.readFileSync('test-results/timetable.'+ext);if(ext==='pdf'){expect(bytes.subarray(0,8).toString()).toBe('%PDF-1.4');expect(bytes.toString('latin1')).toContain('/Count 1');}if(ext==='png')expect(bytes.readUInt32BE(16)).toBe(2380);}
 await page.locator('#scope').selectOption('classes');for(const [button,ext] of [['Download PDF','pdf'],['Download image','zip']]){const event=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const dl=await event;await dl.saveAs('test-results/timetable-all.'+ext);const bytes=fs.readFileSync('test-results/timetable-all.'+ext);if(ext==='pdf')expect(bytes.toString('latin1')).toContain('/Count 2');else expect(bytes.readUInt32LE()).toBe(0x04034b50);}
 await page.evaluate(()=>{window.print=()=>{};});await page.getByRole('button',{name:'Print',exact:true}).click();await expect(page.locator('#print-area .print-sheet')).toHaveCount(2);await page.emulateMedia({media:'print'});await expect(page.locator('body>header')).toBeHidden();await page.pdf({path:'test-results/timetable-print.pdf',preferCSSPageSize:true});await page.emulateMedia({media:'screen'});
 await page.reload();await page.locator('[data-step="5"]').click();await expect(page.locator('.timetable')).toBeVisible();await page.locator('#import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});await expect(page.locator('#message')).toContainText('Backup not imported');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('synapse-timetable-lite-v1')).entries.length)).toBe(20);
 await page.locator('#import').setInputFiles('test-results/timetable.json');await expect(page.locator('#message')).toContainText('Backup imported');expect(errors).toEqual([]);expect(requests.filter(x=>x.includes('/api/'))).toEqual([]);expect((await page.request.get(base+'/api/state')).status()).toBe(401);
});
test('preflight failures, availability restrictions, holiday display and setup invalidation',async({page})=>{
 page.on('dialog',d=>d.accept());await page.goto(base+'/timetable-lite');await page.locator('[data-step="5"]').click();await page.getByRole('button',{name:'Generate timetable',exact:true}).click();await expect(page.locator('#message')).toContainText('Unable to satisfy all timetable constraints.');
 const {emptySetup,makePeriods}=await import('../frontend/engine.js');const setup=emptySetup();setup.institute.name='Test Institute';setup.periods=makePeriods('08:00','12:00',45);setup.classes=[{id:'c1',name:'Class 6',section:'A'}];setup.subjects=[{id:'s1',name:'Mathematics',core:true}];setup.teachers=[{id:'t1',name:'Mr. Shah',subjects:['s1'],days:setup.days,periods:[]}];setup.allocations=[{id:'a1',classId:'c1',subjectId:'s1',teacherId:'t1',weekly:5,daily:1,double:false}];setup.holidays=[{id:'holiday',date:'2026-09-28',name:'Institute holiday'}];setup.teachers[0].days=[];setup.entries=[];await page.locator('#import').setInputFiles({name:'setup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(setup))});await page.locator('[data-step="5"]').click();await expect(page.locator('#workspace')).toContainText('available for only 0');await page.getByRole('button',{name:'Generate timetable',exact:true}).click();await expect(page.locator('#message')).toContainText('Mr. Shah');
 setup.teachers[0].days=setup.days;await page.locator('#import').setInputFiles({name:'setup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(setup))});await page.locator('[data-step="5"]').click();await page.getByRole('button',{name:'Generate timetable',exact:true}).click();await expect(page.locator('.timetable')).toBeVisible();await page.getByLabel('Calendar week').fill('2026-09-28');await expect(page.locator('.timetable thead')).toContainText('Institute holiday');await page.locator('[data-step="1"]').click();await page.getByRole('button',{name:'Edit',exact:true}).first().click();await page.getByLabel('Class / batch name').fill('Updated Class');await page.getByRole('button',{name:'Save class',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('synapse-timetable-lite-v1')).entries)).toEqual([]);
});
