const {test,expect}=require('@playwright/test');const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');let child,base,dir;
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-mixer-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timed out')),15000);child.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve();}});child.once('error',reject);});});test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});

test('colour quilt supports touch, keyboard, undo, patterns and per-mode state without APIs',async({page})=>{
 const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});
 await page.setViewportSize({width:320,height:850});await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+'/pocket-pause');
 await page.locator('[data-mode=quilt]').click();await expect(page.locator('#pop')).toBeHidden();await expect(page.locator('#quilt-grid button')).toHaveCount(25);
 await page.getByRole('button',{name:'Rose',exact:true}).click();await page.getByRole('button',{name:'Tile 1: blank',exact:true}).focus();await page.keyboard.press('Space');
 await expect(page.getByRole('button',{name:'Tile 1: Rose',exact:true})).toBeVisible();
 await page.locator('[data-mode=computer]').click();await expect(page.locator('#quilt')).toBeHidden();await page.locator('[data-mode=quilt]').click();await expect(page.getByRole('button',{name:'Tile 1: Rose',exact:true})).toBeVisible();
 await page.locator('#quilt-undo').click();await expect(page.getByRole('button',{name:'Tile 1: blank',exact:true})).toBeVisible();
 await page.locator('#quilt-surprise').click();await expect(page.locator('#quilt-grid button[data-colour="-1"]')).toHaveCount(0);
 await page.locator('#quilt-clear').click();await expect(page.locator('#quilt-grid button[data-colour="-1"]')).toHaveCount(25);
 await page.locator('#quilt-undo').click();await expect(page.locator('#quilt-grid button[data-colour="-1"]')).toHaveCount(0);
 const box=await page.locator('#quilt-grid button').first().boundingBox();expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);
 await page.locator('#theme').click();await page.locator('#quilt-grid').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/pocket-quilt-mobile.png'});
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.locator('[data-mode=sand]').click();const blank=await page.locator('#garden').evaluate(c=>c.toDataURL());await page.locator('#ripple').click();await page.locator('#sand-undo').click();expect(await page.locator('#garden').evaluate(c=>c.toDataURL())).not.toBe(blank);await page.locator('#clear').click();await expect(page.locator('#sand-undo')).toBeDisabled();
 await page.reload();await page.locator('[data-mode=quilt]').click();await expect(page.locator('#quilt-grid button[data-colour="-1"]')).toHaveCount(25);expect(errors).toEqual([]);expect(api).toEqual([]);
});
test('three quiet modes, keyboard pop, bounded break and mobile themes without APIs',async({page})=>{
const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});await page.goto(base+'/pocket-pause');await expect(page.locator('.bubble')).toHaveCount(36);await expect(page.locator('#sound')).toHaveAttribute('aria-pressed','false');await page.locator('.bubble').first().focus();await page.keyboard.press('Space');await expect(page.locator('.bubble').first()).toHaveAttribute('aria-pressed','true');for(const b of await page.locator('.bubble').all())await b.click();await expect(page.locator('#status')).toContainText('Sheet complete');await page.locator('#fresh').click();await expect(page.locator('.bubble[aria-pressed=true]')).toHaveCount(0);
await page.locator('#sound').click();await expect(page.locator('#sound')).toHaveAttribute('aria-pressed','true');await page.locator('.bubble').first().click();await page.locator('#sound').click();await expect(page.locator('#sound')).toHaveAttribute('aria-pressed','false');await page.locator('[data-mode=sand]').click();await page.locator('#ripple').click();const filled=await page.locator('#garden').evaluate(c=>c.toDataURL());await page.locator('#clear').click();expect(await page.locator('#garden').evaluate(c=>c.toDataURL())).not.toBe(filled);await page.locator('#garden').scrollIntoViewIfNeeded();const box=await page.locator('#garden').boundingBox();await page.mouse.move(box.x+30,box.y+30);await page.mouse.down();await page.mouse.move(box.x+130,box.y+100,{steps:10});await page.mouse.up();const drawn=await page.locator('#garden').evaluate(c=>c.toDataURL());await page.locator('#clear').click();expect(await page.locator('#garden').evaluate(c=>c.toDataURL())).not.toBe(drawn);
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-mode=breathe]').click();await page.clock.install();await page.locator('#start').click();await expect(page.locator('#start')).toBeDisabled();await expect(page.locator('#cue')).toHaveText('Gently breathe in');await page.clock.runFor(4100);await expect(page.locator('#cue')).toHaveText('Gently breathe out');await page.clock.runFor(57000);await expect(page.locator('#status')).toContainText('One minute complete');await expect(page.locator('#start')).toBeEnabled();await expect(page.locator('#stop')).toBeDisabled();await page.locator('#start').click();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.locator('#status')).toContainText('tab is away');await page.evaluate(()=>{delete document.hidden;});await page.locator('#start').click();await page.locator('#stop').click();await expect(page.locator('#status')).toContainText('Paused');await page.locator('#start').click();await page.locator('[data-mode=pop]').click();await expect(page.locator('#stop')).toBeDisabled();
await page.locator('#theme').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/pocket-pause-mobile.png',fullPage:true});await page.reload();await expect(page.locator('.bubble[aria-pressed=true]')).toHaveCount(0);expect(api).toEqual([]);expect(errors).toEqual([]);
});

test('four creative props, channels, touch and keyboard hits, resets, finite scenes and reduced motion',async({page})=>{
const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});await page.route('**/api/**',r=>r.abort());await page.goto(base+'/pocket-pause');await expect(page.locator('[data-mode]')).toHaveCount(8);
for(const [kind,limit] of [['computer',8],['tv',6],['plates',6],['shred',5]]){await page.locator('[data-mode='+kind+']').click();await expect(page.locator('#scene')).toBeVisible();await expect(page.locator('#pop')).toBeHidden();await expect(page.locator('#sound')).toBeVisible();const first=await page.locator('#scene-canvas').evaluate(c=>c.toDataURL());if(kind==='tv'){const before=await page.locator('#scene-caption').textContent();await page.locator('#channel').click();expect(await page.locator('#scene-caption').textContent()).not.toBe(before);}for(let i=0;i<limit;i++){await page.locator('#scene-target').focus();await page.keyboard.press('Space');}await expect(page.locator('#scene-target')).toBeDisabled();await expect(page.locator('#status')).toContainText('Scene complete');expect(await page.locator('#scene-canvas').evaluate(c=>c.toDataURL())).not.toBe(first);await page.locator('#repair').click();await expect(page.locator('#scene-target')).toBeEnabled();await expect(page.locator('#status')).toContainText('Fresh imaginary');}
await page.locator('[data-mode=plates]').click();await page.locator('#scene-target').click({position:{x:10,y:100}});const once=await page.locator('#scene-canvas').evaluate(c=>c.toDataURL());await page.locator('#scene-target').click({position:{x:10,y:100}});expect(await page.locator('#scene-canvas').evaluate(c=>c.toDataURL())).toBe(once);await page.locator('[data-mode=computer]').click();await page.locator('#scene-target').click();await page.waitForTimeout(700);await expect(page.locator('.fragment')).toHaveCount(0);await page.locator('[data-mode=tv]').click();await page.locator('[data-mode=computer]').click();await expect(page.locator('#scene-caption')).toContainText('motivation');
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#scene-target').click();await expect(page.locator('.fragment')).toHaveCount(0);await page.locator('#theme').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');for(const kind of ['computer','tv','plates','shred']){await page.locator('[data-mode='+kind+']').click();for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/pocket-pause-'+kind+'.png',fullPage:true});}await page.reload();await page.locator('[data-mode=computer]').click();await expect(page.locator('#scene-caption')).toHaveText('Loading your patience...');expect(errors).toEqual([]);expect(api).toEqual([]);
});
