import {guides,categories,sources,scope,guideById,findGuides,checklistText} from './guides.mjs?v=20261010-mourning';
const $=s=>document.querySelector(s),p=new URLSearchParams(location.search),checks=new Map();
let language=p.get('lang')==='hi'?'hi':'en',selected=guideById(p.get('guide')),category='all';
const words={en:{eyebrow:'RITUAL ASSIST / HINDU PREPARATION',headline:'Prepare with clarity.\nObserve with care.',intro:'A little guidance for celebrations, family ceremonies and moments of remembrance.',language:'Guide language',choose:'Choose a ritual',search:'Find a ceremony or item',privacy:'Checks stay in this tab only. Refresh clears them. Download or print to keep a copy.',copyFallback:'Copy this text',steps:'Suggested sequence',items:'Materials to arrange',itemHelp:'A starting list, not a shopping prescription. Confirm quantities and who supplies each item.',confirm:'Confirm first',variation:'Family customs & practical care',ask:'Ask your priest / family',references:'Sources & scope',download:'Download checklist',copy:'Copy checklist',share:'Share guide',print:'Print / Save PDF',reset:'Reset checks',count:'arranged',empty:'No matching guides. Try another word or category.',downloaded:'Checklist downloaded.',copied:'Checklist copied.',shared:'Guide shared.',fallback:'Copy the text below.',printNote:'Print dialog opened. Choose Save as PDF to keep a copy.',cancelled:'Sharing cancelled.',link:'Guide link copied.',resetNote:'Checks reset for this guide.'},hi:{eyebrow:'रिचुअल असिस्ट / हिन्दू अनुष्ठान की तैयारी',headline:'स्पष्ट तैयारी।\nश्रद्धा से पालन।',intro:'उत्सव, पारिवारिक संस्कार और स्मरण के अवसरों के लिए सरल मार्गदर्शन।',language:'मार्गदर्शिका की भाषा',choose:'अनुष्ठान चुनें',search:'अनुष्ठान या सामग्री खोजें',privacy:'चेक केवल इस टैब में रहते हैं। रिफ्रेश से मिट जाते हैं। प्रति रखने के लिए डाउनलोड या प्रिंट करें।',copyFallback:'यह पाठ कॉपी करें',steps:'सुझाया गया क्रम',items:'सामग्री की तैयारी',itemHelp:'यह आरंभिक सूची है, खरीदारी का निर्देश नहीं। मात्रा और सामग्री कौन देगा, पूछें।',confirm:'पहले पुष्टि करें',variation:'पारिवारिक रीति और व्यावहारिक ध्यान',ask:'पुरोहित / परिवार से पूछें',references:'संदर्भ और दायरा',download:'सूची डाउनलोड करें',copy:'सूची कॉपी करें',share:'मार्गदर्शिका साझा करें',print:'प्रिंट / PDF रखें',reset:'चेक हटाएँ',count:'तैयार',empty:'कोई मार्गदर्शिका नहीं मिली। दूसरा शब्द या श्रेणी चुनें।',downloaded:'सूची डाउनलोड हुई।',copied:'सूची कॉपी हुई।',shared:'मार्गदर्शिका साझा हुई।',fallback:'नीचे का पाठ कॉपी करें।',printNote:'प्रिंट संवाद खुला। प्रति रखने के लिए PDF चुनें।',cancelled:'साझा करना रद्द हुआ।',link:'मार्गदर्शिका का लिंक कॉपी हुआ।',resetNote:'इस मार्गदर्शिका के चेक हटाए गए।'}};
const text=k=>words[language][k],node=(tag,className='',value='')=>{const el=document.createElement(tag);el.className=className;el.textContent=value;return el;};
function checked(){if(!checks.has(selected.id))checks.set(selected.id,new Set());return checks.get(selected.id);}
function theme(){const choice=window.SynapseTheme.read();document.documentElement.dataset.theme=choice==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):choice;}
$('#theme').outerHTML=window.SynapseTheme.control('id="theme"');$('#theme').addEventListener('change',theme);matchMedia('(prefers-color-scheme: dark)').addEventListener('change',theme);addEventListener('storage',theme);theme();
function url(){const u=new URL('/ritual-assist',location.origin);u.searchParams.set('guide',selected.id);u.searchParams.set('lang',language);return u;}
function syncUrl(){history.replaceState(null,'',url());}
function translations(){document.documentElement.lang=language;$('#language').value=language;document.querySelectorAll('[data-copy]').forEach(e=>{if(e.dataset.copy==='headline'){const parts=text('headline').split('\n');e.replaceChildren(document.createTextNode(parts[0]),document.createElement('br'),node('em','',parts[1]));}else e.textContent=text(e.dataset.copy);});$('#language').setAttribute('aria-label',text('language'));$('#filters').setAttribute('aria-label',language==='hi'?'मार्गदर्शिका श्रेणी':'Guide categories');$('#scope').textContent=scope[language];$('#guide-count').textContent=String(guides.length);}
function renderList(){const rows=findGuides({category,query:$('#search').value});$('#filters').replaceChildren(...Object.entries(categories).map(([id,label])=>{const b=node('button','',label[language]);b.type='button';b.dataset.category=id;b.setAttribute('aria-pressed',String(category===id));b.onclick=()=>{category=id;renderList();$('#filters [data-category='+id+']').focus();};return b;}));$('#results').textContent=rows.length?(language==='hi'?`${rows.length} मार्गदर्शिकाएँ`:`${rows.length} guides`):text('empty');$('#guide-list').replaceChildren(...rows.map(g=>{const b=node('button','guide-option');b.type='button';b.dataset.guide=g.id;b.setAttribute('aria-pressed',String(g.id===selected.id));b.append(node('strong','',g.title[language]),node('small','',g.summary[language]));b.onclick=()=>{selected=g;$('#status').textContent='';$('#copy-fallback').hidden=true;renderList();renderGuide();syncUrl();if(innerWidth<=760)$('#library').open=false;$('#guide-title').focus();};return b;}));}
function progress(){const n=checked().size,total=selected.items.length;$('#progress').textContent=`${n} / ${total} ${text('count')}`;$('#item-progress').value=n;}
async function copy(value,message){try{if(navigator.clipboard){await navigator.clipboard.writeText(value);$('#status').textContent=message;return;}}catch{}$('#copy-fallback').hidden=false;$('#copy-text').value=value;$('#copy-text').focus();$('#copy-text').select();$('#status').textContent=text('fallback');}
function renderGuide(){const root=$('#guide');root.replaceChildren();const top=node('div','guide-top');top.append(node('span','badge'+(selected.category==='ashubh'?' calm':''),categories[selected.category][language]));const title=node('h2','',selected.title[language]);title.id='guide-title';title.tabIndex=-1;top.append(title,node('p','',selected.summary[language]));const actions=node('div','actions');
 const action=(label,id,fn,primary=false)=>{const b=node('button',primary?'primary':'',text(label));b.id=id;b.type='button';b.onclick=fn;actions.append(b);};
 action('download','download',()=>{const blob=new Blob(['\uFEFF'+checklistText(selected,language,checked())],{type:'text/plain;charset=utf-8'}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=`ritual-assist-${selected.id}-${language}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(href),60000);$('#status').textContent=text('downloaded');},true);
 action('copy','copy',()=>copy(checklistText(selected,language,checked()),text('copied')));
 action('share','share',async()=>{const message=`${selected.title[language]} · Ritual Assist\n${url().href}`;if(navigator.share){try{await navigator.share({title:'Ritual Assist',text:message,url:url().href});$('#status').textContent=text('shared');return;}catch(e){if(e.name==='AbortError'){$('#status').textContent=text('cancelled');return;}}}await copy(message,text('link'));});
 action('print','print',()=>{window.print();$('#status').textContent=text('printNote');});top.append(actions);root.append(top);
 const content=node('div','guide-content'),sequence=node('section','card');sequence.append(node('h3','',text('steps')));const steps=node('ol','steps');steps.append(...selected.steps.map(s=>node('li','',s[language])));sequence.append(steps);
 const materials=node('section','card');materials.append(node('h3','',text('items')),node('p','fine',text('itemHelp')),node('p','fine',selected.materialReview[language]));const progressRow=node('div','progress-row'),count=node('span');count.id='progress';const reset=node('button','',text('reset'));reset.type='button';reset.id='reset';reset.onclick=()=>{checked().clear();materials.querySelectorAll('input').forEach(input=>input.checked=false);progress();$('#status').textContent=text('resetNote');};progressRow.append(count,reset);const bar=node('progress');bar.id='item-progress';bar.max=selected.items.length;bar.setAttribute('aria-label',text('items'));materials.append(progressRow,bar);
 const list=node('div','checklist');list.append(...selected.items.map(item=>{const label=node('label','check-item'),input=node('input');input.type='checkbox';input.dataset.item=item.id;input.checked=checked().has(item.id);input.setAttribute('aria-label',item.label[language]);input.onchange=()=>{if(input.checked)checked().add(item.id);else checked().delete(item.id);progress();};const body=node('span');if(item.group)body.append(node('small','item-kind',item.group[language]));body.append(node('strong','',item.label[language]));if(item.kind==='confirm')body.append(node('small','item-kind',text('confirm')));if(item.note[language])body.append(node('small','',item.note[language]));label.append(input,body);return label;}));materials.append(list);content.append(sequence,materials);root.append(content);
 for(const section of selected.sections||[]){const panel=node('section','card variation');panel.append(node('h3','',section.title[language]),node('p','',section.body[language]));root.append(panel);}
 const variation=node('section','card variation');variation.append(node('h3','',text('variation')),node('p','',selected.variation[language]),node('p','',selected.preparation[language]),node('h3','',text('ask')));const questions=node('ul');questions.append(...selected.questions.map(q=>node('li','fine',q[language])));variation.append(questions);root.append(variation);
 const refs=node('details','reference');refs.append(node('summary','',text('references')));const ul=node('ul');ul.append(...selected.sources.map(id=>{const source=sources[id],li=node('li'),a=node('a','',source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';li.append(a,node('small','',source.scope[language]));return li;}));refs.append(ul);root.append(refs);progress();document.title=`${selected.title[language]} · Ritual Assist · Sushant Synapse`;
}
let referenceWasOpen=false;
addEventListener('beforeprint',()=>{const reference=$('#guide .reference');referenceWasOpen=reference.open;reference.open=true;});
addEventListener('afterprint',()=>{$('#guide .reference').open=referenceWasOpen;});
$('#language').onchange=()=>{language=$('#language').value;translations();renderList();renderGuide();syncUrl();$('#status').textContent='';$('#copy-fallback').hidden=true;};$('#search').oninput=renderList;translations();renderList();renderGuide();syncUrl();
document.body.classList.add('ready');
matchMedia('(min-width: 761px)').addEventListener('change',event=>{if(event.matches)$('#library').open=true;});
