import {calendarIcs,reminderSelection,occasionTitle} from './calendar-export.mjs';
import {preparationPack,packText,packGuides,defaultPackGuides,packTasks} from './preparation-pack.mjs';
import {tithiLabel} from './panchang.mjs';
import {sources} from './guides.mjs';

let current=null,selected=new Set(defaultPackGuides),checked=new Set(),assignments=['','',''],open=false,days=1,printState=[];
const element=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
const button=(text,action)=>{const el=element('button',text);el.type='button';el.addEventListener('click',action);return el;};
function save(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),link=element('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const dateText=(date,language)=>new Intl.DateTimeFormat(language==='hi'?'hi-IN':'en-IN',{dateStyle:'long',timeZone:'Asia/Kolkata'}).format(new Date(date+'T12:00:00+05:30'));

export function mountCalendarTools(container,result,language){
 if(current!==result){current=result;selected=new Set(defaultPackGuides);checked=new Set();assignments=['','',''];open=false;days=1;}
 const hi=language==='hi',section=element('section',undefined,'card calendar-tools'),heading=element('h3',hi?'तारीखें और तैयारी साथ रखें':'Keep your dates and preparation together');section.append(heading);
 const selection=reminderSelection(result),help=element('p',hi?'आगामी निश्चित तारीखें ही कैलेंडर में जाएँगी। पुष्टि वाली या अनिश्चित तारीखें पुस्तिका में रहती हैं।':'Only resolved upcoming dates go into the calendar. Conditional or uncertain dates remain in the preparation pack.','fine');section.append(help);
 const count=element('p',(hi?'निर्यात योग्य तारीखें: ':'Dates available: ')+selection.rows.length+' · '+(hi?'पुष्टि के लिए रोकी गई: ':'Withheld for confirmation: ')+selection.withheld.length,'fine');section.append(count);
 const controls=element('div',undefined,'reminder-controls'),label=element('label',hi?'सुबह 9 बजे IST याद दिलाएँ':'Remind me at 9 am IST'),select=element('select');select.id='reminder-days';
 for(const value of [0,1,3,7]){const option=element('option',value===0?(hi?'उसी दिन':'On the day'):(hi?value+' दिन पहले':value+' day'+(value===1?'':'s')+' before'));option.value=String(value);select.append(option);}select.value=String(days);select.addEventListener('change',()=>{days=Number(select.value);});label.append(select);controls.append(label);
 const status=element('p',undefined,'fine');status.setAttribute('role','status');
 const exportButton=button(hi?'कैलेंडर फ़ाइल डाउनलोड करें':'Download calendar reminders',async()=>{const snapshot=current;exportButton.disabled=true;try{const content=await calendarIcs(result,{language,reminderDays:days});if(current!==snapshot||!section.isConnected)return;save(content,'ritual-assist-reminders.ics','text/calendar;charset=utf-8');status.textContent=hi?'फ़ाइल डाउनलोड हुई। अपने कैलेंडर में आयात करके सूचनाएँ जाँचें।':'File downloaded. Import it into your calendar and check its notification settings.';}catch(error){if(section.isConnected)status.textContent=error.message;}finally{exportButton.disabled=!selection.rows.length;}});exportButton.disabled=!selection.rows.length;controls.append(exportButton);
 const packButton=button(hi?'तैयारी पुस्तिका खोलें':'Open preparation pack',()=>{open=!open;packButton.setAttribute('aria-expanded',String(open));packSection.hidden=!open;if(open){packSection.querySelector('h3').focus();}});packButton.id='open-preparation-pack';packButton.setAttribute('aria-controls','preparation-pack');packButton.setAttribute('aria-expanded',String(open));controls.append(packButton);section.append(controls,status);
 const instructions=element('details',undefined,'calendar-import');instructions.append(element('summary',hi?'अपने कैलेंडर में कैसे जोड़ें':'How to add these dates to your calendar'));
 instructions.append(element('p',hi?'यह .ics फ़ाइल है; कैलेंडर ऐप से खोलें। Google Calendar में कंप्यूटर पर Settings → Import & export से अपनी चुनी हुई निजी कैलेंडर में आयात करें। आयात के बाद याद दिलाने का समय जाँचें। हर तिथि अलग घटना है, वार्षिक अंग्रेजी तारीख से दोहराव नहीं।':'Open the .ics file with your calendar app. For Google Calendar, use Settings → Import & export on a computer and choose a private calendar. Check reminders after import. Each tithi date is a separate event, not a repeating Gregorian anniversary.','fine'));
 instructions.append(element('p',hi?'कैलेंडर ऐप सूचनाएँ बदल या अनदेखा कर सकता है। यह एक बार की फ़ाइल है, स्वतः सिंक या WhatsApp संदेश नहीं। दोबारा आयात से दोहरी घटनाएँ बन सकती हैं। पुराने समय की सूचनाएँ नहीं बनतीं। विवरण आपके चुने कैलेंडर प्रदाता के पास जाएँगे।':'Calendar apps may change or ignore imported alarms. This is a one-time file, without automatic sync or WhatsApp delivery. Importing again may duplicate events. Past alarm times are omitted. Importing shares the included dates with your chosen calendar provider.','fine'));
 const link=element('a',hi?'Google Calendar आयात सहायता':'Google Calendar import help');link.href='https://support.google.com/calendar/answer/37118';link.target='_blank';link.rel='noopener noreferrer';instructions.append(link);section.append(instructions);container.append(section);
 const packSection=element('section',undefined,'card preparation-pack');packSection.id='preparation-pack';packSection.hidden=!open;container.append(packSection);
 function drawPack(){
  packSection.replaceChildren();const title=element('h3',hi?'स्मरण और अनुष्ठान तैयारी पुस्तिका':'Remembrance preparation pack');title.tabIndex=-1;packSection.append(title,element('p',hi?'परिवार की रीति के अनुसार मार्गदर्शिकाएँ चुनें। चेक और जिम्मेदारियाँ इसी टैब में हैं; रिफ़्रेश या नई गणना से मिटती हैं।':'Choose guides for your family’s custom. Checks and assignments stay in this tab and clear on refresh or a new calculation.','fine'));
  const choices=element('fieldset',undefined,'pack-controls');choices.append(element('legend',hi?'पुस्तिका में मार्गदर्शिकाएँ':'Guides to include'));for(const guide of packGuides){const wrap=element('label',undefined,'check'),check=element('input');check.type='checkbox';check.value=guide.id;check.checked=selected.has(guide.id);check.dataset.packGuide=guide.id;check.addEventListener('change',()=>{check.checked?selected.add(guide.id):selected.delete(guide.id);drawPack();});wrap.append(check,element('span',guide.title[language]));choices.append(wrap);}packSection.append(choices);
  if(!selected.size){packSection.append(element('p',hi?'कम से कम एक मार्गदर्शिका चुनें।':'Choose at least one guide.','notice'));return;}
  const pack=preparationPack(result,language,[...selected]),actions=element('div',undefined,'actions pack-controls');actions.append(button(hi?'पुस्तिका प्रिंट / PDF':'Print pack / save PDF',()=>{printState=[...packSection.querySelectorAll('details')].map(el=>[el,el.open]);document.body.dataset.printMode='pack';for(const [el]of printState)el.open=true;window.print();}),button(hi?'पुस्तिका डाउनलोड करें':'Download preparation pack',()=>save(packText(pack,{checked,assignments}),'ritual-assist-preparation-pack.txt','text/plain;charset=utf-8')));packSection.append(actions);
  const overview=element('section',undefined,'pack-overview');overview.append(element('h4',hi?'तारीखें, विधि और पुष्टि':'Dates, method and confirmation'),element('p',dateText(result.data.date,language)+' · '+result.data.time+' IST · '+result.data.location.name),element('p',result.tithi?tithiLabel(result.tithi,language):(hi?'मृत्यु तिथि की पुष्टि आवश्यक':'Death tithi requires confirmation')),element('p',pack.scope,'fine'),element('p',hi?'मासिक, बरसी और श्राद्ध चंद्र तिथि और स्थानीय अपराह्न से निकले हैं; चौथा और दिन 10–13 दिन की गिनती से हैं। अनिश्चित या पारिवारिक नियम वाली तारीखें पक्की करें। PIN निर्देशांक और मास निर्धारण अनुमानित हैं; यह प्रमाणित क्षेत्रीय पंचांग नहीं है।':'Masik, Barsi and Shraddha use lunar tithis and local Aparahna; Chautha and days 10–13 use mourning-day counts. Confirm uncertain dates and family-specific rules. PIN coordinates and month classification are approximate; this is not a certified regional Panchang.','notice'));
  const schedule=element('details',undefined,'pack-date-details');schedule.append(element('summary',hi?'पूरी तारीख सूची देखें':'View complete date list'));const table=element('table',undefined,'pack-schedule'),head=element('thead'),header=element('tr');for(const text of [hi?'अनुष्ठान':'Observance',hi?'तारीख / पुष्टि':'Date / confirmation'])header.append(element('th',text));head.append(header);table.append(head);const body=element('tbody');for(const row of pack.schedule){const tr=element('tr'),label=element('td',occasionTitle(row,language)),date=element('td',row.date?dateText(row.date,language):(hi?'तारीख तय नहीं':'Date withheld'));if(row.window)label.append(element('small',tithiLabel(row.window.number,language)));date.append(element('small',row.conditional?(hi?'केवल संभावित · पारिवारिक पुष्टि':'Candidate only · confirm family rules'):row.status==='counted'?(hi?'दिन की गिनती · रीति पक्की करें':'Day count · confirm family custom'):row.date?(hi?'गणना आधारित अपराह्न तारीख':'Calculated Aparahna date'):(hi?'क्षेत्रीय पंचांग से पुष्टि करें':'Confirm with a regional Panchang')));if(!row.date)date.append(element('small',(row.candidates||[]).map(day=>dateText(day.date,language)).join(' / ')));tr.append(label,date);body.append(tr);}table.append(body);schedule.append(table);overview.append(schedule,element('p','GeoNames · CC BY 4.0 · https://www.geonames.org/ · Astronomy Engine 2.1.19 · MIT','fine'));packSection.append(overview);
  const tasks=element('section');tasks.append(element('h4',hi?'पारिवारिक जिम्मेदारियाँ':'Family responsibilities'));packTasks[language].forEach((task,i)=>{const wrap=element('label',task,'pack-task'),input=element('input');input.type='text';input.maxLength=80;input.value=assignments[i];input.autocomplete='off';input.placeholder=hi?'जिम्मेदार का नाम':'Assigned to';input.dataset.packTask=String(i);input.addEventListener('input',()=>{assignments[i]=input.value;printValue.textContent=input.value||'________________';});const printValue=element('span',input.value||'________________','pack-print-value');wrap.append(input,printValue);tasks.append(wrap);});packSection.append(tasks);
  for(const guide of pack.guides){const article=element('details',undefined,'pack-guide');article.open=guide.id==='shraddha';const summary=element('summary');summary.append(element('h4',guide.title[language]));article.append(summary,element('p',guide.summary[language]),element('p',guide.materialReview[language],'fine'));if(guide.care)article.append(element('p',guide.care[language],'scope ritual-care'));const steps=element('ol');for(const step of guide.steps)steps.append(element('li',step[language]));article.append(steps);
   for(const part of guide.sections||[])article.append(element('h5',part.title[language]),element('p',part.body[language]));
   const items=element('div',undefined,'checklist');for(const item of guide.items){const key=guide.id+':'+item.id,wrap=element('label',undefined,'check-item'),check=element('input');check.type='checkbox';check.checked=checked.has(key);check.dataset.packItem=key;check.addEventListener('change',()=>{check.checked?checked.add(key):checked.delete(key);});const body=element('span');body.append(element('strong',item.label[language]));if(item.kind==='confirm')body.append(element('small',hi?'पहले पुष्टि करें':'Confirm first','item-kind'));if(item.group)body.append(element('small',item.group[language]));if(item.note[language])body.append(element('small',item.note[language]));wrap.append(check,body);items.append(wrap);}article.append(items,element('p',guide.variation[language]),element('p',guide.preparation[language]));const questions=element('ul');for(const question of guide.questions)questions.append(element('li',question[language]));article.append(element('h5',hi?'पुरोहित और परिवार से पूछें':'Ask your officiant and family'),questions);
   const references=element('ul',undefined,'pack-references');for(const id of guide.sources){const source=sources[id],li=element('li'),a=element('a',source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';li.append(a,element('small',source.scope[language]),element('span',source.url,'pack-source-url'));references.append(li);}article.append(references);packSection.append(article);
  }
 }
 drawPack();
}

window.addEventListener('afterprint',()=>{for(const [el,wasOpen]of printState)el.open=wasOpen;printState=[];delete document.body.dataset.printMode;});
export function clearCalendarTools(){current=null;selected=new Set(defaultPackGuides);checked.clear();assignments=['','',''];open=false;printState=[];delete document.body.dataset.printMode;}
