// Original preparation summaries. These are not complete liturgical instructions.
const p=(en,hi)=>({en,hi});
export const sources={
 daily:{title:'BAPS · Devotional practices',url:'https://www.baps.org/About-BAPS/WhoWeAre/BasicBeliefs/Practices.aspx',scope:p('Swaminarayan practice; other traditions differ.','स्वामिनारायण पद्धति; अन्य परंपराएँ भिन्न हैं।')},
 ganesh:{title:'Drik Panchang · Ganapati puja',url:'https://www.drikpanchang.com/puja-vidhi/lord-ganesha/ganesha-puja-vidhi.html?lang=en',scope:p('One published worship sequence.','पूजा का एक प्रकाशित क्रम।')},
 lakshmi:{title:'Drik Panchang · Diwali puja',url:'https://www.drikpanchang.com/diwali/info/diwali-puja-vidhi.html?lang=en',scope:p('One Diwali tradition; confirm local timings.','दीवाली की एक पद्धति; स्थानीय समय की पुष्टि करें।')},
 satya:{title:'Hindu Temple of Tallahassee · Materials',url:'https://www.hindutempleoftallahassee.org/Home/PoojaMaterials',scope:p('Temple-specific Satyanarayan materials.','मंदिर की सत्यनारायण सामग्री सूची।')},
 family:{title:'Hindu Temple of SiouxLand · Puja items',url:'https://hindutempleofsd.org/puja-items/',scope:p('Temple-specific housewarming and naming lists.','मंदिर की गृहप्रवेश और नामकरण सूची।')},
 wedding:{title:'Hindu Temple of SiouxLand · Wedding list (PDF)',url:'https://hindutempleofsd.org/wp-content/uploads/2025/10/HTOS-Weddings-Items-Preparations.pdf',scope:p('Confirm both families’ customs; this is one temple’s list.','दोनों परिवारों की रीति पूछें; यह एक मंदिर की सूची है।')},
 havan:{title:'Hindu Temple Nebraska · Homam materials (PDF)',url:'https://hindutemplenebraska.org/uploads/website_menu_file/1033_Navagraha_Homam.pdf',scope:p('One homam example; your officiant chooses the actual materials.','होम का एक उदाहरण; वास्तविक सामग्री पुरोहित तय करें।')},
 death:{title:'AMSUK · Hindu death rites (PDF)',url:'https://www.amsuk.org/wp-content/uploads/2020/05/Hindu-Death-Rites-Guidelines-Published-by-AMSUK.pdf',scope:p('UK Koli Patel community guidance, used for cultural context only. Its UK legal procedures do not apply to India.','ब्रिटेन के कोली पटेल समुदाय का सांस्कृतिक संदर्भ। ब्रिटेन की कानूनी प्रक्रिया भारत पर लागू नहीं है।')},
 shraddha:{title:'Drik Panchang · Shraddha overview',url:'https://www.drikpanchang.com/shraddha/info/shraddha.html?lang=en',scope:p('One description of ancestral rites; regional customs vary.','पितृ अनुष्ठान का एक विवरण; क्षेत्रीय रीति भिन्न है।')}
};
export const categories={all:p('All guides','सभी मार्गदर्शिकाएँ'),shubh:p('Shubh · auspicious','शुभ · मांगलिक'),ashubh:p('Ashubh · mourning & remembrance','अशुभ · शोक एवं स्मरण')};
const item=(id,en,hi,kind='common',noteEn='',noteHi='')=>({id,label:p(en,hi),kind,note:p(noteEn,noteHi)});
const base=[item('image','Deity image / murti','देवता का चित्र / मूर्ति'),item('cloth','Clean cloth, chowki and tray','स्वच्छ कपड़ा, चौकी और थाली'),item('water','Clean water, vessel and spoon','स्वच्छ जल, पात्र और चम्मच'),item('flowers','Flowers','फूल'),item('lamp','Diya, wick and oil / ghee','दीपक, बत्ती और तेल / घी','confirm','Keep any flame attended on a stable surface.','दीपक स्थिर स्थान पर निगरानी में रखें।'),item('offerings','Fruit or prasad','फल या प्रसाद','confirm','Agree the recipe and servings; consider allergies.','विधि और मात्रा तय करें; एलर्जी का ध्यान रखें।'),item('tilak','Kumkum, turmeric, sandalwood and akshata','कुमकुम, हल्दी, चंदन और अक्षत','confirm','Only what your family uses.','केवल आपकी पारिवारिक पद्धति की सामग्री।')];
const kalash=item('kalash','Kalash, coconut and leaves','कलश, नारियल और पत्ते','confirm');
const prep=p('Prepare a clean place and arrange the agreed materials.','स्वच्छ स्थान बनाएँ और तय सामग्री रखें।');
const end=p('Conclude with your customary prayer or aarti and distribute prasad.','अपनी रीति से प्रार्थना या आरती करें और प्रसाद बाँटें।');
const question=p('Which steps, quantities, substitutions and participants suit our family’s tradition?','हमारे परिवार में कौन से चरण, मात्रा, विकल्प और सहभागी उचित हैं?');
const g=(id,category,title,summary,steps,items,variation,refs,questions=[])=>({id,category,title,summary,steps,items,variation,sources:refs,questions:[question,...questions],preparation:p('Assign materials, ceremony coordination and guest support. Arrange seating, drinking water and clean-up.','सामग्री, अनुष्ठान समन्वय और अतिथि सेवा की जिम्मेदारी तय करें। बैठने, पीने के पानी और सफाई की व्यवस्था रखें।')});
export const guides=[
 g('daily-puja','shubh',p('Daily home puja','दैनिक गृह पूजा'),p('A simple household prayer routine.','घर की सरल दैनिक प्रार्थना।'),[prep,p('Sit quietly and remember your chosen deity.','शांत बैठकर अपने इष्ट देव का स्मरण करें।'),p('Offer what your household normally uses and recite a familiar prayer.','घर की रीति के अनुसार अर्पण और परिचित प्रार्थना करें।'),end],base,p('This guide prescribes no fixed duration or number of offerings. Follow your own practice.','यह मार्गदर्शिका अवधि या भोग की निश्चित संख्या तय नहीं करती। अपनी पद्धति अपनाएँ।'),['daily']),
 g('ganesh-puja','shubh',p('Ganesh puja','गणेश पूजा'),p('For new beginnings and family worship.','नए आरंभ और पारिवारिक पूजा के लिए।'),[prep,p('Make your intention (sankalp) and worship Ganesh in the family’s chosen form.','संकल्प करें और परिवार की चुनी पद्धति से गणेश पूजा करें।'),p('Present the agreed offerings while prayers are recited.','प्रार्थना के दौरान तय भोग अर्पित करें।'),end],[...base,item('durva','Durva grass and modak / sweets','दूर्वा और मोदक / मिठाई','confirm'),item('supari','Supari and sacred thread','सुपारी और मौली','confirm')],p('Daily worship and a temporary festival installation have different concluding rites. Confirm before arranging immersion.','दैनिक पूजा और उत्सव की अस्थायी स्थापना का समापन अलग है। विसर्जन से पहले पुष्टि करें।'),['ganesh']),
 g('lakshmi-puja','shubh',p('Lakshmi / Diwali puja','लक्ष्मी / दीवाली पूजा'),p('Organise household or business worship.','घर या व्यवसाय की पूजा व्यवस्थित करें।'),[prep,p('Confirm the local date and chosen time before inviting guests.','अतिथियों को बुलाने से पहले स्थानीय तिथि और समय की पुष्टि करें।'),p('Begin with sankalp and Ganesh worship, then the agreed Lakshmi worship.','संकल्प और गणेश पूजा के बाद तय लक्ष्मी पूजा करें।'),end],[...base,kalash,item('accounts','Account book / business symbol','बही-खाता / व्यवसाय का प्रतीक','confirm','Only if account-book worship is observed.','केवल बही-खाता पूजन करने पर।')],p('Kalash, account-book worship and fasting are not universal. This app does not calculate a muhurat.','कलश, बही पूजा और व्रत सभी के लिए समान नहीं हैं। यह ऐप मुहूर्त नहीं गणना करता।'),['lakshmi']),
 g('satyanarayan','shubh',p('Satyanarayan puja & katha','सत्यनारायण पूजा एवं कथा'),p('Prepare the puja, reading and prasad.','पूजा, कथा और प्रसाद की तैयारी।'),[prep,p('Confirm the kalash arrangement and begin the agreed puja with the officiant.','कलश की पुष्टि करें और पुरोहित के साथ तय पूजा शुरू करें।'),p('Read or listen to the Satyanarayan katha in the agreed order.','तय क्रम में सत्यनारायण कथा पढ़ें या सुनें।'),end],[...base,kalash,item('katha','Katha book / agreed reading','कथा पुस्तक / तय पाठ'),item('prasad','Ingredients for the agreed sweet prasad','तय मीठे प्रसाद की सामग्री','confirm'),item('panchamrit','Panchamrit ingredients','पंचामृत की सामग्री','confirm')],p('Recipes and quantities vary. Ask what the priest brings before shopping.','विधि और मात्रा भिन्न है। खरीदने से पहले पूछें कि पुरोहित क्या लाएँगे।'),['satya']),
 g('griha-pravesh','shubh',p('Griha pravesh','गृहप्रवेश'),p('Coordinate a new-home ceremony.','नए घर के अनुष्ठान का समन्वय।'),[p('Agree the ceremony date, access to the house and the officiant’s plan.','तिथि, घर में प्रवेश और पुरोहित की योजना तय करें।'),prep,p('Follow the agreed entry, deity worship and household blessings.','तय प्रवेश, देव पूजा और घर के आशीर्वाद का क्रम अपनाएँ।'),p('If havan is planned, the officiant leads it in a suitable location.','हवन हो तो उचित स्थान पर पुरोहित करवाएँ।'),end],[...base,kalash,item('milk','Milk and cooking vessel','दूध और पकाने का पात्र','confirm','Only for families observing ceremonial milk boiling.','केवल दूध उबालने की रस्म वाले परिवार के लिए।'),item('havan','Priest-confirmed havan materials','पुरोहित द्वारा तय हवन सामग्री','confirm')],p('Vastu worship, milk boiling and havan may be separate or omitted in your tradition.','वास्तु पूजा, दूध उबालना और हवन आपकी परंपरा में अलग या अनुपस्थित हो सकते हैं।'),['family']),
 g('namkaran','shubh',p('Namkaran · naming ceremony','नामकरण संस्कार'),p('A calm, organised family occasion.','शांत और व्यवस्थित पारिवारिक अवसर।'),[p('Agree the name and ceremony with family and officiant.','परिवार और पुरोहित से नाम और अनुष्ठान तय करें।'),prep,p('Perform the agreed puja and announce the chosen name in your family’s manner.','तय पूजा करें और परिवार की रीति से नाम घोषित करें।'),p('Offer blessings and allow breaks for the child.','आशीर्वाद दें और बच्चे के लिए विराम रखें।')],[...base,item('baby','Clean cloth and comfortable place for the child','बच्चे के लिए स्वच्छ कपड़ा और आरामदायक स्थान'),item('name','Chosen name written clearly','चुना नाम स्पष्ट लिखा हुआ')],p('Timing and naming gestures vary. Ritual food or substances are not needed in the baby’s mouth.','समय और नाम देने की रीति भिन्न है। शिशु के मुँह में अनुष्ठान का भोजन या सामग्री देना आवश्यक नहीं।'),['family']),
 g('vivah','shubh',p('Vivah · wedding preparations','विवाह की तैयारी'),p('Bring both families’ arrangements together.','दोनों परिवारों की तैयारी एक साथ रखें।'),[p('Agree the ceremony sequence with both families and priest.','दोनों परिवारों और पुरोहित के साथ क्रम तय करें।'),p('Label materials by stage and assign someone to hand them over.','सामग्री चरण के अनुसार रखें और देने की जिम्मेदारी तय करें।'),p('Follow the agreed welcome, puja and marriage rites with the officiant.','पुरोहित के साथ तय स्वागत, पूजा और विवाह की रस्में करें।'),p('Confirm completion and gather the family for blessings.','समापन की पुष्टि करें और परिवार का आशीर्वाद लें।')],[...base,item('garlands','Garlands for the couple','वर-वधू की मालाएँ','confirm'),item('customs','Ceremonial clothing, thread or marriage symbols','अनुष्ठान के वस्त्र, सूत्र या विवाह के प्रतीक','confirm','Agree both families’ customs.','दोनों परिवारों की रीति तय करें।'),item('havan','Priest-confirmed havan materials','पुरोहित द्वारा तय हवन सामग्री','confirm')],p('Rites and their order vary widely. This preparation list is not a complete wedding liturgy.','रस्में और क्रम बहुत भिन्न होते हैं। यह तैयारी की सूची है, संपूर्ण विवाह विधि नहीं।'),['wedding']),
 g('havan','shubh',p('Havan / homam','हवन / होम'),p('Prepare for an officiant-led fire offering.','पुरोहित के नेतृत्व में अग्नि अनुष्ठान की तैयारी।'),[p('Ask the officiant to choose the ritual, materials and suitable venue.','पुरोहित से अनुष्ठान, सामग्री और स्थान तय करवाएँ।'),p('Set out approved materials; confirm venue permission and ventilation.','तय सामग्री रखें; स्थान की अनुमति और हवा की व्यवस्था जाँचें।'),p('The officiant establishes the fire and leads all offerings.','पुरोहित अग्नि स्थापित करें और आहुति का नेतृत्व करें।'),p('Keep the area attended until the officiant confirms the fire is fully out.','अग्नि पूरी बुझने की पुष्टि तक स्थान की निगरानी रखें।')],[item('kund','Suitable havan kund and fire-safe base','उचित हवन कुंड और अग्नि-सुरक्षित आधार','confirm'),item('samidha','Approved samidha / wood','तय समिधा / लकड़ी','confirm'),item('samagri','Ritual-specific havan samagri','अनुष्ठान के अनुसार हवन सामग्री','confirm'),item('ghee','Ghee and offering spoon','घी और आहुति का चम्मच','confirm'),item('safety','Water and fire-safety arrangements','पानी और अग्नि सुरक्षा की व्यवस्था')],p('Different homams need different offerings. Do not improvise the fire setup.','विभिन्न होम में अलग आहुति होती है। अग्नि की व्यवस्था स्वयं न गढ़ें।'),['havan']),
 g('antyeshti','ashubh',p('Antyeshti · funeral preparation','अंत्येष्टि की तैयारी'),p('Gentle coordination for the family.','परिवार के लिए संवेदनशील समन्वय।'),[p('Choose a family contact for the local funeral service and officiant.','स्थानीय अंतिम संस्कार सेवा और पुरोहित हेतु पारिवारिक संपर्क चुनें।'),p('Ask the service about local documents, permissions and arrangements.','सेवा से स्थानीय दस्तावेज, अनुमति और व्यवस्था पूछें।'),p('Confirm family rites and who supplies each material before buying.','खरीदने से पहले पारिवारिक रीति और सामग्री कौन देगा, तय करें।'),p('Let the authorised service manage transport and cremation arrangements.','अधिकृत सेवा को परिवहन और अंतिम संस्कार की व्यवस्था करने दें।'),p('Arrange rest, support and practical help afterwards.','बाद में आराम, सहारा और व्यावहारिक सहायता रखें।')],[item('contacts','Service and officiant contact details','सेवा और पुरोहित के संपर्क'),item('documents','Locally requested documents','स्थानीय रूप से माँगे दस्तावेज','confirm'),item('cloth','Cloth / shroud agreed with the service','सेवा के साथ तय वस्त्र / कफन','confirm'),item('flowers','Flowers, if the family wishes','परिवार चाहे तो फूल','confirm'),item('ritual','Officiant-confirmed ritual materials','पुरोहित द्वारा तय सामग्री','confirm'),item('support','Transport, water and seating','परिवहन, पानी और बैठने की व्यवस्था')],p('Local procedures and customs differ. This guide gives no body preparation instructions or fixed deadlines.','स्थानीय प्रक्रिया और रीति भिन्न हैं। यहाँ शरीर की तैयारी के निर्देश या निश्चित समय-सीमा नहीं है।'),['death']),
 g('prarthana-sabha','ashubh',p('Prarthana sabha / remembrance','प्रार्थना सभा / स्मरण'),p('A respectful gathering with room for grief.','शोक का सम्मान करने वाली सभा।'),[p('Ask the family when visitors are welcome and what gathering they want.','परिवार से मिलने का उचित समय और सभा का स्वरूप पूछें।'),p('Arrange a quiet, accessible venue and a simple prayer or remembrance programme.','शांत, सुगम स्थान और सरल प्रार्थना या स्मरण का क्रम रखें।'),p('Invite participation without requiring anyone to speak or perform a ritual.','बोलने या रस्म करने का दबाव डाले बिना सहभागिता दें।'),p('Close gently and coordinate refreshments or help with the family.','संवेदनशील समापन करें और भोजन या सहायता परिवार से तय करें।')],[item('photo','Photograph, if the family wishes','परिवार चाहे तो तस्वीर','confirm'),item('flowers','Flowers or simple tribute','फूल या सरल श्रद्धांजलि','confirm'),item('reading','Chosen prayers, readings or music','चुनी प्रार्थना, पाठ या संगीत','confirm'),item('seating','Chairs, water and accessible seating','कुर्सियाँ, पानी और सुगम बैठने की व्यवस्था'),item('schedule','Time, venue and family contact','समय, स्थान और पारिवारिक संपर्क')],p('Fourth-, tenth-, twelfth- or thirteenth-day observances are not universal. Confirm the family’s preference.','चौथे, दसवें, बारहवें या तेरहवें दिन की रीति सार्वभौमिक नहीं है। परिवार की इच्छा पूछें।'),['death']),
 g('shraddha','ashubh',p('Shraddha / Pitru remembrance','श्राद्ध / पितृ स्मरण'),p('Prepare for ancestral remembrance.','पितृ स्मरण की तैयारी।'),[p('Confirm the observance and tithi with family and officiant.','परिवार और पुरोहित से अनुष्ठान और तिथि की पुष्टि करें।'),p('Ask whether tarpan, pinda offerings, a meal or charity are included.','पूछें कि तर्पण, पिंड अर्पण, भोजन या दान में क्या शामिल है।'),p('Arrange agreed materials and follow the officiant’s sequence.','तय सामग्री रखें और पुरोहित का क्रम अपनाएँ।'),p('Complete agreed meal or charity arrangements within your means.','अपनी क्षमता के अनुसार तय भोजन या दान की व्यवस्था पूरी करें।')],[item('water','Water, vessel and spoon','जल, पात्र और चम्मच'),item('sesame','Black sesame and kusha / darbha','काले तिल और कुश / दर्भ','confirm'),item('pinda','Ingredients for pinda offerings','पिंड अर्पण की सामग्री','confirm'),item('meal','Agreed meal / charity arrangements','तय भोजन / दान की व्यवस्था','confirm'),item('cloth','Clean seating cloth and utensils','स्वच्छ आसन और पात्र')],p('An English-calendar anniversary does not establish the shraddha tithi. Ask about the calendar and substitutions.','अंग्रेजी तारीख की पुण्यतिथि से श्राद्ध तिथि तय नहीं होती। पंचांग और विकल्प पूछें।'),['shraddha']),
 g('asthi','ashubh',p('Asthi collection & immersion planning','अस्थि संचय एवं विसर्जन की योजना'),p('Coordinate with the crematorium and family.','श्मशान सेवा और परिवार से समन्वय।'),[p('Ask the crematorium when collection is permitted and who may collect.','श्मशान सेवा से संग्रह का अनुमत समय और व्यक्ति पूछें।'),p('Confirm the container, handover and travel arrangements.','पात्र, सुपुर्दगी और यात्रा की व्यवस्था तय करें।'),p('Ask the family and officiant about the destination and local rules.','परिवार और पुरोहित से स्थान और स्थानीय नियम पूछें।'),p('Use an authorised, safe access point and follow local instructions.','अधिकृत, सुरक्षित स्थान और स्थानीय निर्देश अपनाएँ।')],[item('container','Container specified by the crematorium','श्मशान सेवा द्वारा तय पात्र','confirm'),item('handover','Collection contact and requested paperwork','संग्रह का संपर्क और माँगे दस्तावेज','confirm'),item('travel','Travel and safe access arrangements','यात्रा और सुरक्षित पहुँच की व्यवस्था'),item('ritual','Officiant-confirmed offerings','पुरोहित द्वारा तय अर्पण','confirm')],p('Timing and offerings vary. Avoid unsafe water access and do not leave packaging in a river.','समय और अर्पण भिन्न हैं। असुरक्षित जल में न उतरें और नदी में पैकेजिंग न छोड़ें।'),['death'])
];
export const scope=p('Hindu preparation guides, not a single universal vidhi. Confirm family customs, quantities and local dates with your priest or elder.','हिन्दू अनुष्ठान की तैयारी; सभी के लिए एक ही विधि नहीं। पारिवारिक रीति, मात्रा और स्थानीय तिथि की पुरोहित या बुजुर्ग से पुष्टि करें।');
export function guideById(id){return guides.find(g=>g.id===id)||guides[0];}
export function findGuides({category='all',query=''}={}){if(!Object.hasOwn(categories,category))throw Error('Unknown category');const q=String(query).normalize('NFKC').trim().toLocaleLowerCase();return guides.filter(g=>(category==='all'||g.category===category)&&(!q||[g.id,g.title.en,g.title.hi,g.summary.en,g.summary.hi,...g.items.flatMap(i=>[i.label.en,i.label.hi])].join(' ').normalize('NFKC').toLocaleLowerCase().includes(q)));}
export function checklistText(guide,language='en',checked=new Set()){
 if(!['en','hi'].includes(language)||!guides.includes(guide))throw Error('Choose a valid guide and language');const hi=language==='hi';
 return [`Ritual Assist · ${guide.title[language]}`,scope[language],'',hi?'चरण':'Steps',...guide.steps.map((s,i)=>`${i+1}. ${s[language]}`),'',hi?'सामग्री की तैयारी':'Materials to arrange',...guide.items.map(i=>`${checked.has(i.id)?'[x]':'[ ]'} ${i.label[language]}${i.kind==='confirm'?(hi?' (पहले पुष्टि करें)':' (confirm first)'):''}${i.note[language]?' — '+i.note[language]:''}`),'',guide.variation[language],guide.preparation[language],'',hi?'पुरोहित / परिवार से पूछें':'Ask your priest / family',...guide.questions.map(q=>'- '+q[language]),'',hi?'संदर्भ':'References',...guide.sources.map(id=>sources[id].title+' · '+sources[id].url+'\n'+sources[id].scope[language]),'','Sushant Synapse · Ritual Assist'].join('\n');
}
