const p=(en,hi)=>({en,hi});
const row=(id,en,hi,noteEn,noteHi,groupEn='Confirm for this ceremony',groupHi='इस अनुष्ठान के लिए तय करें')=>({id,label:p(en,hi),kind:'confirm',note:p(noteEn,noteHi),group:p(groupEn,groupHi)});
export function reviewMaterials(guides,sources){
 sources.havan={title:'Hindu Temple of Charleston · Havan materials (PDF)',url:'https://hindutemplechs.org/wp-content/uploads/2020/06/PujaSamaghri_Havan.pdf',scope:p('A temple Havan checklist; quantities and accompanying puja items are examples, not universal requirements.','मंदिर की हवन सूची; मात्रा और साथ की पूजा-सामग्री उदाहरण हैं, सार्वभौमिक आवश्यकता नहीं।')};
 sources.homam={title:'Hindu Temple of SiouxLand · Homam/Havan list',url:'https://hindutempleofsd.org/puja-items/#homam-havan-list',scope:p('Temple checklist with venue restrictions and optional offerings; ask your own priest.','स्थान की शर्तों और वैकल्पिक अर्पण वाली मंदिर सूची; अपने पुरोहित से पूछें।')};
 // The source page has no guaranteed section fragment; keep its actual page URL.
 sources.homam.url='https://hindutempleofsd.org/puja-items/';
 sources.house={title:'Hindu Temple of Frisco · Puja lists',url:'https://www.hindutempleoffrisco.org/Puja-Lists.php',scope:p('Housewarming and homam examples from one temple; no foreign prices or quantities are adopted.','एक मंदिर के गृहप्रवेश और होम उदाहरण; विदेशी शुल्क या मात्रा नहीं अपनाई गई है।')};
 sources.ganeshDetailed={title:'Drik Panchang · Ganesha Chaturthi preparation',url:'https://www.drikpanchang.com/festivals/ganesh-chaturthi/ganesha-chaturthi-puja-vidhi.html',scope:p('Reference for traditional offerings, not copied mantras or a required universal sequence.','पारंपरिक अर्पण का संदर्भ; मंत्रों की नकल या सबके लिए अनिवार्य क्रम नहीं।')};
 sources.lakshmiMaterials={title:'Drik Panchang · Lakshmi puja materials',url:'https://www.drikpanchang.com/festivals/lakshmipuja/info/lakshmi-puja-samagri.html',scope:p('A detailed tradition-specific list; rare herbs and specialized additions are not automatically required.','विस्तृत परंपरा-विशिष्ट सूची; दुर्लभ जड़ी-बूटियाँ और विशेष सामग्री अपने आप अनिवार्य नहीं।')};
 const by=id=>guides.find(g=>g.id===id),add=(id,items,refs=[])=>{const guide=by(id);guide.items.push(...items);guide.sources=[...new Set([...guide.sources,...refs])];};
 for(const guide of guides){guide.items=guide.items.map(item=>({...item,note:{...item.note}}));guide.materialReview=p('Materials reviewed 10 October 2026. These are preparation suggestions: confirm quantities, substitutions and who supplies them. No single list applies to every Hindu tradition.','सामग्री की समीक्षा 10 अक्टूबर 2026 को हुई। यह तैयारी-सुझाव है: मात्रा, विकल्प और सामग्री देने वाला तय करें। हर हिंदू परंपरा पर एक सूची लागू नहीं होती।');guide.questions.push(p('Which materials does the priest or venue supply, and what may we omit or substitute?','कौन सी सामग्री पुरोहित या स्थान देता है, और क्या छोड़ या बदल सकते हैं?'));}
 const set=(guide,id,en,hi)=>{const item=by(guide).items.find(i=>i.id===id);if(item)item.note=p(en,hi);};
 for(const guide of guides.filter(g=>g.category==='shubh'&&g.id!=='havan')){
  const tilak=guide.items.find(i=>i.id==='tilak');if(tilak)tilak.note=p('Keep powders separate; ask whether akshata is plain or coloured rice in your custom.','चूर्ण अलग रखें; पूछें कि परिवार में अक्षत सादे या रंगे चावल होते हैं।');
  const water=guide.items.find(i=>i.id==='water');if(water)water.note=p('A clean small vessel and spoon; metal type is a family choice, not an app requirement.','स्वच्छ छोटा पात्र और चम्मच; धातु परिवार का विकल्प है, ऐप का नियम नहीं।');
 }
 by('daily-puja').variation=p('A daily prayer need not use every ceremonial item. Keep the image, seating and prayer familiar to your household; BAPS describes its own Swaminarayan practice, not every Hindu family.','दैनिक प्रार्थना में हर समारोह की सामग्री आवश्यक नहीं। चित्र, आसन और प्रार्थना घर की परिचित रीति से रखें; BAPS अपनी स्वामिनारायण पद्धति बताता है, हर हिंदू परिवार की नहीं।');
 by('ganesh-puja').items.find(i=>i.id==='durva').label=p('Durva grass','दूर्वा');
 add('ganesh-puja',[row('modak','Modak or the family’s agreed sweet','मोदक या परिवार से तय मिठाई','Confirm the offering and servings; no fixed count is prescribed here.','भोग और परोसने की मात्रा तय करें; यहाँ निश्चित संख्या नहीं।'),row('betel','Betel leaves for customary tambul offering','पारंपरिक तांबूल के लिए पान के पत्ते','Only if used in the selected puja.','केवल चुनी पूजा में उपयोग हो तो।')],['ganeshDetailed']);
 set('ganesh-puja','supari','A supari representation or murti may be used according to the selected method; ask about mauli/thread.','चुनी विधि में सुपारी का प्रतीक या मूर्ति हो सकती है; मौली/सूत्र पूछें।');
 add('lakshmi-puja',[row('rice','Raw rice / akshata in a separate bowl','अलग कटोरी में चावल / अक्षत','For the agreed worship arrangement, not an automatic large quantity.','तय पूजा-व्यवस्था के लिए; बड़ी मात्रा अपने आप आवश्यक नहीं।'),row('coins','Coins or symbolic wealth offering','सिक्के या धन का प्रतीक','Optional family custom; no fixed amount or promised financial outcome.','पारिवारिक विकल्प; निश्चित राशि या धन-लाभ का वादा नहीं।')],['lakshmiMaterials']);
 set('lakshmi-puja','kalash','Confirm the vessel, coconut and leaf type with the family; do not assume rare herbs are needed.','पात्र, नारियल और पत्तों का प्रकार परिवार से तय करें; दुर्लभ जड़ी-बूटियाँ आवश्यक न मानें।');
 add('satyanarayan',[row('betel','Betel leaves and supari','पान के पत्ते और सुपारी','For the chosen temple/family sequence.','चुने मंदिर/परिवार के क्रम के लिए।'),row('rice','Raw rice for the worship setup','पूजा-व्यवस्था के लिए चावल','Keep separate from cooked prasad ingredients.','पके प्रसाद की सामग्री से अलग रखें।'),row('thread','Ceremonial cloth / thread','पूजा के वस्त्र / सूत्र','Confirm colour and whether the officiant supplies it.','रंग और पुरोहित इसे देगा या नहीं, पूछें।')]);
 set('satyanarayan','panchamrit','Common ingredients are milk, curd, ghee, honey and sugar; confirm the recipe and keep fresh.','प्रचलित सामग्री दूध, दही, घी, शहद और शक्कर है; विधि तय करें और ताजा रखें।');
 set('satyanarayan','prasad','Ask whether your family uses wheat/sooji halva or another recipe, and agree servings.','पूछें कि परिवार गेहूँ/सूजी का हलवा या अन्य विधि रखता है; मात्रा तय करें।');
 add('griha-pravesh',[row('leaves','Mango leaves / customary entrance toran','आम के पत्ते / पारंपरिक तोरण','Use only if part of the selected housewarming.','केवल चुने गृहप्रवेश में हो तो।'),row('grains','Navadhanya (nine grains), if prescribed','नवधान्य, निर्देश हो तो','The priest selects the grains; not required for every housewarming.','अनाज पुरोहित चुने; हर गृहप्रवेश में अनिवार्य नहीं।')],['house']);
 set('griha-pravesh','milk','A clean cooking vessel and milk only if the family follows this custom; arrange a safe cooking place.','यह पारिवारिक रीति हो तो स्वच्छ पकाने का पात्र और दूध; सुरक्षित पकाने का स्थान रखें।');
 set('griha-pravesh','havan','If a Havan is included, use the separate Havan guide and have the priest approve supplies and venue.','हवन शामिल हो तो अलग हवन मार्गदर्शिका देखें और सामग्री/स्थान पुरोहित से तय करें।');
 add('namkaran',[row('rice','Rice tray, if the name-writing custom uses it','नाम-लेखन की रीति हो तो चावल की थाली','Writing method varies; avoid adding a feeding ritual by assumption.','लेखन की विधि भिन्न है; अपने आप भोजन की रीति न जोड़ें।'),row('prasad','Agreed prasad for the gathering','मिलन के लिए तय प्रसाद','Confirm recipe and servings; no infant-feeding instructions are prescribed.','विधि और मात्रा तय करें; शिशु को खिलाने के निर्देश नहीं हैं।')]);
 add('vivah',[row('betel','Betel leaves, supari and fresh coconut','पान के पत्ते, सुपारी और ताजा नारियल','Confirm the quantities with both families.','मात्रा दोनों परिवारों से तय करें।'),row('laja','Laja / puffed rice, if that rite is included','लाजा / फूला चावल, रीति शामिल हो तो','For the officiant-led wedding offering; do not substitute without asking.','पुरोहित के निर्देश में विवाह-अर्पण हेतु; पूछे बिना विकल्प न रखें।'),row('vessels','Separate plates and small bowls','अलग थालियाँ और कटोरियाँ','Arrange offerings separately before the ceremony.','अनुष्ठान से पहले अर्पण अलग रखें।')]);
 set('vivah','customs','Mangalsutra, sindoor, clothing and tying cloth depend on both families’ tradition.','मंगलसूत्र, सिंदूर, वस्त्र और गठबंधन का कपड़ा दोनों परिवारों की परंपरा से तय हों।');
 const fire='Fire setup',fireHi='अग्नि की व्यवस्था',offer='Fire offerings · confirm first',offerHi='अग्नि-अर्पण · पहले तय करें',puja='Accompanying puja',pujaHi='साथ की पूजा';
 by('havan').items=[
 row('kund','Approved Havan kund and heat-safe base','स्वीकृत हवन कुंड और ताप-सुरक्षित आधार','Have the venue approve the vessel, sand/base and placement.','पात्र, रेत/आधार और स्थान की स्वीकृति लें।',fire,fireHi),
 row('samidha','Samidha / clean dry wood sticks','समिधा / स्वच्छ सूखी लकड़ी','The priest chooses the wood and size. No painted or treated wood.','लकड़ी और आकार पुरोहित चुने। रंगी या उपचारित लकड़ी नहीं।',fire,fireHi),
 row('ghee','Separate ghee for the Havan','हवन के लिए अलग घी','Keep unused ghee and a dedicated offering ladle.','अप्रयुक्त घी और अलग अर्पण-चम्मच रखें।',offer,offerHi),
 row('samagri','Ritual-specific Havan samagri mixture','अनुष्ठान-विशिष्ट हवन सामग्री मिश्रण','Have the priest check the pack’s ingredients; there is no one recipe for all homams.','पैकेट की सामग्री पुरोहित से जाँचें; हर होम के लिए एक विधि नहीं।',offer,offerHi),
 row('dry-coconut','Dry coconut pieces, if prescribed','सूखे नारियल के टुकड़े, निर्देश हो तो','Separate from fresh puja coconuts.','पूजा के ताजा नारियल से अलग।',offer,offerHi),
 row('grains','Selected grains or navadhanya, if prescribed','चुने अनाज या नवधान्य, निर्देश हो तो','Ask which grains apply to this Havan. Do not add every grain by assumption.','इस हवन के अनाज पूछें; अपने आप हर अनाज न मिलाएँ।',offer,offerHi),
 row('special','Special food offerings or purnahuti materials','विशेष भोजन-अर्पण या पूर्णाहुति सामग्री','The officiant specifies these; do not burn all puja items.','पुरोहित तय करे; पूजा की सारी सामग्री अग्नि में न डालें।',offer,offerHi),
 row('water','Clean water, vessel and spoon','स्वच्छ जल, पात्र और चम्मच','Keep water for worship separate from fire-safety supplies.','पूजा का जल अग्नि-सुरक्षा सामग्री से अलग रखें।',puja,pujaHi),
 row('rice','Raw rice / akshata','चावल / अक्षत','For the accompanying puja as instructed.','निर्देशानुसार साथ की पूजा के लिए।',puja,pujaHi),
 row('coconut','Fresh coconut, betel leaves and supari','ताजा नारियल, पान के पत्ते और सुपारी','Confirm the number and use.','संख्या और उपयोग तय करें।',puja,pujaHi),
 row('flowers','Flowers, fruit and agreed prasad','फूल, फल और तय प्रसाद','Prepare the agreed servings separately.','तय मात्रा अलग तैयार रखें।',puja,pujaHi),
 row('powders','Turmeric, kumkum and sandalwood','हल्दी, कुमकुम और चंदन','Arrange separate small bowls.','अलग छोटी कटोरियाँ रखें।',puja,pujaHi),
 row('lamp','Diya, wick and oil / ghee','दीपक, बत्ती और तेल / घी','Keep the lamp attended.','दीपक की निगरानी रखें।',puja,pujaHi),
 row('cloth','Clean cloth, trays and offering bowls','स्वच्छ कपड़ा, थालियाँ और अर्पण-कटोरियाँ','Confirm cloth colours and supplied utensils.','वस्त्र का रंग और मिलने वाले पात्र तय करें।',puja,pujaHi),
 row('safety','Venue-approved ignition and fire-safety arrangements','स्थान से स्वीकृत अग्नि-प्रज्वलन और सुरक्षा व्यवस्था','A responsible adult/officiant manages the fire, ventilation and cooling before cleanup.','जिम्मेदार वयस्क/पुरोहित अग्नि, हवा और सफाई से पहले ठंडा होने की व्यवस्था संभाले।',fire,fireHi)];
 by('havan').sources=['havan','homam','wedding','house'];
 by('havan').variation=p('Ganesh, Navagraha, Griha pravesh and other Havans use different offerings. A kit is not approval for every rite. Confirm the ritual name, size, duration, venue and exact quantities; a household list must not copy a temple’s large-event quantities.','गणेश, नवग्रह, गृहप्रवेश और अन्य हवन के अर्पण भिन्न होते हैं। किट हर रीति की स्वीकृति नहीं। अनुष्ठान, आकार, अवधि, स्थान और मात्रा तय करें; घर की सूची में बड़े मंदिर आयोजन की मात्रा न अपनाएँ।');
 for(const id of ['prarthana-sabha','shraddha','asthi','day-10','day-11','day-12','antyeshti']){const guide=by(id);guide.questions.push(p('Are the rites and materials different in our family, and can the venue provide any of them?','क्या हमारे परिवार में विधि या सामग्री अलग है, और क्या स्थान कुछ सामग्री देगा?'));}
 set('shraddha','pinda','Ask whether the family uses cooked rice or another preparation; ingredients and number are tradition-specific.','पूछें कि परिवार पका चावल या अन्य सामग्री रखता है; विधि और संख्या परंपरा-विशिष्ट हैं।');
 set('shraddha','sesame','Confirm black sesame and the local kusha/darbha supply or permitted substitution.','काले तिल, स्थानीय कुश/दर्भ या स्वीकृत विकल्प तय करें।');
 set('asthi','ritual','Only the local priest’s agreed offerings; the container and collection procedure come from crematorium staff.','केवल स्थानीय पुरोहित से तय अर्पण; पात्र और संग्रह प्रक्रिया श्मशान कर्मचारी बताएँ।');
}
