const p=(en,hi)=>({en,hi});
const item=(id,en,hi)=>({id,label:p(en,hi),kind:'confirm',note:p('Confirm the quantity and substitutions with the officiant.','मात्रा और विकल्प पुरोहित से तय करें।')});
export function expandMourning(guides,sources){
 sources.funeral={title:'Himalayan Academy · Death and Dying',url:'https://www.himalayanacademy.com/media/books/death-and-dying_ei/death-and-dying_ei.pdf',scope:p('A Shaiva account of funeral customs; regional and family practices differ.','शैव परंपरा का विवरण; क्षेत्रीय और पारिवारिक रीति भिन्न है।')};
 sources.postdeath={title:'Hindu Janajagruti Samiti · Post-cremation ceremonies',url:'https://www.hindujagruti.org/hinduism/rituals-to-be-performed-after-cremation-till-the-13th-day-after-death',scope:p('One tradition’s day 10–13 account, not a universal schedule. Original preparation summaries here do not reproduce its liturgy.','एक परंपरा के दिन 10–13 का विवरण, सार्वभौमिक क्रम नहीं। यहाँ मौलिक तैयारी-सार है, विधि की नकल नहीं।')};
 const funeral=guides.find(g=>g.id==='antyeshti');
 funeral.summary=p('Antim sanskar: family duties, ceremony stages and male/female customs.','अंतिम संस्कार: पारिवारिक जिम्मेदारियाँ, चरण और पुरुष/महिला की रीति।');
 funeral.steps=[
 p('Record the death date, exact IST time and location. Obtain the medical confirmation and paperwork requested by the local authority or crematorium.','मृत्यु की तारीख, सही IST समय और स्थान लिखें। स्थानीय अधिकारी या श्मशान द्वारा माँगी चिकित्सा पुष्टि और दस्तावेज लें।'),
 p('Contact the family priest and crematorium. Agree the venue, transport, timing, charges and wood or electric cremation arrangements.','पारिवारिक पुरोहित और श्मशान से संपर्क करें। स्थान, वाहन, समय, शुल्क और लकड़ी या विद्युत दाह की व्यवस्था तय करें।'),
 p('Choose the karta (person performing the rites) with the family and officiant. Discuss participation by daughters, spouse or another relative; do not assume only a son can help.','परिवार और पुरोहित के साथ कर्ता चुनें। पुत्री, जीवनसाथी या अन्य परिजन की भूमिका पूछें; सहायता केवल पुत्र तक सीमित न मानें।'),
 p('Arrange respectful preparation and agreed clothing or shroud with the service, including privacy and the family’s male/female customs. Confirm which offerings the venue allows.','सेवा के साथ सम्मानजनक तैयारी और तय वस्त्र या कफन रखें। निजता तथा पुरुष/महिला की पारिवारिक रीति का ध्यान रखें। स्थान पर अनुमत अर्पण पूछें।'),
 p('Gather for a brief prayer and farewell. The priest guides any sankalpa, customary offerings and procession; assign one person to coordinate guests and elders.','संक्षिप्त प्रार्थना और अंतिम दर्शन के लिए मिलें। संकल्प, पारंपरिक अर्पण और यात्रा पुरोहित के निर्देश में हों; अतिथि और बुजुर्गों का समन्वय किसी एक को दें।'),
 p('At the crematorium, follow the officiant and staff for the farewell and mukhagni or electric-cremation procedure. Staff manage the equipment and fire.','श्मशान में विदाई तथा मुखाग्नि या विद्युत दाह के लिए पुरोहित और कर्मचारी का निर्देश लें। उपकरण और अग्नि कर्मचारी संभालें।'),
 p('Collect the cremation receipt and ask when and how asthi collection is permitted. Agree the immersion destination separately.','दाह की रसीद लें और अस्थि-संचय का अनुमत समय एवं प्रक्रिया पूछें। विसर्जन का स्थान अलग से तय करें।'),
 p('Arrange meals, rest and help for the household. Confirm Chautha, days 10, 11 and 12, any day 13 observance and the monthly remembrance plan.','परिवार के लिए भोजन, आराम और सहायता रखें। चौथा, दिन 10, 11, 12, लागू हो तो दिन 13 और मासिक स्मरण की योजना तय करें।')];
 funeral.items=[item('documents','Medical/death paperwork and identity documents requested locally','स्थानीय रूप से माँगे चिकित्सा/मृत्यु तथा पहचान दस्तावेज'),item('contacts','Priest, crematorium and transport contacts','पुरोहित, श्मशान और वाहन के संपर्क'),item('cloth','Agreed clothing and clean shroud','तय वस्त्र और स्वच्छ कफन'),item('flowers','Flowers or garland','फूल या माला'),item('water','Water, vessel and spoon','जल, पात्र और चम्मच'),item('offerings','Rice, sesame, kusha/darbha and other agreed offerings','चावल, तिल, कुश/दर्भ और अन्य तय अर्पण'),item('fire','Venue-supplied wood or electric cremation; agreed ghee/incense if permitted','स्थान द्वारा लकड़ी या विद्युत दाह; अनुमति हो तो तय घी/धूप'),item('container','Staff-specified asthi container for later collection','बाद के अस्थि-संचय हेतु कर्मचारी द्वारा तय पात्र'),item('support','Drinking water, seating, transport and family support','पीने का पानी, बैठक, वाहन और पारिवारिक सहायता')];
 funeral.variation=p('This is an adult funeral preparation guide for India. Children, renunciants, unusual deaths and different communities may follow other rites; obtain individual guidance. Local medical/legal release takes priority over a preferred ceremony time.','यह भारत में वयस्क के अंतिम संस्कार की तैयारी है। बच्चों, संन्यासियों, असामान्य मृत्यु और अलग समुदायों की रीति भिन्न हो सकती है; व्यक्तिगत मार्गदर्शन लें। इच्छित समय से पहले स्थानीय चिकित्सा/कानूनी अनुमति आवश्यक है।');
 funeral.sections=[
 {title:p('Male deceased · पुरुष','पुरुष दिवंगत'),body:p('Discuss the family’s usual dhoti or other clothing, shroud, sacred thread if applicable, and who assists with preparation. White is common in many families, but colour and symbols are not universal requirements.','परिवार के प्रचलित धोती या अन्य वस्त्र, कफन, लागू हो तो जनेऊ और तैयारी में सहायता करने वाले व्यक्ति तय करें। कई परिवार सफेद रखते हैं, पर रंग और चिह्न सार्वभौमिक नियम नहीं हैं।')},
 {title:p('Female deceased · महिला','महिला दिवंगत'),body:p('Discuss the family’s usual sari or other clothing and privacy during preparation. Some families distinguish a married woman whose spouse survives from a widow or unmarried woman through clothing or marriage symbols; ask before arranging these. Do not impose the same dress or jewellery rule on every woman.','परिवार के प्रचलित साड़ी या अन्य वस्त्र और तैयारी की निजता तय करें। कुछ परिवार जीवित जीवनसाथी वाली विवाहित महिला, विधवा और अविवाहित महिला के वस्त्र या वैवाहिक चिह्न अलग रखते हैं; व्यवस्था से पहले पूछें। हर महिला पर एक ही वस्त्र या आभूषण नियम न लगाएँ।')},
 {title:p('What stays shared','साझी बातें'),body:p('Dignity, consent, family participation and local procedures apply to everyone. Gender does not change the astronomical death tithi. The karta’s role and later ceremonies follow family tradition, not an automatic gender restriction in this app.','सम्मान, सहमति, पारिवारिक सहभागिता और स्थानीय प्रक्रिया सभी के लिए हैं। लिंग से मृत्यु की खगोलीय तिथि नहीं बदलती। कर्ता और आगे की रीति परिवार की परंपरा से तय हों, ऐप के लिंग-आधारित प्रतिबंध से नहीं।')}];
 funeral.sources=['death','funeral'];
 const rows=[
 ['day-10','Day 10 · Dashgatra / Daswa','दिन 10 · दशगात्र / दसवाँ','Prepare for the tenth-day mourning observance.','दसवें दिन के शोक-अनुष्ठान की तैयारी।','Ask whether the family completes daily pinda/tarpan observances on this day and whether any grooming or household-cleaning custom applies.','पूछें कि परिवार इस दिन दैनिक पिंड/तर्पण पूरा करता है या नहीं, और मुंडन या घर की सफाई की कौन सी रीति लागू है।'],
 ['day-11','Day 11 · Ekadashah / Ekoddishta','दिन 11 · एकादशाह / एकोद्दिष्ट','Arrange the eleventh-day rite with the officiant.','पुरोहित के साथ ग्यारहवें दिन की व्यवस्था।','Ask which ekoddishta or other shraddha, prayer and charity arrangements your family observes; do not assume every named rite is compulsory.','पूछें कि परिवार कौन सा एकोद्दिष्ट या अन्य श्राद्ध, प्रार्थना और दान रखता है; हर नामित अनुष्ठान अनिवार्य न मानें।'],
 ['day-12','Day 12 · Dwadashah / Barahva','दिन 12 · द्वादशाह / बारहवाँ','Coordinate the twelfth-day remembrance and family gathering.','बारहवें दिन का स्मरण और पारिवारिक मिलन तय करें।','Confirm whether sapindikarana belongs on this day, a later day or near the annual rite in your tradition, and whether a separate day 13 gathering remains.','पूछें कि सपिंडीकरण परिवार में इसी दिन, बाद में या वार्षिक अनुष्ठान के पास होता है, तथा दिन 13 का अलग मिलन रखा जाएगा या नहीं।']];
 for(const [id,en,hi,summaryEn,summaryHi,detailEn,detailHi]of rows)guides.push({id,category:'ashubh',title:p(en,hi),summary:p(summaryEn,summaryHi),steps:[p('Confirm the counted date with the family: death date or another customary starting day may be used.','परिवार से गिनी तारीख तय करें: मृत्यु की तारीख या परंपरा का अन्य आरंभिक दिन हो सकता है।'),p(detailEn,detailHi),p('Agree the venue, karta, priest, start time and people attending. Prepare a clean place and arrange the approved materials.','स्थान, कर्ता, पुरोहित, समय और सहभागी तय करें। स्वच्छ स्थान और स्वीकृत सामग्री रखें।'),p('Follow the officiant’s sequence for the agreed rites. Arrange food or donations within the family’s means and confirm the next observance.','तय अनुष्ठान पुरोहित के क्रम से करें। क्षमता के अनुसार भोजन या दान रखें और अगला अनुष्ठान तय करें।')],items:[item('water','Water, vessel and spoon','जल, पात्र और चम्मच'),item('sesame','Black sesame and kusha/darbha','काले तिल और कुश/दर्भ'),item('pinda','Cooked rice or other priest-agreed pinda ingredients','पका चावल या पुरोहित से तय पिंड सामग्री'),item('cloth','Clean seating cloth, tray and utensils','स्वच्छ आसन, थाली और पात्र'),item('meal','Agreed meal, food-grain or charity arrangements','तय भोजन, अनाज या दान की व्यवस्था')],variation:p('Day numbers count mourning days, not the Dashami/Ekadashi/Dwadashi lunar tithi. Customs can combine or move ceremonies. These are preparation guides, not mandatory rites for every family.','ये शोक के दिन हैं, चंद्र दशमी/एकादशी/द्वादशी तिथि नहीं। परंपरा में अनुष्ठान साथ या अन्य दिन हो सकते हैं। तैयारी का मार्गदर्शन है, हर परिवार के लिए अनिवार्य रीति नहीं।'),preparation:p('Confirm quantities before buying. Provide drinking water, seating and support for the household.','खरीदने से पहले मात्रा तय करें। परिवार के लिए पीने का पानी, बैठक और सहायता रखें।'),questions:[p('Which rites apply to our family, and which day-counting rule should we use?','हमारे परिवार में कौन से अनुष्ठान और दिन-गणना का नियम लागू है?')],sources:['postdeath','death']});
}
