import {Body,Observer,MoonPhase,SearchMoonPhase,SearchRiseSet,DefineStar,GeoVector,Ecliptic} from './astronomy-engine.mjs';
export const DAY=86400000,IST=330*60000;
export const cities=[{id:'delhi',name:'New Delhi',lat:28.6139,lon:77.209},{id:'mumbai',name:'Mumbai',lat:19.076,lon:72.8777},{id:'ahmedabad',name:'Ahmedabad',lat:23.0225,lon:72.5714},{id:'jaipur',name:'Jaipur',lat:26.9124,lon:75.7873},{id:'lucknow',name:'Lucknow',lat:26.8467,lon:80.9462},{id:'varanasi',name:'Varanasi',lat:25.3176,lon:82.9739},{id:'kolkata',name:'Kolkata',lat:22.5726,lon:88.3639},{id:'bengaluru',name:'Bengaluru',lat:12.9716,lon:77.5946},{id:'chennai',name:'Chennai',lat:13.0827,lon:80.2707},{id:'hyderabad',name:'Hyderabad',lat:17.385,lon:78.4867},{id:'pune',name:'Pune',lat:18.5204,lon:73.8567},{id:'surat',name:'Surat',lat:21.1702,lon:72.8311}];
export const tithiNames={en:['Pratipada','Dwitiya','Tritiya','Chaturthi','Panchami','Shashthi','Saptami','Ashtami','Navami','Dashami','Ekadashi','Dwadashi','Trayodashi','Chaturdashi','Purnima','Pratipada','Dwitiya','Tritiya','Chaturthi','Panchami','Shashthi','Saptami','Ashtami','Navami','Dashami','Ekadashi','Dwadashi','Trayodashi','Chaturdashi','Amavasya'],hi:['प्रतिपदा','द्वितीया','तृतीया','चतुर्थी','पंचमी','षष्ठी','सप्तमी','अष्टमी','नवमी','दशमी','एकादशी','द्वादशी','त्रयोदशी','चतुर्दशी','पूर्णिमा','प्रतिपदा','द्वितीया','तृतीया','चतुर्थी','पंचमी','षष्ठी','सप्तमी','अष्टमी','नवमी','दशमी','एकादशी','द्वादशी','त्रयोदशी','चतुर्दशी','अमावस्या']};
export const monthNames={en:['Chaitra','Vaishakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashwina','Kartika','Margashirsha','Pausha','Magha','Phalguna'],hi:['चैत्र','वैशाख','ज्येष्ठ','आषाढ़','श्रावण','भाद्रपद','आश्विन','कार्तिक','मार्गशीर्ष','पौष','माघ','फाल्गुन']};
export const methodology={version:'ritual-panchang-1',engine:'Astronomy Engine 2.1.19 (MIT)',zone:'Asia/Kolkata',precision:'Minute-rounded calculated times; allow a 5-minute boundary guard. Not a certified Panchang provider.',sources:[{name:'IMD Rashtriya Panchang · tithi definition',url:'https://packolkata.imd.gov.in/panchang/en/explanation'},{name:'Drik Panchang · death tithi and annual/Pitru Paksha Shraddha',url:'https://www.drikpanchang.com/utilities/tithi/hindu-shraddha-tithi-calculator.html'},{name:'Astronomy Engine · computation and accuracy',url:'https://github.com/cosinekitty/astronomy'},{name:'PanchangTime · Aparahna observance rules',url:'https://panchangtime.com/methodology/pitru-paksha-shraddha'}]};
// Chitra/Spica-aligned sidereal classification is used only for month labels.
// Tithi is geocentric Moon-Sun separation and does not require an ayanamsha.
// This is not an assertion of exact Lahiri/Swiss-Ephemeris equivalence.
DefineStar(Body.Star1,13.419883,-11.161322,250);
const mod=(n,d)=>((n%d)+d)%d,stamp=value=>Number(value instanceof Date?value:new Date(value));
export const localDate=value=>new Date(stamp(value)+IST).toISOString().slice(0,10);
export function midnight(date){if(typeof date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Enter a valid date');const d=new Date(date+'T00:00:00+05:30');if(!Number.isFinite(+d)||localDate(d)!==date)throw Error('Enter a valid date');return +d;}
export const addDays=(date,days)=>localDate(midnight(date)+days*DAY);
export function tithiAt(value){return Math.floor(MoonPhase(new Date(value))/12)+1;}
export function tithiLabel(tithi,language='en'){const paksha=tithi<=15?(language==='hi'?'शुक्ल':'Shukla'):(language==='hi'?'कृष्ण':'Krishna');return paksha+' '+tithiNames[language][tithi-1];}
function phase(angle,start,days){const value=SearchMoonPhase(angle,new Date(start),days);if(!value)throw Error('Lunar boundary could not be resolved');return +value.date;}
export function tithiWindow(value){const number=tithiAt(value),start=phase((number-1)*12,value,-3),end=phase(mod(number*12,360),value,3);if(start>value+1000||end<value-1000)throw Error('Tithi boundary is unresolved');return {number,start,end};}
function siderealSun(value){const date=new Date(value),sun=Ecliptic(GeoVector(Body.Sun,date,true)).elon,spica=Ecliptic(GeoVector(Body.Star1,date,true)).elon;return mod(sun-spica+180,360);}
function solarSign(value){const longitude=siderealSun(value);return {sign:Math.floor(longitude/30),near:Math.min(longitude%30,30-longitude%30)<.15};}
function lunarMonth(start){const end=phase(0,start+DAY,32),a=solarSign(start),b=solarSign(end),delta=mod(b.sign-a.sign,12);return {start,end,index:mod(a.sign+1,12),adhika:delta===0,kshaya:delta>1,uncertain:a.near||b.near};}
export function monthAt(value){return lunarMonth(phase(0,value,-32));}
export function displayedMonth(month,tithi,calendar){return calendar==='purnimanta'&&tithi>15?mod(month.index+1,12):month.index;}
function intervalFor(month,tithi){const start=tithi===1?month.start:phase((tithi-1)*12,month.start+1000,32),end=tithi===30?month.end:phase(tithi*12,start+1000,3);if(start<month.start-1000||end>month.end+1000)throw Error('Tithi is outside lunar month');return {number:tithi,start,end};}
export function daylight(date,location){const start=midnight(date),observer=new Observer(location.lat,location.lon,location.height||0),rise=SearchRiseSet(Body.Sun,observer,1,new Date(start),1),set=SearchRiseSet(Body.Sun,observer,-1,new Date(start),1);if(!rise||!set||set.date<=rise.date)throw Error('Local sunrise/sunset is unavailable');const sunrise=+rise.date,sunset=+set.date,length=sunset-sunrise;return {date,sunrise,sunset,aparahnaStart:sunrise+length*.6,aparahnaEnd:sunrise+length*.8};}
export function observance(window,location){const days=[],start=localDate(window.start-DAY);for(let i=0;i<5;i++){const date=addDays(start,i),light=daylight(date,location),overlap=Math.max(0,Math.min(window.end,light.aparahnaEnd)-Math.max(window.start,light.aparahnaStart));if(window.end>midnight(date)&&window.start<midnight(date)+DAY)days.push({...light,overlap});}const eligible=days.filter(day=>day.overlap>0).sort((a,b)=>b.overlap-a.overlap||a.date.localeCompare(b.date));if(!eligible.length)return {date:null,status:'no-aparahna',candidates:days,window};const winner=eligible[0],near=winner.overlap<5*60000||Math.abs(window.start-winner.aparahnaStart)<5*60000||Math.abs(window.end-winner.aparahnaEnd)<5*60000,tie=eligible.length>1&&Math.abs(eligible[0].overlap-eligible[1].overlap)<5*60000;return {date:tie||near?null:winner.date,status:tie?'two-day-tie':near?'boundary':'computed',candidates:eligible,window,aparahnaStart:winner.aparahnaStart,aparahnaEnd:winner.aparahnaEnd};}
export function validateInput(input,now=Date.now()){
 if(!input||typeof input!=='object')throw Error('Invalid calendar details');const date=input.date,start=midnight(date),year=Number(date.slice(0,4));if(year<1950||year>2098||date>localDate(now))throw Error('Choose a past or present date from 1950 onwards');
 const city=cities.find(city=>city.id===input.city);let location=city?{...city,height:0}:{id:'custom',name:'Custom location in India',lat:Number(input.lat),lon:Number(input.lon),height:Number(input.height||0)};
 if(!city&&(input.city!=='custom'||input.lat===''||input.lon===''||input.lat===undefined||input.lon===undefined))throw Error('Choose the place where ceremonies will be observed');if(!Number.isFinite(location.lat)||location.lat<6||location.lat>37.5||!Number.isFinite(location.lon)||location.lon<68||location.lon>98||!Number.isFinite(location.height)||location.height<0||location.height>4500)throw Error('Enter supported Indian coordinates and elevation');
 if(!['amanta','purnimanta'].includes(input.calendar))throw Error('Choose the Hindu lunar month convention');if(!['civil','sunrise'].includes(input.counting))throw Error('Choose how to count the first day');
 if(typeof input.time!=='string'||(input.time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(input.time)))throw Error('Enter a valid death time in IST');const moment=input.time?+new Date(date+'T'+input.time+':00+05:30'):null;if(moment&&moment>now)throw Error('Death time cannot be in the future');
 const confirmed=input.confirmedTithi===''||input.confirmedTithi===undefined?null:Number(input.confirmedTithi);if(confirmed!==null&&(!Number.isInteger(confirmed)||confirmed<1||confirmed>30))throw Error('Choose a valid confirmed tithi');
 return {date,start,moment,time:input.time,location,calendar:input.calendar,counting:input.counting,include13:input.include13===true,confirmedTithi:confirmed};
}
export function generateCalendar(input,options={}){
 const data=validateInput(input,options.now),deathDay=daylight(data.date,data.location),dayWindows=[];let cursor=data.start;for(let i=0;i<3&&cursor<data.start+DAY;i++){const window=tithiWindow(cursor+1000);dayWindows.push(window);cursor=window.end+1000;}
 const warnings=[],anchor=data.moment?tithiWindow(data.moment):null;let tithi=data.confirmedTithi||anchor?.number;
 if(data.confirmedTithi&&data.moment&&data.confirmedTithi!==anchor.number&&!dayWindows.some(w=>w.number===data.confirmedTithi&&Math.min(Math.abs(data.moment-w.start),Math.abs(data.moment-w.end))<5*60000))throw Error('Confirmed tithi differs from the tithi at the entered time. Check the input before proceeding.');
 if(data.confirmedTithi&&!dayWindows.some(w=>w.number===data.confirmedTithi))throw Error('The confirmed tithi does not occur on the entered IST date');
 if(anchor&&Math.min(data.moment-anchor.start,anchor.end-data.moment)<5*60000)warnings.push('death-boundary');
 if(!data.moment&&data.counting==='sunrise')throw Error('Sunrise-based day counting requires the death time');
 const firstDate=data.counting==='sunrise'&&data.moment<deathDay.sunrise?addDays(data.date,-1):data.date,early=[4,10,11,12,...data.include13?[13]:[]].map(day=>({kind:'day',day,date:addDays(firstDate,day-1),status:'counted'}));
 const result={methodology,data:{...data,start:undefined},firstDate,deathDay,tithi,deathWindow:anchor,dayWindows,early,monthly:[],annual:null,pitru:null,warnings};
 if(!tithi){warnings.push('time-required');return result;}if(warnings.includes('death-boundary')&&!data.confirmedTithi){warnings.push('confirm-boundary-tithi');return result;}
 let reference=data.moment;if(!reference||tithi!==anchor.number){const window=dayWindows.find(w=>w.number===tithi);reference=Math.max(window.start+1000,data.start);result.deathWindow=window;warnings.push('confirmed-tithi');}
 const deathMonth=monthAt(reference);result.deathMonth=deathMonth;
 const months=[deathMonth];for(let i=0;i<38;i++)months.push(lunarMonth(months.at(-1).end+1000));
 if(deathMonth.adhika)warnings.push('death-adhika');
 const annualIndex=months.findIndex((m,i)=>i>=11&&m.index===deathMonth.index&&!m.adhika);if(annualIndex<0)throw Error('Annual lunar month could not be resolved');
 if(months.slice(0,annualIndex+1).some(m=>m.kshaya||m.uncertain))warnings.push('month-boundary');
 let regularCount=0;for(let i=1;i<annualIndex;i++){const month=months[i],number=month.adhika?regularCount+1:++regularCount,row=observance(intervalFor(month,tithi),data.location);result.monthly.push({...row,kind:'monthly',number,cycle:i,month,conditional:month.adhika||month.kshaya||month.uncertain});}
 result.annual={...observance(intervalFor(months[annualIndex],tithi),data.location),kind:'annual',month:months[annualIndex],conditional:deathMonth.adhika||deathMonth.uncertain||months[annualIndex].uncertain||months.slice(0,annualIndex+1).some(m=>m.kshaya)};
 const after=result.annual.window.end,pitruTithi=tithi===15?15:tithi===30?30:15+(tithi-1)%15+1;
 // Pitru Paksha is Bhadrapada Krishna in Amanta / Ashwina Krishna in Purnimanta.
 for(const month of months){if(month.index!==5||month.adhika)continue;const window=intervalFor(month,pitruTithi);if(window.start<=after)continue;result.pitru={...observance(window,data.location),kind:'pitru',month,tithi:pitruTithi,conditional:[14,15,29].includes(tithi)||month.uncertain||result.annual.conditional};break;}
 if(result.monthly.some(row=>row.month.adhika))warnings.push('adhika-in-year');if(!result.pitru)warnings.push('pitru-unresolved');
 return result;
}
export function calendarText(result,language='en'){
 const hi=language==='hi',time=value=>new Intl.DateTimeFormat(hi?'hi-IN':'en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata',hour12:false}).format(new Date(Math.round(value/60000)*60000))+' IST';
 const lines=[hi?'रिचुअल असिस्ट · पंचांग स्मरण योजना':'Ritual Assist · Panchang remembrance plan',`${hi?'मृत्यु की तारीख':'Death date'}: ${result.data.date} ${result.data.time||(hi?'समय अज्ञात':'time unknown')} IST`,`${hi?'अनुष्ठान का स्थान':'Observance place'}: ${result.data.location.name} (${result.data.location.lat}, ${result.data.location.lon})`,`${hi?'मास पद्धति':'Lunar months'}: ${result.data.calendar}`,`${hi?'दिन गणना':'Day counting'}: ${result.data.counting}; ${hi?'पहला दिन':'day 1'} = ${result.firstDate}`,`${hi?'मृत्यु तिथि':'Death tithi'}: ${result.tithi?tithiLabel(result.tithi,language):(hi?'अनिश्चित — समय या पुरोहित द्वारा निश्चित तिथि चाहिए':'Unresolved — time or priest-confirmed tithi required')}`,'',hi?'यह गणना आधारित योजना है। व्यवस्था से पहले पारिवारिक नियम और सम्भावित तारीख पुरोहित से निश्चित करें।':'Calculated planning dates, not priest-approved ritual instructions. Confirm family rules and candidate dates before booking.',''];
 for(const row of [...result.early,...result.monthly,...result.annual?[result.annual]:[],...result.pitru?[result.pitru]:[]]){
  const title=row.kind==='day'?(row.day===4?(hi?'चौथा':'Chautha'):(hi?'दिन ':'Day ')+row.day):row.kind==='monthly'?(hi?'मासिक ':'Masik ')+row.number:row.kind==='annual'?(hi?'बरसी / पहला वार्षिक श्राद्ध':'Barsi / first annual Shraddha'):(hi?'बरसी के बाद पहला पितृ पक्ष':'First Pitru Paksha tithi after Barsi');
  lines.push(`${title}: ${row.date||(hi?'अनिश्चित':'UNRESOLVED')} · ${row.status}${row.conditional?(hi?' · केवल सम्भावित, पारिवारिक पुष्टि आवश्यक':' · candidate only; family confirmation required'):''}${row.month?.adhika?(hi?' · अधिक मास':' · Adhik Maas'):''}`);
  if(row.window){lines.push(`${tithiLabel(row.window.number,language)}: ${time(row.window.start)} → ${time(row.window.end)}`);for(const day of row.candidates)lines.push(`${day.date} · ${hi?'अपराह्न':'Aparahna'}: ${time(day.aparahnaStart)} → ${time(day.aparahnaEnd)}`);}
 }
 lines.push('',(hi?'सावधानियाँ':'Warnings')+': '+(result.warnings.join(', ')||'none'),'Method: '+methodology.engine+'; '+methodology.precision,'Month classification: Chitra/Spica-aligned sidereal Sun; not exact Lahiri. All times IST.','All entered details stay in tab memory; no API or saved server record.','Sources:',...methodology.sources.map(source=>source.name+' — '+source.url));return lines.join('\n');
}
