const p=(en,hi)=>({en,hi});
export function addSeedha(guides,sources){
 sources.seedha={title:'Panda Ji · Shraddha preparation list',url:'https://www.pandaji.live/puja-samagri/pitru-amavasya-shraddha-samagri',scope:p('A priest-service example lists flour, pulses, rice, ghee and sugar for raw-food donation. It does not establish universal quantities or your temple’s annual-rite rules.','पुरोहित सेवा का एक उदाहरण सीधा में आटा, दाल, चावल, घी और चीनी बताता है। इससे सार्वभौमिक मात्रा या आपके मंदिर की बरसी-विधि तय नहीं होती।')};
 sources.templeFood={title:'Yugal Kunj · Temple kitchen food donation',url:'https://yugalkunj.org/fooddonation',scope:p('The temple accepts grocery donations and asks donors to discuss items and quantities. This is kitchen-donation guidance, not a universal Shraddha prescription.','मंदिर राशन दान स्वीकार करता है और सामग्री व मात्रा पहले बताने को कहता है। यह रसोई दान का संदर्भ है, सबके लिए श्राद्ध का विधान नहीं।')};
 const guide=guides.find(g=>g.id==='shraddha');
 guide.title=p('Shraddha / Barsi / Samvatsari remembrance','श्राद्ध / बरसी / संवत्सरी स्मरण');
 guide.summary=p('Ancestral remembrance and temple Seedha preparation.','पितृ स्मरण और मंदिर में सीधा देने की तैयारी।');
 const group=p('Temple Seedha · confirm acceptance','मंदिर के लिए सीधा · स्वीकृति तय करें');
 const row=(id,en,hi,noteEn,noteHi)=>({id,label:p(en,hi),kind:'confirm',group,note:p(noteEn,noteHi)});
 guide.items.push(
  row('seedha-flour','Seedha: wheat flour / atta','सीधा: गेहूँ का आटा','Ask whether the temple wants flour or whole wheat; agree quantity.','मंदिर से पूछें कि आटा चाहिए या साबुत गेहूँ; मात्रा तय करें।'),
  row('seedha-rice','Seedha: uncooked rice','सीधा: कच्चे चावल','Pack clean, dry rice separately; confirm variety and quantity.','स्वच्छ, सूखे चावल अलग पैक करें; किस्म और मात्रा तय करें।'),
  row('seedha-dal','Seedha: pulses / dal','सीधा: दाल','Use the dal accepted by this temple; no single variety is prescribed here.','इस मंदिर में स्वीकार दाल लें; यहाँ कोई एक दाल अनिवार्य नहीं।'),
  row('seedha-ghee','Seedha: ghee','सीधा: घी','Use a clean, closed container; confirm type and quantity.','स्वच्छ, बंद डिब्बे में रखें; प्रकार और मात्रा तय करें।'),
  row('seedha-sugar','Seedha: sugar','सीधा: चीनी','Confirm acceptance and quantity; ask before substituting jaggery.','स्वीकृति और मात्रा तय करें; गुड़ का विकल्प लेने से पहले पूछें।'),
  row('seedha-extras','Seedha: any additional groceries requested','सीधा: मंदिर से माँगी अतिरिक्त राशन सामग्री','Salt, spices or oil only if the temple asks for them; these are not automatically required.','नमक, मसाले या तेल मंदिर के कहने पर ही लें; ये अपने आप अनिवार्य नहीं।'),
  row('seedha-fresh','Optional: fruit / fresh vegetables','वैकल्पिक: फल / ताजी सब्जियाँ','Bring only accepted items, at the agreed time, without spoilage.','स्वीकार सामग्री ही तय समय पर दें; खराब या बासी सामग्री न दें।'),
  row('seedha-dakshina','Optional: agreed dakshina / donation','वैकल्पिक: तय दक्षिणा / दान','Agree with the temple and stay within your means; the app prescribes no amount.','मंदिर से तय करें और अपनी क्षमता में दें; ऐप कोई राशि तय नहीं करता।')
 );
 guide.sections=[...(guide.sections||[]),{title:p('Temple Seedha for Shraddha & Barsi / Samvatsari','श्राद्ध और बरसी / संवत्सरी पर मंदिर में सीधा'),body:p('Seedha means uncooked food ingredients given for a meal or donation in some family traditions. Start by asking your temple whether it accepts this on the planned observance, which ingredients it needs, how many recipients or meals to arrange for, and the quantities. The list above is a practical starting point, not a compulsory package. Pack dry groceries separately in clean containers; check freshness and expiry dates. Confirm the delivery time, recipient and your family’s remembrance/sankalp details privately with the officiant. Ask separately whether cloth or any other donation is customary. Giving Seedha alone does not establish that tarpan, pinda offerings or the family’s complete rite has been performed.','कुछ पारिवारिक परंपराओं में भोजन या दान के लिए दी जाने वाली कच्ची खाद्य सामग्री को सीधा कहते हैं। पहले अपने मंदिर से पूछें कि तय श्राद्ध या बरसी / संवत्सरी पर वह इसे स्वीकार करता है या नहीं, कौन सी सामग्री चाहिए, कितने लोगों या भोजन के लिए व्यवस्था करनी है और कितनी मात्रा चाहिए। ऊपर की सूची तैयारी का आधार है, अनिवार्य पैकेट नहीं। सूखा राशन अलग-अलग स्वच्छ डिब्बों या थैलियों में पैक करें; ताजगी और समाप्ति तिथि जाँचें। देने का समय, प्राप्तकर्ता और परिवार के स्मरण/संकल्प का विवरण पुरोहित से निजी रूप से तय करें। वस्त्र या अन्य दान की पारिवारिक रीति अलग से पूछें। केवल सीधा देने से तर्पण, पिंडदान या परिवार की पूरी विधि संपन्न हुई मान लेना उचित नहीं।')}];
 guide.questions.push(p('What Seedha does this temple accept for our Shraddha or Barsi/Samvatsari, in what quantities and at what time?','हमारे श्राद्ध या बरसी/संवत्सरी के लिए यह मंदिर कौन सा सीधा, कितनी मात्रा में और किस समय स्वीकार करेगा?'));
 guide.sources.push('seedha','templeFood');
}
