const p=(en,hi)=>({en,hi});
export function addSeedha(guides,sources){
 sources.seedha={title:'Panda Ji · Shraddha preparation list',url:'https://www.pandaji.live/puja-samagri/pitru-amavasya-shraddha-samagri',scope:p('A priest-service example lists flour, pulses, rice, ghee and sugar for raw-food donation. It does not establish universal quantities or your temple’s annual-rite rules.','पुरोहित सेवा का एक उदाहरण सीधा में आटा, दाल, चावल, घी और चीनी बताता है। इससे सार्वभौमिक मात्रा या आपके मंदिर की बरसी-विधि तय नहीं होती।')};
 sources.templeFood={title:'Yugal Kunj · Temple kitchen food donation',url:'https://yugalkunj.org/fooddonation',scope:p('The temple accepts grocery donations and asks donors to discuss items and quantities. This is kitchen-donation guidance, not a universal Shraddha prescription.','मंदिर राशन दान स्वीकार करता है और सामग्री व मात्रा पहले बताने को कहता है। यह रसोई दान का संदर्भ है, सबके लिए श्राद्ध का विधान नहीं।')};
 const guide=guides.find(g=>g.id==='shraddha');
 guide.title=p('Shraddha / Barsi / Samvatsari remembrance','श्राद्ध / बरसी / संवत्सरी स्मरण');
 guide.summary=p('Ancestral remembrance and temple Seedha preparation.','पितृ स्मरण और मंदिर में सीधा देने की तैयारी।');
 const group=p('Temple Seedha · confirm acceptance','मंदिर के लिए सीधा · स्वीकृति तय करें');
 const row=(id,en,hi,noteEn,noteHi)=>({id,label:p(en,hi),kind:'confirm',group,note:p(noteEn,noteHi)});
 guide.items.push(
  row('seedha-flour','Seedha: wheat flour / atta','सीधा: गेहूँ का आटा','Choose flour or whole wheat according to family custom. Keep enough, with the other groceries, to comfortably prepare a meal for about 1–2 people.','आटा या साबुत गेहूँ परिवार की रीति अनुसार लें। दूसरी सामग्री के साथ लगभग 1–2 लोगों का भोजन आराम से बन सके, इतनी मात्रा रखें।'),
  row('seedha-rice','Seedha: uncooked rice','सीधा: कच्चे चावल','Pack clean, dry rice separately. Choose variety and quantity according to family custom and the planned meal for about 1–2 people.','स्वच्छ, सूखे चावल अलग पैक करें। किस्म और मात्रा परिवार की रीति और लगभग 1–2 लोगों के तय भोजन के अनुसार रखें।'),
  row('seedha-dal','Seedha: pulses / dal','सीधा: दाल','Choose dal according to family custom, with enough for the planned meal. Check that the recipient accepts it; no single variety is prescribed here.','परिवार की रीति के अनुसार तय भोजन के लिए पर्याप्त दाल लें। प्राप्तकर्ता की स्वीकृति पूछें; यहाँ कोई एक दाल अनिवार्य नहीं।'),
  row('seedha-ghee','Seedha: ghee','सीधा: घी','Use a clean, closed container. Choose type and quantity according to family custom and the planned cooking.','स्वच्छ, बंद डिब्बे में रखें। प्रकार और मात्रा परिवार की रीति और तय भोजन की जरूरत अनुसार रखें।'),
  row('seedha-sugar','Seedha: sugar','सीधा: चीनी','Choose quantity according to family custom and the planned preparation; ask family before substituting jaggery.','मात्रा परिवार की रीति और तय पकवान अनुसार रखें; गुड़ का विकल्प लेने से पहले परिवार से पूछें।'),
  row('seedha-extras','Seedha: customary additional groceries','सीधा: पारिवारिक रीति की अतिरिक्त राशन सामग्री','Salt, spices or oil according to family custom and the planned meal, if accepted by the recipient; these are not automatically required.','नमक, मसाले या तेल परिवार की रीति और तय भोजन अनुसार, प्राप्तकर्ता की स्वीकृति होने पर लें; ये अपने आप अनिवार्य नहीं।'),
  row('seedha-fresh','Optional: fruit / fresh vegetables','वैकल्पिक: फल / ताजी सब्जियाँ','Bring only accepted items, at the agreed time, without spoilage.','स्वीकार सामग्री ही तय समय पर दें; खराब या बासी सामग्री न दें।'),
  row('seedha-dakshina','Optional: agreed dakshina / donation','वैकल्पिक: तय दक्षिणा / दान','Give according to family custom, personal willingness and means; the app prescribes no amount.','परिवार की रीति, अपनी श्रद्धा और क्षमता अनुसार दें; ऐप कोई राशि तय नहीं करता।')
 );
 guide.sections=[...(guide.sections||[]),{title:p('Temple Seedha for Shraddha & Barsi / Samvatsari','श्राद्ध और बरसी / संवत्सरी पर मंदिर में सीधा'),body:p('Seedha means uncooked food ingredients given for a meal or donation in some family traditions. Choose materials and quantities according to your family’s Shraddha/Barsi custom, personal willingness and means. For the family practice described here, keep enough groceries together to comfortably cook one meal for about 1–2 people; appetite, the chosen dishes and family practice may change the amounts. This is not a fixed religious measure. Ask the temple only about accepting the materials and the delivery time. The list above is a practical starting point, not a compulsory package. Pack dry groceries separately in clean containers; check freshness and expiry dates. Confirm the delivery time, recipient and your family’s remembrance/sankalp details privately with the officiant. Ask separately whether cloth or any other donation is customary. Seedha, tarpan and pinda offerings have different roles in different traditions. Discuss what your family chooses to observe; this guide does not judge whether anyone’s remembrance is complete.','कुछ पारिवारिक परंपराओं में भोजन या दान के लिए दी जाने वाली कच्ची खाद्य सामग्री को सीधा कहते हैं। सामग्री और मात्रा परिवार की श्राद्ध/बरसी की रीति, अपनी श्रद्धा और क्षमता अनुसार रखें। यहाँ बताई पारिवारिक व्यवस्था के लिए इतनी सामग्री साथ रखें कि लगभग 1–2 लोगों का एक समय का भोजन आराम से बन जाए; भूख, तय पकवान और पारिवारिक रीति के अनुसार मात्रा बदल सकती है। यह कोई निश्चित शास्त्रीय माप नहीं है। मंदिर से केवल सामग्री स्वीकार करने और देने के समय की पुष्टि करें। ऊपर की सूची तैयारी का आधार है, अनिवार्य पैकेट नहीं। सूखा राशन अलग-अलग स्वच्छ डिब्बों या थैलियों में पैक करें; ताजगी और समाप्ति तिथि जाँचें। देने का समय, प्राप्तकर्ता और परिवार के स्मरण/संकल्प का विवरण पुरोहित से निजी रूप से तय करें। वस्त्र या अन्य दान की पारिवारिक रीति अलग से पूछें। सीधा, तर्पण और पिंडदान की भूमिका परंपरा के अनुसार अलग होती है। आपका परिवार जो पालन करना चाहता है, वह आपस में तय करें; यह मार्गदर्शिका किसी के स्मरण को पूर्ण या अपूर्ण घोषित नहीं करती।')}];
 guide.questions.push(p('What materials and quantities suit our family’s Shraddha/Barsi custom and a meal for about 1–2 people? Does the temple accept them, and when should we deliver?','परिवार की श्राद्ध/बरसी की रीति और लगभग 1–2 लोगों के भोजन के लिए कौन सी सामग्री व मात्रा रखें? क्या मंदिर इसे स्वीकार करेगा और किस समय देना है?'));
 guide.sources.push('seedha','templeFood');
}
