import {istDate} from '/daily-spark/engine.mjs';
import {mountSpark} from '/daily-spark/play.mjs';
import {sparkMarkup} from '/daily-spark/view.mjs';
import {version,validDay,oddRound,memoryGame,memorySymbols,turnMemory,closeMemoryPair,clues,clueFor,acceptsClue,parseChoices,faceOff,chooseFace,shuffle} from './engine.mjs';
const $=s=>document.querySelector(s),media=matchMedia('(prefers-color-scheme: dark)');
$('#theme').outerHTML=SynapseTheme.control('id="theme"');function theme(){const p=SynapseTheme.read();document.documentElement.dataset.theme=p==='system'?(media.matches?'dark':'light'):p;}$('#theme').addEventListener('change',theme);media.addEventListener('change',theme);theme();
const params=new URLSearchParams(location.search),today=istDate(),day=validDay(params.get('day'),today)&&(!params.get('v')||params.get('v')===version)?params.get('day'):today;
const games={24:{name:'Make 24',description:'The original Daily Spark number game. Use every number once to make 24.',next:'odd'},odd:{name:'Oddly Different',description:'One tile points a little differently. Find it in five rounds, at your own pace.',next:'memory'},memory:{name:'Memory Minute',description:'Turn over two cards and find six matching pairs. “Minute” is a little break, not a time limit.',next:'clue'},clue:{name:'Clue Club',description:'Guess an everyday thing from up to three clues. English and Hindi answers are welcome.',next:'face'},face:{name:'Face-Off',description:'Choose between two options until your favourite is left. This is your preference, not a random draw.',next:'24'}};
const controllers={},panes={};let active=null;
const element=(tag,className,text)=>{const e=document.createElement(tag);e.className=className;e.textContent=text;return e;};
const nonce=()=>String(crypto.getRandomValues(new Uint32Array(1))[0]);
function url(game,date=day){const u=new URL('/take-a-break',location.origin);u.searchParams.set('game',game);if(game!=='face'){u.searchParams.set('day',date);u.searchParams.set('v',version);}return u.href;}
async function share(text){try{if(navigator.share){await navigator.share({title:'Take a Break · Sushant Synapse',text});return;}if(navigator.clipboard){await navigator.clipboard.writeText(text);$('#link-note').textContent='Message copied. Share it when you like.';return;}}catch(e){if(e.name==='AbortError')return;}$('#share-box').hidden=false;$('#share-message').value=text;$('#share-message').focus();$('#share-message').select();}
$('#close-share').onclick=()=>{$('#share-box').hidden=true;$('#play-title').focus();};
function result(root,id,title,summary,getShare){
 let card=root.querySelector('.result-card');if(!card){card=element('section','result-card','');root.append(card);}card.replaceChildren(element('h3','',title),element('p','',summary));card.hidden=false;
 const actions=element('div','actions',''),shareButton=element('button','','Share '+(id==='face'?'winner':'result'));shareButton.type='button';shareButton.onclick=()=>share(getShare());
 const next=element('button','','Try '+games[games[id].next].name);next.type='button';next.onclick=()=>openGame(games[id].next);actions.append(shareButton,next);card.append(actions,element('p','fine','Or stop here. Your break, your pace.'));
}
function hideResult(root){const card=root.querySelector('.result-card');if(card)card.hidden=true;}
function challengeText(id,mode,summary){return `${games[id].name} · Sushant Synapse\n${mode==='daily'?day+' (IST)':'Practice · not the daily board'}\n${summary}\n${url(id,mode==='daily'?day:today)}`;}
function mountOdd(root){
 root.innerHTML='<section class="game-card"><div class="progress-line"><span class="round"></span><span class="mistakes"></span></div><div class="board odd-board" aria-label="Find the different tile"></div><p class="status" role="status"></p><button class="odd-hint" type="button">Narrow it down</button></section>';
 const card=root.querySelector('.game-card'),board=root.querySelector('.board'),status=root.querySelector('.status');let seed,mode,round,mistakes,helps,hint,done,data;
 const paths={arrow:'<path d="M8 24h32m-12-12 12 12-12 12"/>',flag:'<path d="M14 40V8h25l-5 7 5 7H14"/>',key:'<circle cx="15" cy="24" r="8"/><path d="M23 24h19m-5 0v7m-7-7v5"/>'};
 function render(){data=oddRound(seed,Math.min(round,4));root.querySelector('.round').textContent=`Round ${Math.min(round+1,5)} / 5`;root.querySelector('.mistakes').textContent=`${mistakes} extra ${mistakes===1?'try':'tries'} · ${helps} hints`;board.dataset.size=data.size;
  const candidates=hint?shuffle(data.cells.map((_,i)=>i).filter(i=>i!==data.oddIndex),`${seed}:hint:${round}`).slice(0,2).concat(data.oddIndex):[];
  board.replaceChildren(...data.cells.map((cell,i)=>{const b=element('button','odd-tile'+(candidates.includes(i)?' candidate':''),'');b.type='button';b.disabled=done;b.setAttribute('aria-label',`Tile ${i+1}: ${cell.glyph}, rotated ${cell.angle} degrees`);b.innerHTML=`<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><g transform="rotate(${cell.angle} 24 24)">${paths[cell.glyph]}</g></svg>`;
   b.onclick=()=>{if(i!==data.oddIndex){mistakes++;status.textContent='Look at how each symbol points. Have another gentle try.';render();board.children[i]?.focus();return;}round++;hint=false;if(round===5){done=true;status.textContent='Five differences found. A good little reset.';render();result(card,'odd','A fresh pair of eyes.',`${mistakes} extra tries · ${helps} hints · five rounds complete.`,()=>challengeText('odd',mode,`Five rounds · ${mistakes} extra tries · ${helps} hints`));card.querySelector('.result-card button').focus();}else{status.textContent='Found it. Here is the next pattern.';render();board.children[0].focus();}};return b;}));root.querySelector('.odd-hint').disabled=done||hint;
 }
 root.querySelector('.odd-hint').onclick=()=>{hint=true;helps++;status.textContent='The different tile is one of the three outlined tiles.';render();};
 const controller={get mode(){return mode;},reset(practice=false){mode=practice?'practice':'daily';seed=practice?nonce():day;round=0;mistakes=0;helps=0;hint=false;done=false;hideResult(card);status.textContent='Look closely. Tap the tile that points differently.';render();}};controller.reset();return controller;
}
function mountMemory(root){
 root.innerHTML='<section class="game-card"><div class="progress-line"><span class="pairs"></span><span class="moves"></span></div><div class="board memory-board" aria-label="Memory cards"></div><p class="status" role="status"></p><button class="continue-pair" type="button" hidden>Turn these back over</button></section>';
 const card=root.querySelector('.game-card'),board=root.querySelector('.board'),status=root.querySelector('.status'),close=root.querySelector('.continue-pair');let state,mode;
 function render(){root.querySelector('.pairs').textContent=`${state.matched.length/2} / 6 pairs`;root.querySelector('.moves').textContent=`${state.moves} moves`;close.hidden=state.open.length!==2;
  board.replaceChildren(...state.cards.map((value,i)=>{const visible=state.open.includes(i)||state.matched.includes(i),matched=state.matched.includes(i),symbol=memorySymbols[value],b=element('button','memory-tile'+(matched?' matched':''),visible?symbol.mark:'?');b.type='button';b.disabled=matched||state.open.length===2&&!state.open.includes(i);b.setAttribute('aria-label',`Card ${i+1}: ${visible?symbol.name:'face down'}${matched?', matched':''}`);b.setAttribute('aria-pressed',String(visible));b.onclick=()=>{const before=state;state=turnMemory(state,i);if(before===state)return;render();if(state.matched.length===12){status.textContent='All six pairs found.';result(card,'memory','A lovely little match.',`Six pairs in ${state.moves} moves. No clock to beat.`,()=>challengeText('memory',mode,`Six pairs in ${state.moves} moves`));card.querySelector('.result-card button').focus();}else if(state.open.length===2){status.textContent='Different symbols. Take a look, then turn them back when you are ready.';close.focus();}else{status.textContent=state.open.length?'Choose one more card.':'A pair found. Keep going when you like.';board.querySelector('button:not(:disabled)')?.focus();}};return b;}));
 }
 close.onclick=()=>{state=closeMemoryPair(state);status.textContent='Try another pair.';render();board.querySelector('button:not(:disabled)')?.focus();};
 const controller={get mode(){return mode;},reset(practice=false){mode=practice?'practice':'daily';state=memoryGame(practice?nonce():day);hideResult(card);status.textContent='Turn over a card to begin.';render();}};controller.reset();return controller;
}
function mountClue(root){
 root.innerHTML='<section class="game-card"><label class="language">Clue language<select aria-label="Clue language"><option value="en">English</option><option value="hi">हिन्दी</option></select></label><ol class="clue-list"></ol><div class="actions"><button class="next-clue" type="button">Show next clue</button><button class="reveal-answer" type="button">Reveal answer</button></div><form class="guess-form"><label>Your guess<input name="guess" maxlength="80" required autocomplete="off"></label><button class="primary" type="submit">Check guess</button></form><p class="status" role="status"></p></section>';
 const card=root.querySelector('.game-card'),list=root.querySelector('.clue-list'),language=root.querySelector('select'),status=root.querySelector('.status'),form=root.querySelector('form');let clue,count,guesses,done,revealed,mode;
 if(params.get('lang')==='hi')language.value='hi';
 function render(){list.replaceChildren(...clue[language.value].slice(0,count).map(text=>{const li=element('li','',text);li.lang=language.value;return li;}));root.querySelector('.next-clue').disabled=done||count===3;root.querySelector('.reveal-answer').disabled=done;form.querySelector('button').disabled=done;form.elements.guess.disabled=done;}
 function finish(show){done=true;revealed=show;render();const answer=language.value==='hi'?clue.answers.at(-1):clue.answers[0];status.textContent=show?'Answer revealed. A little curiosity still counts.':'That is it!';result(card,'clue',show?'The answer is '+answer:'It clicked: '+answer,`${count} of 3 clues · ${guesses} guesses${show?' · answer revealed':''}`,()=>challengeText('clue',mode,show?'Answer revealed · no spoiler here':`Solved with ${count}/3 clues · ${guesses} guesses`));}
 language.onchange=render;root.querySelector('.next-clue').onclick=()=>{count++;render();status.textContent='One more clue, when you need it.';};root.querySelector('.reveal-answer').onclick=()=>finish(true);
 form.onsubmit=e=>{e.preventDefault();const guess=form.elements.guess.value.trim();if(!guess)return;guesses++;if(acceptsClue(clue,guess))finish(false);else{status.textContent='Not this one. Try another word or open the next clue.';form.elements.guess.select();}};
 const controller={get mode(){return mode;},reset(practice=false){mode=practice?'practice':'daily';const candidate=clueFor(practice?nonce():day);clue=practice&&candidate===clue?clues[(clues.indexOf(clue)+1)%clues.length]:candidate;count=1;guesses=0;done=false;revealed=false;form.reset();hideResult(card);status.textContent='One clue to start. You can ask for two more.';render();}};controller.reset();return controller;
}
function mountFace(root){
 root.innerHTML='<div class="face-layout"><form class="face-editor"><h2>What are we choosing?</h2><label>Face-Off title<input name="title" value="Our lunch favourite" maxlength="100"></label><label>Choices, one per line<textarea name="choices" rows="8" maxlength="2000"></textarea></label><p class="fine">2–16 different choices. Only the winner and title are included when you choose to share. Your full list stays in this tab.</p><div class="actions"><button class="primary" type="submit">Start Face-Off</button><button class="face-sample" type="button">Weekend ideas</button></div><p class="face-error status" role="status"></p></form><section class="game-card"><div class="progress-line"><span class="face-round"></span><span class="face-remaining"></span></div><h2 class="face-title"></h2><div class="face-pair"></div><p class="status face-status" role="status"></p><button class="face-undo" type="button" disabled>Undo last choice</button><ol class="face-history"></ol></section></div>';
 root.querySelector('.face-layout').prepend(root.querySelector('.game-card'));
 const form=root.querySelector('form'),card=root.querySelector('.game-card'),pair=root.querySelector('.face-pair'),status=root.querySelector('.face-status'),error=root.querySelector('.face-error');let state,undo=[],title;
 form.elements.choices.value=['Dosa','Poha','Idli','Paratha','Upma','Pulao','Khichdi','Sandwich'].join('\n');
 function render(){root.querySelector('.face-title').textContent=title;root.querySelector('.face-round').textContent=state.winner?'Your favourite':`Round ${state.round}`;root.querySelector('.face-remaining').textContent=`${state.picks.length} comparisons`;root.querySelector('.face-undo').disabled=!undo.length;
  pair.replaceChildren(...(state.winner?[]:state.contenders.slice(0,2)).map((choice,i)=>{const b=element('button','',choice);b.type='button';b.onclick=()=>{undo.push(structuredClone(state));state=chooseFace(state,i);render();if(!state.winner)pair.children[0]?.focus();};return b;}));root.querySelector('.face-history').replaceChildren(...state.picks.map(p=>element('li','',`${p.winner} over ${p.other}`)));
  if(state.winner){status.textContent='Your favourite is '+state.winner+'.';result(card,'face',state.winner,`Your choice after ${state.picks.length} comparisons.`,()=>`Face-Off · Sushant Synapse\n${title}\nMy favourite: ${state.winner}\nMake your own choices: ${url('face')}`);}else{status.textContent='Which would you rather choose?';hideResult(card);}
 }
 function start(){try{const choices=parseChoices(form.elements.choices.value),newTitle=form.elements.title.value.trim();if(newTitle.length>100)throw Error('Keep the title under 100 characters.');title=newTitle||'My favourite';state=faceOff(choices,day);undo=[];error.textContent='';render();return true;}catch(e){error.textContent=e.message;return false;}}
 form.onsubmit=e=>{e.preventDefault();if(start())pair.children[0]?.focus();};root.querySelector('.face-sample').onclick=()=>{form.elements.choices.value=['A walk','A film','A book','Cooking','A nap','Calling a friend'].join('\n');form.elements.title.value='A little weekend plan';start();};root.querySelector('.face-undo').onclick=()=>{state=undo.pop();render();pair.children[0]?.focus();};start();return {mode:'custom',reset:start};
}
function openGame(id,update=true){if(!Object.hasOwn(games,id))return;active=id;$('#hub').hidden=true;$('#play-area').hidden=false;$('#share-box').hidden=true;$('#play-title').textContent=games[id].name;$('#play-description').textContent=games[id].description;$('#hub-edition').textContent=id==='face'?'YOUR CHOICES · NO UPLOAD':`${day} · IST`;
 if(!panes[id]){const root=element('div','game-pane','');root.dataset.pane=id;$('#game-panes').append(root);panes[id]=root;
  if(id==='24'){root.innerHTML=sparkMarkup;mountSpark(root,{day,challengeUrl:date=>url('24',date),onComplete:()=>{const section=root.querySelector('#result');if(!section.querySelector('[data-next-break]')){const next=element('button','','Try Oddly Different');next.type='button';next.dataset.nextBreak='1';next.onclick=()=>openGame('odd');section.append(next);}}});}
  else controllers[id]=({odd:mountOdd,memory:mountMemory,clue:mountClue,face:mountFace}[id])(root);
 }
 Object.entries(panes).forEach(([key,pane])=>pane.hidden=key!==id);$('#round-controls').hidden=id==='24'||id==='face';syncMode();$('#link-note').textContent='';if(update)history.replaceState(null,'',url(id));$('#play-title').focus({preventScroll:true});scrollTo(0,0);
}
function syncMode(){const mode=controllers[active]?.mode;$('#daily-mode').setAttribute('aria-pressed',String(mode==='daily'));$('#practice-mode').setAttribute('aria-pressed',String(mode==='practice'));$('#hub-edition').textContent=active==='face'?'YOUR CHOICES · NO UPLOAD':mode==='practice'?'PRACTICE · NEW BOARD':`${day} · IST`;}
$('#daily-mode').onclick=()=>{controllers[active]?.reset(false);syncMode();};$('#practice-mode').onclick=()=>{controllers[active]?.reset(true);syncMode();};$('#challenge-friend').onclick=()=>share(`A little challenge for you: ${games[active].name}\n${url(active)}\nTake a Break · Sushant Synapse`);
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$('#surprise').onclick=()=>openGame(Object.keys(games)[crypto.getRandomValues(new Uint32Array(1))[0]%5]);
$('#all-breaks').onclick=()=>{$('#hub').hidden=false;$('#play-area').hidden=true;$('#share-box').hidden=true;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter==='all')));document.querySelectorAll('.break-card').forEach(card=>card.hidden=false);history.replaceState(null,'','/take-a-break');const card=document.querySelector(`[data-game="${active}"]`);card?.focus({preventScroll:true});scrollTo(0,0);};
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(button=>button.setAttribute('aria-pressed',String(button===b)));document.querySelectorAll('.break-card').forEach(card=>card.hidden=b.dataset.filter!=='all'&&card.dataset.kind!==b.dataset.filter);});
$('#daily-note').textContent=`${day} · New daily challenges at midnight IST`;
const initial=params.get('game');if(initial&&Object.hasOwn(games,initial))openGame(initial,false);
if(params.has('day')&&params.get('day')!==day||params.has('v')&&params.get('v')!==version){const message=element('p','quiet-note','That shared date or version is unavailable. Today’s challenges are ready instead.');$('#main').prepend(message);}
