import {clues} from './clues.mjs';
export {clues};export const version='1';
export function random(seed){let state=2166136261;for(const c of `break-v1:${seed}`)state=Math.imul(state^c.charCodeAt(0),16777619)>>>0;return()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};}
export function shuffle(values,seed){const result=[...values],next=random(seed);for(let i=result.length-1;i>0;i--){const j=Math.floor(next()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
export function validDay(value,today){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value&&value<=today;}
export function oddRound(seed,round){if(!Number.isInteger(round)||round<0||round>4)throw Error('Choose a round from 1 to 5.');const next=random(`${seed}:odd:${round}`),size=[3,4,4,5,5][round],oddIndex=Math.floor(next()*size*size),glyph=['arrow','flag','key'][Math.floor(next()*3)],angle=Math.floor(next()*4)*90,offset=[90,90,45,30,15][round];return {size,oddIndex,glyph,cells:Array.from({length:size*size},(_,i)=>({glyph,angle:i===oddIndex?(angle+offset)%360:angle}))};}
export const memorySymbols=[{mark:'★',name:'star'},{mark:'♥',name:'heart'},{mark:'◆',name:'diamond'},{mark:'☀',name:'sun'},{mark:'☂',name:'umbrella'},{mark:'♣',name:'club'}];
export function memoryGame(seed){return {cards:shuffle([0,0,1,1,2,2,3,3,4,4,5,5],`${seed}:memory`),open:[],matched:[],moves:0};}
export function turnMemory(state,index){if(!Number.isInteger(index)||index<0||index>=state.cards.length)throw Error('Choose a card on the board.');if(state.open.length===2||state.open.includes(index)||state.matched.includes(index))return state;const next={...state,open:[...state.open,index],matched:[...state.matched]};if(next.open.length===2){next.moves++;if(next.cards[next.open[0]]===next.cards[next.open[1]]){next.matched.push(...next.open);next.open=[];}}return next;}
export function closeMemoryPair(state){return {...state,open:[]};}
export function normalizeAnswer(value){return String(value).normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{M}\p{N}]/gu,'');}
export function clueFor(seed){const ordinal=/^\d{4}-\d{2}-\d{2}$/.test(seed)?Math.floor(Date.parse(seed)/86400000):Math.floor(random(`${seed}:clue`)()*100000);return clues[((ordinal%clues.length)+clues.length)%clues.length];}
export function acceptsClue(clue,guess){const normalized=normalizeAnswer(guess);return !!normalized&&clue.answers.some(answer=>normalizeAnswer(answer)===normalized);}
export function parseChoices(text){if(typeof text!=='string'||text.length>2000)throw Error('Keep your list under 2,000 characters.');const choices=text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(choices.length<2||choices.length>16||choices.some(s=>s.length>60))throw Error('Use 2–16 choices, up to 60 characters each.');if(new Set(choices.map(s=>s.normalize('NFKC').toLowerCase())).size!==choices.length)throw Error('Give each choice a different name.');return choices;}
export function faceOff(choices,seed){parseChoices(choices.join('\n'));return {contenders:shuffle(choices,`${seed}:face`),winners:[],round:1,picks:[],winner:null};}
export function chooseFace(state,index){if(state.winner||![0,1].includes(index)||state.contenders.length<2)throw Error('Choose one of the two options.');const next={...state,contenders:state.contenders.slice(2),winners:[...state.winners,state.contenders[index]],picks:[...state.picks,{winner:state.contenders[index],other:state.contenders[1-index],round:state.round}]};if(next.contenders.length===1){next.winners.push(next.contenders[0]);next.contenders=[];}if(!next.contenders.length){if(next.winners.length===1){next.winner=next.winners[0];next.winners=[];}else{next.contenders=next.winners;next.winners=[];next.round++;}}return next;}
