const {test}=require('node:test'),assert=require('node:assert/strict');

test('reviewed material details export bilingual notes and preserve ceremony-specific requirements',async()=>{const {guides,guideById,checklistText,sources}=await import('../apps/ritual-assist/frontend/guides.mjs');const havan=guideById('havan');assert.equal(havan.items.length,15);assert.equal(new Set(havan.items.map(i=>i.group.en)).size,3);assert.match(sources.havan.url,/hindutemplechs/);for(const language of ['en','hi']){for(const guide of guides)assert.ok(guide.materialReview[language]);const text=checklistText(havan,language);for(const item of havan.items){assert.ok(item.note[language]);assert.ok(text.includes(item.note[language]));assert.ok(text.includes(item.group[language]));}}assert.equal(guideById('antyeshti').sections.length,3);assert.ok(guideById('ganesh-puja').items.some(i=>i.id==='modak'));});
test('Ritual Assist guides have bilingual steps, unique items and scoped references',async()=>{
 const {guides,sources,scope}=await import('../apps/ritual-assist/frontend/guides.mjs');assert.equal(guides.length,15);assert.equal(new Set(guides.map(g=>g.id)).size,15);assert.equal(guides.filter(g=>g.category==='shubh').length,8);assert.equal(guides.filter(g=>g.category==='ashubh').length,7);
 for(const guide of guides){assert.ok(guide.steps.length>=4);assert.ok(guide.items.length>=4);assert.equal(new Set(guide.items.map(i=>i.id)).size,guide.items.length);for(const language of ['en','hi']){for(const value of [scope,guide.title,guide.summary,guide.variation,guide.preparation,...guide.steps,...guide.questions,...guide.items.map(i=>i.label)]){assert.ok(value[language]);if(language==='hi')assert.match(value[language],/\p{Script=Devanagari}/u);}}for(const id of guide.sources){assert.ok(sources[id]);assert.equal(new URL(sources[id].url).protocol,'https:');}for(const item of guide.items)assert.ok(['common','confirm'].includes(item.kind));}
 assert.match(sources.death.scope.en,/UK legal procedures do not apply to India/);
});
test('bilingual search, safe links and checklist export preserve per-item completion',async()=>{
 const {guides,findGuides,guideById,checklistText}=await import('../apps/ritual-assist/frontend/guides.mjs');assert.deepEqual(findGuides({category:'ashubh'}).map(g=>g.id),['antyeshti','prarthana-sabha','shraddha','asthi','day-10','day-11','day-12']);assert.ok(findGuides({query:'श्राद्ध'}).some(g=>g.id==='shraddha'));assert.ok(findGuides({query:'  GANESH  '}).some(g=>g.id==='ganesh-puja'));assert.equal(findGuides({query:'<script>'}).length,0);assert.equal(guideById('../../data'),guides[0]);assert.throws(()=>findGuides({category:'unknown'}));assert.throws(()=>checklistText(guides[0],'bad'));
 const guide=guideById('shraddha'),done=new Set(['water']);for(const lang of ['en','hi']){const output=checklistText(guide,lang,done);assert.ok(output.includes('[x] '+guide.items[0].label[lang]));assert.ok(output.includes('[ ] '+guide.items[1].label[lang]));assert.ok(output.includes(guide.variation[lang]));assert.ok(output.includes('https://www.drikpanchang.com/'));assert.ok(output.includes('Sushant Synapse'));}assert.deepEqual([...done],['water']);
});
test('Ritual Assist is public, allowlisted and does not expose app source directories',()=>{
 const {apps}=require('../packages/app-registry'),{staticAssets}=require('../server/static-assets');const app=apps.find(a=>a.id==='ritual-assist');assert.equal(app.public,true);assert.equal(app.status,'Available');for(const route of ['/ritual-assist','/ritual-assist/','/ritual-assist/app.js','/ritual-assist/guides.mjs','/ritual-assist/style.css'])assert.ok(staticAssets[route].startsWith('apps/ritual-assist/frontend/'));assert.equal(staticAssets['/apps/ritual-assist/package.json'],undefined);
});
