const {test}=require('node:test'),assert=require('node:assert/strict');
const engine=import('../apps/ritual-assist/frontend/panchang.mjs');
const input={date:'2025-10-01',time:'12:00',city:'delhi',calendar:'amanta',counting:'civil'};
test('ten upcoming annual and Pitru cycles start today, retain lunar identity and export without duplicates',async()=>{
 const {generateCalendar,calendarRows,calendarText,midnight}=await engine,now=+new Date('2026-10-10T12:00:00+05:30');
 for(const date of ['1980-10-01','2025-10-01','2026-10-09']){const r=generateCalendar({...input,date},{now});assert.equal(r.planningFrom,'2026-10-10');assert.equal(r.upcomingAnnual.length,10);assert.equal(r.upcomingPitru.length,10);for(const [kind,rows]of [['annual',r.upcomingAnnual],['pitru',r.upcomingPitru]]){for(let i=0;i<rows.length;i++){const row=rows[i];assert.equal(row.kind,kind);assert.equal(row.month.adhika,false);assert.ok(row.date?midnight(row.date)>=midnight(r.planningFrom):row.window.end>midnight(r.planningFrom));assert.equal(row.window.number,kind==='annual'?r.tithi:r.pitru.tithi);if(kind==='annual')assert.equal(row.month.index,r.deathMonth.index);else assert.ok(row.window.start>r.annual.window.end);if(i)assert.ok(row.window.start-rows[i-1].window.start>320*86400000);}}const all=calendarRows(r),keys=all.map(row=>row.kind+':'+(row.window?Math.round(row.window.start/60000):row.date));assert.equal(new Set(keys).size,all.length);for(const lang of ['en','hi']){const text=calendarText(r,lang);for(const row of [...r.upcomingAnnual,...r.upcomingPitru])if(row.date)assert.ok(text.includes(row.date));}}
 const unknown=generateCalendar({...input,time:''},{now});assert.deepEqual(unknown.upcomingAnnual,[]);assert.deepEqual(unknown.upcomingPitru,[]);
});
const within=(actual,expected,minutes=3)=>assert.ok(Math.abs(actual-+new Date(expected))<minutes*60000,`${new Date(actual).toISOString()} differs from ${expected}`);
test('independent published 2026 Panchang tithi and sunrise fixtures agree within three minutes',async()=>{const {tithiWindow,daylight,cities,monthAt,observance}=await engine;
 // Drik Panchang: Adhika Purnima 2026 (Dharampur), Delhi 26 September, Patna Amavasya 10 October.
 let t=tithiWindow(+new Date('2026-05-31T12:00:00+05:30'));assert.equal(t.number,15);within(t.start,'2026-05-30T11:57:00+05:30');within(t.end,'2026-05-31T14:14:00+05:30');const m=monthAt(t.start+1000);assert.equal(m.index,2);assert.equal(m.adhika,true);
 t=tithiWindow(+new Date('2026-09-26T12:00:00+05:30'));assert.equal(t.number,15);within(t.end,'2026-09-26T22:18:00+05:30');const light=daylight('2026-09-26',cities[0]);within(light.sunrise,'2026-09-26T06:11:00+05:30',2);within(light.sunset,'2026-09-26T18:13:00+05:30',2);
 t=tithiWindow(+new Date('2026-10-10T12:00:00+05:30'));assert.equal(t.number,30);within(t.start,'2026-10-09T21:35:00+05:30');within(t.end,'2026-10-10T21:19:00+05:30');const row=observance(t,{lat:25.5941,lon:85.1376});assert.equal(row.date,'2026-10-10');within(row.aparahnaStart,'2026-10-10T12:46:00+05:30');within(row.aparahnaEnd,'2026-10-10T15:07:00+05:30');
 t=tithiWindow(+new Date('2026-09-30T12:00:00+05:30'));assert.equal(observance(t,cities[0]).date,'2026-09-30');
});
test('unknown death time produces counted ceremonies but withholds lunar dates',async()=>{const {generateCalendar}=await engine;const r=generateCalendar({...input,time:''});assert.equal(r.early[0].date,'2025-10-04');assert.equal(r.early.at(-1).day,12);assert.equal(r.annual,null);assert.equal(r.monthly.length,0);assert.ok(r.dayWindows.length>=1);assert.ok(r.warnings.includes('time-required'));const resolved=generateCalendar({...input,time:'',confirmedTithi:r.dayWindows[0].number});assert.ok(resolved.annual);assert.throws(()=>generateCalendar({...input,time:'',counting:'sunrise'}),/requires/);});
test('lunar recurrence handles Adhik Maas without treating it as a mandatory regular Masik',async()=>{const {generateCalendar,displayedMonth,calendarText}=await engine;const r=generateCalendar(input);assert.equal(r.tithi,9);assert.equal(r.monthly[0].date,'2025-10-30');assert.equal(r.annual.date,'2026-10-19');assert.equal(r.pitru.date,'2027-09-24');assert.ok(r.pitru.window.start>r.annual.window.end);const extra=r.monthly.find(m=>m.month.adhika);assert.ok(extra.conditional);assert.equal(extra.number,r.monthly.find(m=>m.cycle===extra.cycle+1).number);assert.equal(r.monthly.filter(m=>!m.month.adhika).length,11);const north=generateCalendar({...input,calendar:'purnimanta'});assert.deepEqual(north.monthly.map(m=>m.date),r.monthly.map(m=>m.date));assert.equal(displayedMonth({index:5},16,'purnimanta'),6);assert.match(calendarText(r),/family confirmation required/);});
test('boundary, no-Aparahna and tied dates are withheld rather than guessed',async()=>{const {generateCalendar,tithiWindow,observance,daylight,cities}=await engine;const window=tithiWindow(+new Date('2025-10-01T12:00:00+05:30'));const date=new Date(window.end+330*60000).toISOString(),r=generateCalendar({...input,date:date.slice(0,10),time:date.slice(11,16)});assert.ok(r.warnings.includes('confirm-boundary-tithi'));assert.equal(r.annual,null);const a=daylight('2026-10-01',cities[0]),b=daylight('2026-10-02',cities[0]);assert.equal(observance({number:1,start:a.sunrise,end:a.aparahnaStart-60000},cities[0]).date,null);assert.equal(observance({number:1,start:a.aparahnaEnd-3600000,end:b.aparahnaStart+3600000},cities[0]).status,'two-day-tie');assert.equal(observance({number:1,start:a.aparahnaStart+60000,end:a.aparahnaEnd},cities[0]).date,null);});
test('validation and inclusive early-day counting preserve dates and custom rules',async()=>{const {generateCalendar,validateInput,addDays}=await engine;assert.equal(addDays('2024-02-28',1),'2024-02-29');assert.equal(generateCalendar({...input,time:'04:00',counting:'sunrise',include13:true}).early.at(-1).date,'2025-10-12');for(const invalid of [{date:'2025-02-30'},{date:'2099-01-01'},{city:'custom',lat:'',lon:''},{time:'25:00'},{calendar:'hindu'},{confirmedTithi:31},{confirmedTithi:30}])assert.throws(()=>generateCalendar({...input,...invalid}));assert.throws(()=>validateInput({...input,date:'2026-10-10',time:'23:59'},+new Date('2026-10-10T12:00:00+05:30')),/future/);});
