const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
let child,base,dir;
before(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-ritual-api-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timeout')),15000);child.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve();}});child.once('error',reject);});});
after(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});
const details={date:'2025-10-01',time:'12:00',city:'delhi'};
const post=(input,headers={})=>fetch(base+'/api/ritual-assist/calendar',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(input)});
test('simple public IST request produces early, monthly and ten-year dates without account or database writes',async()=>{
 const {DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(path.join(dir,'chambers.sqlite'),{readOnly:true});const counts=()=>Object.fromEntries(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(({name})=>[name,db.prepare('SELECT COUNT(*) AS n FROM "'+name+'"').get().n]));const before=counts();
 const response=await post(details);assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const {result}=await response.json();assert.equal(result.calculation.processing,'server');assert.equal(result.calculation.stored,false);assert.equal(result.data.calendar,'purnimanta');assert.equal(result.data.counting,'civil');assert.deepEqual(result.early.map(r=>r.day),[4,10,11,12,13]);assert.equal(result.early.find(r=>r.day===10).date,'2025-10-10');assert.equal(result.upcomingAnnual.length,10);assert.equal(result.upcomingPitru.length,10);assert.ok(result.monthly.length>=11);assert.deepEqual(counts(),before);db.close();assert.equal((await fetch(base+'/api/state')).status,401);
});
test('server rejects malformed input, foreign locations, extra personal fields, oversized bodies and cross-site requests',async()=>{
 for(const input of [{...details,time:''},{...details,time:'24:00'},{...details,date:'2025-02-30'},{...details,date:'2099-01-01'},{...details,city:'london'},{...details,name:'Unneeded personal data'},{...details,include13:'true'}])assert.equal((await post(input)).status,400);
 assert.equal((await post({...details,time:'x'.repeat(3000)})).status,413);assert.equal((await post(details,{'Origin':'https://example.org'})).status,403);assert.equal((await fetch(base+'/api/ritual-assist/calendar')).status,405);
 const {calendarInput}=await import('../apps/ritual-assist/backend/calendar-input.mjs');assert.equal(calendarInput({...details,city:'mumbai'}).calendar,'amanta');assert.equal(calendarInput({...details,calendar:'amanta',counting:'sunrise',include13:false}).include13,false);
});
test('public calculation budget bounds repeat work',async()=>{for(let i=0;i<5;i++)assert.equal((await post(details)).status,200);assert.equal((await post(details)).status,429);});
