const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
let child,base,cookie='';const dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-support-')),password='Support test password 2026!';
async function start(){child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timeout')),15000);child.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve();}});child.once('error',reject);});}
async function stop(){if(child.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});}
async function req(route,method='GET',body,session=cookie,headers={}){const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',Cookie:session,...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
before(start);after(async()=>{await stop();fs.rmSync(dir,{recursive:true,force:true});});
test('payment validation rejects unsafe destinations and encodes chosen amounts',async()=>{const {emptySupport,validateSupport,paymentTarget,treats}=await import('../apps/portal/frontend/support-engine.mjs');assert.equal(paymentTarget(emptySupport,treats[0]),'');const config={title:'Test & Example',upiId:'test@bank',paymentUrl:'',isActive:true};for(const treat of treats){const url=new URL(paymentTarget(config,treat));assert.equal(url.protocol,'upi:');assert.equal(url.searchParams.get('am'),String(treat.amount));assert.equal(url.searchParams.get('pn'),config.title);assert.equal(url.searchParams.get('cu'),'INR');}for(const change of [{upiId:'bad'},{title:'<script>'},{paymentUrl:'javascript:alert(1)'},{paymentUrl:'http://example.com'},{paymentUrl:'https://user:pass@example.com'},{paymentUrl:'https://example.com/\nfoo'},{isActive:'true'},{upiId:'',paymentUrl:''}])assert.throws(()=>validateSupport({...config,...change}));assert.equal(paymentTarget({...config,upiId:'',paymentUrl:'https://example.com/pay'},treats[1]),'https://example.com/pay');});
test('public config fails closed; only authenticated owners can validate and persist destinations',async()=>{
 assert.equal((await req('support')).body.isActive,false);assert.equal((await req('platform/support')).status,401);
 const owner=await req('auth/setup','POST',{name:'Support Owner',email:'owner@example.com',firmName:'Test',password});assert.equal(owner.status,201);cookie=owner.cookie;
 const config={title:'Test Recipient',upiId:'test@bank',paymentUrl:'',isActive:true};assert.equal((await req('platform/support','PUT',config,'')).status,401);assert.equal((await req('platform/support','PUT',config,cookie,{Origin:'https://untrusted.example'})).status,403);
 await req('users','POST',{name:'Clerk',email:'clerk@example.com',role:'Clerk',password,appIds:[]});const member=(await req('auth/login','POST',{email:'clerk@example.com',password})).cookie;assert.equal((await req('platform/support','GET',undefined,member)).status,403);assert.equal((await req('platform/support','PUT',config,member)).status,403);
 for(const change of [{upiId:'bad'},{paymentUrl:'javascript:alert(1)'},{isActive:'true'}])assert.equal((await req('platform/support','PUT',{...config,...change})).status,400);
 assert.equal((await req('support','POST',config)).status,405);assert.equal((await req('platform/support','PUT',config)).status,200);assert.deepEqual((await req('support','GET',undefined,'')).body,config);
 await stop();await start();assert.deepEqual((await req('support')).body,config);assert.equal((await req('platform/support','PUT',{...config,isActive:false})).status,200);assert.equal((await req('support')).body.upiId,'');assert.equal((await req('platform/support')).body.upiId,config.upiId);
 for(const route of ['/support','/support/','/support.js','/support-engine.mjs','/support-qr.mjs','/support.css'])assert.equal((await fetch(base+route)).status,200);assert.equal((await fetch(base+'/apps/portal/SUPPORT-QR-LICENSE.txt')).status,404);
});
