const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{Readable}=require('node:stream');
const {create,apply,view}=require('../apps/tournament-lite/backend/engine');
const {score,balls}=require('../apps/tournament-lite/backend/sports');
const {createTournament}=require('../apps/tournament-lite/backend/routes');
const {Store}=require('../apps/advocate/backend/store');
const {DatabaseSync}=require('node:sqlite');
test('Capped games end on the first winning score, including deuce at the cap',()=>{
 const t=setup(2,'Knockout','Badminton',{rules:{points:21,cap:30,bestOf:1}}),m=t.matches[0];
 assert.equal(score(t,m,{games:[[30,29]]}).winner,m.a);
 assert.equal(score(t,m,{games:[[30,28]]}).winner,m.a);
 assert.throws(()=>score(t,m,{games:[[30,4]]}),/rules/);
 assert.throws(()=>score(t,m,{games:[[31,29]]}),/rules/);
});
function setup(n=4,format='Knockout',sport='Chess',extra={}){const t=create({name:'Club Cup',sport,mode:sport==='Cricket'?'Teams':'Singles',format,...extra});apply(t,'participants',{participants:Array.from({length:n},(_,i)=>({name:'Player '+(i+1),seed:i+1}))});apply(t,'generate',{});return t;}
function finish(t){let m;while((m=t.matches.find(x=>!x.result&&x.a&&x.b)))apply(t,'result',{id:m.id,outcome:'white'});return view(t);}
test('Tournament knockout handles 2–64 entries, seeded separation, byes and winner corrections',()=>{for(let n=2;n<=64;n++){const t=setup(n);assert.equal(t.matches.filter(m=>m.result?.bye).length,2**Math.ceil(Math.log2(n))-n);const v=finish(t);assert.equal(v.status,'Completed');assert.equal(v.champion,t.participants[0].id);assert.equal(new Set(t.matches.map(x=>x.id)).size,t.matches.length);}const t=setup(8);finish(t);const m=t.matches[0];apply(t,'result',{id:m.id,outcome:'black'});assert.equal(view(t).champion,null);assert.equal(t.matches.filter(x=>!x.result).length,2);assert.equal(finish(t).champion,m.b);});
test('Round robin covers every pair exactly once, draws, qualifiers and corrections',()=>{for(let n=2;n<=12;n++){const t=setup(n,'League / Round Robin');assert.equal(t.matches.length,n*(n-1)/2);assert.equal(new Set(t.matches.map(m=>[m.a,m.b].sort().join(':'))).size,t.matches.length);for(const round of new Set(t.matches.map(m=>m.round))){const ids=t.matches.filter(m=>m.round===round).flatMap(m=>[m.a,m.b]);assert.equal(ids.length,new Set(ids).size);}}const t=setup(4,'League + Knockout');for(const m of [...t.matches])apply(t,'result',{id:m.id,outcome:'draw'});assert.equal(t.qualified.length,2);assert.equal(view(t).tables.All[0].points,1.5);finish(t);assert.throws(()=>apply(t,'result',{id:t.matches[0].id,outcome:'white'}),/Confirm/);apply(t,'result',{id:t.matches[0].id,outcome:'white',confirmReset:true});assert.equal(view(t).champion,null);assert.equal(t.matches.filter(m=>m.stage==='knockout').length,1);const g=setup(8,'Group Stage + Knockout','Chess',{qualifiers:4,groupCount:2});finish(g);assert.equal(g.qualified.length,4);assert.equal(view(g).status,'Completed');assert.throws(()=>setup(5,'Group Stage + Knockout','Chess',{qualifiers:3}),/equal qualifiers/);});
test('All six sport rules validate series, local boards, chess, overs and aggregate NRR',()=>{for(const sport of ['Badminton','Table Tennis','Pickleball','Carrom']){const t=setup(2,'Knockout',sport,{rules:{points:11,bestOf:3}}),m=t.matches[0];apply(t,'result',{id:m.id,games:[[11,5],[11,7]]});assert.equal(view(t).champion,m.a);assert.throws(()=>score(t,m,{games:[[11,5]]}),/enough/);assert.throws(()=>score(t,m,{games:[[11,5],[11,7],[11,2]]}),/decided/);assert.throws(()=>score(t,m,{games:[[4,4],[11,3]]}),/tied/);if(sport!=='Carrom')assert.throws(()=>score(t,m,{games:[[11,10],[11,7]]}),/rules/);}const chess=setup(2);assert.throws(()=>score(chess,chess.matches[0],{outcome:'draw'}),/replay/);assert.equal(balls('4.3'),27);assert.throws(()=>balls('4.6'));
 const t=setup(2,'League / Round Robin','Cricket',{rules:{overs:10}}),m=t.matches[0];apply(t,'result',{id:m.id,a:{runs:100,wickets:10,overs:'8.2'},b:{runs:101,wickets:4,overs:'9.3'},battingFirst:'a'});const v=view(t),winner=v.tables.All[0];assert.equal(v.champion,m.b);assert.equal(m.result.target,101);assert.equal(m.result.a.balls,60);assert.ok(Math.abs(winner.nrr-(101/9.5-10))<1e-9);assert.throws(()=>score(t,m,{a:{runs:100,wickets:11,overs:10},b:{runs:50,wickets:2,overs:10},battingFirst:'a'}));
});
test('Tournament API protects ownership, publication, revisions and persistence, exports additive SQL',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tournament-test-'));let store=new Store(dir),user={id:'owner',role:'Owner'},allowed=true;let handler=createTournament({store,auth:{hasAppAccess:()=>allowed}});const call=async(method,route='',body={})=>{const req=Readable.from([Buffer.from(JSON.stringify(body))]);req.headers={'content-type':'application/json'};let result;await handler({route:'tournament-lite'+route,method,req,user,json:(status,data)=>{result=data;}});return result;};try{store.create('clients',{name:'Existing client'});const original=store.all('clients');let t=await call('POST','',{name:'Test Cup',sport:'Chess',mode:'Singles',format:'Knockout',contact:'Private contact'});const id=t.id,token=t.publicToken;user=null;await assert.rejects(call('GET'),/sign in/);await assert.rejects(call('GET','/public/'+token),/not shared/);user={id:'other',role:'Owner'};await assert.rejects(call('POST','/'+id,{revision:1,type:'publish',input:{published:true}}),/not found/);user={id:'owner',role:'Clerk'};await assert.rejects(call('GET'),/access/);user.role='Owner';allowed=false;await assert.rejects(call('GET'),/access/);allowed=true;t=await call('POST','/'+id,{revision:1,type:'publish',input:{published:true}});await assert.rejects(call('POST','/'+id,{revision:1,type:'generate'}),/changed/);await assert.rejects(call('POST','/'+id,{revision:2,type:'participants',input:{participants:[{name:'Same'},{name:'Same'}]}}),/unique/);assert.equal((await call('GET')).tournaments[0].participants.length,0);user=null;const pub=await call('GET','/public/'+token);assert.equal(pub.contact,undefined);assert.equal(pub.revision,undefined);await assert.rejects(call('POST','/public/'+token,{type:'publish'}),/sign in/);user={id:'owner',role:'Owner'};store.sql.close();store=new Store(dir);handler=createTournament({store,auth:{hasAppAccess:()=>true}});assert.equal((await call('GET')).tournaments[0].name,'Test Cup');assert.deepEqual(store.all('clients'),original);const sql=store.exportSql();assert.match(sql,/tournament_lite_events/);const restored=new DatabaseSync(':memory:');restored.exec(sql);assert.equal(restored.prepare('SELECT count(*) AS n FROM tournament_lite_events').get().n,1);restored.close();await call('POST','/'+id,{revision:2,type:'publish',input:{published:false}});user=null;await assert.rejects(call('GET','/public/'+token),/not shared/);}finally{store.sql.close();fs.rmSync(dir,{recursive:true,force:true});}});
