const {randomUUID,randomInt}=require('node:crypto');
const {sports,check,integer,rules,score}=require('./sports');
const scheduler=require('../frontend/scheduling');
const formats=['Knockout','League / Round Robin','League + Knockout','Group Stage + Knockout'];
function text(v,max=120){check(typeof v==='string'&&v.trim().length<=max,'Invalid text');return v.trim();}
function date(v){if(!v)return '';check(/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Invalid date');return v;}
function create(b){check(sports.includes(b.sport)&&formats.includes(b.format),'Select sport and format');check((b.sport==='Cricket'?['Teams']:b.sport==='Chess'?['Singles']:['Singles','Doubles']).includes(b.mode),'Invalid participant mode');const name=text(b.name);check(name,'Tournament name required');const start=date(b.start),end=date(b.end);check(!start||!end||end>=start,'End date must follow start');const logo=b.logo||'';check(typeof logo==='string'&&logo.length<350000&&(!logo||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(logo)),'Use a small PNG, JPEG or WebP logo');return {name,sport:b.sport,format:b.format,mode:b.mode,venue:text(b.venue||''),start,end,organizer:text(b.organizer||''),contact:text(b.contact||'',80),logo,rules:rules(b.sport,b.rules),expected:integer(b.expected||8,2,64),qualifiers:integer(b.qualifiers||2,2,16),groupCount:integer(b.groupCount||2,2,8),participants:[],matches:[],published:false};}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function fixture(t,stage,round,a,b,group='',sources=null){return {id:randomUUID(),stage,round,a,b,group,sources,result:null,status:'upcoming',when:'',location:t.venue};}
function knockout(t,ids){let size=2;while(size<ids.length)size*=2;let order=[1,2];while(order.length<size){const n=order.length*2+1;order=order.flatMap(x=>[x,n-x]);}let prev=[];for(let i=0;i<size;i+=2){const m=fixture(t,'knockout',1,ids[order[i]-1]||null,ids[order[i+1]-1]||null);t.matches.push(m);prev.push(m);}let round=2;while(prev.length>1){const next=[];for(let i=0;i<prev.length;i+=2){const m=fixture(t,'knockout',round,null,null,'',[prev[i].id,prev[i+1].id]);t.matches.push(m);next.push(m);}prev=next;round++;}}
function league(t,ids,group){const list=[...ids];if(list.length%2)list.push(null);for(let round=1;round<list.length;round++){for(let i=0;i<list.length/2;i++){const a=list[i],b=list[list.length-1-i];if(a&&b)t.matches.push(fixture(t,'league',round,round%2?a:b,round%2?b:a,group));}list.splice(1,0,list.pop());}}
function standings(t,group){const ids=group?t.groups[group]:t.participants.map(p=>p.id);const rows=ids.map(id=>({id,played:0,won:0,lost:0,draw:0,points:0,difference:0,runs:0,balls:0,against:0,againstBalls:0})),map=new Map(rows.map(x=>[x.id,x]));for(const m of t.matches.filter(x=>x.stage==='league'&&x.result&&(!group||x.group===group))){const a=map.get(m.a),b=map.get(m.b),r=m.result;for(const [x,side,other]of [[a,'a','b'],[b,'b','a']]){x.played++;const win=r.winner===x.id,draw=!r.winner;x.won+=+win;x.draw+=+draw;x.lost+=+(!win&&!draw);x.points+=win?t.rules.win:draw?t.rules.draw:t.rules.loss;x.difference+=side==='a'?r.sa-r.sb:r.sb-r.sa;if(t.sport==='Cricket'){x.runs+=r[side].runs;x.balls+=r[side].balls;x.against+=r[other].runs;x.againstBalls+=r[other].balls;}}}for(const x of rows)x.nrr=x.balls?6*x.runs/x.balls-6*x.against/x.againstBalls:0;return rows.sort((a,b)=>b.points-a.points||(t.sport==='Cricket'?b.nrr-a.nrr:b.difference-a.difference)||t.participants.findIndex(p=>p.id===a.id)-t.participants.findIndex(p=>p.id===b.id));}
function progress(t){for(const m of t.matches.filter(x=>x.stage==='knockout')){if(m.sources){const src=m.sources.map(id=>t.matches.find(x=>x.id===id)),ids=src.map(x=>x.result?.winner||null);if(m.a!==ids[0]||m.b!==ids[1]){m.result=null;delete m.score;m.status='upcoming';}[m.a,m.b]=ids;}else if(!m.a||!m.b){m.result={winner:m.a||m.b,bye:true};m.status='completed';}}
 const matches=t.matches.filter(x=>x.stage==='league');if(t.format.includes('+')&&matches.length&&matches.every(x=>x.result)&&!t.matches.some(x=>x.stage==='knockout')){let ids;if(t.groups){const groups=Object.keys(t.groups),ranked=groups.map(g=>standings(t,g));ids=[];for(let rank=0;rank<t.qualifiers/groups.length;rank++)for(const rows of ranked)ids.push(rows[rank].id);}else ids=standings(t).slice(0,t.qualifiers).map(x=>x.id);t.qualified=ids;knockout(t,ids);progress(t);}}
function apply(t,type,b){if(type==='participants'){check(!t.matches.length,'Participants are locked after fixture generation');check(Array.isArray(b.participants)&&b.participants.length<=64,'Maximum 64 participants');const used=new Set(),seeds=new Set();t.participants=b.participants.map(p=>{const name=text(p.name);check(name&&!used.has(name.toLowerCase()),'Participant names must be unique');used.add(name.toLowerCase());const members=text(p.members||'',500);if(t.mode==='Doubles')check(members.split(',').map(x=>x.trim()).filter(Boolean).length===2,'Doubles pairs require two comma-separated players');const seed=p.seed?integer(p.seed,1,64):0;check(!seed||!seeds.has(seed),'Seeds must be unique');if(seed)seeds.add(seed);return {id:randomUUID(),name,members,seed};});}
 else if(type==='generate'){check(!t.matches.length,'Fixtures already generated');check(t.participants.length>=2,'Add at least two participants');const entries=shuffle([...t.participants]).sort((a,b)=>(a.seed||999)-(b.seed||999)),ids=entries.map(x=>x.id);if(t.format==='Knockout')knockout(t,ids);else if(t.format==='Group Stage + Knockout'){check(t.groupCount*2<=ids.length&&t.qualifiers%t.groupCount===0&&t.qualifiers<=ids.length&&t.qualifiers/t.groupCount<=Math.floor(ids.length/t.groupCount),'Use two or more players per group and equal qualifiers per group');t.groups={};ids.forEach((id,i)=>{const g=String.fromCharCode(65+i%t.groupCount);(t.groups[g]??=[]).push(id);});for(const [g,list]of Object.entries(t.groups))league(t,list,g);}else{check(t.format==='League / Round Robin'||t.qualifiers<=ids.length,'Too many qualifiers');league(t,ids,'');}progress(t);}
 else if(type==='result'||type==='score'){const m=t.matches.find(x=>x.id===b.id);check(m&&!m.result?.bye,'Match not found or automatic bye');const result=score(t,m,b,type==='score');if(m.stage==='league'&&t.matches.some(x=>x.stage==='knockout')){check(b.confirmReset===true,'Confirm clearing the knockout stage before correcting a league result');t.matches=t.matches.filter(x=>x.stage==='league');delete t.qualified;}if(result.games&&!result.winner){m.score=result;m.result=null;m.status='live';}else{m.result=result;delete m.score;m.status='completed';}progress(t);}
 else if(type==='schedule'){const m=t.matches.find(x=>x.id===b.id);check(m,'Match not found');const when=b.when||'';check(!when||(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(when)&&Number.isFinite(Date.parse(when+'+05:30'))),'Invalid match time');if(when){date(when.slice(0,10));check(Number(when.slice(11,13))<24&&Number(when.slice(14))<60,'Invalid match time');}const location=text(b.location||''),duration=integer(b.duration===undefined?60:b.duration,5,480);check(['upcoming','live'].includes(b.status),'Invalid status');check(!when||!scheduler.conflicts(t.matches,m,when,location,duration,t.participants).length,'Court or participant already has an overlapping match');m.when=when;m.location=location;m.duration=duration;if(!m.result)m.status=b.status;}
 else if(type==='qualification'){
  check(!t.matches.length,'Qualification is locked after fixture generation');check(t.format.includes('+'),'This format has no qualification stage');
  const qualifiers=integer(b.qualifiers,2,16),groupCount=t.format==='Group Stage + Knockout'?integer(b.groupCount,2,8):t.groupCount;
  check(t.format!=='Group Stage + Knockout'||qualifiers%groupCount===0,'Qualifiers must divide equally between groups');
  t.qualifiers=qualifiers;t.groupCount=groupCount;
 }
 else if(type==='details'){const details=create({...t,...Object.fromEntries(['name','venue','start','end','organizer','contact'].map(key=>[key,b[key]]))});for(const key of ['name','venue','start','end','organizer','contact'])t[key]=details[key];}
 else if(type==='publish'){check(typeof b.published==='boolean','Invalid publication state');t.published=b.published;}
 else throw Error('Unknown command');return t;}
function view(t){const v=structuredClone(t);v.tables=t.groups?Object.fromEntries(Object.keys(t.groups).map(g=>[g,standings(t,g)])):{All:standings(t)};const final=t.matches.filter(x=>x.stage==='knockout').at(-1),complete=t.matches.length&&t.matches.every(x=>x.result);v.champion=complete?(final?.result.winner||standings(t)[0]?.id):null;v.runnerUp=complete?(final?(final.a===v.champion?final.b:final.a):standings(t)[1]?.id):null;v.status=complete?'Completed':t.matches.some(x=>x.result&&!x.result.bye||x.status==='live')?'Active':'Upcoming';return v;}
module.exports={create,apply,view,standings,formats};
