const sports=['Cricket','Badminton','Table Tennis','Pickleball','Chess','Carrom'];
function check(ok,message){if(!ok)throw Error(message);}
function number(v,min,max){const n=Number(v);check(v!==''&&v!==null&&v!==undefined&&Number.isFinite(n)&&n>=min&&n<=max,'Invalid number');return n;}
function integer(v,min,max){const n=number(v,min,max);check(Number.isInteger(n),'Whole number required');return n;}
function balls(v){check(/^\d{1,3}(\.[0-5])?$/.test(String(v)),'Use cricket overs notation, e.g. 4.3');const [o,b=0]=String(v).split('.').map(Number);return o*6+b;}
function rules(sport,i={}){const r={bestOf:integer(i.bestOf??3,1,7),points:integer(i.points??(sport==='Pickleball'?11:21),1,100),winBy:integer(i.winBy??2,1,2),cap:integer(i.cap??0,0,200),overs:integer(i.overs??10,1,100),wickets:integer(i.wickets??10,1,10),win:number(i.win??(sport==='Chess'?1:2),0,10),draw:number(i.draw??(sport==='Chess'?.5:1),0,10),loss:number(i.loss??0,0,10)};check(r.bestOf%2===1,'Best of must be odd');check(!r.cap||r.cap>=r.points,'Cap must be at least the points target');return r;}
function score(t,m,i){const r=t.rules;check(m.a&&m.b,'Both participants must be known');
 if(t.sport==='Chess'){check(['white','black','draw'].includes(i.outcome),'Choose a chess outcome');check(i.outcome!=='draw'||m.stage!=='knockout','Knockout draws require a decisive replay');return {outcome:i.outcome,winner:i.outcome==='draw'?null:i.outcome==='white'?m.a:m.b,sa:i.outcome==='white'?1:i.outcome==='draw'?.5:0,sb:i.outcome==='black'?1:i.outcome==='draw'?.5:0};}
 if(t.sport==='Cricket'){const innings=['a','b'].map(side=>{const x=i[side]||{},runs=integer(x.runs,0,2000),wickets=integer(x.wickets,0,r.wickets),bowled=balls(x.overs);check(bowled>0&&bowled<=r.overs*6,'Overs must be positive and within the match limit');return {runs,wickets,overs:String(x.overs),balls:wickets===r.wickets?r.overs*6:bowled};});const [a,b]=innings;check(['a','b'].includes(i.battingFirst),'Select batting first');const tied=a.runs===b.runs;check(!tied||m.stage!=='knockout'||['a','b'].includes(i.tieWinner),'Choose a knockout tiebreak winner');return {a,b,battingFirst:i.battingFirst,target:innings[i.battingFirst==='a'?0:1].runs+1,winner:tied?(m.stage==='knockout'?m[i.tieWinner]:null):a.runs>b.runs?m.a:m.b,sa:a.runs,sb:b.runs};}
 check(Array.isArray(i.games)&&i.games.length>0&&i.games.length<=r.bestOf,'Enter game scores');let aw=0,bw=0,sa=0,sb=0;const needed=Math.floor(r.bestOf/2)+1;const games=i.games.map(g=>{check(aw<needed&&bw<needed,'Remove games after the match was decided');const a=integer(g[0],0,999),b=integer(g[1],0,999),hi=Math.max(a,b),lo=Math.min(a,b);check(a!==b,'Games cannot be tied');if(t.sport!=='Carrom')check(hi>=r.points&&((hi-lo===r.winBy)||(hi===r.points&&hi-lo>=r.winBy)||(r.cap>=r.points&&hi===r.cap&&hi-lo<r.winBy))&&(!r.cap||hi<=r.cap),'Game score does not meet points, win-by or cap rules');a>b?aw++:bw++;sa+=a;sb+=b;return [a,b];});check(aw===needed||bw===needed,'Enter enough games to decide the match');return {games,winner:aw>bw?m.a:m.b,sa,sb};
}
module.exports={sports,check,number,integer,rules,score,balls};
