const {test,expect}=require('@playwright/test');const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');let child,base,dir;
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-showcase-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timed out')),15000);child.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve();}});child.once('error',reject);});});
test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});
test('eleven demos, playback, screen mode, fullscreen, themes and narrow layouts',async({page})=>{
 const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});await page.goto(base+'/showcase');await expect(page.locator('#scene-nav button')).toHaveCount(11);await expect(page.locator('#scene-name')).toHaveText('Team Mixer');await page.locator('#play').click();await expect(page.locator('#play')).toHaveText('Play demo');const stopped=await page.locator('#progress-fill').getAttribute('style');await page.waitForTimeout(400);expect(await page.locator('#progress-fill').getAttribute('style')).toBe(stopped);
 for(const [i,name]of ['Team Mixer','Moment Studio','Timetable Lite','Ritual Assist','Take a Break','Decision Wheel','Chambers','DIGITAL SAMAJ','Tournament Lite','BatchFee Lite','Explore the platform'].entries()){await page.locator('#scene-nav button').nth(i).click();await expect(page.locator('#scene-name')).toHaveText(name);await expect(page.locator('#scene-number')).toHaveText(String(i+1).padStart(2,'0')+' / 11');await expect(page.locator('#scene-link')).toHaveAttribute('href',/^https:\/\/apps.sushantsynapse.com\//);await expect(page.locator('.sample-label')).toContainText('SAMPLE DATA');await expect.poll(()=>page.locator('#scene-stage').evaluate(el=>el.scrollHeight<=el.clientHeight),{message:name+' must fit the stage'}).toBe(true);}
 await page.locator('#next').click();await expect(page.locator('#scene-name')).toHaveText('Team Mixer');await page.locator('#previous').click();await expect(page.locator('#scene-name')).toHaveText('Explore the platform');await page.locator('#restart').click();await page.locator('#duration').selectOption('8');await page.locator('#play').click();await expect(page.locator('#scene-name')).toHaveText('Moment Studio',{timeout:12000});await page.locator('#play').click();await page.locator('#theme').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const name of ['Decision Wheel','Chambers','DIGITAL SAMAJ','Tournament Lite','BatchFee Lite']){await page.locator('#scene-nav').getByRole('button',{name,exact:true}).click();await expect(page.locator('#scene-stage')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}}await page.locator('#scene-nav button').nth(1).click();await expect(page.locator('.certificate h3')).toBeVisible();await page.screenshot({path:'test-results/showcase-desktop-dark.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('#theme').click();await page.screenshot({path:'test-results/showcase-mobile-light.png',fullPage:true});await page.goto(base+'/showcase?screen=1');await expect(page.locator('body')).toHaveClass('screen-mode');await page.locator('#player').click({position:{x:10,y:100}});await page.keyboard.press('Space');await expect(page.locator('#play')).toHaveText('Play demo');await page.keyboard.press('ArrowRight');await expect(page.locator('#scene-name')).toHaveText('Moment Studio');await page.locator('#fullscreen').click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await expect(page.locator('#fullscreen-play')).toBeVisible();await page.locator('#fullscreen-exit').click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(false);await page.locator('#exit-screen').click();await expect(page.locator('body')).not.toHaveClass('screen-mode');expect(errors).toEqual([]);expect(api).toEqual([]);
});
test('downloaded HTML runs offline with embedded assets and reduced-motion demos start paused',async({page,browser})=>{
 await page.goto(base+'/showcase');const pending=page.waitForEvent('download');await page.locator('#download-player').click();const file=await pending,filename=path.resolve('test-results/sushant-synapse-demo-player.html');await file.saveAs(filename);const html=fs.readFileSync(filename,'utf8');expect(html).toContain('showcase-export');expect(html).toContain('data:image/png;base64,');const external=await page.evaluate(text=>{const doc=new DOMParser().parseFromString(text,'text/html');return {scripts:doc.querySelectorAll('script[src]').length,styles:doc.querySelectorAll('link[rel=stylesheet]').length};},html);expect(external).toEqual({scripts:0,styles:0});
 const context=await browser.newContext({reducedMotion:'reduce'});try{const offline=await context.newPage(),errors=[],network=[];offline.on('pageerror',e=>errors.push(e.message));offline.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await context.setOffline(true);await offline.goto(require('node:url').pathToFileURL(filename).href);await expect(offline.locator('#play')).toHaveText('Play demo');await expect(offline.locator('#download-player')).toBeHidden();await expect(offline.locator('.team-columns')).toBeVisible();await offline.locator('#scene-nav button').nth(1).click();await expect(offline.locator('.certificate h3')).toHaveText('Meera Sharma');await expect(offline.locator('.certificate h3')).toBeVisible();for(const name of ['Decision Wheel','Chambers','DIGITAL SAMAJ','Tournament Lite','BatchFee Lite']){await offline.locator('#scene-nav').getByRole('button',{name,exact:true}).click();await expect(offline.locator('#scene-name')).toHaveText(name);await expect(offline.locator('#scene-stage')).toBeVisible();}await offline.locator('#scene-nav button').nth(10).click();await expect(offline.locator('.closing-orbit img')).toHaveAttribute('src',/^data:/);await offline.getByRole('link',{name:'Open display screen'}).click();await expect(offline.locator('body')).toHaveClass('screen-mode');expect(errors).toEqual([]);expect(network).toEqual([]);}finally{await context.close();}
 const nojs=await browser.newContext({javaScriptEnabled:false});try{const p=await nojs.newPage();await p.goto(base+'/showcase');await expect(p.locator('noscript p')).toContainText('Enable JavaScript');await expect(p.getByRole('link',{name:'Explore sponsorship'})).toBeVisible();}finally{await nojs.close();}
});
