import {cast,reactions,tally} from './catalogue.mjs';
import {playReaction,stopVibration} from './feedback.mjs';
const $=s=>document.querySelector(s),api='/api/satire-arena';let round=null,busy=false,pending=null,loading=null;
const media=matchMedia('(prefers-color-scheme: dark)');function applyTheme(){const value=window.SynapseTheme.read();document.documentElement.dataset.theme=value==='system'?(media.matches?'dark':'light'):value;}
document.querySelector('[data-theme-toggle]').outerHTML=window.SynapseTheme.control();document.addEventListener('change',event=>{if(event.target.matches('[data-theme-toggle]'))applyTheme();});media.addEventListener('change',applyTheme);applyTheme();
async function request(path='',options={}){const response=await fetch(api+path,{cache:'no-store',credentials:'same-origin',...options});const body=response.status===204?null:await response.json().catch(()=>null);if(!response.ok){const error=Error(body?.error||'The arena could not load. Try again.');error.status=response.status;throw error;}return body;}
function notice(message){$('#notice').textContent=message;$('#notice').hidden=!message;}
function render(){
 const {fans,critics,amused}=tally(round?.characters);$('#amused').textContent=round?amused:'—';
 $('#fans').textContent=round?fans:'—';$('#critics').textContent=round?critics:'—';$('#round').textContent=round?.round||'—';$('#verdict').textContent=!round?'Shared scores unavailable':fans+critics===0?'Who will make the first move?':fans===critics?'A dead heat!':fans>critics?'Fans have the edge.':'Critics have the edge.';$('#meter').style.width=(fans+critics?fans/(fans+critics)*100:50)+'%';
 for(const c of cast){const card=$(`[data-character="${c.id}"]`),score=round?.characters.find(x=>x.id===c.id);for(const r of reactions){const button=card.querySelector(`[data-reaction="${r.id}"]`);button.disabled=busy||!round;button.setAttribute('aria-pressed',String(score?.selected===r.id));button.querySelector('strong').textContent=score?score[r.id]:'—';}card.querySelector('.vote-state').textContent=score?.selected?`Your pick: ${reactions.find(r=>r.id===score.selected).name}. Tap another to change it.`:round?`${reactions.reduce((n,r)=>n+(score[r.id]||0),0)} reactions today · Your move.`:'Connect to the shared arena to react.';}
 $('#confirm').disabled=busy||!round;$('#refresh').disabled=busy;$('#remove').disabled=busy;
}
async function load(){if(loading)return loading;loading=(async()=>{try{round=await request();render();}catch(e){round=null;render();notice(e.message);}finally{loading=null;}})();return loading;}
async function vote(character,reaction){if(busy||!round)return;busy=true;render();notice('');try{await request('/'+character+'/vote',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({reaction,round:round.round})});pending=null;$('#pending').hidden=true;history.replaceState(null,'','/satire-arena');playReaction($(`[data-character="${character}"]`),reaction,{haptics:$('#haptics').checked});if(loading)await loading;await load();if(round)notice('Reaction saved. You can change it until midnight IST.');}catch(e){notice(e.message);if(e.status===409||e.status===428)await load();}finally{busy=false;render();}}
for(const [i,c]of cast.entries()){
 const article=document.createElement('article');article.className='arena-card';article.dataset.character=c.id;article.innerHTML=`<div class="portrait portrait-${c.portrait}" role="img" aria-label="${c.name}, a fictional political cartoon"><span>FICTIONAL PARODY</span></div><div class="card-body"><small>${c.tag}</small><h2>${c.name}</h2><p>${c.copy}</p><div class="reactions">${reactions.map(r=>`<button type="button" data-reaction="${r.id}" disabled aria-pressed="false" aria-label="${r.name} for ${c.name}"><span aria-hidden="true">${r.icon}</span><b>${r.name}</b><strong>—</strong></button>`).join('')}</div><p class="vote-state" role="status">Loading shared scores…</p></div>`;article.querySelectorAll('[data-reaction]').forEach(b=>b.onclick=()=>vote(c.id,b.dataset.reaction));$('#cast').append(article);
}
const query=new URLSearchParams(location.search),character=query.get('character'),reaction=query.get('reaction');if(cast.some(c=>c.id===character)&&reactions.some(r=>r.id===reaction)){pending={character,reaction};$('#pending-copy').textContent=`Your reaction is ready: ${cast.find(c=>c.id===character).name} · ${reactions.find(r=>r.id===reaction).name}. Confirm to make it count.`;$('#pending').hidden=false;}
$('#confirm').onclick=()=>pending&&vote(pending.character,pending.reaction);$('#cancel').onclick=()=>{pending=null;$('#pending').hidden=true;history.replaceState(null,'','/satire-arena');};$('#refresh').onclick=()=>{notice('');load();};
$('#export').onclick=async()=>{try{const data=await request('/mine'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='satire-arena-my-reactions.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Your browser’s reactions exported. Keep the file private.');}catch(e){notice(e.message);}};
$('#remove').onclick=async()=>{if(busy||!confirm('Remove every reaction saved under this browser identity? This also updates the shared scores.'))return;busy=true;render();try{await request('/mine',{method:'DELETE',headers:{'X-Arena-Confirm':'DELETE'}});if(loading)await loading;await load();if(round)notice('Your saved reactions were removed.');}catch(e){notice(e.message);}finally{busy=false;render();}};
$('#haptics').addEventListener('change',()=>{if(!$('#haptics').checked)stopVibration();});if(typeof navigator.vibrate!=='function'){$('#haptics').checked=false;$('#haptics').disabled=true;$('#haptic-help').textContent='Animations are on. Vibration is unavailable in this browser.';}document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVibration();});
load();setInterval(()=>{if(!document.hidden&&!busy)load();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!busy)load();});
