'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang='en',samaj,communities=[],session,grants=[],section='directory',kind='persons',currentProfile,draft,saveQueue=Promise.resolve(),autosave,treeScale=1,expandedMember=null,viewEpoch=0;
const t=(key)=>SamajStrings[lang][key]||SamajStrings.en[key]||key;
const fieldNames=['englishName','hindiName','gender','dob','birthTime','birthPlace','bloodGroup','maritalStatus','mobile','whatsapp','email','education','qualification','achievements','occupation','designation','organization','workplace','isDeceased','dateOfDeath','nativeVillage','district','state','currentCity','address','pin'];
const familyFields=['name','nativeVillage','district','state','gotra','kul','kuldevi','kuldevta','address','currentCity','pin','mobile','alternateMobile','whatsapp','email'];
const sensitive=['mobile','alternateMobile','whatsapp','email','dob','birthTime','birthPlace','address','pin','photo','bloodGroup','achievements'];
const options={gender:['','Male','Female','Other','Unspecified'],maritalStatus:['','Single','Married','Widowed','Divorced','Separated','Unspecified'],membership:['BirthFamily','MaritalFamily','GuardianFamily','Other'],relationship:['','Father','Mother','Spouse','Child','Sibling','Guardian','Other']};
const name=p=>p.englishName||p.hindiName||p.name||p.code;
const has=p=>grants.some(g=>g.permission===p);
const button=(label,action,attrs='')=>`<button type="button" data-action="${action}" ${attrs}>${esc(t(label))}</button>`;
function notice(msg){$('#notice').textContent=msg;$('#notice').classList.add('show');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#notice').classList.remove('show'),4500);}
function theme(value){SynapseTheme.write(value);document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value;$('#theme').innerHTML=SynapseTheme.control('data-theme');}
theme(SynapseTheme.read());matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>theme(SynapseTheme.read()));
async function api(path='',method='GET',body){const epoch=viewEpoch,response=await fetch('/api/digital-samaj'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(epoch!==viewEpoch&&!(method==='PATCH'&&path.includes('/drafts/')))throw Object.assign(Error('View changed'),{stale:true});if(!response.ok)throw Error(data.error||String(response.status));return data;}
const endpoint=(path='')=>'/'+samaj.id+path;
async function eventCalendar(){const result=await api(endpoint('/events'));$('#content').innerHTML='<h2>Community calendar · IST</h2><p>Participation is optional. Your response belongs to your account; attendee names are not shared.</p>'+(has('announcement.create')?'<form id="event-create" class="card"><h3>Create an event</h3><label>Title<input name="title" maxlength="120" required></label><label>Start · IST<input name="startsAt" type="datetime-local" required></label><label>Location<input name="location" maxlength="200" required></label><label>Description<textarea name="description" maxlength="2000"></textarea></label><label>Family ID (optional; limits visibility to its authorized viewers)<input name="familyId"></label><button>Create event</button><p class="error" role="alert"></p></form>':'')+'<div class="grid">'+result.items.map(e=>'<article class="card"><h3>'+esc(e.title)+'</h3><p>'+esc(e.starts_at.replace('T',' '))+' IST · '+esc(e.location)+'</p><p>'+esc(e.description)+'</p><p>'+(e.cancelled?'Cancelled':e.going+' going · Your response: '+esc(e.response||'Not set'))+'</p>'+(!e.cancelled?['Going','Maybe','Not going','Clear'].map(response=>'<button type="button" data-event-rsvp="'+e.id+'" data-response="'+response+'" aria-pressed="'+(e.response===response)+'">'+response+'</button>').join('')+(has('announcement.create')?'<button type="button" data-event-cancel="'+e.id+'">Cancel event</button>':''):'')+'</article>').join('')+'</div>';const form=$('#event-create');if(form)form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await api(endpoint('/events'),'POST',Object.fromEntries(new FormData(form)));await eventCalendar();}catch(error){form.querySelector('.error').textContent=error.message;button.disabled=false;}};}
document.addEventListener('click',async event=>{const rsvp=event.target.closest('[data-event-rsvp]'),cancel=event.target.closest('[data-event-cancel]');if(!rsvp&&!cancel)return;const button=rsvp||cancel;button.disabled=true;try{if(cancel&&!confirm('Cancel this event for everyone?'))return;await api(endpoint('/events/'+(rsvp?rsvp.dataset.eventRsvp:cancel.dataset.eventCancel)+'/'+(rsvp?'rsvp':'cancel')),'POST',rsvp?{response:rsvp.dataset.response}:{});await eventCalendar();}catch(error){notice(error.message);}finally{button.disabled=false;}});
function field(key,value='',attrs=''){const type=key==='dob'||key==='dateOfDeath'?'date':key==='birthTime'?'time':key==='email'?'email':key==='mobile'||key==='whatsapp'?'tel':'text';return `<label>${esc(t(key))}${key==='isDeceased'?`<input type="checkbox" name="${key}" ${value?'checked':''} ${attrs}>`:options[key]?`<select name="${key}" ${attrs}>${options[key].map(v=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(t(v||'none'))}</option>`).join('')}</select>`:`<input name="${key}" type="${type}" value="${esc(value)}" maxlength="${key==='address'||key==='achievements'?1000:200}" ${attrs}>`}</label>`;}
function select(label,key,values,value='',attrs=''){return `<label>${esc(t(label))}<select name="${key}" aria-label="${esc(t(label))}" ${attrs}>${values.map(v=>`<option value="${esc(typeof v==='string'?v:v.id)}" ${value===(typeof v==='string'?v:v.id)?'selected':''}>${esc(typeof v==='string'?t(v||'none'):v.name)}</option>`).join('')}</select></label>`;}
function formData(form){return Object.fromEntries(new FormData(form));}
function shell(content){$('#all-apps').textContent=t('allApps');document.documentElement.lang=lang;$('#app').innerHTML=`<div class="hero"><div><p class="eyebrow">${esc(t('title'))}</p><h1>${esc(t('tagline'))}</h1><p class="muted">${esc(t('intro'))}</p>${samaj?`<div class="toolbar"><strong>${esc(samaj.name)}</strong>${button('chooseSamaj','communities')}</div>`:''}</div><div class="hero-mark" aria-hidden="true">✳</div></div>${samaj?`<nav class="nav" aria-label="${esc(t('title'))}">${['directory',...(has('family.create')?['register']:[]),'reviews','events','connect',...(has('report.view')?['dashboard']:[]),...(has('admin.manage')?['admin']:[])].map(s=>`<button data-section="${s}" aria-current="${section===s?'page':'false'}">${esc(t(s))}</button>`).join('')}</nav>`:''}<div id="content">${content}</div>`;}
async function boot(){shell(`<p>${t('loading')}</p>`);try{session=await (await fetch('/api/auth/status')).json();if(!session.user){shell(`<div class="card"><h2>${t('signIn')}</h2><p>${t('signInNote')}</p><a class="button primary" href="/signin?next=digital-samaj">${t('signIn')}</a></div>`);return;}await showCommunities();}catch(e){shell(`<div class="card"><p class="error">${esc(e.message)}</p><p>${t('noAccess')}</p>${button('reload','boot')}</div>`);}}
async function showCommunities(){samaj=null;const data=await api();communities=data.communities;shell(`<h2>${t('chooseSamaj')}</h2><div class="grid">${communities.map(c=>`<button class="card" data-community="${c.id}"><h3>${esc(c.name)}</h3></button>`).join('')}</div>${data.canSetup?`<form class="card" data-form="community"><h2>${t('createSamaj')}</h2><label>${t('samajName')}<input name="name" required maxlength="120"></label><div class="toolbar"><button class="primary">${t('createSamaj')}</button></div><p class="error"></p></form>`:`<p>${t('noAccess')}</p>`}`);}
async function choose(id){samaj=communities.find(c=>c.id===id)||{id};const data=await api(endpoint());samaj.name=data.name;grants=data.grants;draft=null;await show('directory');}
async function show(next=section){const epoch=++viewEpoch;clearTimeout(autosave);if(draft&&$('#wizard'))await saveDraft();await saveQueue;if(epoch!==viewEpoch)return;draft=null;section=next;currentProfile=null;shell(`<p>${t('loading')}</p>`);try{await ({directory:directory,register:registrations,reviews:reviews,connect:connect,events:eventCalendar,dashboard:dashboard,admin:administration}[section])();}catch(e){if(e.stale||epoch!==viewEpoch)return;$('#content').innerHTML=`<div class="card"><p class="error">${esc(e.message)}</p>${section==='connect'?`<p>${t('chatHelp')}</p>`:''}${button('reload','reload')}</div>`;}}
function profileCard(p){return `<article class="card"><div class="profile-card-heading">${p.kind!=='family'&&p.photo?`<img class="profile-photo" src="/api/digital-samaj${endpoint('/photos/'+p.photo)}" alt="${esc(t('photo'))}">`:''}<div><span class="pill">${esc(t(p.status))}</span><small>${esc(p.code)}</small><h3>${esc(name(p))}</h3></div></div><p class="muted">${esc([p.nativeVillage,p.currentCity,p.occupation].filter(Boolean).join(' · '))}</p><button data-profile="${p.id}" data-kind="${p.kind==='family'?'families':'persons'}">${t('view')}</button></article>`;}
async function directory(q='',offset=0){const result=await api(endpoint('/'+kind+'?q='+encodeURIComponent(q)+'&offset='+offset+'&'+new URLSearchParams(directoryFilters)));$('#content').innerHTML=`<div class="toolbar"><h2>${t('directory')}</h2><div>${button('families','families')}${button('persons','persons')}</div></div><form class="toolbar" data-form="search"><label class="sr-only" for="query">${t('search')}</label><input id="query" name="q" type="search" placeholder="${t('search')}" value="${esc(q)}"><button>${t('search')}</button></form><details class="card no-print"><summary>${t('filters')}</summary><form data-form="filters"><div class="form-grid">${['familyCode','gotra','nativeVillage','currentCity','district','state','occupation','qualification','maritalStatus','minAge','maxAge'].map(k=>field(k,directoryFilters[k]||'')).join('')}</div><button>${t('filters')}</button><p class="error"></p></form></details><p class="muted">${result.total} ${t('total')}</p><div class="grid">${result.items.map(profileCard).join('')||`<div class="empty">${t('empty')}</div>`}</div><div class="toolbar">${offset?button('back','page',`data-offset="${Math.max(0,offset-50)}" data-query="${esc(q)}"`):''}${offset+50<result.total?button('next','page',`data-offset="${offset+50}" data-query="${esc(q)}"`):''}</div>`;}
async function registrations(){const data=await api(endpoint('/drafts'));$('#content').innerHTML=`<div class="toolbar"><h2>${t('register')}</h2>${button('newDraft','new-draft','class="primary"')}</div><p>${t('draftNote')}</p><div class="grid">${data.items.filter(d=>!d.submitted_family_id).map(d=>`<article class="card"><p>${esc(new Date(d.updated_at).toLocaleString(lang==='hi'?'hi-IN':'en-IN'))}</p><p>${t('register')}</p><button data-draft="${d.id}">${t('resume')}</button></article>`).join('')}</div>`;}
const steps=['family','headContact','members','privacy','reviewSubmit'];
function captureDraft(){if(!draft||!$('#wizard'))return;const data=draft.data;for(const el of $('#wizard').querySelectorAll('[data-bind]')){const path=el.dataset.bind.split('.');let object=data;for(const key of path.slice(0,-1))object=object[key]??=(/^\d+$/.test(key)?[]:{});object[path.at(-1)]=el.type==='checkbox'?el.checked:el.value;}}
function saveDraft(capture=true){if(!draft)return Promise.resolve();if(capture)captureDraft();const snapshot=JSON.parse(JSON.stringify(draft.data)),step=draft.step,did=draft.id;saveQueue=saveQueue.catch(()=>{}).then(async()=>{const result=await api(endpoint('/drafts/'+did),'PATCH',{revision:draft.revision,step,data:snapshot});if(draft?.id===did)draft.revision=result.revision;const status=$('#save-status');if(status&&draft?.id===did)status.textContent=t(JSON.stringify(draft.data)===JSON.stringify(snapshot)?'saved':'saving');});return saveQueue;}
function bound(key,value,path){return field(key,value,`data-bind="${path}.${key}"`);}
function normalizeDraft(){const d=draft.data;if(d.formVersion!==2){draft.step=[0,1,1,2,2,2,3,3,4,4][draft.step]??0;d.formVersion=2;}d.family||={};d.head||={};d.members||=[];d.privacy||={};}
function draftPhoto(photo,target){return `<div class="person-photo">${photo?`<img src="data:${photo.mime};base64,${photo.content}" alt="${esc(t('photoPreview'))}">`:`<span class="photo-placeholder" aria-hidden="true">${esc(t('photo'))}</span>`}<label class="photo-choice">${t(photo?'changePhoto':'addPhoto')}<input type="file" data-person-photo="${target}" accept="image/png,image/jpeg"></label>${photo?button('removePhoto','remove-person-photo',`data-target="${target}"`):''}<small>${t('optionalPhoto')}</small></div>`;}
function existingPicker(target,id,label){return `<details class="existing-picker"><summary>${t('reusePerson')}</summary><p class="muted">${t('reuseHelp')}</p><div class="toolbar"><label>${t('findPerson')}<input type="search" data-person-query="${target}" value="${esc(label||id||'')}"></label>${button('search','find-person',`data-target="${target}"`)}</div><div data-person-results="${target}"></div></details>${id?`<p class="linked-person"><strong>${esc(label||id)}</strong> · ${t('linkedExisting')} ${button('cancelLink','unlink-person',`data-target="${target}"`)}</p>`:''}`;}
function personFieldsEditor(data,path){return `<div class="form-grid">${['englishName','hindiName','gender','dob','maritalStatus','occupation'].map(k=>bound(k,data[k]||'',path)).join('')}</div><details class="optional-details"><summary>${t('morePersonDetails')}</summary><div class="form-grid">${['mobile','whatsapp','email','birthTime','birthPlace','bloodGroup','education','qualification','achievements','designation','organization','workplace','nativeVillage','district','state','currentCity','address','pin'].map(k=>bound(k,data[k]||'',path)).join('')}</div></details><div class="deceased-fields">${bound('isDeceased',!!data.isDeceased,path)}<div data-death-fields ${data.isDeceased?'':'hidden'}>${bound('dateOfDeath',data.dateOfDeath||'',path)}</div></div>`;}
function relatedLabel(target){const d=draft.data;return target===undefined||target==='head'?(d.headLabel||name(d.head)||t('head')):(d.members[Number(target)]?.existingLabel||name(d.members[Number(target)]?.data||{})||`${t('person')} ${Number(target)+1}`);}
function memberEditor(m,i){const title=m.existingLabel||name(m.data||{})||`${t('person')} ${i+1}`,targets=[{id:'head',name:relatedLabel('head')},...draft.data.members.flatMap((other,j)=>j===i?[]:[{id:String(j),name:relatedLabel(String(j))}])];return `<details class="member-row" data-member="${i}" ${expandedMember===i?'open':''}><summary class="member-summary">${m.photo?`<img src="data:${m.photo.mime};base64,${m.photo.content}" alt="${esc(t('photo'))}">`: `<span class="member-initial" aria-hidden="true">${esc(Array.from(title)[0])}</span>`}<span><strong>${esc(title)}</strong><small>${esc(t(m.relationship||'none'))} · ${esc(relatedLabel(m.relatedTo))}</small></span></summary><div class="toolbar">${button('remove','remove-member',`data-index="${i}"`)}</div>${existingPicker(String(i),m.personId,m.existingLabel)}<div class="person-editor">${!m.personId?draftPhoto(m.photo,String(i)):''}<div class="person-fields">${!m.personId?personFieldsEditor(m.data||{},`members.${i}.data`):`<p class="muted">${t('existingUnchanged')}</p>`}<div class="form-grid">${select('relationshipTo','relationship',options.relationship,m.relationship||'',`data-bind="members.${i}.relationship"`)}${select('relatedPerson','relatedTo',targets,m.relatedTo??'head',`data-bind="members.${i}.relatedTo"`)}</div><details class="optional-details"><summary>${t('familyContextOptional')}</summary>${select('membership','membership',options.membership,m.type||'BirthFamily',`data-bind="members.${i}.type"`)}</details><div></div></div></div></details>`;}
function reviewPerson(data,photo,label){return `<div class="review-person">${photo?`<img class="profile-photo" src="data:${photo.mime};base64,${photo.content}" alt="${esc(t('photoPreview'))}">`:''}<div><h4>${esc(label||name(data)||t('person'))}</h4>${details(data)}</div></div>`;}
function wizard(){normalizeDraft();const d=draft.data;let content='';
 if(draft.step===0)content=`<p class="muted">${t('familyHelp')}</p><div class="form-grid">${['name','nativeVillage','district','state'].map(k=>bound(k,d.family[k]||'','family')).join('')}</div><details class="optional-details"><summary>${t('communityDetails')}</summary><div class="form-grid">${['gotra','kul','kuldevi','kuldevta'].map(k=>bound(k,d.family[k]||'','family')).join('')}</div></details>`;
 if(draft.step===1)content=`<h4>${t('head')}</h4>${existingPicker('head',d.headPersonId,d.headLabel)}<div class="person-editor">${!d.headPersonId?draftPhoto(d.headPhoto,'head'):''}<div class="person-fields">${!d.headPersonId?personFieldsEditor(d.head,'head'):`<p class="muted">${t('existingUnchanged')}</p>`}</div></div><h4>${t('contact')}</h4><div class="form-grid">${['address','currentCity','pin','mobile','whatsapp','email'].map(k=>bound(k,d.family[k]||'','family')).join('')}</div><details class="optional-details"><summary>${t('alternateContact')}</summary>${bound('alternateMobile',d.family.alternateMobile||'','family')}</details>`;
 if(draft.step===2)content=`<p class="muted">${t('membersHelp')}</p>${d.members.map(memberEditor).join('')}${!d.members.length?`<p class="empty">${t('noMembersYet')}</p>`:''}<div class="toolbar">${button('addMember','add-member')}${button('addAncestor','add-ancestor')}</div><small>${d.members.length}/40</small>`;
 if(draft.step===3)content=`<p>${t('privacyHelp')}</p><p class="muted">${t('privacySummary')}</p><details class="optional-details"><summary>${t('advancedPrivacy')}</summary><div class="form-grid">${sensitive.map(k=>select(k,k,['PRIVATE','FAMILY','SAMAJ','ADMIN','PUBLIC'],d.privacy[k]||'PRIVATE',`data-bind="privacy.${k}"`)).join('')}</div></details><p>${t('photoConsent')}</p>`;
 if(draft.step===4)content=`<p>${t('reviewHelp')}</p><section class="review-section"><div class="toolbar"><h4>${t('family')}</h4>${button('edit','wizard-edit','data-step="0"')}</div>${details(d.family)}</section><section class="review-section"><div class="toolbar"><h4>${t('headContact')}</h4>${button('edit','wizard-edit','data-step="1"')}</div>${reviewPerson(d.headPersonId?{}:d.head,d.headPhoto,d.headLabel||d.headPersonId)}</section><section class="review-section"><div class="toolbar"><h4>${t('members')}</h4>${button('edit','wizard-edit','data-step="2"')}</div>${d.members.map(m=>`${reviewPerson(m.personId?{}:m.data||{},m.photo,m.existingLabel||m.personId)}<p>${esc(t(m.type||'BirthFamily'))} · ${esc(t(m.relationship||'none'))} · ${esc(relatedLabel(m.relatedTo))}</p>`).join('')||`<p>${t('noMembersYet')}</p>`}</section><section class="review-section"><div class="toolbar"><h4>${t('privacy')}</h4>${button('edit','wizard-edit','data-step="3"')}</div>${details(Object.fromEntries(sensitive.map(k=>[k,d.privacy[k]||'PRIVATE'])))}</section><p>${t('consentNote')}</p><p>${t('reviewerNote')}</p><label class="consent"><input id="consent" type="checkbox"> ${t('consent')}</label>`;
 $('#content').innerHTML=`<div class="registration"><div class="toolbar"><h2>${t('register')}</h2><small id="save-status" role="status">${t('saved')}</small></div><div class="step-heading"><span>${t('step')} ${draft.step+1} / ${steps.length}</span><progress value="${draft.step+1}" max="${steps.length}" aria-label="${esc(t('register'))}"></progress></div><div class="steps">${steps.map((s,i)=>`<span class="${i===draft.step?'active':''}" ${i===draft.step?'aria-current="step"':''}>${i+1}. ${t(s)}</span>`).join('')}</div><form id="wizard" class="card"><h3 tabindex="-1">${t(steps[draft.step])}</h3>${content}<p class="error" id="wizard-error" role="alert"></p><div class="toolbar wizard-actions">${draft.step?button('back','wizard-back'):''}${button('saveLater','save-draft')}${draft.step<4?button('next','wizard-next','class="primary"'):button('submit','submit-draft','class="primary"')}</div></form></div>`;
}
function validateStep(){captureDraft();const d=draft.data;const check=(data,requireName=false)=>{if(requireName&&!data.englishName?.trim()&&!data.hindiName?.trim())throw Error(t('nameRequired'));for(const [k,v]of Object.entries(data)){if(!v)continue;if(['mobile','alternateMobile','whatsapp'].includes(k)&&!/^\+?[0-9 ()-]{7,20}$/.test(v))throw Error(`${t(k)}: ${t('invalidValue')}`);if(k==='pin'&&!/^\d{6}$/.test(v))throw Error(`${t(k)}: ${t('invalidValue')}`);if(k==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw Error(`${t(k)}: ${t('invalidValue')}`);if(['dob','dateOfDeath'].includes(k)){const date=new Date(v+'T00:00:00Z');if(!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==v||v>new Date().toISOString().slice(0,10))throw Error(`${t(k)}: ${t('invalidValue')}`);}}if(data.dateOfDeath&&(!data.isDeceased||data.dob&&data.dateOfDeath<data.dob))throw Error(`${t('dateOfDeath')}: ${t('invalidValue')}`);};if(draft.step===0&&!d.family.name?.trim())throw Error(t('familyNameRequired'));if(draft.step===1){if(!d.headPersonId)check(d.head,true);check(d.family);}if(draft.step===2)for(const m of d.members){if(!m.personId)check(m.data||{},true);}}
function details(p,printLang=lang){const label=k=>printLang==='both'?`${SamajStrings.en[k]||k} / ${SamajStrings.hi[k]||k}`:(SamajStrings[printLang]?.[k]||k);return `<dl class="details">${Object.entries(p).filter(([k,v])=>!['id','kind','privacy','members','memberships','photo','revision','headId'].includes(k)&&v!==''&&v!==null&&typeof v!=='object').map(([k,v])=>`<dt>${esc(label(k))}</dt><dd>${esc(typeof v==='boolean'?(v?'✓':'—'):t(v))}</dd>`).join('')}</dl>`;}
async function profile(id,k=kind){const p=await api(endpoint('/'+k+'/'+id));profilePhoto=null;currentProfile={...p,resource:k};draft=null;const canEdit=has(p.kind+'.edit');$('#content').innerHTML=`<article class="card" id="profile"><div class="print-title"><p class="eyebrow">${t('title')} · ${esc(samaj.name)}</p><h2>${esc(name(p))}</h2><span class="pill">${t(p.status)}</span><small>${esc(p.code)}</small></div>${p.kind==='person'&&p.photo?`<img class="profile-photo" src="/api/digital-samaj${endpoint('/photos/'+p.photo)}" alt="${esc(t('photo'))}">`:''}<div class="toolbar no-print">${canEdit&&!['SUBMITTED','UNDER_REVIEW','ARCHIVED'].includes(p.status)?button('edit','edit-profile'):''}${(p.kind==='person'||p.headId?button('tree','tree'):'')+(p.kind==='person'?button('claim','claim')+button('message','request-chat'):'')}${has('report.export')?`${select('printLanguage','print-language',[{id:'en',name:'English'},{id:'hi',name:'हिन्दी'},{id:'both',name:t('bilingual')}],lang)}${button('print','print')}`:''}${has('admin.manage')&&p.kind==='person'?button('duplicates','duplicates'):''}</div><div id="profile-details">${details(p)}</div>${p.members?`<h3>${t('members')}</h3><div class="grid">${p.members.map(profileCard).join('')}</div>`:''}${p.memberships?`<h3>${t('families')}</h3>${p.memberships.map(m=>`<p>${t(m.type)} <button data-profile="${m.family_id}" data-kind="families">${t('view')}</button></p>`).join('')}`:''}</article>${canEdit?`${p.kind==='person'&&!['SUBMITTED','UNDER_REVIEW','ARCHIVED'].includes(p.status)?`<form class="card no-print" data-form="photo"><h3>${t('photo')}</h3><p>${t('photoHelp')}</p><label class="photo-choice">${t(p.photo?'changePhoto':'addPhoto')}<input aria-label="${t('photo')}" name="photo" data-profile-photo type="file" accept="image/png,image/jpeg" required></label><div data-photo-preview></div><p class="muted">${t('photoConsent')}</p><div class="toolbar"><button type="submit" class="primary" disabled>${t('savePhoto')}</button>${p.photo?button('removePhoto','remove-profile-photo'):''}</div><p class="error" role="alert"></p></form>`:''}${['DRAFT','CORRECTION_REQUIRED','REJECTED'].includes(p.status)?`<form class="card no-print" data-form="submit-profile"><label><input type="checkbox" name="consent" required> ${t('consent')}</label><div class="toolbar"><button>${t('submit')}</button></div><p class="error"></p></form>`:''}`:''}<div id="profile-extra"></div>`;}
function profilePersonPicker(target){return `<input type="hidden" name="personId"><div data-selected-person="${target}"></div>${existingPicker(target,'','')}`;}
function profileEditFields(p){const available=k=>!sensitive.includes(k)||Object.hasOwn(p,k);const groups=p.kind==='family'?[[ 'family',['name','nativeVillage','district','state'] ],['contact',['address','currentCity','pin','mobile','alternateMobile','whatsapp','email']],['communityDetails',['gotra','kul','kuldevi','kuldevta']]]:[['person',['englishName','hindiName','gender','dob','maritalStatus','occupation']],['contact',['mobile','whatsapp','email','address','currentCity','pin']],['morePersonDetails',fieldNames.filter(k=>!['englishName','hindiName','gender','dob','maritalStatus','occupation','mobile','whatsapp','email','address','currentCity','pin'].includes(k))]];return groups.map(([label,keys],i)=>i<2?`<h4>${t(label)}</h4><div class="form-grid">${keys.filter(available).map(k=>field(k,p[k]??'')).join('')}</div>`:`<details class="optional-details"><summary>${t(label)}</summary><div class="form-grid">${keys.filter(available).map(k=>field(k,p[k]??'')).join('')}</div></details>`).join('');}
function editProfile(){const p=currentProfile;$('#profile-extra').innerHTML=`<form class="card" data-form="edit"><h3>${t('edit')}</h3>${profileEditFields(p)}<details class="optional-details"><summary>${t('advancedPrivacy')}</summary><p class="muted">${t('privacyHelp')}</p><div class="form-grid">${sensitive.map(k=>select(k,'privacy.'+k,['PRIVATE','FAMILY','SAMAJ','ADMIN','PUBLIC'],p.privacy?.[k]||'PRIVATE')).join('')}</div></details><button class="primary">${t('save')}</button><p class="error"></p></form>${p.kind==='family'?`<form class="card" data-form="membership"><h3>${t('linkMember')}</h3>${profilePersonPicker('profile-member')}${select('membership','type',options.membership)}<label><input type="checkbox" name="isPrimary"> ${t('isPrimary')}</label><button>${t('save')}</button><p class="error"></p></form><form class="card" data-form="head"><h3>${t('head')}</h3>${profilePersonPicker('profile-head')}<button>${t('save')}</button><p class="error"></p></form>`:`<form class="card" data-form="relationship"><h3>${t('addRelationship')}</h3>${profilePersonPicker('profile-relationship')}${select('relationship','type',options.relationship.slice(1))}<button>${t('save')}</button><p class="error"></p></form>`}`;$('#profile-extra').scrollIntoView({block:'start'});}
async function tree(){const data=await api(endpoint('/tree/'+(currentProfile.headId||currentProfile.id))),levels=new Map([[data.root,0]]);for(let i=0;i<8;i++)for(const e of data.edges){if(['Father','Mother','Parent'].includes(e.type)){if(levels.has(e.personId)&&!levels.has(e.relatedId))levels.set(e.relatedId,levels.get(e.personId)-1);if(levels.has(e.relatedId)&&!levels.has(e.personId))levels.set(e.personId,levels.get(e.relatedId)+1);}else if(levels.has(e.personId)&&!levels.has(e.relatedId))levels.set(e.relatedId,levels.get(e.personId));else if(levels.has(e.relatedId)&&!levels.has(e.personId))levels.set(e.personId,levels.get(e.relatedId));}
 const groups=[...new Set(data.nodes.map(n=>levels.get(n.id)||0))].sort((a,b)=>a-b);$('#profile-extra').innerHTML=`<section class="card"><h3>${t('tree')}</h3><div class="toolbar">${button('zoomIn','zoom-in')}${button('zoomOut','zoom-out')}${button('collapse','collapse')}</div><div class="tree-window" tabindex="0" aria-label="${t('tree')}"><div class="tree">${groups.map(level=>`<div class="tree-column">${data.nodes.filter(n=>(levels.get(n.id)||0)===level).map(n=>`<button class="tree-node" data-profile="${n.id}" data-kind="persons" ${n.id!==data.root?'data-relative="true"':''}>${n.photo?`<img class="profile-photo" src="/api/digital-samaj${endpoint('/photos/'+n.photo)}" alt="">`:''}<strong>${esc(name(n))}</strong><small>${esc(n.dob?.slice(0,4)||'')}${n.isDeceased?' · '+t('isDeceased'):''}</small><small>${data.edges.filter(e=>e.personId===data.root&&e.relatedId===n.id).map(e=>t(e.type)).join(', ')}</small></button>`).join('')}</div>`).join('')}</div></div><div class="scroll"><table><tbody>${data.edges.map(e=>`<tr><td>${esc(name(data.nodes.find(n=>n.id===e.personId)))}</td><td>${t(e.type)}</td><td>${esc(name(data.nodes.find(n=>n.id===e.relatedId)))}</td></tr>`).join('')}</tbody></table></div></section>`;treeScale=1;const viewport=$('.tree-window');let drag;viewport.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};viewport.setPointerCapture(e.pointerId);});viewport.addEventListener('pointermove',e=>{if(drag){viewport.scrollLeft=drag.left+drag.x-e.clientX;viewport.scrollTop=drag.top+drag.y-e.clientY;}});viewport.addEventListener('pointerup',()=>drag=null);}
async function reviews(){const result=await api(endpoint('/reviews'));$('#content').innerHTML=`<h2>${t('reviews')}</h2><p>${t('reviewerNote')}</p><div class="grid">${result.items.map(r=>`<article class="card"><span class="pill">${t(r.status)}</span><h3>${esc(reviewLabel(r.kind))}</h3><small>${esc(r.entityId)}</small><div class="toolbar">${has('verification.approve')?button('reviewDetail','review-detail',`data-id="${r.id}"`):''}${r.requestedBy===session.user.id?button('withdraw','withdraw',`data-id="${r.id}"`):''}${r.kind.includes('.')?`<button data-profile="${r.entityId}" data-kind="${r.kind.endsWith('family')?'families':'persons'}">${t('view')}</button>`:''}</div></article>`).join('')||`<div class="empty">${t('empty')}</div>`}</div><div id="review-detail"></div>`;}
async function reviewDetail(id){let r=await api(endpoint('/reviews/'+id));if(r.requestedBy!==session.user.id){await api(endpoint('/reviews/'+id+'/start'),'POST',{});r=await api(endpoint('/reviews/'+id));}$('#review-detail').innerHTML=`<form class="card" data-form="decision" data-id="${id}"><h3>${t('reviewDetail')}</h3><div class="grid"><div><h3>${t('oldValue')}</h3>${details(r.oldValue?.data||r.oldValue||{})}</div><div><h3>${t('newValue')}</h3>${r.newValue?.person?details(r.newValue.person)+details(r.newValue.related)+details({relationship:r.newValue.type}):details(r.newValue?.profile||r.newValue?.data||r.newValue||{})}</div></div>${select('status','decision',[{id:'APPROVE',name:t('approve')},{id:'REJECT',name:t('reject')},{id:'CORRECTION_REQUIRED',name:t('correction')}])}<label>${t('decisionReason')}<textarea name="reason" required maxlength="1000"></textarea></label><button class="primary">${t('save')}</button><p class="error"></p></form>`;$('#review-detail').scrollIntoView({block:'start'});}
async function dashboard(){const d=await api(endpoint('/dashboard'));$('#content').innerHTML=`<h2>${t('dashboard')}</h2><div class="stats">${['families','members','verified','pending','corrections'].map(k=>`<div class="stat"><strong>${d[k]}</strong>${t(k)}</div>`).join('')}</div><h3>${t('statistics')}</h3><p>${t('suppression')}</p><div class="grid">${Object.entries(d.statistics).map(([k,v])=>`<div class="card"><h3>${t(k)}</h3>${Object.entries(v).map(([label,count])=>`<p>${esc(t(label))}: ${count}</p>`).join('')||t('empty')}</div>`).join('')}</div>`;}
async function administration(){const d=await api(endpoint('/grants'));$('#content').innerHTML=`<h2>${t('admin')}</h2><form class="card" data-form="grant"><h3>${t('grant')}</h3><div class="form-grid">${select('account','userId',d.users)}${select('role','role',Object.keys(d.roles))}${select('scope','scope',['ALL','STATE','DISTRICT','VILLAGE','FAMILY','SELF'])}${field('scopeValue')}</div><p>${t('scopeHelp')}</p><button class="primary">${t('grant')}</button><p class="error"></p></form><div class="card">${d.grants.map(g=>`<p>${esc(d.users.find(u=>u.id===g.user_id)?.name||g.user_id)} · ${t(g.role_id)} · ${t(g.scope)} ${esc(g.scope_value)} ${g.user_id!==session.user.id?button('revoke','revoke',`data-id="${g.id}"`):''}</p>`).join('')}</div><form class="card" data-form="import-file"><h3>${t('import')}</h3><p>${t('importHelp')}</p><input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" name="file" aria-label="${t('file')}" required><button>${t('preview')}</button><p class="error"></p></form><div id="import-preview"></div><form class="card" data-form="announcement"><h3>${t('announcements')}</h3>${field('announcementTitle')}<label>${t('announcementBody')}<textarea name="body" maxlength="4000" required></textarea></label><button>${t('publish')}</button><p class="error"></p></form><div class="toolbar">${button('audit','audit')}${button('moderation','moderation')}</div><div id="admin-extra"></div>`;}
function parseCSV(source){if(source.length>1000000)throw Error('CSV: 1 MB maximum');const rows=[];let row=[],cell='',quote=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quote&&source[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(cell);cell='';}else if(c==='\n'&&!quote){row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(quote)throw Error('CSV: unclosed quote');row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);const headers=rows.shift()?.map(x=>x.replace(/^\uFEFF/,'').trim());if(!headers?.length||new Set(headers).size!==headers.length)throw Error('CSV: unique headings required');return {headers,rows:rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))};}
let importData,importJob;
let directoryFilters={};
const reviewLabel=kind=>t({'verify.person':'verifyPerson','verify.family':'verifyFamily','change.person':'changePerson','change.family':'changeFamily','head.family':'changeHead',membership:'membershipReview',relationship:'relationshipReview',claim:'claimReview'}[kind]||kind);
async function connect(){const announcements=await api(endpoint('/announcements'));let chat;try{chat=await api(endpoint('/connect'));}catch(e){$('#content').innerHTML=`<h2>${t('connect')}</h2><p>${t('chatHelp')}</p><p class="error">${esc(e.message)}</p>${announcementCards(announcements.items)}`;return;}const pref=await api(endpoint('/messaging-preference'));$('#content').innerHTML=`<div class="toolbar"><h2>${t('connect')}</h2>${button('reload','reload')}</div><p>${t('chatHelp')}</p><form data-form="preference" class="toolbar">${select('preference','visibility',['Nobody','FamilyOnly','VerifiedMembers','Connections','SamajMembers'],pref.visibility)}<button>${t('save')}</button><p class="error"></p></form><div class="grid">${chat.items.map(c=>`<article class="card"><h3>${esc(c.other.name)}</h3><span class="pill">${t(c.status)}</span><p>${esc(c.reason)} · ${c.unread} ${t('unread')}</p><div class="toolbar">${c.status==='PENDING'&&c.incoming?button('accept','chat-decision',`data-id="${c.id}" data-status="ACCEPTED"`)+button('decline','chat-decision',`data-id="${c.id}" data-status="DECLINED"`):''}${c.status==='ACCEPTED'?button('message','conversation',`data-id="${c.id}"`):''}${button(c.muted?'unmute':'mute','mute',`data-id="${c.id}" data-muted="${!c.muted}"`)}${button('block','block',`data-id="${c.other.id}"`)}</div></article>`).join('')||`<div class="empty">${t('empty')}</div>`}</div><div id="conversation"></div>${announcementCards(announcements.items)}<div class="toolbar">${button('blocked','blocked')}</div><div id="blocked"></div>`;}
function announcementCards(items){return `<h3>${t('announcements')}</h3>${items.map(a=>`<article class="card"><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><small>${esc(new Date(a.created_at).toLocaleDateString())}</small></article>`).join('')}`;}
async function conversation(id){const c=await api(endpoint('/connect/'+id));$('#conversation').innerHTML=`<section class="card"><h3>${t('message')}</h3>${c.items.map(m=>`<div class="chat-message ${m.mine?'mine':''}">${esc(m.body)}${m.attachments.map(a=>`<p><a href="/api/digital-samaj${endpoint('/message-files/'+a.id)}" download>${esc(a.name)}</a></p>`).join('')}<small>${esc(new Date(m.created_at).toLocaleString())} ${m.mine&&c.participants.some(p=>p.user_id!==m.sender&&p.read_at>=m.created_at)?t('read'):''}</small>${!m.mine?button('report','report-message',`data-id="${m.id}"`):''}</div>`).join('')}<form data-form="message" data-id="${id}"><label>${t('messageBody')}<textarea name="body" maxlength="4000"></textarea></label><label>${t('file')}<input type="file" name="attachment" accept="image/png,image/jpeg,application/pdf"></label><div class="toolbar"><button class="primary">${t('send')}</button>${button('reload','conversation',`data-id="${id}"`)}</div><p class="error"></p></form></section>`;await api(endpoint('/connect/'+id+'/read'),'POST',{});}
async function encodedFile(file,photo=false,crop=false,compact=false){if(!file||file.size>8*1024*1024)throw Error(t('inputPhotoLimit'));let blob=file;if(photo){if(!['image/png','image/jpeg'].includes(file.type))throw Error(t('photoType'));const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>24000000)throw Error(t('photoDimensions'));const w=crop?Math.min(bitmap.width,bitmap.height):bitmap.width,h=crop?w:bitmap.height,scale=Math.min(1,(compact?640:1600)/Math.max(w,h)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));const context=canvas.getContext('2d');context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,(bitmap.width-w)/2,(bitmap.height-h)/2,w,h,0,0,canvas.width,canvas.height);for(const quality of (compact?[.8,.65,.5,.35]:[.86])){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(blob&&(!compact||blob.size<=120*1024))break;}}finally{bitmap.close();}}if(!blob||blob.size>(compact?120*1024:2*1024*1024))throw Error(t('photoOutputLimit'));const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {name:file.name.slice(0,120),mime:blob.type,content:btoa(binary)};}
document.addEventListener('toggle',e=>{if(!e.target.isConnected||!e.target.matches('.member-row[data-member]'))return;if(e.target.open){expandedMember=Number(e.target.dataset.member);document.querySelectorAll('.member-row[data-member]').forEach(row=>{if(row!==e.target)row.open=false;});}},true);
let photoBusy=false,profilePhoto;
document.addEventListener('input',e=>{if(e.target.closest('#wizard')&&e.target.type!=='file'){captureDraft();if(e.target.name==='isDeceased'){const container=e.target.closest('.deceased-fields');container.querySelector('[data-death-fields]').hidden=!e.target.checked;if(!e.target.checked){container.querySelector('[name=dateOfDeath]').value='';captureDraft();}}clearTimeout(autosave);$('#save-status').textContent=t('saving');autosave=setTimeout(()=>saveDraft().catch(err=>{if($('#wizard-error'))$('#wizard-error').textContent=err.message;}),900);}});
document.addEventListener('change',async e=>{try{if(e.target.matches('[data-theme]'))theme(e.target.value);if(e.target.matches('[data-person-photo]')&&e.target.files[0]){if(photoBusy)return;photoBusy=true;clearTimeout(autosave);captureDraft();const owner=draft,target=e.target.dataset.personPhoto;const controls=[...document.querySelectorAll('#wizard button,#wizard input[type=file],.nav button,#language,[data-action=communities]')];controls.forEach(el=>el.disabled=true);try{const photo=await encodedFile(e.target.files[0],true,false,true);if(draft!==owner)return;if(target==='head')draft.data.headPhoto=photo;else draft.data.members[Number(target)].photo=photo;await saveDraft();wizard();}finally{photoBusy=false;controls.forEach(el=>el.disabled=false);}}if(e.target.matches('[data-profile-photo]')&&e.target.files[0]){if(photoBusy)return;photoBusy=true;const form=e.target.closest('form'),owner=currentProfile,controls=[...document.querySelectorAll('button,#language,input[type=file]')];controls.forEach(el=>el.disabled=true);try{const photo=await encodedFile(e.target.files[0],true);if(currentProfile!==owner||!form.isConnected)return;profilePhoto=photo;form.querySelector('[data-photo-preview]').innerHTML=`<img class="photo-full-preview" src="data:${profilePhoto.mime};base64,${profilePhoto.content}" alt="${esc(t('photoPreview'))}">`;}catch(error){profilePhoto=null;form.querySelector('[data-photo-preview]').innerHTML='';throw error;}finally{photoBusy=false;controls.forEach(el=>el.disabled=false);form.querySelector('button[type=submit]').disabled=!profilePhoto;}}if(e.target.id==='language'){if(photoBusy)return;if(draft)await saveDraft();const consent=$('#consent')?.checked;lang=e.target.value;if(draft){shell('');wizard();if($('#consent'))$('#consent').checked=!!consent;}else if(samaj)await show();else await boot();document.documentElement.lang=lang;}}catch(error){notice(error.message);}});
document.addEventListener('click',async e=>{const el=e.target.closest('button,a');if(!el)return;if(photoBusy){e.preventDefault();return;}let draftAction=false;try{
 if(el.dataset.section){await show(el.dataset.section);return;}if(el.dataset.community){await choose(el.dataset.community);return;}if(el.dataset.profile){viewEpoch++;await profile(el.dataset.profile,el.dataset.kind);return;}if(el.dataset.draft){viewEpoch++;draft=await api(endpoint('/drafts/'+el.dataset.draft));expandedMember=null;wizard();return;}
 const action=el.dataset.action;if(!action)return;el.disabled=true;
 if(draft&&$('#wizard')&&['add-member','add-ancestor','remove-member','remove-person-photo','pick-person','unlink-person','wizard-next','wizard-back','wizard-edit','save-draft','submit-draft'].includes(action)){draftAction=true;photoBusy=true;$('#wizard').inert=true;document.querySelectorAll('.nav button,#language').forEach(control=>control.disabled=true);}
 if(action==='boot')await boot();if(action==='communities'){if(draft)await saveDraft();draft=null;await showCommunities();}if(action==='reload')await show();
 if(['families','persons'].includes(action)){kind=action;await directory();}if(action==='page')await directory(el.dataset.query,Number(el.dataset.offset));
 if(action==='new-draft'){draft=await api(endpoint('/drafts'),'POST',{});expandedMember=null;wizard();}
 if(action==='add-member'||action==='add-ancestor'){captureDraft();if(draft.data.members.length>=40)throw Error(t('memberLimit'));draft.data.members.push({data:{},type:'BirthFamily',relationship:action==='add-ancestor'?'Parent':''});expandedMember=draft.data.members.length-1;await saveDraft();wizard();const rows=document.querySelectorAll('.member-row');rows[rows.length-1]?.querySelector('[name=englishName]')?.focus();}
 if(action==='remove-member'){captureDraft();const removed=Number(el.dataset.index);draft.data.members.splice(removed,1);for(const m of draft.data.members)if(m.relatedTo!==undefined&&m.relatedTo!=='head'){const index=Number(m.relatedTo);if(index===removed){m.relatedTo='head';m.relationship='';}else if(index>removed)m.relatedTo=String(index-1);}expandedMember=expandedMember===removed?null:expandedMember!==null&&expandedMember>removed?expandedMember-1:expandedMember;clearTimeout(autosave);await saveDraft(false);wizard();}
 if(action==='remove-person-photo'){captureDraft();if(el.dataset.target==='head')delete draft.data.headPhoto;else delete draft.data.members[Number(el.dataset.target)].photo;await saveDraft();wizard();}
 if(action==='wizard-next'||action==='wizard-back'||action==='wizard-edit'){clearTimeout(autosave);if(action==='wizard-next')validateStep();await saveDraft();draft.step=action==='wizard-edit'?Number(el.dataset.step):draft.step+(action==='wizard-next'?1:-1);await saveDraft();wizard();$('#wizard h3').focus();}
 if(action==='find-person'){const target=el.dataset.target,q=document.querySelector(`[data-person-query="${target}"]`).value.trim(),results=document.querySelector(`[data-person-results="${target}"]`);if(!q){results.textContent=t('enterSearch');return;}const data=await api(endpoint('/persons?q='+encodeURIComponent(q)));results.innerHTML=data.items.filter(p=>p.status!=='ARCHIVED').map(p=>`<button type="button" data-action="pick-person" data-target="${target}" data-id="${p.id}" data-label="${esc(name(p)+' · '+p.code)}">${esc(name(p))}<small>${esc(p.code)} · ${esc([p.nativeVillage,p.currentCity].filter(Boolean).join(' · '))}</small></button>`).join('')||`<p>${t('empty')}</p>`;}
 if(action==='pick-person'&&el.dataset.target.startsWith('profile-')){const form=el.closest('form');form.querySelector('[name=personId]').value=el.dataset.id;form.querySelector('[data-selected-person]').textContent=el.dataset.label;el.closest('details').open=false;return;}
 if(action==='pick-person'||action==='unlink-person'){captureDraft();const target=el.dataset.target,d=draft.data,id=action==='pick-person'?el.dataset.id:'',label=action==='pick-person'?el.dataset.label:'';if(id&&(target==='head'?d.members.some(m=>m.personId===id):d.headPersonId===id||d.members.some((m,i)=>i!==Number(target)&&m.personId===id)))throw Error(t('alreadyLinked'));if(target==='head'){d.headPersonId=id;d.headLabel=label;delete d.headPhoto;}else{const m=d.members[Number(target)];m.personId=id;m.existingLabel=label;delete m.photo;}await saveDraft();wizard();}
 if(action==='save-draft'){await saveDraft();notice(t('savedDraft'));}
 if(action==='submit-draft'){if(!$('#consent').checked)throw Error(t('consentRequired'));await saveDraft();const result=await api(endpoint('/drafts/'+draft.id+'/submit'),'POST',{revision:draft.revision,consent:true});draft=null;notice(t('submitted'));await profile(result.familyId,'families');}
 if(action==='edit-profile')editProfile();if(action==='tree')await tree();
 if(action==='remove-profile-photo'){await api(endpoint('/photos/'+currentProfile.photo),'DELETE',{revision:currentProfile.revision});await profile(currentProfile.id,currentProfile.resource);}
 if(action==='zoom-in'||action==='zoom-out'){treeScale=Math.max(.5,Math.min(1.8,treeScale+(action==='zoom-in'?.15:-.15)));$('.tree').style.zoom=treeScale;}
 if(action==='collapse'){const collapsed=el.dataset.collapsed==='true';document.querySelectorAll('[data-relative]').forEach(n=>n.hidden=!collapsed);el.dataset.collapsed=String(!collapsed);el.textContent=t(collapsed?'collapse':'expand');}
 if(action==='print'){const pl=$('[name="print-language"]').value,exported=await api(endpoint('/'+currentProfile.resource+'/'+currentProfile.id+'/export'));$('#print-document')?.remove();const people=[...(exported.members||[]),...(exported.relatives||[])],all=[exported.family||exported.person,...people];$('#app').insertAdjacentHTML('beforeend',`<section id="print-document"><div class="print-title"><h1>${t('title')}</h1><p>${esc(samaj.name)}</p></div>${all.map(p=>`<article><h2>${esc(name(p))}</h2>${p.kind==='person'&&p.photo?`<img class="profile-photo" src="/api/digital-samaj${endpoint('/photos/'+p.photo)}" alt="">`:''}${details(p,pl)}</article>`).join('')}<table><tbody>${(exported.relationships||[]).map(e=>`<tr><td>${esc(name(people.find(p=>p.id===e.personId)||{}))}</td><td>${esc(pl==='both'?(SamajStrings.en[e.type]||e.type)+' / '+(SamajStrings.hi[e.type]||e.type):(SamajStrings[pl][e.type]||e.type))}</td><td>${esc(name(people.find(p=>p.id===e.relatedId)||{}))}</td></tr>`).join('')}</tbody></table></section>`);await Promise.all([...$('#print-document').querySelectorAll('img')].map(img=>img.decode().catch(()=>{})));document.body.dataset.printing='true';window.print();}
 if(action==='review-detail')await reviewDetail(el.dataset.id);
 if(action==='withdraw'){await api(endpoint('/reviews/'+el.dataset.id+'/withdraw'),'POST',{});await reviews();}
 if(action==='claim')$('#profile-extra').innerHTML=`<form class="card" data-form="claim"><h3>${t('claim')}</h3><label>${t('claimReason')}<textarea name="reason" required maxlength="1000"></textarea></label><button>${t('request')}</button><p class="error"></p></form>`;
 if(action==='request-chat')$('#profile-extra').innerHTML=`<form class="card" data-form="request-chat">${select('reason','reason',[{id:'Family Connection',name:t('FamilyConnection')},{id:'Professional',name:t('Professional')},{id:'Samaj Activity',name:t('SamajActivity')},{id:'Business',name:t('Business')},{id:'Other',name:t('Other')}])}<button>${t('request')}</button><p class="error"></p></form>`;
 if(action==='revoke'){await api(endpoint('/grants/'+el.dataset.id),'DELETE',{});await administration();}
 if(action==='audit'){const r=await api(endpoint('/audit'));$('#admin-extra').innerHTML=`<div class="card"><h3>${t('audit')}</h3>${r.items.map(a=>`<p>${esc(a.at)} · ${esc(a.action)} · ${esc(a.actor)}</p>`).join('')}</div>`;}
 if(action==='moderation'){const r=await api(endpoint('/moderation'));$('#admin-extra').innerHTML=`<h3>${t('moderation')}</h3>${r.items.map(m=>`<article class="card"><p>${esc(m.body)}</p><p>${esc(m.reason)}</p><small>${esc(m.status)}</small>${button('REVIEWED','report-decision',`data-id="${m.id}" data-status="REVIEWED"`)}${button('DISMISSED','report-decision',`data-id="${m.id}" data-status="DISMISSED"`)}</article>`).join('')}`;}
 if(action==='report-decision'){await api(endpoint('/moderation/'+el.dataset.id),'POST',{status:el.dataset.status});notice(t('saved'));}
 if(action==='commit-import'){const r=await api(endpoint('/imports/'+importJob+'/commit'),'POST',{});$('#import-preview').innerHTML=`<div class="card">${details(r)}</div>`;}
 if(action==='duplicates'){const r=await api(endpoint('/duplicates/'+currentProfile.id));$('#profile-extra').innerHTML=`<div class="card"><h3>${t('duplicates')}</h3><p>${t('mergeNote')}</p>${r.items.map(m=>`<div class="member-row"><h3>${esc(name(m.person))}</h3><p>${t('score')}: ${m.score} · ${m.reasons.map(t).join(', ')}</p>${details(m.person)}${button('ignore','ignore-duplicate',`data-id="${m.person.id}"`)}${button('merge','merge-duplicate',`data-id="${m.person.id}" data-revision="${m.person.revision}"`)}</div>`).join('')||t('empty')}</div>`;}
 if(action==='ignore-duplicate'){await api(endpoint('/duplicates/'+currentProfile.id+'/ignore'),'POST',{relatedId:el.dataset.id});el.closest('.member-row').remove();}
 if(action==='merge-duplicate'){const r=await api(endpoint('/duplicates/merge'),'POST',{sourceId:el.dataset.id,targetId:currentProfile.id,sourceRevision:Number(el.dataset.revision),targetRevision:currentProfile.revision});await profile(r.id,'persons');}
 if(action==='chat-decision'){await api(endpoint('/connect/'+el.dataset.id+'/decision'),'POST',{status:el.dataset.status});await connect();}
 if(action==='conversation')await conversation(el.dataset.id);if(action==='mute'){await api(endpoint('/connect/'+el.dataset.id+'/mute'),'POST',{muted:el.dataset.muted==='true'});await connect();}
 if(action==='block'||action==='unblock'){await api(endpoint('/blocks'),action==='block'?'POST':'DELETE',{userId:el.dataset.id});await connect();}
 if(action==='blocked'){const r=await api(endpoint('/blocks'));$('#blocked').innerHTML=r.items.map(u=>`<p>${esc(u.name)} ${button('unblock','unblock',`data-id="${u.id}"`)}</p>`).join('')||t('empty');}
 if(action==='report-message'){$('#conversation').insertAdjacentHTML('beforeend',`<form class="card" data-form="report" data-id="${el.dataset.id}"><label>${t('reportReason')}<textarea name="reason" required maxlength="1000"></textarea></label><button>${t('report')}</button><p class="error"></p></form>`);}
 }catch(error){if(error.stale)return;if($('#wizard-error'))$('#wizard-error').textContent=error.message;notice(error.message);}finally{el.disabled=false;if(draftAction){photoBusy=false;if($('#wizard'))$('#wizard').inert=false;document.querySelectorAll('.nav button,#language').forEach(control=>control.disabled=false);}}});
document.addEventListener('submit',async e=>{const form=e.target;e.preventDefault();if(!form.dataset.form)return;const submit=form.querySelector('button');submit.disabled=true;const err=form.querySelector('.error');if(err)err.textContent='';try{const d=formData(form),type=form.dataset.form;
 if(type==='community'){await api('','POST',d);await showCommunities();}
 if(type==='search')await directory(d.q);
 if(type==='filters'){directoryFilters=Object.fromEntries(Object.entries(d).filter(([,v])=>v));await directory();}
 if(type==='edit'){const data={},pv={};for(const [k,v]of Object.entries(d)){if(k.startsWith('privacy.'))pv[k.slice(8)]=v;else data[k]=v;}if(form.querySelector('[name=isDeceased]'))data.isDeceased=form.querySelector('[name=isDeceased]').checked;const changedPrivacy=Object.fromEntries(Object.entries(pv).filter(([k,v])=>v!==(currentProfile.privacy?.[k]||'PRIVATE')));await api(endpoint('/'+currentProfile.resource+'/'+currentProfile.id),'PATCH',{revision:currentProfile.revision,data,privacy:changedPrivacy});notice(t('saved'));await profile(currentProfile.id,currentProfile.resource);}
 if(type==='membership'){await api(endpoint('/memberships'),'POST',{personId:d.personId,familyId:currentProfile.id,type:d.type,isPrimary:!!d.isPrimary});await profile(currentProfile.id,currentProfile.resource);}
 if(type==='head'){await api(endpoint('/families/'+currentProfile.id+'/head'),'POST',{personId:d.personId,revision:currentProfile.revision});await profile(currentProfile.id,currentProfile.resource);}
 if(type==='relationship'){await api(endpoint('/relationships'),'POST',{personId:currentProfile.id,relatedId:d.personId,type:d.type});notice(t('saved'));}
 if(type==='photo'){if(!profilePhoto)throw Error(t('choosePhoto'));await api(endpoint('/photos'),'POST',{...profilePhoto,kind:'person',entityId:currentProfile.id,revision:currentProfile.revision});profilePhoto=null;await profile(currentProfile.id,currentProfile.resource);}
 if(type==='submit-profile'){await api(endpoint('/'+currentProfile.resource+'/'+currentProfile.id+'/submit'),'POST',{revision:currentProfile.revision,consent:true});await profile(currentProfile.id,currentProfile.resource);}
 if(type==='claim'){await api(endpoint('/claims'),'POST',{personId:currentProfile.id,reason:d.reason});notice(t('submitted'));form.remove();}
 if(type==='decision'){await api(endpoint('/reviews/'+form.dataset.id),'POST',d);await reviews();}
 if(type==='grant'){await api(endpoint('/grants'),'POST',d);await administration();}
 if(type==='announcement'){await api(endpoint('/announcements'),'POST',{title:d.announcementTitle,body:d.body});form.reset();notice(t('saved'));}
 if(type==='import-file'){const file=form.file.files[0],bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length>2*1024*1024)throw Error('Import: 2 MB maximum');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));importData=await api(endpoint('/imports/file'),'POST',{name:file.name,content:btoa(binary)});$('#import-preview').innerHTML=`<form class="card" data-form="import-map"><h3>${t('import')}</h3><div class="form-grid">${fieldNames.filter(k=>k!=='isDeceased').map(k=>select(k,k,['',...importData.headers],importData.headers.find(h=>h.toLowerCase()===k.toLowerCase())||'')).join('')}</div><button>${t('preview')}</button><p class="error"></p></form>`;}
 if(type==='import-map'){const mapping=Object.fromEntries(Object.entries(d).filter(([,v])=>v));if(importData.excelDateSystem)for(const row of importData.rows)for(const field of ['dob','dateOfDeath']){const col=mapping[field];if(col&&/^\d{1,6}$/.test(row[col]))row[col]=new Date(Date.UTC(importData.excelDateSystem===1904?1904:1899,importData.excelDateSystem===1904?0:11,importData.excelDateSystem===1904?1:30)+Number(row[col])*86400000).toISOString().slice(0,10);}const result=await api(endpoint('/imports'),'POST',{mapping,rows:importData.rows});importJob=result.id;$('#import-preview').innerHTML=`<div class="card"><div class="scroll"><table><tbody>${result.rows.map(r=>`<tr><td>${r.row}</td><td>${esc(r.data?.englishName||r.data?.hindiName||'')}</td><td>${t(r.status)}</td><td>${esc(r.error||'')}</td></tr>`).join('')}</tbody></table></div>${button('commitImport','commit-import','class="primary"')}</div>`;}
 if(type==='request-chat'){await api(endpoint('/connect'),'POST',{personId:currentProfile.id,reason:d.reason});await show('connect');}
 if(type==='preference'){await api(endpoint('/messaging-preference'),'POST',d);notice(t('saved'));}
 if(type==='message'){const file=form.attachment.files[0],attachment=file?await encodedFile(file):undefined;await api(endpoint('/connect/'+form.dataset.id+'/send'),'POST',{body:d.body,attachment});await conversation(form.dataset.id);}
 if(type==='report'){await api(endpoint('/messages/'+form.dataset.id+'/report'),'POST',d);notice(t('saved'));form.remove();}
 }catch(error){if(error.stale)return;if(err)err.textContent=error.message;else notice(error.message);}finally{submit.disabled=false;}});
window.addEventListener('afterprint',()=>{delete document.body.dataset.printing;$('#print-document')?.remove();});
window.addEventListener('beforeunload',e=>{if(draft&&$('#save-status')?.textContent!==t('saved')){e.preventDefault();e.returnValue='';}});
boot();
