'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang='en',samaj,communities=[],session,grants=[],section='directory',kind='persons',currentProfile,draft,saveQueue=Promise.resolve(),autosave,treeScale=1;
const t=(key)=>SamajStrings[lang][key]||SamajStrings.en[key]||key;
const fieldNames=['englishName','hindiName','gender','dob','birthTime','birthPlace','bloodGroup','maritalStatus','mobile','whatsapp','email','education','qualification','achievements','occupation','designation','organization','workplace','isDeceased','dateOfDeath','nativeVillage','district','state','currentCity','address','pin'];
const familyFields=['name','nativeVillage','district','state','gotra','kul','kuldevi','kuldevta','address','currentCity','pin','mobile','alternateMobile','whatsapp','email'];
const sensitive=['mobile','alternateMobile','whatsapp','email','dob','birthTime','birthPlace','address','pin','photo','bloodGroup','achievements'];
const options={gender:['','Male','Female','Other','Unspecified'],maritalStatus:['','Single','Married','Widowed','Divorced','Separated','Unspecified'],membership:['BirthFamily','MaritalFamily','GuardianFamily','Other'],relationship:['','Father','Mother','Spouse','Child','Sibling','Guardian','Other']};
const name=p=>p.englishName||p.hindiName||p.name||p.code;
const has=p=>grants.some(g=>g.permission===p);
const button=(label,action,attrs='')=>`<button type="button" data-action="${action}" ${attrs}>${esc(t(label))}</button>`;
function notice(msg){$('#notice').textContent=msg;$('#notice').classList.add('show');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#notice').classList.remove('show'),4500);}
function theme(value){SynapseTheme.write(value);document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value;$('#theme').innerHTML=SynapseTheme.control('data-theme');}
theme(SynapseTheme.read());matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>theme(SynapseTheme.read()));
async function api(path='',method='GET',body){const response=await fetch('/api/digital-samaj'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||String(response.status));return data;}
const endpoint=(path='')=>'/'+samaj.id+path;
function field(key,value='',attrs=''){const type=key==='dob'||key==='dateOfDeath'?'date':key==='birthTime'?'time':key==='email'?'email':key==='mobile'||key==='whatsapp'?'tel':'text';return `<label>${esc(t(key))}${key==='isDeceased'?`<input type="checkbox" name="${key}" ${value?'checked':''} ${attrs}>`:options[key]?`<select name="${key}" ${attrs}>${options[key].map(v=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(t(v||'none'))}</option>`).join('')}</select>`:`<input name="${key}" type="${type}" value="${esc(value)}" maxlength="${key==='address'||key==='achievements'?1000:200}" ${attrs}>`}</label>`;}
function select(label,key,values,value='',attrs=''){return `<label>${esc(t(label))}<select name="${key}" aria-label="${esc(t(label))}" ${attrs}>${values.map(v=>`<option value="${esc(typeof v==='string'?v:v.id)}" ${value===(typeof v==='string'?v:v.id)?'selected':''}>${esc(typeof v==='string'?t(v||'none'):v.name)}</option>`).join('')}</select></label>`;}
function formData(form){return Object.fromEntries(new FormData(form));}
function shell(content){$('#all-apps').textContent=t('allApps');document.documentElement.lang=lang;$('#app').innerHTML=`<div class="hero"><div><p class="eyebrow">${esc(t('title'))}</p><h1>${esc(t('tagline'))}</h1><p class="muted">${esc(t('intro'))}</p>${samaj?`<div class="toolbar"><strong>${esc(samaj.name)}</strong>${button('chooseSamaj','communities')}</div>`:''}</div><div class="hero-mark" aria-hidden="true">✳</div></div>${samaj?`<nav class="nav" aria-label="${esc(t('title'))}">${['directory',...(has('family.create')?['register']:[]),'reviews','connect',...(has('report.view')?['dashboard']:[]),...(has('admin.manage')?['admin']:[])].map(s=>`<button data-section="${s}" aria-current="${section===s?'page':'false'}">${esc(t(s))}</button>`).join('')}</nav>`:''}<div id="content">${content}</div>`;}
async function boot(){shell(`<p>${t('loading')}</p>`);try{session=await (await fetch('/api/auth/status')).json();if(!session.user){shell(`<div class="card"><h2>${t('signIn')}</h2><p>${t('signInNote')}</p><a class="button primary" href="/signin?next=digital-samaj">${t('signIn')}</a></div>`);return;}await showCommunities();}catch(e){shell(`<div class="card"><p class="error">${esc(e.message)}</p><p>${t('noAccess')}</p>${button('reload','boot')}</div>`);}}
async function showCommunities(){samaj=null;const data=await api();communities=data.communities;shell(`<h2>${t('chooseSamaj')}</h2><div class="grid">${communities.map(c=>`<button class="card" data-community="${c.id}"><h3>${esc(c.name)}</h3></button>`).join('')}</div>${data.canSetup?`<form class="card" data-form="community"><h2>${t('createSamaj')}</h2><label>${t('samajName')}<input name="name" required maxlength="120"></label><div class="toolbar"><button class="primary">${t('createSamaj')}</button></div><p class="error"></p></form>`:`<p>${t('noAccess')}</p>`}`);}
async function choose(id){samaj=communities.find(c=>c.id===id)||{id};const data=await api(endpoint());samaj.name=data.name;grants=data.grants;draft=null;await show('directory');}
async function show(next=section){clearTimeout(autosave);if(draft&&$('#wizard'))await saveDraft();await saveQueue;draft=null;section=next;currentProfile=null;shell(`<p>${t('loading')}</p>`);try{await ({directory:directory,register:registrations,reviews:reviews,connect:connect,dashboard:dashboard,admin:administration}[section])();}catch(e){$('#content').innerHTML=`<div class="card"><p class="error">${esc(e.message)}</p>${section==='connect'?`<p>${t('chatHelp')}</p>`:''}${button('reload','reload')}</div>`;}}
function profileCard(p){return `<article class="card"><span class="pill">${esc(t(p.status))}</span><small>${esc(p.code)}</small><h3>${esc(name(p))}</h3><p class="muted">${esc([p.nativeVillage,p.currentCity,p.occupation].filter(Boolean).join(' · '))}</p><button data-profile="${p.id}" data-kind="${p.kind==='family'?'families':'persons'}">${t('view')}</button></article>`;}
async function directory(q='',offset=0){const result=await api(endpoint('/'+kind+'?q='+encodeURIComponent(q)+'&offset='+offset+'&'+new URLSearchParams(directoryFilters)));$('#content').innerHTML=`<div class="toolbar"><h2>${t('directory')}</h2><div>${button('families','families')}${button('persons','persons')}</div></div><form class="toolbar" data-form="search"><label class="sr-only" for="query">${t('search')}</label><input id="query" name="q" type="search" placeholder="${t('search')}" value="${esc(q)}"><button>${t('search')}</button></form><details class="card no-print"><summary>${t('filters')}</summary><form data-form="filters"><div class="form-grid">${['familyCode','gotra','nativeVillage','currentCity','district','state','occupation','qualification','maritalStatus','minAge','maxAge'].map(k=>field(k,directoryFilters[k]||'')).join('')}</div><button>${t('filters')}</button><p class="error"></p></form></details><p class="muted">${result.total} ${t('total')}</p><div class="grid">${result.items.map(profileCard).join('')||`<div class="empty">${t('empty')}</div>`}</div><div class="toolbar">${offset?button('back','page',`data-offset="${Math.max(0,offset-50)}" data-query="${esc(q)}"`):''}${offset+50<result.total?button('next','page',`data-offset="${offset+50}" data-query="${esc(q)}"`):''}</div>`;}
async function registrations(){const data=await api(endpoint('/drafts'));$('#content').innerHTML=`<div class="toolbar"><h2>${t('register')}</h2>${button('newDraft','new-draft','class="primary"')}</div><p>${t('draftNote')}</p><div class="grid">${data.items.filter(d=>!d.submitted_family_id).map(d=>`<article class="card"><p>${esc(new Date(d.updated_at).toLocaleString(lang==='hi'?'hi-IN':'en-IN'))}</p><p>${t('register')} · ${d.step+1}/10</p><button data-draft="${d.id}">${t('resume')}</button></article>`).join('')}</div>`;}
const steps=['family','head','contact','ancestors','members','relationships','photos','privacy','review','submitStep'];
function captureDraft(){if(!draft||!$('#wizard'))return;const data=draft.data;for(const el of $('#wizard').querySelectorAll('[data-bind]')){const path=el.dataset.bind.split('.');let object=data;for(const key of path.slice(0,-1))object=object[key]??=(/^\d+$/.test(key)?[]:{});object[path.at(-1)]=el.type==='checkbox'?el.checked:el.value;}}
function saveDraft(){if(!draft)return Promise.resolve();captureDraft();const snapshot=JSON.parse(JSON.stringify(draft.data)),step=draft.step,did=draft.id;saveQueue=saveQueue.catch(()=>{}).then(async()=>{const result=await api(endpoint('/drafts/'+did),'PATCH',{revision:draft.revision,step,data:snapshot});if(draft?.id===did)draft.revision=result.revision;const status=$('#save-status');if(status)status.textContent=t('saved');});return saveQueue;}
function bound(key,value,path){return field(key,value,`data-bind="${path}.${key}"`);}
function memberEditor(m,i){return `<div class="member-row"><div class="form-grid">${field('existingPerson',m.personId||'',`data-bind="members.${i}.personId"`)}${bound('englishName',m.data?.englishName||'',`members.${i}.data`)}${bound('hindiName',m.data?.hindiName||'',`members.${i}.data`)}${bound('dob',m.data?.dob||'',`members.${i}.data`)}${bound('isDeceased',m.data?.isDeceased||false,`members.${i}.data`)}${bound('dateOfDeath',m.data?.dateOfDeath||'',`members.${i}.data`)}${select('membership','membership',options.membership,m.type||'BirthFamily',`data-bind="members.${i}.type"`)}${select('relationship','relationship',options.relationship,m.relationship||'',`data-bind="members.${i}.relationship"`)}</div>${button('remove','remove-member',`data-index="${i}"`)}</div>`;}
function wizard(){const d=draft.data;d.family||={};d.head||={};d.members||=[];d.privacy||={};let content='';
 if(draft.step===0)content=`<div class="form-grid">${['name','nativeVillage','district','state','gotra','kul','kuldevi','kuldevta'].map(k=>bound(k,d.family[k]||'','family')).join('')}</div>`;
 if(draft.step===1)content=`${field('existingPerson',d.headPersonId||'','data-bind="headPersonId"')}<div class="form-grid">${['englishName','hindiName','gender','dob','birthTime','birthPlace','maritalStatus','education','qualification','occupation','designation','organization','workplace'].map(k=>bound(k,d.head[k]||'','head')).join('')}</div>`;
 if(draft.step===2)content=`<div class="form-grid">${['address','currentCity','pin','mobile','alternateMobile','whatsapp','email'].map(k=>bound(k,d.family[k]||'','family')).join('')}</div>`;
 if([3,4].includes(draft.step))content=`${d.members.map(memberEditor).join('')}${button(draft.step===3?'addAncestor':'addMember','add-member')}`;
 if(draft.step===5)content=`<p>${t('existingPerson')}</p>${d.members.map((m,i)=>`<div class="member-row"><h3>${esc(m.data?.englishName||m.data?.hindiName||m.personId)}</h3>${select('relationship','relationship',options.relationship,m.relationship||'',`data-bind="members.${i}.relationship"`)}</div>`).join('')}`;
 if(draft.step===6)content=`<p>${t('photoHelp')}</p><label>${t('photo')}<input id="draft-photo" type="file" accept="image/png,image/jpeg" capture="environment"></label><p>${esc(d.familyPhoto?.name||t('noPhoto'))}</p>${d.familyPhoto?button('remove','remove-photo'):''}<p class="muted">${t('photoConsent')}</p>`;
 if(draft.step===7)content=`<p>${t('privacyHelp')}</p><div class="form-grid">${sensitive.map(k=>select(k,k,['PRIVATE','FAMILY','SAMAJ','ADMIN','PUBLIC'],d.privacy[k]||'PRIVATE',`data-bind="privacy.${k}"`)).join('')}</div>`;
 if(draft.step===8)content=`<p>${t('reviewHelp')}</p><h3>${t('family')}</h3>${details(d.family)}<h3>${t('head')}</h3>${details(d.head)}${d.members.map(m=>`<h3>${esc(m.data?.englishName||m.personId)}</h3>${details(m.data||{})}<p>${esc(t(m.type||'BirthFamily'))} · ${esc(t(m.relationship||'none'))}</p>`).join('')}`;
 if(draft.step===9)content=`<p>${t('consentNote')}</p><p>${t('reviewerNote')}</p><label><input id="consent" type="checkbox"> ${t('consent')}</label>`;
 $('#content').innerHTML=`<div class="toolbar"><h2>${t('register')}</h2><small id="save-status">${t('saved')}</small></div><div class="steps">${steps.map((s,i)=>`<span class="${i===draft.step?'active':''}" ${i===draft.step?'aria-current="step"':''}>${i+1}. ${t(s)}</span>`).join('')}</div><form id="wizard" class="card"><h3>${draft.step+1}. ${t(steps[draft.step])}</h3>${content}<p class="error" id="wizard-error"></p><div class="toolbar">${draft.step?button('back','wizard-back'):''}${button('saveLater','save-draft')}${draft.step<9?button('next','wizard-next','class="primary"'):button('submit','submit-draft','class="primary"')}</div></form>`;$('.steps .active')?.scrollIntoView({block:'nearest',inline:'center'});}
function details(p,printLang=lang){const label=k=>printLang==='both'?`${SamajStrings.en[k]||k} / ${SamajStrings.hi[k]||k}`:(SamajStrings[printLang]?.[k]||k);return `<dl class="details">${Object.entries(p).filter(([k,v])=>!['id','kind','privacy','members','memberships','photo','revision','headId'].includes(k)&&v!==''&&v!==null&&typeof v!=='object').map(([k,v])=>`<dt>${esc(label(k))}</dt><dd>${esc(typeof v==='boolean'?(v?'✓':'—'):t(v))}</dd>`).join('')}</dl>`;}
async function profile(id,k=kind){const p=await api(endpoint('/'+k+'/'+id));currentProfile={...p,resource:k};draft=null;const canEdit=has(p.kind+'.edit');$('#content').innerHTML=`<article class="card" id="profile"><div class="print-title"><p class="eyebrow">${t('title')} · ${esc(samaj.name)}</p><h2>${esc(name(p))}</h2><span class="pill">${t(p.status)}</span><small>${esc(p.code)}</small></div>${p.photo?`<img class="profile-photo" src="/api/digital-samaj${endpoint('/photos/'+p.photo)}" alt="${esc(t('photo'))}">`:''}<div class="toolbar no-print">${canEdit?button('edit','edit-profile'):''}${(p.kind==='person'||p.headId?button('tree','tree'):'')+(p.kind==='person'?button('claim','claim')+button('message','request-chat'):'')}${has('report.export')?`${select('printLanguage','print-language',[{id:'en',name:'English'},{id:'hi',name:'हिन्दी'},{id:'both',name:t('bilingual')}],lang)}${button('print','print')}`:''}${has('admin.manage')&&p.kind==='person'?button('duplicates','duplicates'):''}</div><div id="profile-details">${details(p)}</div>${p.members?`<h3>${t('members')}</h3><div class="grid">${p.members.map(profileCard).join('')}</div>`:''}${p.memberships?`<h3>${t('families')}</h3>${p.memberships.map(m=>`<p>${t(m.type)} <button data-profile="${m.family_id}" data-kind="families">${t('view')}</button></p>`).join('')}`:''}</article>${canEdit?`<form class="card no-print" data-form="photo"><h3>${t('upload')}</h3><p>${t('photoHelp')}</p><input aria-label="${t('photo')}" name="photo" type="file" accept="image/png,image/jpeg" capture="environment" required><p>${t('photoConsent')}</p><label><input type="checkbox" name="crop"> ${t('crop')}</label><div class="toolbar"><button>${t('upload')}</button></div><p class="error"></p></form>${['DRAFT','CORRECTION_REQUIRED','REJECTED'].includes(p.status)?`<form class="card no-print" data-form="submit-profile"><label><input type="checkbox" name="consent" required> ${t('consent')}</label><div class="toolbar"><button>${t('submit')}</button></div><p class="error"></p></form>`:''}`:''}<div id="profile-extra"></div>`;}
function editProfile(){const p=currentProfile;$('#profile-extra').innerHTML=`<form class="card" data-form="edit"><h3>${t('edit')}</h3><div class="form-grid">${(p.kind==='family'?familyFields:fieldNames).filter(k=>!sensitive.includes(k)||Object.hasOwn(p,k)).map(k=>field(k,p[k]??'')).join('')}</div><h3>${t('privacy')}</h3><div class="form-grid">${sensitive.map(k=>select(k,'privacy.'+k,['PRIVATE','FAMILY','SAMAJ','ADMIN','PUBLIC'],p.privacy?.[k]||'PRIVATE')).join('')}</div><button class="primary">${t('save')}</button><p class="error"></p></form>${p.kind==='family'?`<form class="card" data-form="membership"><h3>${t('linkMember')}</h3>${field('personId')}${select('membership','type',options.membership)}<label><input type="checkbox" name="isPrimary"> ${t('isPrimary')}</label><button>${t('save')}</button><p class="error"></p></form><form class="card" data-form="head"><h3>${t('head')}</h3>${field('personId')}<button>${t('save')}</button><p class="error"></p></form>`:`<form class="card" data-form="relationship"><h3>${t('addRelationship')}</h3>${field('personId')}${select('relationship','type',options.relationship.slice(1))}<button>${t('save')}</button><p class="error"></p></form>`}`;$('#profile-extra').scrollIntoView({block:'start'});}
async function tree(){const data=await api(endpoint('/tree/'+(currentProfile.headId||currentProfile.id))),levels=new Map([[data.root,0]]);for(let i=0;i<8;i++)for(const e of data.edges){if(['Father','Mother','Parent'].includes(e.type)){if(levels.has(e.personId)&&!levels.has(e.relatedId))levels.set(e.relatedId,levels.get(e.personId)-1);if(levels.has(e.relatedId)&&!levels.has(e.personId))levels.set(e.personId,levels.get(e.relatedId)+1);}else if(levels.has(e.personId)&&!levels.has(e.relatedId))levels.set(e.relatedId,levels.get(e.personId));else if(levels.has(e.relatedId)&&!levels.has(e.personId))levels.set(e.personId,levels.get(e.relatedId));}
 const groups=[...new Set(data.nodes.map(n=>levels.get(n.id)||0))].sort((a,b)=>a-b);$('#profile-extra').innerHTML=`<section class="card"><h3>${t('tree')}</h3><div class="toolbar">${button('zoomIn','zoom-in')}${button('zoomOut','zoom-out')}${button('collapse','collapse')}</div><div class="tree-window" tabindex="0" aria-label="${t('tree')}"><div class="tree">${groups.map(level=>`<div class="tree-column">${data.nodes.filter(n=>(levels.get(n.id)||0)===level).map(n=>`<button class="tree-node" data-profile="${n.id}" data-kind="persons" ${n.id!==data.root?'data-relative="true"':''}>${n.photo?`<img class="profile-photo" src="/api/digital-samaj${endpoint('/photos/'+n.photo)}" alt="">`:''}<strong>${esc(name(n))}</strong><small>${esc(n.dob?.slice(0,4)||'')}${n.isDeceased?' · '+t('isDeceased'):''}</small><small>${data.edges.filter(e=>e.personId===data.root&&e.relatedId===n.id).map(e=>t(e.type)).join(', ')}</small></button>`).join('')}</div>`).join('')}</div></div><div class="scroll"><table><tbody>${data.edges.map(e=>`<tr><td>${esc(name(data.nodes.find(n=>n.id===e.personId)))}</td><td>${t(e.type)}</td><td>${esc(name(data.nodes.find(n=>n.id===e.relatedId)))}</td></tr>`).join('')}</tbody></table></div></section>`;treeScale=1;const viewport=$('.tree-window');let drag;viewport.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};viewport.setPointerCapture(e.pointerId);});viewport.addEventListener('pointermove',e=>{if(drag){viewport.scrollLeft=drag.left+drag.x-e.clientX;viewport.scrollTop=drag.top+drag.y-e.clientY;}});viewport.addEventListener('pointerup',()=>drag=null);}
async function reviews(){const result=await api(endpoint('/reviews'));$('#content').innerHTML=`<h2>${t('reviews')}</h2><p>${t('reviewerNote')}</p><div class="grid">${result.items.map(r=>`<article class="card"><span class="pill">${t(r.status)}</span><h3>${esc(reviewLabel(r.kind))}</h3><small>${esc(r.entityId)}</small><div class="toolbar">${has('verification.approve')?button('reviewDetail','review-detail',`data-id="${r.id}"`):''}${r.requestedBy===session.user.id?button('withdraw','withdraw',`data-id="${r.id}"`):''}${r.kind.includes('.')?`<button data-profile="${r.entityId}" data-kind="${r.kind.endsWith('family')?'families':'persons'}">${t('view')}</button>`:''}</div></article>`).join('')||`<div class="empty">${t('empty')}</div>`}</div><div id="review-detail"></div>`;}
async function reviewDetail(id){let r=await api(endpoint('/reviews/'+id));if(r.requestedBy!==session.user.id){await api(endpoint('/reviews/'+id+'/start'),'POST',{});r=await api(endpoint('/reviews/'+id));}$('#review-detail').innerHTML=`<form class="card" data-form="decision" data-id="${id}"><h3>${t('reviewDetail')}</h3><div class="grid"><div><h3>${t('oldValue')}</h3>${details(r.oldValue?.data||r.oldValue||{})}</div><div><h3>${t('newValue')}</h3>${r.newValue?.person?details(r.newValue.person)+details(r.newValue.related)+details({relationship:r.newValue.type}):details(r.newValue?.profile||r.newValue?.data||r.newValue||{})}</div></div>${select('status','decision',[{id:'APPROVE',name:t('approve')},{id:'REJECT',name:t('reject')},{id:'CORRECTION_REQUIRED',name:t('correction')}])}<label>${t('decisionReason')}<textarea name="reason" required maxlength="1000"></textarea></label><button class="primary">${t('save')}</button><p class="error"></p></form>`;$('#review-detail').scrollIntoView({block:'start'});}
async function dashboard(){const d=await api(endpoint('/dashboard'));$('#content').innerHTML=`<h2>${t('dashboard')}</h2><div class="stats">${['families','members','verified','pending','corrections'].map(k=>`<div class="stat"><strong>${d[k]}</strong>${t(k)}</div>`).join('')}</div><h3>${t('statistics')}</h3><p>${t('suppression')}</p><div class="grid">${Object.entries(d.statistics).map(([k,v])=>`<div class="card"><h3>${t(k)}</h3>${Object.entries(v).map(([label,count])=>`<p>${esc(t(label))}: ${count}</p>`).join('')||t('empty')}</div>`).join('')}</div>`;}
async function administration(){const d=await api(endpoint('/grants'));$('#content').innerHTML=`<h2>${t('admin')}</h2><form class="card" data-form="grant"><h3>${t('grant')}</h3><div class="form-grid">${select('account','userId',d.users)}${select('role','role',Object.keys(d.roles))}${select('scope','scope',['ALL','STATE','DISTRICT','VILLAGE','FAMILY','SELF'])}${field('scopeValue')}</div><p>${t('scopeHelp')}</p><button class="primary">${t('grant')}</button><p class="error"></p></form><div class="card">${d.grants.map(g=>`<p>${esc(d.users.find(u=>u.id===g.user_id)?.name||g.user_id)} · ${t(g.role_id)} · ${t(g.scope)} ${esc(g.scope_value)} ${g.user_id!==session.user.id?button('revoke','revoke',`data-id="${g.id}"`):''}</p>`).join('')}</div><form class="card" data-form="import-file"><h3>${t('import')}</h3><p>${t('importHelp')}</p><input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" name="file" aria-label="${t('file')}" required><button>${t('preview')}</button><p class="error"></p></form><div id="import-preview"></div><form class="card" data-form="announcement"><h3>${t('announcements')}</h3>${field('announcementTitle')}<label>${t('announcementBody')}<textarea name="body" maxlength="4000" required></textarea></label><button>${t('publish')}</button><p class="error"></p></form><div class="toolbar">${button('audit','audit')}${button('moderation','moderation')}</div><div id="admin-extra"></div>`;}
function parseCSV(source){if(source.length>1000000)throw Error('CSV: 1 MB maximum');const rows=[];let row=[],cell='',quote=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quote&&source[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(cell);cell='';}else if(c==='\n'&&!quote){row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(quote)throw Error('CSV: unclosed quote');row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);const headers=rows.shift()?.map(x=>x.replace(/^\uFEFF/,'').trim());if(!headers?.length||new Set(headers).size!==headers.length)throw Error('CSV: unique headings required');return {headers,rows:rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))};}
let importData,importJob;
let directoryFilters={};
const reviewLabel=kind=>t({'verify.person':'verifyPerson','verify.family':'verifyFamily','change.person':'changePerson','change.family':'changeFamily','head.family':'changeHead',membership:'membershipReview',relationship:'relationshipReview',claim:'claimReview'}[kind]||kind);
async function connect(){const announcements=await api(endpoint('/announcements'));let chat;try{chat=await api(endpoint('/connect'));}catch(e){$('#content').innerHTML=`<h2>${t('connect')}</h2><p>${t('chatHelp')}</p><p class="error">${esc(e.message)}</p>${announcementCards(announcements.items)}`;return;}const pref=await api(endpoint('/messaging-preference'));$('#content').innerHTML=`<div class="toolbar"><h2>${t('connect')}</h2>${button('reload','reload')}</div><p>${t('chatHelp')}</p><form data-form="preference" class="toolbar">${select('preference','visibility',['Nobody','FamilyOnly','VerifiedMembers','Connections','SamajMembers'],pref.visibility)}<button>${t('save')}</button><p class="error"></p></form><div class="grid">${chat.items.map(c=>`<article class="card"><h3>${esc(c.other.name)}</h3><span class="pill">${t(c.status)}</span><p>${esc(c.reason)} · ${c.unread} ${t('unread')}</p><div class="toolbar">${c.status==='PENDING'&&c.incoming?button('accept','chat-decision',`data-id="${c.id}" data-status="ACCEPTED"`)+button('decline','chat-decision',`data-id="${c.id}" data-status="DECLINED"`):''}${c.status==='ACCEPTED'?button('message','conversation',`data-id="${c.id}"`):''}${button(c.muted?'unmute':'mute','mute',`data-id="${c.id}" data-muted="${!c.muted}"`)}${button('block','block',`data-id="${c.other.id}"`)}</div></article>`).join('')||`<div class="empty">${t('empty')}</div>`}</div><div id="conversation"></div>${announcementCards(announcements.items)}<div class="toolbar">${button('blocked','blocked')}</div><div id="blocked"></div>`;}
function announcementCards(items){return `<h3>${t('announcements')}</h3>${items.map(a=>`<article class="card"><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><small>${esc(new Date(a.created_at).toLocaleDateString())}</small></article>`).join('')}`;}
async function conversation(id){const c=await api(endpoint('/connect/'+id));$('#conversation').innerHTML=`<section class="card"><h3>${t('message')}</h3>${c.items.map(m=>`<div class="chat-message ${m.mine?'mine':''}">${esc(m.body)}${m.attachments.map(a=>`<p><a href="/api/digital-samaj${endpoint('/message-files/'+a.id)}" download>${esc(a.name)}</a></p>`).join('')}<small>${esc(new Date(m.created_at).toLocaleString())} ${m.mine&&c.participants.some(p=>p.user_id!==m.sender&&p.read_at>=m.created_at)?t('read'):''}</small>${!m.mine?button('report','report-message',`data-id="${m.id}"`):''}</div>`).join('')}<form data-form="message" data-id="${id}"><label>${t('messageBody')}<textarea name="body" maxlength="4000"></textarea></label><label>${t('file')}<input type="file" name="attachment" accept="image/png,image/jpeg,application/pdf"></label><div class="toolbar"><button class="primary">${t('send')}</button>${button('reload','conversation',`data-id="${id}"`)}</div><p class="error"></p></form></section>`;await api(endpoint('/connect/'+id+'/read'),'POST',{});}
async function encodedFile(file,photo=false,crop=false){if(!file||file.size>8*1024*1024)throw Error('File: 8 MB maximum input');let blob=file;if(photo){const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>24000000){bitmap.close();throw Error('Photo: 24 megapixels maximum');}const w=crop?Math.min(bitmap.width,bitmap.height):bitmap.width,h=crop?w:bitmap.height,scale=Math.min(1,1600/Math.max(w,h)),canvas=document.createElement('canvas');canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);canvas.getContext('2d').drawImage(bitmap,(bitmap.width-w)/2,(bitmap.height-h)/2,w,h,0,0,canvas.width,canvas.height);bitmap.close();blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.86));}if(!blob||blob.size>2*1024*1024)throw Error('File: 2 MB maximum');const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {name:file.name,mime:blob.type,content:btoa(binary)};}
document.addEventListener('input',e=>{if(e.target.closest('#wizard')){captureDraft();clearTimeout(autosave);$('#save-status').textContent=t('save');autosave=setTimeout(()=>saveDraft().catch(err=>{$('#wizard-error').textContent=err.message;}),900);}});
document.addEventListener('change',async e=>{try{if(e.target.matches('[data-theme]'))theme(e.target.value);if(e.target.id==='draft-photo'&&e.target.files[0]){draft.data.familyPhoto=await encodedFile(e.target.files[0],true);await saveDraft();wizard();}if(e.target.id==='language'){if(draft)await saveDraft();lang=e.target.value;if(draft)wizard();else if(samaj)await show();else await boot();document.documentElement.lang=lang;}}catch(error){notice(error.message);}});
document.addEventListener('click',async e=>{const el=e.target.closest('button,a');if(!el)return;try{
 if(el.dataset.section){await show(el.dataset.section);return;}if(el.dataset.community){await choose(el.dataset.community);return;}if(el.dataset.profile){await profile(el.dataset.profile,el.dataset.kind);return;}if(el.dataset.draft){draft=await api(endpoint('/drafts/'+el.dataset.draft));wizard();return;}
 const action=el.dataset.action;if(!action)return;el.disabled=true;
 if(action==='boot')await boot();if(action==='communities'){if(draft)await saveDraft();draft=null;await showCommunities();}if(action==='reload')await show();
 if(['families','persons'].includes(action)){kind=action;await directory();}if(action==='page')await directory(el.dataset.query,Number(el.dataset.offset));
 if(action==='new-draft'){draft=await api(endpoint('/drafts'),'POST',{});wizard();}
 if(action==='add-member'){captureDraft();draft.data.members.push({data:{},type:'BirthFamily',relationship:draft.step===3?'Father':''});await saveDraft();wizard();}
 if(action==='remove-member'){captureDraft();draft.data.members.splice(Number(el.dataset.index),1);await saveDraft();wizard();}
 if(action==='remove-photo'){delete draft.data.familyPhoto;await saveDraft();wizard();}
 if(action==='wizard-next'||action==='wizard-back'){await saveDraft();draft.step+=action==='wizard-next'?1:-1;await saveDraft();wizard();}
 if(action==='save-draft'){await saveDraft();notice(t('savedDraft'));}
 if(action==='submit-draft'){if(!$('#consent').checked)throw Error(t('consentRequired'));await saveDraft();const result=await api(endpoint('/drafts/'+draft.id+'/submit'),'POST',{revision:draft.revision,consent:true});draft=null;notice(t('submitted'));await profile(result.familyId,'families');}
 if(action==='edit-profile')editProfile();if(action==='tree')await tree();
 if(action==='zoom-in'||action==='zoom-out'){treeScale=Math.max(.5,Math.min(1.8,treeScale+(action==='zoom-in'?.15:-.15)));$('.tree').style.zoom=treeScale;}
 if(action==='collapse'){const collapsed=el.dataset.collapsed==='true';document.querySelectorAll('[data-relative]').forEach(n=>n.hidden=!collapsed);el.dataset.collapsed=String(!collapsed);el.textContent=t(collapsed?'collapse':'expand');}
 if(action==='print'){const pl=$('[name="print-language"]').value,exported=await api(endpoint('/'+currentProfile.resource+'/'+currentProfile.id+'/export'));$('#print-document')?.remove();const people=[...(exported.members||[]),...(exported.relatives||[])],all=[exported.family||exported.person,...people];$('#app').insertAdjacentHTML('beforeend',`<section id="print-document"><div class="print-title"><h1>${t('title')}</h1><p>${esc(samaj.name)}</p></div>${all.map(p=>`<article><h2>${esc(name(p))}</h2>${p.photo?`<img class="profile-photo" src="/api/digital-samaj${endpoint('/photos/'+p.photo)}" alt="">`:''}${details(p,pl)}</article>`).join('')}<table><tbody>${(exported.relationships||[]).map(e=>`<tr><td>${esc(name(people.find(p=>p.id===e.personId)||{}))}</td><td>${esc(pl==='both'?(SamajStrings.en[e.type]||e.type)+' / '+(SamajStrings.hi[e.type]||e.type):(SamajStrings[pl][e.type]||e.type))}</td><td>${esc(name(people.find(p=>p.id===e.relatedId)||{}))}</td></tr>`).join('')}</tbody></table></section>`);await Promise.all([...$('#print-document').querySelectorAll('img')].map(img=>img.decode().catch(()=>{})));document.body.dataset.printing='true';window.print();}
 if(action==='review-detail')await reviewDetail(el.dataset.id);
 if(action==='withdraw'){await api(endpoint('/reviews/'+el.dataset.id+'/withdraw'),'POST',{});await reviews();}
 if(action==='claim')$('#profile-extra').innerHTML=`<form class="card" data-form="claim"><h3>${t('claim')}</h3><label>${t('claimReason')}<textarea name="reason" required maxlength="1000"></textarea></label><button>${t('request')}</button><p class="error"></p></form>`;
 if(action==='request-chat')$('#profile-extra').innerHTML=`<form class="card" data-form="request-chat">${select('reason','reason',[{id:'Family Connection',name:t('FamilyConnection')},{id:'Professional',name:t('Professional')},{id:'Samaj Activity',name:t('SamajActivity')},{id:'Business',name:t('Business')},{id:'Other',name:t('Other')}])}<button>${t('request')}</button><p class="error"></p></form>`;
 if(action==='revoke'){await api(endpoint('/grants/'+el.dataset.id),'DELETE',{});await administration();}
 if(action==='audit'){const r=await api(endpoint('/audit'));$('#admin-extra').innerHTML=`<div class="card"><h3>${t('audit')}</h3>${r.items.map(a=>`<p>${esc(a.at)} · ${esc(a.action)} · ${esc(a.actor)}</p>`).join('')}</div>`;}
 if(action==='moderation'){const r=await api(endpoint('/moderation'));$('#admin-extra').innerHTML=`<h3>${t('moderation')}</h3>${r.items.map(m=>`<article class="card"><p>${esc(m.body)}</p><p>${esc(m.reason)}</p><small>${esc(m.status)}</small>${button('REVIEWED','report-decision',`data-id="${m.id}" data-status="REVIEWED"`)}${button('DISMISSED','report-decision',`data-id="${m.id}" data-status="DISMISSED"`)}</article>`).join('')}`;}
 if(action==='report-decision'){await api(endpoint('/moderation/'+el.dataset.id),'POST',{status:el.dataset.status});notice(t('saved'));}
 if(action==='commit-import'){const r=await api(endpoint('/imports/'+importJob+'/commit'),'POST',{});$('#import-preview').innerHTML=`<div class="card">${details(r)}</div>`;}
 if(action==='duplicates'){const r=await api(endpoint('/duplicates/'+currentProfile.id));$('#profile-extra').innerHTML=`<div class="card"><h3>${t('duplicates')}</h3><p>${t('mergeNote')}</p>${r.items.map(m=>`<div class="member-row"><h3>${esc(name(m.person))}</h3><p>${t('score')}: ${m.score} · ${m.reasons.map(t).join(', ')}</p>${details(m.person)}${button('ignore','ignore-duplicate',`data-id="${m.person.id}"`)}${button('merge','merge-duplicate',`data-id="${m.person.id}" data-revision="${m.person.revision}"`)}</div>`).join('')||t('empty')}</div>`;}
 if(action==='ignore-duplicate'){await api(endpoint('/duplicates/'+currentProfile.id+'/ignore'),'POST',{relatedId:el.dataset.id});el.closest('.member-row').remove();}
 if(action==='merge-duplicate'){const r=await api(endpoint('/duplicates/merge'),'POST',{sourceId:el.dataset.id,targetId:currentProfile.id,sourceRevision:Number(el.dataset.revision),targetRevision:currentProfile.revision});await profile(r.id,'persons');}
 if(action==='chat-decision'){await api(endpoint('/connect/'+el.dataset.id+'/decision'),'POST',{status:el.dataset.status});await connect();}
 if(action==='conversation')await conversation(el.dataset.id);if(action==='mute'){await api(endpoint('/connect/'+el.dataset.id+'/mute'),'POST',{muted:el.dataset.muted==='true'});await connect();}
 if(action==='block'||action==='unblock'){await api(endpoint('/blocks'),action==='block'?'POST':'DELETE',{userId:el.dataset.id});await connect();}
 if(action==='blocked'){const r=await api(endpoint('/blocks'));$('#blocked').innerHTML=r.items.map(u=>`<p>${esc(u.name)} ${button('unblock','unblock',`data-id="${u.id}"`)}</p>`).join('')||t('empty');}
 if(action==='report-message'){$('#conversation').insertAdjacentHTML('beforeend',`<form class="card" data-form="report" data-id="${el.dataset.id}"><label>${t('reportReason')}<textarea name="reason" required maxlength="1000"></textarea></label><button>${t('report')}</button><p class="error"></p></form>`);}
 }catch(error){if($('#wizard-error'))$('#wizard-error').textContent=error.message;notice(error.message);}finally{el.disabled=false;}});
document.addEventListener('submit',async e=>{const form=e.target;e.preventDefault();if(!form.dataset.form)return;const submit=form.querySelector('button');submit.disabled=true;const err=form.querySelector('.error');if(err)err.textContent='';try{const d=formData(form),type=form.dataset.form;
 if(type==='community'){await api('','POST',d);await showCommunities();}
 if(type==='search')await directory(d.q);
 if(type==='filters'){directoryFilters=Object.fromEntries(Object.entries(d).filter(([,v])=>v));await directory();}
 if(type==='edit'){const data={},pv={};for(const [k,v]of Object.entries(d)){if(k.startsWith('privacy.'))pv[k.slice(8)]=v;else data[k]=v;}if(form.querySelector('[name=isDeceased]'))data.isDeceased=form.querySelector('[name=isDeceased]').checked;const changedPrivacy=Object.fromEntries(Object.entries(pv).filter(([k,v])=>v!==(currentProfile.privacy?.[k]||'PRIVATE')));await api(endpoint('/'+currentProfile.resource+'/'+currentProfile.id),'PATCH',{revision:currentProfile.revision,data,privacy:changedPrivacy});notice(t('saved'));await profile(currentProfile.id,currentProfile.resource);}
 if(type==='membership'){await api(endpoint('/memberships'),'POST',{personId:d.personId,familyId:currentProfile.id,type:d.type,isPrimary:!!d.isPrimary});await profile(currentProfile.id,currentProfile.resource);}
 if(type==='head'){await api(endpoint('/families/'+currentProfile.id+'/head'),'POST',{personId:d.personId,revision:currentProfile.revision});await profile(currentProfile.id,currentProfile.resource);}
 if(type==='relationship'){await api(endpoint('/relationships'),'POST',{personId:currentProfile.id,relatedId:d.personId,type:d.type});notice(t('saved'));}
 if(type==='photo'){const file=await encodedFile(form.photo.files[0],true,!!d.crop);await api(endpoint('/photos'),'POST',{...file,kind:currentProfile.kind,entityId:currentProfile.id,revision:currentProfile.revision});await profile(currentProfile.id,currentProfile.resource);}
 if(type==='submit-profile'){await api(endpoint('/'+currentProfile.resource+'/'+currentProfile.id+'/submit'),'POST',{revision:currentProfile.revision,consent:true});await profile(currentProfile.id,currentProfile.resource);}
 if(type==='claim'){await api(endpoint('/claims'),'POST',{personId:currentProfile.id,reason:d.reason});notice(t('submitted'));form.remove();}
 if(type==='decision'){await api(endpoint('/reviews/'+form.dataset.id),'POST',d);await reviews();}
 if(type==='grant'){await api(endpoint('/grants'),'POST',d);await administration();}
 if(type==='announcement'){await api(endpoint('/announcements'),'POST',{title:d.announcementTitle,body:d.body});form.reset();notice(t('saved'));}
 if(type==='import-file'){const file=form.file.files[0],bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length>2*1024*1024)throw Error('Import: 2 MB maximum');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));importData=await api(endpoint('/imports/file'),'POST',{name:file.name,content:btoa(binary)});$('#import-preview').innerHTML=`<form class="card" data-form="import-map"><h3>${t('import')}</h3><div class="form-grid">${fieldNames.filter(k=>k!=='isDeceased').map(k=>select(k,k,['',...importData.headers],importData.headers.find(h=>h.toLowerCase()===k.toLowerCase())||'')).join('')}</div><button>${t('preview')}</button><p class="error"></p></form>`;}
 if(type==='import-map'){const mapping=Object.fromEntries(Object.entries(d).filter(([,v])=>v));if(importData.excelDateSystem)for(const row of importData.rows)for(const field of ['dob','dateOfDeath']){const col=mapping[field];if(col&&/^\d{1,6}$/.test(row[col]))row[col]=new Date(Date.UTC(importData.excelDateSystem===1904?1904:1899,importData.excelDateSystem===1904?0:11,importData.excelDateSystem===1904?1:30)+Number(row[col])*86400000).toISOString().slice(0,10);}const result=await api(endpoint('/imports'),'POST',{mapping,rows:importData.rows});importJob=result.id;$('#import-preview').innerHTML=`<div class="card"><div class="scroll"><table><tbody>${result.rows.map(r=>`<tr><td>${r.row}</td><td>${esc(r.data?.englishName||r.data?.hindiName||'')}</td><td>${t(r.status)}</td><td>${esc(r.error||'')}</td></tr>`).join('')}</tbody></table></div>${button('commitImport','commit-import','class="primary"')}</div>`;}
 if(type==='request-chat'){await api(endpoint('/connect'),'POST',{personId:currentProfile.id,reason:d.reason});await show('connect');}
 if(type==='preference'){await api(endpoint('/messaging-preference'),'POST',d);notice(t('saved'));}
 if(type==='message'){const file=form.attachment.files[0],attachment=file?await encodedFile(file):undefined;await api(endpoint('/connect/'+form.dataset.id+'/send'),'POST',{body:d.body,attachment});await conversation(form.dataset.id);}
 if(type==='report'){await api(endpoint('/messages/'+form.dataset.id+'/report'),'POST',d);notice(t('saved'));form.remove();}
 }catch(error){if(err)err.textContent=error.message;else notice(error.message);}finally{submit.disabled=false;}});
window.addEventListener('afterprint',()=>{delete document.body.dataset.printing;$('#print-document')?.remove();});
window.addEventListener('beforeunload',e=>{if(draft&&$('#save-status')?.textContent!==t('saved')){e.preventDefault();e.returnValue='';}});
boot();
