import {DAYS,emptySetup,makePeriods,validateShape,validateSetup,validateEntries,available,className,move,generate} from './engine.js';
import {exportTimetables,printTimetables,download} from './export.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID();
const KEY='synapse-timetable-lite-v1',steps=['Schedule','Classes','Subjects','Teachers','Allocation','Generate'];
let state=emptySetup(),step=0,editing=null,view='class',selection='',selected=null,week='',worker=null,undo=null,loadError='';
try{const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved),errors=validateShape(parsed);if(!errors.length&&parsed.entries.length)errors.push(...validateEntries(parsed,parsed.entries));if(errors.length)throw Error(errors.join(' '));state=parsed;}}catch(e){loadError='The saved setup could not be loaded. Your stored copy has not been overwritten. Import a valid backup or correct your browser storage. '+e.message;}
function notify(message,errors=false){$('#message').className=errors?'error':'success';$('#message').innerHTML=Array.isArray(message)?'<strong>Unable to satisfy all timetable constraints.</strong><ul>'+message.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':esc(message);}
function save(){if(loadError){$('#save-status').textContent='Saving paused: existing backup could not be read';return;}try{localStorage.setItem(KEY,JSON.stringify(state));$('#save-status').textContent='Saved on this device · '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch{$('#save-status').textContent='Not saved — export a backup now';notify('Browser storage is unavailable or full. Export a backup before closing this tab.',true);}}
function commit(next,{invalidate=true}={}){const issues=validateShape(next);if(issues.length){notify(issues.join(' '),true);return false;}const had=state.entries.length;if(invalidate)next.entries=[];state=next;selected=null;undo=null;save();if(had&&invalidate)notify('Setup saved. Generate again to apply the updated constraints.');return true;}
const input=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='text'?'maxlength="100"':''} ${extra}></label>`;
const options=(items,current,label=x=>x.name)=>items.map(x=>`<option value="${esc(x.id)}" ${x.id===current?'selected':''}>${esc(label(x))}</option>`).join('');
const select=(label,name,items,current,fn)=>`<label>${label}<select name="${name}" aria-label="${esc(label)}" required><option value="">Choose…</option>${options(items,current,fn)}</select></label>`;
const checks=(label,name,items,values)=>`<fieldset><legend>${label}</legend><div class="checks">${items.map(x=>`<label><input type="checkbox" name="${name}" value="${esc(x.id)}" ${values.includes(x.id)?'checked':''}>${esc(x.name)}</label>`).join('')}</div></fieldset>`;
const dayItems=DAYS.map(d=>({id:d,name:d.slice(0,3)}));
const buttons=(type,id)=>`<div class="actions"><button data-edit="${type}" data-id="${esc(id)}">Edit</button><button data-delete="${type}" data-id="${esc(id)}" aria-label="Delete ${esc(type)}">Delete</button></div>`;
function list(headers,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>'<th scope="col">'+h+'</th>').join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')}</tbody></table></div>`:'<div class="empty">Nothing added yet. Add your first item above.</div>';}
function render(){
 $('#steps').innerHTML=steps.map((s,i)=>`<button data-step="${i}" ${i===step?'aria-current="step"':''}><span>${i+1}</span>${s}</button>`).join('');$('#summary').textContent=`${state.classes.length} classes · ${state.teachers.length} teachers · ${state.allocations.reduce((n,a)=>n+a.weekly,0)} weekly lessons`;
 const screens=[schedule,classes,subjects,teachers,allocation,review];$('#workspace').innerHTML=screens[step]()+`<div class="next">${step?'<button data-step="'+(step-1)+'">← '+steps[step-1]+'</button>':'<span></span>'}${step<5?'<button class="primary" data-step="'+(step+1)+'">Continue to '+steps[step+1]+' →</button>':''}</div>`;
 if(worker){$('#generate').disabled=true;$('#generate').textContent='Finding a valid timetable…';}
}
function schedule(){const p=editing?.type==='periods'?state.periods.find(p=>p.id===editing.id):null;return `<div class="card"><div class="section-head"><div><h2>Make room for a great week</h2><p>Start with your institute and its working days.</p></div><span class="eyebrow">01 / SCHEDULE</span></div><form id="institute-form"><div class="grid">${input('Institute name','name',state.institute.name,'text','required')}${input('Academic year','year',state.institute.year,'text','maxlength="40" required')}<label>Institute logo (optional)<input id="logo" type="file" accept="image/png,image/jpeg,image/webp"></label></div>${state.institute.logo?`<img class="logo-preview" src="${state.institute.logo}" alt="Institute logo"><button type="button" id="remove-logo">Remove logo</button>`:''}${checks('Working days','days',dayItems,state.days)}<button class="primary">Save institute & days</button></form></div>
 <div class="card"><h2>Build your school day</h2><p>Create periods automatically, then edit individual rows below. Breaks are always protected.</p><form id="period-builder"><div class="grid">${input('Start time','start','08:00','time','required')}${input('End time','end','14:10','time','required')}${input('Period duration (minutes)','duration',45,'number','min="10" max="180" required')}${input('Lunch starts (optional)','lunchStart','12:00','time')}${input('Lunch ends','lunchEnd','12:40','time')}${input('Short break starts (optional)','breakStart','10:15','time')}${input('Short break ends','breakEnd','10:30','time')}</div><p class="muted">A period is shortened if it reaches a break or the end of the day. Review the rows before continuing.</p><button class="primary">Build periods</button></form>${list(['Period','Time','Type',''],state.periods.map(p=>[esc(p.name),esc(p.start)+' – '+esc(p.end),p.kind==='break'?'Break':'Teaching',buttons('periods',p.id)]))}<details ${p?'open':''}><summary>${p?'Edit period':'Add a period or break manually'}</summary><form id="period-form" class="grid">${input('Name','name',p?.name||'','text','required')}${input('Start','start',p?.start||'','time','required')}${input('End','end',p?.end||'','time','required')}<label>Type<select name="kind"><option value="lesson">Teaching period</option><option value="break" ${p?.kind==='break'?'selected':''}>Break / Lunch</option></select></label><div class="actions"><button class="primary">${p?'Save period':'Add row'}</button>${p?'<button type="button" data-cancel>Cancel</button>':''}</div></form></details></div>
 <div class="card"><h3>Holidays & special non-working days</h3><p>Holidays annotate the selected calendar week. Your recurring weekly timetable stays intact.</p><form id="holiday-form" class="grid">${input('Date','date','','date','required')}${input('Holiday name','name','','text','required')}<div class="actions"><button>Add holiday</button></div></form>${list(['Date','Holiday',''],state.holidays.map(h=>[esc(h.date),esc(h.name),`<button data-delete="holidays" data-id="${esc(h.id)}">Remove</button>`]))}</div>`;}
function classes(){const c=editing?.type==='classes'?state.classes.find(x=>x.id===editing.id):null;return `<div class="card"><div class="section-head"><div><h2>Your classes & batches</h2><p>From Class 6-A to NEET Morning. Use the names that work for you.</p></div><span class="eyebrow">02 / CLASSES</span></div><form id="class-form" class="grid">${input('Class / batch name','name',c?.name||'','text','required placeholder="e.g. Class 6"')}${input('Section (optional)','section',c?.section||'','text','maxlength="40" placeholder="e.g. A"')}<div class="actions"><button class="primary">${c?'Save class':'Add class'}</button>${c?'<button type="button" data-cancel>Cancel</button>':''}</div></form>${list(['Class / batch','Section',''],state.classes.map(c=>[esc(c.name),esc(c.section)||'—',buttons('classes',c.id)]))}</div>`;}
function subjects(){const s=editing?.type==='subjects'?state.subjects.find(x=>x.id===editing.id):null;return `<div class="card"><div class="section-head"><div><h2>What will they learn?</h2><p>Add any subject. Weekly requirements are set per class in Allocation.</p></div><span class="eyebrow">03 / SUBJECTS</span></div><form id="subject-form" class="grid">${input('Subject name','name',s?.name||'','text','required list="subject-names" placeholder="e.g. Mathematics"')}<datalist id="subject-names">${['Mathematics','Science','English','Hindi','Gujarati','Social Science','Computer','Physical Education','Art'].map(x=>'<option>'+x+'</option>').join('')}</datalist><label>Core / demanding subject<select name="core"><option value="false">No</option><option value="true" ${s?.core?'selected':''}>Yes — try to separate from other core lessons</option></select></label><div class="actions"><button class="primary">${s?'Save subject':'Add subject'}</button>${s?'<button type="button" data-cancel>Cancel</button>':''}</div></form>${list(['Subject','Core subject',''],state.subjects.map(s=>[esc(s.name),s.core?'Yes':'No',buttons('subjects',s.id)]))}</div>`;}
function teachers(){const t=editing?.type==='teachers'?state.teachers.find(x=>x.id===editing.id):null;return `<div class="card"><div class="section-head"><div><h2>The people behind each lesson</h2><p>Choose subjects and availability. A teacher can teach across classes.</p></div><span class="eyebrow">04 / TEACHERS</span></div>${!state.subjects.length?'<div class="note">Add subjects first so you can select what each teacher teaches.</div>':''}<form id="teacher-form">${input('Teacher name','name',t?.name||'','text','required placeholder="e.g. Mr. Shah"')}${checks('Subjects they can teach','subjects',state.subjects,t?.subjects||[])}${checks('Available days','days',dayItems,t?.days||state.days)}<details><summary>Available periods (optional)</summary><p>Leave all unchecked for every teaching period. The selected periods apply on each available day.</p>${checks('Restrict to these periods','periods',state.periods.filter(p=>p.kind==='lesson').map(p=>({...p,name:p.name+' · '+p.start})),t?.periods||[])}</details><div class="actions"><button class="primary">${t?'Save teacher':'Add teacher'}</button>${t?'<button type="button" data-cancel>Cancel</button>':''}</div></form>${list(['Teacher','Subjects','Available days',''],state.teachers.map(t=>[esc(t.name),t.subjects.map(id=>esc(state.subjects.find(s=>s.id===id)?.name)).join(', '),t.days.map(d=>d.slice(0,3)).join(', '),buttons('teachers',t.id)]))}</div>`;}
function allocation(){const a=editing?.type==='allocations'?state.allocations.find(x=>x.id===editing.id):null,sub=a?.subjectId||state.subjects[0]?.id;return `<div class="card"><div class="section-head"><div><h2>A subject. A teacher. A weekly plan.</h2><p>Set the required lessons for each class. Daily limits are enforced, including manual edits.</p></div><span class="eyebrow">05 / ALLOCATION</span></div><form id="allocation-form"><div class="grid">${select('Class / batch','classId',state.classes,a?.classId,className)}${select('Subject','subjectId',state.subjects,sub)}${select('Teacher','teacherId',state.teachers.filter(t=>t.subjects.includes(sub)),a?.teacherId)}${input('Required periods / week','weekly',a?.weekly||5,'number','min="1" max="168" required')}${input('Maximum periods / day','daily',a?.daily||1,'number','min="1" max="24" required')}<label>Double periods allowed<select name="double"><option value="false">No — keep lessons separated</option><option value="true" ${a?.double?'selected':''}>Yes — up to two consecutive lessons</option></select></label></div><div class="actions"><button class="primary">${a?'Save allocation':'Add allocation'}</button>${a?'<button type="button" data-cancel>Cancel</button>':''}</div></form>${list(['Class','Subject','Teacher','Weekly / daily max','Double',''],state.allocations.map(a=>[esc(className(state.classes.find(c=>c.id===a.classId))),esc(state.subjects.find(s=>s.id===a.subjectId).name),esc(state.teachers.find(t=>t.id===a.teacherId).name),`${a.weekly} / ${a.daily}`,a.double?'Yes':'No',buttons('allocations',a.id)]))}</div>`;}
function holiday(day){if(!week)return '';const d=new Date(week+'T12:00:00Z'),offset=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-offset+DAYS.indexOf(day));return state.holidays.filter(h=>h.date===d.toISOString().slice(0,10)).map(h=>h.name).join(', ');}
function grid(kind,id){const title=kind==='class'?className(state.classes.find(c=>c.id===id)):state.teachers.find(t=>t.id===id)?.name;return `<h3>${esc(title)}</h3><div class="table-wrap"><table class="timetable"><thead><tr><th scope="col">Period</th>${state.days.map(d=>`<th scope="col">${d.slice(0,3)}${holiday(d)?'<small class="danger">'+esc(holiday(d))+'</small>':''}</th>`).join('')}</tr></thead><tbody>${state.periods.map(p=>p.kind==='break'?`<tr class="break"><th scope="row">${esc(p.name)}<small>${p.start}–${p.end}</small></th><td colspan="${state.days.length}">${esc(p.name)} · ${p.start}–${p.end}</td></tr>`:`<tr><th scope="row">${esc(p.name)}<small>${p.start}–${p.end}</small></th>${state.days.map(d=>{const i=state.entries.findIndex(e=>e.day===d&&e.periodId===p.id&&state.allocations.find(a=>a.id===e.allocationId)[kind==='class'?'classId':'teacherId']===id),e=state.entries[i],a=e&&state.allocations.find(a=>a.id===e.allocationId);return `<td><button class="cell ${e?'':'free'} ${selected===i?'selected':''}" ${kind==='class'?`data-cell data-class="${esc(id)}" data-day="${d}" data-period="${esc(p.id)}" data-index="${i}" ${e?'draggable="true"':''}`:'disabled'} aria-label="${esc(title)}, ${d}, ${esc(p.name)}${a?', '+esc(state.subjects.find(s=>s.id===a.subjectId).name):', Free'}">${a?esc(state.subjects.find(s=>s.id===a.subjectId).name)+'<small>'+esc(kind==='class'?state.teachers.find(t=>t.id===a.teacherId).name:className(state.classes.find(c=>c.id===a.classId)))+'</small>':'—'}${holiday(d)?'<small>Holiday · recurring lesson</small>':''}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}
function workload(){return list(['Teacher','Assigned / week','Available','Free','Workload'],state.teachers.map(t=>{const assigned=state.allocations.filter(a=>a.teacherId===t.id).reduce((n,a)=>n+a.weekly,0),cap=state.days.reduce((n,d)=>n+state.periods.filter(p=>available(state,t,d,p)).length,0),ratio=cap?assigned/cap:assigned?2:0;return [esc(t.name),assigned,cap,Math.max(0,cap-assigned),ratio>.85?'<span class="danger">High · over 85%</span>':ratio<.3?'Low · under 30%':'Balanced'];}));}
function review(){const issues=validateSetup(state),entities=view==='teacher'?state.teachers:state.classes;if(!entities.some(x=>x.id===selection))selection=entities[0]?.id||'';return `<div class="card"><div class="section-head"><div><h2>Your week, thoughtfully arranged</h2><p>All required lessons. No teacher clashes. Breaks kept free.</p></div><button id="generate" class="primary">${state.entries.length?'Regenerate timetable':'Generate timetable'}</button></div><div class="stats"><div class="stat"><strong>${state.days.length}</strong><small>Working days</small></div><div class="stat"><strong>${state.periods.filter(p=>p.kind==='lesson').length}</strong><small>Teaching periods / day</small></div><div class="stat"><strong>${state.allocations.reduce((n,a)=>n+a.weekly,0)}</strong><small>Required lessons / week</small></div></div>${issues.length?'<div class="note"><strong>Before you generate</strong><ul>'+issues.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div>':'<div class="note">Setup checks passed. The generator will now check how all constraints fit together.</div>'}${worker?'<progress aria-label="Generating timetable"></progress><button id="cancel-generation">Cancel generation</button>':''}</div>
 ${state.entries.length?`<div class="card"><div class="section-head"><div><h2>Weekly timetable</h2><p>${state.institute.name?esc(state.institute.name)+' · ':''}${esc(state.institute.year)}</p></div><div class="actions"><button id="print">Print</button><button id="pdf">Download PDF</button><button id="png">Download image</button></div></div><div class="grid"><label>View<select id="view"><option value="class" ${view==='class'?'selected':''}>Class view</option><option value="teacher" ${view==='teacher'?'selected':''}>Teacher view</option><option value="master" ${view==='master'?'selected':''}>Master view · all classes</option></select></label>${view!=='master'?`<label>${view==='teacher'?'Teacher':'Class'}<select id="selection">${options(entities,selection,view==='class'?className:x=>x.name)}</select></label>`:''}<label>Calendar week (optional)<input id="week" type="date" value="${esc(week)}"></label></div><div class="actions"><label>Export scope<select id="scope"><option value="current">Current view</option><option value="classes">Complete timetable · all classes</option><option value="teachers">All teacher timetables</option></select></label></div><div class="note">${view==='teacher'?'Teacher schedules are read-only here. Open Class view to adjust lessons.':'Select a lesson, then a free slot to move it or another lesson in the same class to swap. You can also drag and drop.'} ${selected!==null?'<button id="cancel-selection">Cancel selection</button>':''} ${undo?'<button id="undo">Undo last adjustment</button>':''}</div>${view==='master'?state.classes.map(c=>`<details><summary>${esc(className(c))}</summary>${grid('class',c.id)}</details>`).join(''):selection?grid(view,selection):''}</div>`:'<div class="card empty"><h3>A clear week is a click away</h3><p>Your generated timetable will appear here. Free periods stay visibly empty.</p></div>'}<div class="card"><h2>Teacher workload</h2><p>Based on your allocations and available teaching slots. Holiday annotations do not change recurring workload.</p>${workload()}</div>`;}
function upsert(type,item){const next=structuredClone(state),id=editing?.type===type?editing.id:uid();item.id=id;const i=next[type].findIndex(x=>x.id===id);if(i<0)next[type].push(item);else next[type][i]=item;if(type==='periods')next.periods.sort((a,b)=>a.start.localeCompare(b.start));if(commit(next)){editing=null;render();}}
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,f=new FormData(form),v=k=>String(f.get(k)||'').trim();try{
 if(form.id==='institute-form'){const next=structuredClone(state);next.institute.name=v('name');next.institute.year=v('year');next.days=f.getAll('days');if(commit(next))render();}
 if(form.id==='period-builder'){const breaks=[];for(const [prefix,name] of [['lunch','Lunch'],['break','Short break']]){if(v(prefix+'Start')||v(prefix+'End')){if(!v(prefix+'Start')||!v(prefix+'End'))throw Error('Enter both start and end for each break, or clear both.');breaks.push({start:v(prefix+'Start'),end:v(prefix+'End'),name});}}if(state.periods.length&&!confirm('Replace the daily periods? Teacher period restrictions will be cleared and the timetable will need regeneration.'))return;const next=structuredClone(state);next.periods=makePeriods(v('start'),v('end'),Number(v('duration')),breaks);next.teachers.forEach(t=>t.periods=[]);if(commit(next)){editing=null;render();}}
 if(form.id==='period-form')upsert('periods',{name:v('name'),start:v('start'),end:v('end'),kind:v('kind')});
 if(form.id==='class-form')upsert('classes',{name:v('name'),section:v('section')});
 if(form.id==='subject-form')upsert('subjects',{name:v('name'),core:v('core')==='true'});
 if(form.id==='teacher-form'){if(!f.getAll('subjects').length||!f.getAll('days').length)throw Error('Choose at least one subject and available day.');upsert('teachers',{name:v('name'),subjects:f.getAll('subjects'),days:f.getAll('days'),periods:f.getAll('periods')});}
 if(form.id==='allocation-form')upsert('allocations',{classId:v('classId'),subjectId:v('subjectId'),teacherId:v('teacherId'),weekly:Number(v('weekly')),daily:Number(v('daily')),double:v('double')==='true'});
 if(form.id==='holiday-form'){const next=structuredClone(state);next.holidays.push({id:uid(),date:v('date'),name:v('name')});if(commit(next,{invalidate:false}))render();}
 }catch(error){notify(error.message,true);}});
function adjust(cell){if(selected===null){if(Number(cell.dataset.index)>=0){selected=Number(cell.dataset.index);render();}return;}const a=state.allocations.find(a=>a.id===state.entries[selected].allocationId);if(a.classId!==cell.dataset.class){notify('Choose a destination within the same class.',true);return;}const result=move(state,selected,{day:cell.dataset.day,periodId:cell.dataset.period});if(!result.ok){notify(result.errors.join(' '),true);return;}undo=structuredClone(state.entries);state.entries=result.entries;selected=null;save();render();notify('Timetable adjusted. All constraints still pass.');}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.step!==undefined){if(worker){notify('Cancel generation before changing the setup.',true);return;}step=Number(b.dataset.step);editing=null;selected=null;render();return;}if(b.hasAttribute('data-cancel')){editing=null;render();}if(b.dataset.edit){editing={type:b.dataset.edit,id:b.dataset.id};render();$('#workspace').scrollIntoView({behavior:'smooth'});}if(b.dataset.delete){const type=b.dataset.delete,id=b.dataset.id;if(!confirm('Delete this item? Linked allocations will also be removed.'))return;const next=structuredClone(state);next[type]=next[type].filter(x=>x.id!==id);if(['classes','subjects','teachers'].includes(type)){const field={classes:'classId',subjects:'subjectId',teachers:'teacherId'}[type];next.allocations=next.allocations.filter(a=>a[field]!==id);}if(type==='subjects')next.teachers.forEach(t=>t.subjects=t.subjects.filter(x=>x!==id));if(type==='periods')next.teachers.forEach(t=>t.periods=t.periods.filter(x=>x!==id));if(commit(next,{invalidate:type!=='holidays'})){editing=null;render();}}
 if(b.id==='generate'){const issues=validateSetup(state);if(issues.length){notify(issues,true);return;}worker=new Worker('/timetable-lite/worker.js',{type:'module'});worker.onmessage=({data})=>{worker.terminate();worker=null;if(data.ok){state.entries=data.entries;undo=null;selected=null;save();notify('Timetable generated. Every required lesson is scheduled and all constraints pass.');}else notify(data.errors,true);render();};worker.onerror=()=>{worker.terminate();worker=null;notify('Generation could not finish. Your setup is safe; try again.',true);render();};worker.postMessage(state);render();}
 if(b.id==='cancel-generation'){worker?.terminate();worker=null;render();notify('Generation cancelled. Your previous timetable is unchanged.');}
 if(b.hasAttribute('data-cell'))adjust(b);
 if(b.id==='cancel-selection'){selected=null;render();}
 if(b.id==='undo'&&undo){state.entries=undo;undo=null;selected=null;save();render();notify('Last adjustment undone.');}
 if(b.id==='help-download')download(new Blob([$('#help-content').innerText],{type:'text/plain;charset=utf-8'}),'timetable-lite-help.txt');
 if(b.id==='sample-download'){
 const sample=emptySetup();sample.institute.name='Sample Academy';sample.days=DAYS.slice(0,5);sample.periods=makePeriods('08:00','12:15',45,[{name:'Short break',start:'09:30',end:'09:45'}]);
 sample.classes=[{id:'c1',name:'Class 6',section:'A'},{id:'c2',name:'Class 7',section:'A'}];sample.subjects=[{id:'s1',name:'Mathematics',core:true},{id:'s2',name:'English',core:false}];sample.teachers=sample.subjects.map((s,i)=>({id:'t'+(i+1),name:['Ms. Sample Shah','Mr. Sample Patel'][i],subjects:[s.id],days:[...sample.days],periods:[]}));
 sample.allocations=sample.classes.flatMap(c=>sample.subjects.map((s,i)=>({id:c.id+s.id,classId:c.id,subjectId:s.id,teacherId:'t'+(i+1),weekly:5,daily:1,double:false})));
 const result=generate(sample);if(!result.ok){notify('Sample could not be prepared.',true);return;}sample.entries=result.entries;download(new Blob([JSON.stringify(sample,null,2)],{type:'application/json'}),'timetable-lite-sample.json');
 }
 if(b.id==='backup')download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'timetable-lite-backup.json');
 if(b.id==='remove-logo'){state.institute.logo='';save();render();}
 if(['print','pdf','png'].includes(b.id)){b.disabled=true;try{const scope=$('#scope').value,kind=scope==='teachers'?'teacher':scope==='classes'?'class':view==='teacher'?'teacher':'class',ids=scope==='current'&&view!=='master'?[selection]:(kind==='teacher'?state.teachers:state.classes).map(x=>x.id);if(b.id==='print')await printTimetables(state,kind,ids,week);else await exportTimetables(state,kind,ids,b.id,week);}catch(error){notify('Export failed: '+error.message,true);}finally{b.disabled=false;}}
});
document.addEventListener('change',async e=>{const el=e.target;if(el.name==='subjectId'){const form=el.closest('form');form.querySelector('[name=teacherId]').innerHTML='<option value="">Choose…</option>'+options(state.teachers.filter(t=>t.subjects.includes(el.value)),'');}if(el.id==='view'){view=el.value;selected=null;render();}if(el.id==='selection'){selection=el.value;selected=null;render();}if(el.id==='week'){week=el.value;render();}if(el.id==='theme'){try{window.SynapseTheme.write(el.value);}catch{}applyTheme(el.value);}
 if(el.id==='import'){try{const file=el.files[0];if(!file)return;if(file.size>3*1024*1024)throw Error('Backup must be under 3 MB.');const next=JSON.parse(await file.text()),issues=validateShape(next);if(!issues.length&&next.entries.length)issues.push(...validateEntries(next,next.entries));if(issues.length)throw Error(issues.join(' '));if(!confirm('Replace this device’s current Timetable Lite setup with this backup? Export the current setup first if needed.'))return;worker?.terminate();worker=null;loadError='';commit(next,{invalidate:false});editing=null;step=next.entries.length?5:0;render();notify('Backup imported and validated.');}catch(error){notify('Backup not imported: '+error.message,true);}el.value='';}
 if(el.id==='logo'){try{const file=el.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>3*1024*1024)throw Error('Choose a PNG, JPEG or WebP image under 3 MB.');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>24000000){bitmap.close();throw Error('Logo must be smaller than 24 megapixels.');}const c=document.createElement('canvas'),scale=Math.min(1,600/Math.max(bitmap.width,bitmap.height));c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();state.institute.logo=c.toDataURL('image/png');save();render();}catch(error){notify(error.message,true);}}
});
document.addEventListener('dragstart',e=>{const c=e.target.closest('[data-cell]');if(c){selected=Number(c.dataset.index);e.dataTransfer.setData('text/plain',String(selected));e.dataTransfer.effectAllowed='move';}});document.addEventListener('dragover',e=>{if(e.target.closest('[data-cell]'))e.preventDefault();});document.addEventListener('drop',e=>{const c=e.target.closest('[data-cell]');if(c){e.preventDefault();if(selected!==null)adjust(c);}});
const media=matchMedia('(prefers-color-scheme: dark)');function applyTheme(value){document.body.dataset.theme=value==='system'?(media.matches?'dark':'light'):value;}let theme='system';try{theme=window.SynapseTheme.read();}catch{}$('#theme').value=theme;applyTheme(theme);media.addEventListener('change',()=>applyTheme($('#theme').value));render();if(loadError){notify(loadError,true);$('#save-status').textContent='Local save paused — backup recovery needed';}
