import {className,DAYS,validateEntries} from './engine.js';
const credit='Created with Timetable Lite • Sushant Synapse';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function holiday(s,day,week){if(!week)return '';const d=new Date(week+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7+DAYS.indexOf(day));return s.holidays.filter(h=>h.date===d.toISOString().slice(0,10)).map(h=>h.name).join(', ');}
export function sheets(s,kind,ids,week=''){
 const errors=validateEntries(s,s.entries);if(errors.length)throw Error('Timetable validation failed. Regenerate before exporting.');
 return ids.map(id=>({title:kind==='class'?className(s.classes.find(c=>c.id===id)):s.teachers.find(t=>t.id===id).name,days:s.days.map(day=>day+(holiday(s,day,week)?' · '+holiday(s,day,week):'')),rows:s.periods.map(p=>({label:p.name,time:p.start+'–'+p.end,break:p.kind==='break',cells:s.days.map(day=>{if(p.kind==='break')return [p.name,''];const e=s.entries.find(e=>e.day===day&&e.periodId===p.id&&s.allocations.find(a=>a.id===e.allocationId)[kind==='class'?'classId':'teacherId']===id);if(!e)return ['Free',''];const a=s.allocations.find(a=>a.id===e.allocationId);return [s.subjects.find(x=>x.id===a.subjectId).name,kind==='class'?s.teachers.find(t=>t.id===a.teacherId).name:className(s.classes.find(c=>c.id===a.classId))];})}))}));
}
export async function printTimetables(s,kind,ids,week){
 const data=sheets(s,kind,ids,week),target=document.querySelector('#print-area');target.innerHTML=data.map(sheet=>`<section class="print-sheet">${s.institute.logo?`<img src="${s.institute.logo}" alt="Institute logo">`:''}<h1>${esc(s.institute.name)}</h1><h2>${esc(sheet.title)} · ${esc(s.institute.year)}</h2>${week?'<p>Week containing '+esc(week)+' · Holidays annotate the recurring timetable.</p>':''}<table><thead><tr><th>Period</th>${sheet.days.map(d=>'<th>'+esc(d)+'</th>').join('')}</tr></thead><tbody>${sheet.rows.map(row=>'<tr><th>'+esc(row.label)+'<br>'+esc(row.time)+'</th>'+row.cells.map(c=>'<td>'+esc(c[0])+'<br><small>'+esc(c[1])+'</small></td>').join('')+'</tr>').join('')}</tbody></table><footer>${credit}</footer></section>`).join('');await Promise.all([...target.querySelectorAll('img')].map(i=>i.decode().catch(()=>{})));window.print();
}
function wrap(ctx,text,width){const words=String(text).split(/\s+/),lines=[];let line='';for(const word of words){if(ctx.measureText(word).width>width){if(line){lines.push(line);line='';}for(const ch of word){if(ctx.measureText(line+ch).width>width){lines.push(line);line='';}line+=ch;}}else if(ctx.measureText(line+' '+word).width>width){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines;}
async function canvasSheet(s,sheet,week){
 const c=document.createElement('canvas');c.width=2380;c.height=1684;const ctx=c.getContext('2d');const palette={paper:'#ffffff',ink:'#172d45',muted:'#53677b',line:'#cfdce8',tint:'#edf5fc',accent:'#1766b3'};
 ctx.fillStyle=palette.paper;ctx.fillRect(0,0,c.width,c.height);let textX=65;
 if(s.institute.logo){const image=new Image();image.src=s.institute.logo;await image.decode();const scale=Math.min(120/image.width,100/image.height);ctx.drawImage(image,65,48,image.width*scale,image.height*scale);textX=210;}
 function text(value,x,y,width,size=24,weight=400,maxLines=3){ctx.fillStyle=palette.ink;let lines;do{ctx.font=`${weight} ${size}px system-ui, sans-serif`;lines=wrap(ctx,value,width);if(lines.length<=maxLines||size<=9)break;size--;}while(true);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*size*1.2));return lines.length*size*1.2;}
 text(s.institute.name,textX,83,2100-textX,40,700,2);text(sheet.title+' · '+s.institute.year,65,179,2240,29,600,2);if(week)text('Week containing '+week+' · Holidays annotate recurring lessons',65,225,2240,20);
 const top=260,left=65,width=2250,first=230,col=(width-first)/sheet.days.length,head=85,rowH=Math.min(115,(1510-top-head)/sheet.rows.length);
 ctx.fillStyle=palette.tint;ctx.fillRect(left,top,width,head);text('PERIOD',left+14,top+35,first-28,20,700,2);sheet.days.forEach((d,i)=>text(d,left+first+i*col+14,top+32,col-28,23,700,3));
 sheet.rows.forEach((row,i)=>{const y=top+head+i*rowH;if(row.break){ctx.fillStyle=palette.tint;ctx.fillRect(left,y,width,rowH);}text(row.label,left+14,y+rowH*.34,first-28,Math.min(23,rowH*.26),600,1);text(row.time,left+14,y+rowH*.72,first-28,Math.min(19,rowH*.23),400,1);row.cells.forEach((cell,j)=>{const x=left+first+j*col+14;text(cell[0],x,y+rowH*.31,col-28,Math.min(24,rowH*.26),600,2);text(cell[1],x,y+rowH*.76,col-28,Math.min(19,rowH*.2),400,1);});});
 ctx.strokeStyle=palette.line;ctx.lineWidth=1;const bottom=top+head+sheet.rows.length*rowH;for(let i=0;i<=sheet.rows.length;i++){ctx.beginPath();ctx.moveTo(left,top+head+i*rowH);ctx.lineTo(left+width,top+head+i*rowH);ctx.stroke();}for(const x of [left,...Array.from({length:sheet.days.length+1},(_,i)=>left+first+i*col)]){ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke();}ctx.strokeRect(left,top,width,bottom-top);ctx.font='18px system-ui, sans-serif';ctx.fillStyle=palette.muted;ctx.textAlign='center';ctx.fillText(credit,c.width/2,1628);return c;
}
// Self-contained multipage A4 landscape PDF; image glyphs preserve local scripts.
export function pdfBlob(canvases){const encoder=new TextEncoder(),chunks=[],offsets=[0];let length=0;const add=v=>{const b=typeof v==='string'?encoder.encode(v):v;chunks.push(b);length+=b.length;},object=(id,body)=>{offsets[id]=length;add(`${id} 0 obj\n${body}\nendobj\n`);};add('%PDF-1.4\n');object(1,'<< /Type /Catalog /Pages 2 0 R >>');object(2,`<< /Type /Pages /Kids [${canvases.map((_,i)=>(3+i*3)+' 0 R').join(' ')}] /Count ${canvases.length} >>`);
 canvases.forEach((c,i)=>{const page=3+i*3,img=page+1,content=page+2,raw=atob(c.toDataURL('image/jpeg',.95).split(',')[1]),jpeg=Uint8Array.from(raw,x=>x.charCodeAt(0));object(page,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 841.889764 595.275591] /Resources << /XObject << /Im0 ${img} 0 R >> >> /Contents ${content} 0 R >>`);offsets[img]=length;add(`${img} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${c.width} /Height ${c.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`);add(jpeg);add('\nendstream\nendobj\n');const commands='q\n841.889764 0 0 595.275591 0 0 cm\n/Im0 Do\nQ\n';object(content,`<< /Length ${commands.length} >>\nstream\n${commands}endstream`);});const start=length,count=3+canvases.length*3;add(`xref\n0 ${count}\n0000000000 65535 f \n`);for(let i=1;i<count;i++)add(`${String(offsets[i]).padStart(10,'0')} 00000 n \n`);add(`trailer\n<< /Size ${count} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF\n`);return new Blob(chunks,{type:'application/pdf'});}
function zip(files){const chunks=[];let offset=0;const central=[];const enc=new TextEncoder();const crc=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};const header=(size,values)=>{const b=new Uint8Array(size),v=new DataView(b.buffer);for(const [at,value,bits] of values)bits===16?v.setUint16(at,value,true):v.setUint32(at,value,true);return b;};for(const file of files){const name=enc.encode(file.name),data=file.data,checksum=crc(data),local=header(30,[[0,0x04034b50],[4,20,16],[14,checksum],[18,data.length],[22,data.length],[26,name.length,16]]);chunks.push(local,name,data);central.push(header(46,[[0,0x02014b50],[4,20,16],[6,20,16],[16,checksum],[20,data.length],[24,data.length],[28,name.length,16],[42,offset]]),name);offset+=local.length+name.length+data.length;}const centralSize=central.reduce((n,b)=>n+b.length,0);return new Blob([...chunks,...central,header(22,[[0,0x06054b50],[8,files.length,16],[10,files.length,16],[12,centralSize],[16,offset]])],{type:'application/zip'});}
export async function exportTimetables(s,kind,ids,format,week){const data=sheets(s,kind,ids,week);if(!data.length)throw Error('No timetables to export.');const canvases=[];for(const sheet of data)canvases.push(await canvasSheet(s,sheet,week));if(format==='pdf'){download(pdfBlob(canvases),'timetable-lite.pdf');return;}const files=[];for(let i=0;i<canvases.length;i++){const blob=await new Promise(resolve=>canvases[i].toBlob(resolve,'image/png'));if(!blob)throw Error('Image could not be created.');files.push({name:`timetable-${i+1}.png`,data:new Uint8Array(await blob.arrayBuffer())});}download(files.length===1?new Blob([files[0].data],{type:'image/png'}):zip(files),files.length===1?'timetable-lite.png':'timetable-lite-images.zip');}
