const {test,expect}=require('@playwright/test');const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');let child,base,dir;
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-ritual-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timed out')),15000);child.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve();}});child.once('error',reject);});});
test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});
test('all bilingual guides, materials, search, completion isolation, downloads and printing',async({page})=>{
 const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});await page.route('**/api/**',r=>r.abort());await page.goto(base+'/ritual-assist');await expect(page.locator('.guide-option')).toHaveCount(12);
 for(const lang of ['en','hi']){await page.locator('#language').selectOption(lang);for(const button of await page.locator('.guide-option').all()){const id=await button.getAttribute('data-guide');await button.click();await expect(page.locator('#guide-title')).not.toBeEmpty();await expect(page.locator('.steps li').first()).toBeVisible();expect(await page.locator('.check-item').count()).toBeGreaterThanOrEqual(4);await expect(page.locator('.guide-option[aria-pressed=true]')).toHaveAttribute('data-guide',id);await page.locator('.reference summary').click();await expect(page.locator('.reference a').first()).toHaveAttribute('href',/^https:/);}}
 await page.locator('#search').fill('श्राद्ध');await expect(page.locator('.guide-option')).toHaveCount(1);await page.locator('.guide-option').click();await page.locator('[data-item=water]').check();await expect(page.locator('#progress')).toContainText('1 / 5');await page.locator('#language').selectOption('en');await expect(page.locator('[data-item=water]')).toBeChecked();
 const dl=page.waitForEvent('download');await page.locator('#download').click();const file=await dl,target='test-results/ritual-shraddha.txt';await file.saveAs(target);const contents=fs.readFileSync(target,'utf8');expect(contents).toContain('[x] Water, vessel and spoon');expect(contents).toContain('confirm first');expect(contents).toContain('References');
 await page.locator('#search').fill('');await page.locator('[data-guide=ganesh-puja]').click();await expect(page.locator('[data-item=water]')).not.toBeChecked();await page.locator('[data-guide=shraddha]').click();await expect(page.locator('[data-item=water]')).toBeChecked();await page.locator('#reset').click();await expect(page.locator('[data-item=water]')).not.toBeChecked();
 await page.locator('#search').fill('<img src=x onerror=alert(1)>');await expect(page.locator('.guide-option')).toHaveCount(0);await expect(page.locator('#results')).toContainText('No matching');expect(await page.locator('#guide-list img').count()).toBe(0);await page.locator('#search').fill('');await page.getByRole('button',{name:'Ashubh · mourning & remembrance',exact:true}).click();await expect(page.locator('.guide-option')).toHaveCount(4);
 await page.evaluate(()=>{window.print=()=>{window.printInvoked=true;window.dispatchEvent(new Event('beforeprint'));};});await page.locator('#print').click();expect(await page.evaluate(()=>window.printInvoked)).toBe(true);await page.emulateMedia({media:'print'});await expect(page.locator('.library')).toBeHidden();await expect(page.locator('.reference a')).toBeVisible();await expect(page.locator('.actions')).toBeHidden();const pdf=await page.pdf({path:'test-results/ritual-checklist.pdf',format:'A4',preferCSSPageSize:true});expect(pdf.subarray(0,8).toString()).toContain('%PDF-');await page.emulateMedia({media:'screen'});await page.reload();await expect(page.locator('[data-item=water]')).not.toBeChecked();expect(errors).toEqual([]);expect(api).toEqual([]);
});
test('mobile navigation, themes, copy fallback, native sharing cancellation and valid deep links',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:undefined});Object.defineProperty(navigator,'share',{value:async data=>{window.shareData=data;throw new DOMException('Cancelled','AbortError');}});});await page.setViewportSize({width:390,height:844});await page.goto(base+'/ritual-assist?guide=antyeshti&lang=hi');await expect(page.locator('#guide-title')).toHaveText('अंत्येष्टि की तैयारी');await expect(page.locator('html')).toHaveAttribute('lang','hi');await page.locator('#copy').click();await expect(page.locator('#copy-text')).toHaveValue(/अंत्येष्टि/);await page.locator('#share').click();await expect(page.locator('#status')).toContainText('रद्द');expect((await page.evaluate(()=>window.shareData)).url).toContain('guide=antyeshti');
 await page.locator('[data-guide=ganesh-puja]').click();await expect(page.locator('#library')).not.toHaveAttribute('open','');await expect(page.locator('#guide-title')).toBeFocused();await expect(page.locator('#guide-title')).toHaveText('गणेश पूजा');await page.locator('#language').selectOption('en');await page.locator('#theme').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.screenshot({path:'test-results/ritual-desktop-dark.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('#theme').click();await page.screenshot({path:'test-results/ritual-mobile-light.png',fullPage:true});await page.goto(base+'/ritual-assist?guide=bad&lang=bad');await expect(page.locator('#guide-title')).toHaveText('Daily home puja');await expect(page.locator('#language')).toHaveValue('en');expect(errors).toEqual([]);
});
test('public homepage finder and no-JavaScript discovery link to the new app',async({page,browser})=>{
 await page.goto(base+'/');await page.getByRole('button',{name:'Search apps',exact:true}).click();await page.getByLabel('Search apps or activities').fill('samagri');await expect(page.locator('.finder-result')).toHaveCount(1);await page.locator('.finder-result').click();await expect(page).toHaveURL(/\/ritual-assist/);await expect(page.locator('#guide-title')).toBeVisible();
 const context=await browser.newContext({javaScriptEnabled:false});try{const nojs=await context.newPage();await nojs.goto(base+'/');await nojs.getByRole('link',{name:'Ritual Assist',exact:true}).click();await expect(nojs.locator('noscript .scope')).toContainText('Enable JavaScript');}finally{await context.close();}
});
