'use strict';
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={
 grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',
 scales:'<path d="M12 3v17m-4 1h8M4 7h16M6 7l-3 7h6L6 7zm12 0-3 7h6l-3-7zM3 14a3 3 0 0 0 6 0m6 0a3 3 0 0 0 6 0"/>',
 projects:'<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M8 2v4m8-4v4M3 9h18m-13 5 3 3 5-5"/>',
 finance:'<path d="M4 21V4h16v17l-4-2-4 2-4-2-4 2zm4-14h8m-8 4h8m-8 4h3"/>',
 knowledge:'<path d="M12 5C8 2 5 3 3 4v16c3-2 6-1 9 1 3-2 6-3 9-1V4c-3-2-6-1-9 1zm0 0v16"/>',
 star:'<path d="m12 3 2.8 5.8 6.4 1-4.6 4.5 1 6.4-5.6-3-5.6 3 1-6.4L2.8 9.8l6.4-1L12 3z"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 team:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 4v3"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',
 moon:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11z"/>',
 logout:'<path d="M10 3H4v18h6m5-15 6 6-6 6m-6-6h12"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/>',
 plus:'<path d="M12 4v16M4 12h16"/>',
};
const icon=name=>`<svg viewBox="0 0 24 24" class="icon" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.grid}</svg>`;
const initials=name=>name.split(' ').filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();
let state,section='apps',category='All',query='',authStatus;
let theme=SynapseTheme.read();
const systemTheme=matchMedia('(prefers-color-scheme: dark)');
function setTheme(value){theme=value;SynapseTheme.write(value);document.documentElement.dataset.theme=theme==='system'?(systemTheme.matches?'dark':'light'):theme;document.querySelectorAll('[data-theme-icon]').forEach(el=>el.innerHTML=icon(document.documentElement.dataset.theme==='dark'?'moon':'sun'));}
setTheme(theme);systemTheme.addEventListener('change',()=>setTheme(theme));
function themeControl(){return `<label class="theme-picker" title="Colour theme"><span data-theme-icon>${icon(document.documentElement.dataset.theme==='dark'?'moon':'sun')}</span><select aria-label="Colour theme" data-theme>${['system','light','dark'].map(t=>`<option value="${t}" ${t===theme?'selected':''}>${t[0].toUpperCase()+t.slice(1)}</option>`).join('')}</select></label>`;}
function brand(){return `<a class="brand" href="/" aria-label="Sushant Synapse home"><img src="/logo-adaptive-192.png" alt="" width="42" height="42"><span>Sushant Synapse<small>PLATFORM</small></span></a>`;}
function notice(text){$('#notice').textContent=text;$('#notice').classList.add('show');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#notice').classList.remove('show'),3500);}
async function api(route,method='GET',body){const r=await fetch('/api/'+route,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok){if(r.status===401&&state){state=null;section='apps';category='All';query='';await boot();}throw Error(data.error||'Request failed');}return data;}
async function submit(form,fn){const button=form.querySelector('[type="submit"]');button.disabled=true;form.querySelector('.error').textContent='';try{await fn();}catch(e){form.querySelector('.error').textContent=e.message;}finally{button.disabled=false;}}
function authView(){const setup=authStatus.setupRequired;$('#platform').innerHTML=`<main id="main" class="auth-layout"><section class="welcome">${brand()}<div class="welcome-copy"><span class="eyebrow">ONE ACCOUNT. A WORLD OF POSSIBILITIES.</span><h1>Your world of work.<br><em>Connected.</em></h1><p>Thoughtfully built apps. One familiar home.<br>Welcome to Sushant Synapse.</p><div class="welcome-app"><span class="app-icon green">${icon('scales')}</span><div><strong>Meet Chambers</strong><small>Your advocate workspace, now part of Synapse.</small></div>${icon('arrow')}</div></div><span class="welcome-footer">apps.sushantsynapse.com</span></section><section class="auth-panel"><div class="auth-theme">${themeControl()}</div><form id="auth-form"><span class="eyebrow">${setup?'LET’S GET STARTED':'YOUR APPS ARE WAITING'}</span><h2>${setup?'Set up your platform':'Welcome back'}</h2><p>${setup?'Create your owner account. Existing Chambers records will stay right where they are.':'Sign in once to access the apps available to you.'}</p>${setup?'<label>Your name<input name="name" required autocomplete="name" maxlength="120"></label><label>Workspace name<input name="firmName" required placeholder="Your organisation or chambers" maxlength="200"></label>':''}<label>Email address<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required minlength="${setup?'12':'1'}" maxlength="128" autocomplete="${setup?'new-password':'current-password'}"></label>${setup?'<p class="hint">Use at least 12 characters.</p>':''}${setup&&authStatus.setupProtected?'<label>Setup token<input name="setupToken" type="password" required autocomplete="off"><small>Provided by the person deploying this platform.</small></label>':''}<p class="error" role="alert"></p><button class="primary wide" type="submit">${setup?'Create platform':'Sign in'} ${icon('arrow')}</button><p class="auth-note">${setup?'Add team members and choose their app access after setup.':'Need an account or a password reset? Contact your platform owner.'}</p></form><div class="secure-note">${icon('lock')} One account across Sushant Synapse apps</div></section></main>`;$('#auth-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{await api(setup?'auth/setup':'auth/login','POST',Object.fromEntries(new FormData(e.target)));const next=new URLSearchParams(location.search).get('next');if(next==='advocate'){location.assign('/advocate');return;}history.replaceState(null,'','/');await load();});};}
const navItems=[['apps','grid','All apps'],['favorites','star','Favourites'],['recent','clock','Recent'],['team','team','Team access'],['profile','user','My profile']];
function nav(){return navItems.filter(([id])=>id!=='team'||state.user.role==='Owner').map(([id,glyph,name])=>`<button data-section="${id}" class="nav-item ${section===id?'selected':''}" ${section===id?'aria-current="page"':''}>${icon(glyph)}<span>${name}</span></button>`).join('');}
async function load(){state=await api('platform');if(section==='team'&&state.user.role!=='Owner')section='apps';render();}
function render(){const count=state.apps.filter(a=>a.accessible).length;$('#platform').innerHTML=`<aside class="sidebar">${brand()}<span class="nav-caption">YOUR WORKSPACE</span><nav aria-label="Platform navigation">${nav()}</nav><div class="sidebar-bottom"><div class="platform-note"><span class="dot"></span> Built to grow with you<p>One home for everything<br>you do next.</p></div><div class="account"><span class="avatar">${escapeHtml(initials(state.user.name))}</span><div><strong>${escapeHtml(state.user.name)}</strong><small>${escapeHtml(state.user.role)}</small></div><button class="icon-button" data-action="logout" aria-label="Sign out">${icon('logout')}</button></div></div></aside><div class="shell"><header class="topbar"><div class="mobile-brand">${brand()}</div><span class="breadcrumb">Sushant Synapse <span>/</span> ${navItems.find(x=>x[0]===section)?.[2]}</span><div class="header-actions">${themeControl()}<button class="avatar profile-button" data-section="profile" aria-label="My profile">${escapeHtml(initials(state.user.name))}</button></div></header><main id="main"><div class="page-top"><div><span class="eyebrow">SUSHANT SYNAPSE PLATFORM</span><h1>${section==='apps'?`Welcome, ${escapeHtml(state.user.name.split(' ')[0])}.`:section==='favorites'?'Your favourites.':section==='recent'?'Pick up where you left off.':section==='team'?'The right apps. The right people.':'Make yourself at home.'}</h1><p>${section==='apps'?'One home for your apps. More room for what matters.':section==='favorites'?'Keep your everyday apps close at hand.':section==='recent'?'Your recently opened apps, ready when you are.':section==='team'?'Manage accounts and access to each available app.':'Your account is shared across all Sushant Synapse apps.'}</p></div>${section==='apps'?`<span class="available-count"><span class="dot"></span>${count} app${count===1?'':'s'} available to you</span>`:''}</div><div id="content">${content()}</div><footer><span>Sushant Synapse Platform</span><span>Designed to connect your work.</span></footer></main></div><nav class="mobile-nav" aria-label="Mobile platform navigation">${nav()}</nav>`;bindForms();}
function content(){if(section==='team')return teamView();if(section==='profile')return profileView();const list=filteredApps();return `${section==='apps'?`<section class="intro-banner"><div><span class="eyebrow">YOUR APP COLLECTION</span><h2>Different tools.<br>One connected workspace.</h2><p>Start with Chambers. Discover more apps as the platform grows.</p></div><div class="constellation" aria-hidden="true"><span>${icon('scales')}</span><span>${icon('projects')}</span><span>${icon('knowledge')}</span><span>${icon('finance')}</span><img src="/logo-adaptive-192.png" alt=""></div></section>`:''}<div class="catalog-toolbar"><div class="tabs" aria-label="App categories">${['All','Legal','Productivity','Business'].map(c=>`<button data-category="${c}" class="${category===c?'active':''}">${c}</button>`).join('')}</div><label class="search">${icon('search')}<input id="app-search" type="search" placeholder="Find an app…" aria-label="Search apps" value="${escapeHtml(query)}"></label></div><div id="app-results">${appGrid(list)}</div>${section==='apps'?'<p class="catalog-note">Planned apps are a preview of the roadmap. They are not available to open yet.</p>':''}`;}
function filteredApps(){let list=state.apps;if(section==='favorites')list=list.filter(a=>state.preferences.favorites.includes(a.id));if(section==='recent')list=state.preferences.recent.map(r=>state.apps.find(a=>a.id===r.id)).filter(Boolean);return list.filter(a=>(category==='All'||a.category===category)&&[a.name,a.subtitle,a.category,a.description].join(' ').toLowerCase().includes(query.toLowerCase()));}
function appGrid(list){return list.length?`<div class="app-grid">${list.map(a=>`<article class="app-card ${a.status==='Planned'?'planned':''}"><div class="app-card-top"><span class="app-icon ${a.accent}">${icon(a.icon)}</span><span class="badge ${a.accessible?'available':''}">${a.status==='Planned'?'Planned':a.accessible?'Available':'Access required'}</span>${a.accessible?`<button class="icon-button favorite ${state.preferences.favorites.includes(a.id)?'saved':''}" data-action="favorite" data-id="${a.id}" aria-label="${state.preferences.favorites.includes(a.id)?'Remove '+a.name+' from favourites':'Add '+a.name+' to favourites'}" aria-pressed="${state.preferences.favorites.includes(a.id)}">${icon('star')}</button>`:''}</div><span class="app-category">${a.category}</span><h2>${a.name}</h2><h3>${a.subtitle}</h3><p>${a.description}</p><div class="feature-tags">${a.features.map(f=>`<span>${f}</span>`).join('')}</div><div class="app-card-bottom">${a.accessible?`<button class="launch" data-action="launch" data-id="${a.id}">Open ${a.name} ${icon('arrow')}</button>`:a.status==='Planned'?`<span class="not-live">${icon('clock')} In the pipeline</span>`:`<span class="not-live">${icon('lock')} Contact your platform owner</span>`}${section==='recent'?`<small>${new Date(state.preferences.recent.find(r=>r.id===a.id).at).toLocaleDateString('en-IN')}</small>`:''}</div></article>`).join('')}</div>`:`<div class="empty">${icon(section==='favorites'?'star':'search')}<h2>${section==='favorites'&&!query?'No favourites yet':'No apps to show'}</h2><p>${section==='favorites'?'Use the star on an available app to save it here.':section==='recent'?'Apps you open from this platform will appear here.':'Try another category or search term.'}</p><button class="secondary" data-section="apps">Browse all apps</button></div>`;}
function profileView(){return `<div class="settings-grid"><section class="panel"><h2>Your profile</h2><p>This identity appears across your apps.</p><form id="profile-form"><label>Name<input name="name" value="${escapeHtml(state.user.name)}" required maxlength="120"></label><label>Email<input name="email" type="email" value="${escapeHtml(state.user.email)}" required></label><p class="error" role="alert"></p><button type="submit" class="primary">Save profile</button></form></section><section class="panel"><h2>Password & security</h2><p>Changing your password signs out other sessions.</p><form id="password-form"><label>Current password<input type="password" name="currentPassword" required autocomplete="current-password"></label><label>New password<input type="password" name="newPassword" minlength="12" maxlength="128" required autocomplete="new-password"></label><p class="error" role="alert"></p><button type="submit" class="secondary">Change password</button></form></section><section class="panel"><h2>Appearance</h2><p>Your theme follows you between Synapse and Chambers on this device.</p>${themeControl()}<button class="secondary signout" data-action="logout">${icon('logout')} Sign out</button></section></div>`;}
function teamView(){return `<section class="panel team-panel"><div class="section-heading"><div><h2>Platform accounts</h2><p>Owners can open every available app. Other users receive access individually. Advocate and clerk permissions apply inside Chambers.</p></div><button class="primary" data-action="add-user">${icon('plus')} Add member</button></div>${state.team.map(u=>`<article class="team-row"><span class="avatar">${escapeHtml(initials(u.name))}</span><div class="team-person"><strong>${escapeHtml(u.name)}</strong><small>${escapeHtml(u.email)}</small><span class="role-label">${u.role}${u.active?'':' · Inactive'}</span></div><div class="access-list">${state.apps.filter(a=>a.status==='Available').map(a=>`<label class="check"><input type="checkbox" data-access-user="${u.id}" data-app="${a.id}" ${u.role==='Owner'||u.appIds.includes(a.id)?'checked':''} ${u.role==='Owner'?'disabled':''}>${a.name}</label>`).join('')}</div><button class="secondary" data-action="edit-user" data-id="${u.id}">Manage</button></article>`).join('')}</section>`;}
function bindForms(){if($('#profile-form'))$('#profile-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{await api('auth/profile','PATCH',Object.fromEntries(new FormData(e.target)));await load();notice('Profile saved');});};if($('#password-form'))$('#password-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{await api('auth/password','POST',Object.fromEntries(new FormData(e.target)));e.target.reset();notice('Password updated');});};}
function userForm(id){const u=state.team.find(x=>x.id===id)||{};const modal=$('#platform-dialog');modal.innerHTML=`<div class="dialog-heading"><h2 id="dialog-title">${id?'Manage member':'Add a team member'}</h2><button class="icon-button" data-action="close" aria-label="Close dialog">×</button></div><form id="user-form"><label>Name<input name="name" required value="${escapeHtml(u.name)}"></label><label>Email<input name="email" type="email" required value="${escapeHtml(u.email)}"></label><label>Role<select name="role" aria-label="Role">${['Advocate','Clerk','Owner'].map(r=>`<option ${u.role===r?'selected':''}>${r}</option>`).join('')}</select></label><label>${id?'New password (optional)':'Initial password'}<input name="password" type="password" minlength="12" maxlength="128" ${id?'':'required'} autocomplete="new-password"></label>${id?`<label class="check"><input type="checkbox" name="active" ${u.active?'checked':''}>Account active</label>`:`<label class="check"><input type="checkbox" name="advocate" checked>Chambers access</label>`}<p class="error" role="alert"></p><button type="submit" class="primary wide">Save member</button></form>`;modal.showModal();$('#user-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{const input=Object.fromEntries(new FormData(e.target));if(id)input.active=input.active==='on';else input.appIds=input.advocate==='on'?['advocate']:[];delete input.advocate;await api('users'+(id?'/'+id:''),id?'PATCH':'POST',input);modal.close();await load();notice('Team member saved');});};}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-section],[data-category],[data-action]');if(!target)return;try{if(target.dataset.section){section=target.dataset.section;category='All';query='';render();scrollTo(0,0);return;}if(target.dataset.category){category=target.dataset.category;$('#content').innerHTML=content();return;}const {action,id}=target.dataset;if(action==='launch'){target.disabled=true;try{const result=await api('platform/apps/'+id+'/launch','POST',{});location.assign(result.path);}finally{target.disabled=false;}}if(action==='favorite'){const favorites=state.preferences.favorites.includes(id)?state.preferences.favorites.filter(x=>x!==id):[...state.preferences.favorites,id];await api('platform/preferences','PATCH',{favorites});await load();}if(action==='logout'){await api('auth/logout','POST');state=null;section='apps';category='All';query='';await boot();}if(action==='add-user')userForm();if(action==='edit-user')userForm(id);if(action==='close')$('#platform-dialog').close();}catch(err){notice(err.message);}});
document.addEventListener('input',e=>{if(e.target.id==='app-search'){query=e.target.value;$('#app-results').innerHTML=appGrid(filteredApps());}});
document.addEventListener('change',async e=>{if(e.target.matches('[data-theme]')){setTheme(e.target.value);document.querySelectorAll('[data-theme]').forEach(el=>el.value=theme);}if(e.target.dataset.accessUser){const u=state.team.find(x=>x.id===e.target.dataset.accessUser),appId=e.target.dataset.app,ids=e.target.checked?[...u.appIds,appId]:u.appIds.filter(id=>id!==appId);try{await api('platform/access/'+u.id,'PATCH',{appIds:ids});await load();notice('App access updated');}catch(err){e.target.checked=!e.target.checked;notice(err.message);}}});
async function boot(){authStatus=await api('auth/status');if(authStatus.user)await load();else authView();}
boot().catch(e=>{$('#platform').innerHTML=`<main id="main" class="loading"><h1>Unable to open Synapse</h1><p>${escapeHtml(e.message)}</p><a href="/" class="secondary">Try again</a></main>`;});
