const $=selector=>document.querySelector(selector),origin='https://apps.sushantsynapse.com';
const scenes=[
 {name:'Team Mixer',category:'GOOD PEOPLE. FRESH COMBINATIONS.',title:'Bring everyone\ninto the game.',description:'Turn a class, match or workshop into balanced teams. Enter names, reveal the groups and share the team card.',tags:['Free · No sign-in','Balanced team sizes','Download & share'],path:'/team-mixer',markup:`<div class="mini-top"><span>Team Mixer</span><span>ILLUSTRATIVE GROUP</span></div><div class="demo-step">1. Add your people</div><div class="name-pills" data-until=".52">${['Asha','Rohan','Meera','Kabir','Diya','Arjun'].map((name,i)=>`<span class="reveal" data-at="${i*.05}">${name}</span>`).join('')}</div><div class="demo-action reveal" data-at=".3" data-until=".52">Mix into 2 teams →</div><div class="team-columns reveal" data-at=".52"><div class="demo-team"><h4>TEAM ONE</h4><span>Asha</span><span>Kabir</span><span>Diya</span></div><div class="demo-team"><h4>TEAM TWO</h4><span>Rohan</span><span>Meera</span><span>Arjun</span></div></div><p class="demo-caption reveal" data-at=".68">Six people. Two teams. Everyone included.</p>`},
 {name:'Moment Studio',category:'WORDS FOR EVERY KIND OF MOMENT.',title:'Make a small\nmoment meaningful.',description:'Create appreciation certificates, celebrations and thoughtful cards in English or Hindi. Export a branded PNG or PDF.',tags:['Free · No sign-in','Cards & certificates','English & Hindi'],path:'/moment-studio',markup:`<div class="mini-top"><span>Moment Studio</span><span>SAMPLE CERTIFICATE</span></div><div class="certificate"><div class="award-mark reveal" data-at=".05">✦</div><small class="reveal" data-at=".13">Certificate of appreciation</small><h3 class="reveal" data-at=".25">Meera Sharma</h3><p class="reveal" data-at=".4">For bringing care, creativity and a little extra kindness to the team.</p><span class="signature reveal" data-at=".55">Community workshop · Sushant Synapse</span></div><div class="export-line reveal" data-at=".7"><span>PNG image</span><span>PDF document</span></div>`},
 {name:'Timetable Lite',category:'LESS ADMIN. MORE LEARNING.',title:'Give your week\na little order.',description:'Plan a school or coaching timetable around your teachers and classes, then download or print the finished week.',tags:['Free · No sign-in','Conflict-free scheduling','Print & export'],path:'/timetable-lite',markup:`<div class="mini-top"><span>Timetable Lite</span><span>SAMPLE WEEK · CLASS 6</span></div><div class="demo-step">Arrange the week</div><div class="mini-timetable"><span class="table-heading"></span><span class="table-heading">MON</span><span class="table-heading">TUE</span><span class="table-heading">WED</span>${['09:00','10:00','11:00','12:00'].map((time,row)=>`<span class="time-heading">${time}</span>${[['Maths','English','Science'],['English','Science','Maths'],['Science','Maths','English'],['Art','Sports','Art']][row].map((subject,col)=>`<span class="filled reveal" data-at="${.1+(row*3+col)*.04}">${subject}</span>`).join('')}`).join('')}</div><p class="demo-caption reveal" data-at=".7">A sample schedule, ready to review and print.</p>`},
 {name:'Ritual Assist',category:'PREPARE WITH CLARITY. OBSERVE WITH CARE.',title:'Tradition,\nthoughtfully prepared.',description:'Explore Hindu Shubh ceremonies and Ashubh mourning or remembrance preparation. Read suggested steps and arrange an item checklist.',tags:['12 Hindu guides','English & Hindi','Print your checklist'],path:'/ritual-assist',markup:`<div class="mini-top"><span>Ritual Assist</span><span>SAMPLE PREPARATION</span></div><div class="mini-checklist"><h3>Ganesh puja</h3><p>Arrange the essentials with your family.</p>${['Clean puja space','Water, vessel and spoon','Flowers and a lamp','Confirm your family’s custom'].map((item,i)=>`<div class="mini-item" data-check-at="${.16+i*.16}"><span class="check-mark">✓</span><span>${item}</span></div>`).join('')}</div><p class="ritual-footnote">Suggested preparation; confirm details with your family or priest.</p>`},
 {name:'Take a Break',category:'A LITTLE SPACE IN A BUSY DAY.',title:'Your next break\ncan be a little lighter.',description:'A puzzle, a playful challenge or a Pocket Pause. Seven activities in one free hub, ready when you need a change of pace.',tags:['Free · No sign-in','Seven activities','Play at your pace'],path:'/take-a-break',markup:`<div class="mini-top"><span>Pocket Pause</span><span>PART OF TAKE A BREAK</span></div><div class="bubble-field">${Array.from({length:15},(_,i)=>`<span class="demo-bubble" data-pop-at="${.1+(i%5)*.12+Math.floor(i/5)*.025}" aria-hidden="true"></span>`).join('')}</div><p class="pause-message reveal" data-at=".7">A little room to breathe.</p><p class="demo-caption">Sample bubble animation · no sound or score.</p>`},
 {name:'Explore the platform',category:'YOUR EVERYDAY TOOLS. ONE THOUGHTFUL HOME.',title:'Find your little\neveryday advantage.',description:'Start with a free public tool. Sign in for your assigned private workspace. Or help the platform grow with a voluntary contribution or sponsorship.',tags:['Public tools are free','Private apps require access','Support is optional'],path:'/',markup:`<div class="mini-top"><span>Sushant Synapse</span><span>EXPLORE THE PLATFORM</span></div><div class="closing-orbit reveal" data-at=".05"><img src="/logo-adaptive-192.png" alt="" width="86" height="86"></div><h3 class="closing-title reveal" data-at=".2">A little clarity.<br>Every day.</h3><p class="closing-url reveal" data-at=".4">apps.sushantsynapse.com</p><div class="export-line reveal" data-at=".6"><span>Explore free apps</span><span>Meet your next useful tool</span></div>`}
];
const standalone=!!document.querySelector('meta[name=showcase-export]'),motion=matchMedia('(prefers-reduced-motion:reduce)'),system=matchMedia('(prefers-color-scheme:dark)');let index=0,elapsed=0,duration=12,playing=!motion.matches,last=0,focused=false,previewFinal=motion.matches;
function theme(){const choice=window.SynapseTheme?.read()||'system';document.documentElement.dataset.theme=choice==='system'?(system.matches?'dark':'light'):choice;if(window.SynapseTheme)$('#theme').innerHTML=window.SynapseTheme.control().match(/<button[^>]*>([\s\S]*)<\/button>/)[1];}
theme();$('#theme').addEventListener('change',theme);system.addEventListener('change',theme);
function screen(value){document.body.classList.toggle('screen-mode',value);$('#exit-screen').hidden=!value;if(!standalone){const url=new URL(location.href);if(value)url.searchParams.set('screen','1');else url.searchParams.delete('screen');history.replaceState(null,'',url);}if(value)$('#player-status').textContent='Display mode · Space to pause · ← / → to change demo · F for full screen.';else $('#player-status').textContent='';}
screen(new URL(location.href).searchParams.get('screen')==='1');$('#exit-screen').onclick=()=>screen(false);
function controls(){$('#play').textContent=playing?'Pause demo':'Play demo';$('#fullscreen-play').textContent=playing?'Pause demo':'Play demo';$('#fullscreen-play').setAttribute('aria-pressed',String(!playing));$('#play').setAttribute('aria-pressed',String(!playing));$('#player').classList.toggle('paused',!playing||focused);}
function update(){const progress=Math.min(1,elapsed/duration),sample=previewFinal?1:progress;$('#progress-fill').style.width=(progress*100)+'%';for(const node of $('#scene-stage').querySelectorAll('[data-at]'))node.classList.toggle('is-visible',sample>=Number(node.dataset.at));for(const node of $('#scene-stage').querySelectorAll('[data-until]'))node.hidden=sample>=Number(node.dataset.until);for(const node of $('#scene-stage').querySelectorAll('[data-check-at]'))node.classList.toggle('complete',sample>=Number(node.dataset.checkAt));for(const node of $('#scene-stage').querySelectorAll('[data-pop-at]'))node.classList.toggle('popped',sample>=Number(node.dataset.popAt));}
function render(){const scene=scenes[index];$('#scene-category').textContent=scene.category;$('#scene-title').textContent=scene.title;$('#scene-description').textContent=scene.description;$('#scene-name').textContent=scene.name;$('#scene-number').textContent=String(index+1).padStart(2,'0')+' / '+String(scenes.length).padStart(2,'0');$('#scene-link').href=origin+scene.path;$('#scene-link').textContent=index===scenes.length-1?'Explore the platform ↗':'Try '+scene.name+' ↗';$('#scene-tags').replaceChildren(...scene.tags.map(text=>{const span=document.createElement('span');span.textContent=text;return span;}));$('#scene-stage').innerHTML=scene.markup;for(const button of $('#scene-nav').children)button.setAttribute('aria-pressed',String(Number(button.dataset.index)===index));update();controls();}
function choose(value,announce=true){index=(value+scenes.length)%scenes.length;elapsed=0;last=0;previewFinal=!playing;render();if(announce)$('#player-status').textContent='Demo '+(index+1)+' of '+scenes.length+' · '+scenes[index].name;}
function toggle(){playing=!playing;if(playing)previewFinal=false;last=0;controls();$('#player-status').textContent=playing?'Playing · demos repeat automatically.':'Paused · use the arrows or choose a demo.';update();}
for(const [i,scene]of scenes.entries()){const button=document.createElement('button');button.type='button';button.textContent=scene.name;button.dataset.index=i;button.setAttribute('aria-pressed',String(i===0));button.onclick=()=>choose(i);$('#scene-nav').append(button);}
$('#fullscreen-play').onclick=toggle;$('#fullscreen-next').onclick=()=>choose(index+1);$('#fullscreen-exit').onclick=()=>void fullscreen();$('#play').onclick=toggle;$('#previous').onclick=()=>choose(index-1);$('#next').onclick=()=>choose(index+1);$('#restart').onclick=()=>choose(0);$('#duration').onchange=()=>{const fraction=elapsed/duration;duration=Number($('#duration').value);elapsed=fraction*duration;last=0;update();};
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#player').requestFullscreen)await $('#player').requestFullscreen();else{screen(true);$('#player-status').textContent='Display mode opened. Use your browser’s full-screen command if needed.';}}catch{$('#player-status').textContent='Full screen was unavailable. Open display mode for a larger player.';}}
$('#fullscreen').onclick=fullscreen;document.addEventListener('fullscreenchange',()=>{$('#fullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen';});
$('#player').addEventListener('focusin',event=>{focused=!!event.target.closest('a');last=0;controls();});$('#player').addEventListener('focusout',event=>{if(!$('#player').contains(event.relatedTarget)){focused=false;last=0;controls();}});document.addEventListener('visibilitychange',()=>last=0);motion.addEventListener('change',()=>{if(motion.matches){playing=false;previewFinal=true;controls();update();$('#player-status').textContent='Motion reduced · demos start paused.';}});
document.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey||(event.target.closest('input,select,textarea,button,a,[contenteditable]')&&!document.fullscreenElement))return;if(event.key===' '){event.preventDefault();toggle();}else if(event.key==='ArrowRight'){event.preventDefault();choose(index+1);}else if(event.key==='ArrowLeft'){event.preventDefault();choose(index-1);}else if(event.key.toLowerCase()==='f'){event.preventDefault();void fullscreen();}else if(event.key==='Escape'&&!document.fullscreenElement)screen(false);});
function frame(now){if(playing&&!focused&&!document.hidden){if(last){elapsed+=Math.min((now-last)/1000,.25);if(elapsed>=duration){choose(index+1,false);}}last=now;update();}else last=0;requestAnimationFrame(frame);}render();requestAnimationFrame(frame);
function blobData(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Unable to embed the logo'));reader.readAsDataURL(blob);});}
async function loadAsset(url,kind='text'){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw Error('Unable to download a player asset');return kind==='image'?blobData(await response.blob()):response.text();}
$('#download-player').hidden=standalone;
$('#download-player').onclick=async()=>{
 const button=$('#download-player');button.disabled=true;$('#player-status').textContent='Preparing a self-contained HTML player…';
 try{
  const urls=['/showcase','/platform.css','/shared/platform-header.css','/showcase.css','/shared/theme.js','/showcase.js','/logo-adaptive-192.png'];
  const [html,platform,header,css,themeScript,script,logo]=await Promise.all(urls.map((url,i)=>loadAsset(url,i===6?'image':'text')));
  const doc=new DOMParser().parseFromString(html,'text/html'),meta=doc.createElement('meta');meta.name='showcase-export';meta.content='standalone';doc.head.prepend(meta);
  const styles={'/platform.css':platform,'/shared/platform-header.css':header,'/showcase.css':css};
  for(const link of doc.querySelectorAll('link[rel=stylesheet]')){const contents=styles[link.getAttribute('href')];if(contents){const style=doc.createElement('style');style.textContent=contents;link.replaceWith(style);}else link.remove();}
  for(const external of doc.querySelectorAll('script[src]')){
   const src=external.getAttribute('src'),contents=src==='/shared/theme.js'?themeScript:src==='/showcase.js'?script.replaceAll('/logo-adaptive-192.png',logo):null;
   if(contents!==null){const embedded=doc.createElement('script');if(external.type)embedded.type=external.type;embedded.textContent=contents.replace(/<\/script/gi,'<\\/script');external.replaceWith(embedded);}else external.remove();
  }
  for(const image of doc.querySelectorAll('img'))if(image.getAttribute('src')==='/logo-adaptive-192.png')image.src=logo;
  doc.querySelector('link[rel=icon]').href=logo;
  for(const link of doc.querySelectorAll('a[href]')){const href=link.getAttribute('href');if(href==='/showcase?screen=1')link.setAttribute('href','?screen=1');else if(href.startsWith('/')&&!href.startsWith('//'))link.href=origin+href;}
  const result='<!doctype html>\n'+doc.documentElement.outerHTML,url=URL.createObjectURL(new Blob([result],{type:'text/html;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='sushant-synapse-demo-player.html';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);
  $('#player-status').textContent='HTML player downloaded. Open it in a browser; demos run offline. Tool and sponsorship links need internet.';
 }catch(error){$('#player-status').textContent=error.message+'. Try again when connected.';}finally{button.disabled=false;}
};
