import {emptySupport,treats,validateSupport,paymentTarget} from './support-engine.mjs';
import QRCode from './support-qr.mjs';
const $=selector=>document.querySelector(selector);let config={...emptySupport},selected=treats[1],version=0;
function theme(){const value=window.SynapseTheme.read();document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):value;$('#theme').innerHTML=window.SynapseTheme.control().match(/<button[^>]*>([\s\S]*)<\/button>/)[1];}
theme();$('#theme').addEventListener('change',theme);matchMedia('(prefers-color-scheme:dark)').addEventListener('change',theme);
async function request(path,options={}){const response=await fetch('/api/'+path,{...options,cache:'no-store',signal:AbortSignal.timeout(10000)});const body=await response.json();if(!response.ok)throw Error(body.error||'Unable to load support settings');return body;}
async function render(){
 const current=++version,target=paymentTarget(config,selected);$('#treats').hidden=!target||!config.upiId;$('#payment').hidden=!target;$('#availability').hidden=!!target;$('#manual-copy').hidden=true;$('#status').textContent='';$('#qr').hidden=true;
 if(!target){$('#availability').textContent='Direct support is not configured yet. You can explore sponsorship or enjoy the free tools.';return;}
 for(const button of $('#treats').children)button.setAttribute('aria-pressed',String(button.dataset.amount===String(selected.amount)));
 $('#amount').textContent=config.upiId?'₹'+selected.amount:'Choose an amount at checkout';$('#recipient').textContent='Recipient · '+config.title;$('#details').textContent=config.upiId||new URL(config.paymentUrl).hostname;$('#pay').href=target;$('#pay').textContent=config.upiId?'Open payment app ↗':'Open secure checkout ↗';$('#pay').rel='noopener noreferrer';$('#payment-note').textContent=config.upiId?'Scan this QR with a UPI app, or open your payment app on this device.':'The hosted checkout controls the amount and payment options.';$('#qr-status').textContent='Preparing QR…';
 try{const data=await QRCode.toDataURL(target,{width:360,margin:4,errorCorrectionLevel:'M'});if(current!==version)return;$('#qr').src=data;$('#qr').alt=config.upiId?'UPI payment QR for ₹'+selected.amount:'QR for the configured payment checkout';$('#qr').hidden=false;$('#qr-status').textContent='';}catch{if(current===version)$('#qr-status').textContent='QR unavailable. Use the payment link or copy the details.';}
}
for(const treat of treats){const button=document.createElement('button');button.type='button';button.className='treat';button.dataset.amount=treat.amount;button.setAttribute('aria-pressed',String(treat===selected));button.setAttribute('aria-label',treat.name+' · ₹'+treat.amount);for(const [tag,content,cls]of [['span',treat.icon,'treat-icon'],['b',treat.name],['strong','₹'+treat.amount],['small',treat.line]]){const node=document.createElement(tag);node.textContent=content;if(cls)node.className=cls;button.append(node);}button.onclick=()=>{selected=treat;void render();};$('#treats').append(button);}
$('#copy').onclick=async()=>{const value=config.upiId||config.paymentUrl;if(!config.isActive||!value)return;try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(value);$('#status').textContent='Payment details copied.';}catch{$('#manual-copy').hidden=false;$('#copy-value').value=value;$('#copy-value').focus();$('#copy-value').select();$('#status').textContent='Select and copy the payment details below.';}};
$('#support-settings').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;$('#owner-status').textContent='Saving…';try{const data=new FormData(form),input=validateSupport({title:data.get('title'),upiId:data.get('upiId'),paymentUrl:data.get('paymentUrl'),isActive:form.elements.isActive.checked});config=validateSupport(await request('platform/support',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}));await render();$('#owner-status').textContent='Support settings saved.';}catch(error){$('#owner-status').textContent=error.message;}finally{button.disabled=false;}};
$('#availability').textContent='Checking support availability…';
try{config=validateSupport(await request('support'));await render();}catch{$('#availability').textContent='Support details are temporarily unavailable. Please try again later. You can still explore sponsorship.';}
try{const auth=await request('auth/status');if(auth.user?.role==='Owner'){const settings=validateSupport(await request('platform/support'));for(const key of ['title','upiId','paymentUrl'])$('#support-settings').elements[key].value=settings[key];$('#support-settings').elements.isActive.checked=settings.isActive;$('#owner-panel').hidden=false;}}catch{/* Public support remains usable without a session. */}
