const {test,expect}=require('@playwright/test'),{spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');let child,base,dir;
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-language-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let text='';const timeout=setTimeout(()=>reject(Error('Startup timeout')),15000);child.stdout.on('data',chunk=>{text+=chunk;const match=text.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timeout);resolve();}});child.once('error',reject);});});
test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});
const toggle=(page,lang)=>page.locator('.synapse-legal-footer [data-interface-language='+lang+']');
test('footer switches homepage/navigation and remembers choice across pages, reload and themes',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/');await expect(toggle(page,'en')).toHaveAttribute('aria-pressed','true');await toggle(page,'hi').click();await expect(page.locator('.public-hero h1')).toContainText('थोड़ी स्पष्टता');await expect(page.locator('.synapse-legal-footer')).toContainText('गोपनीयता');await expect(page.locator('html')).toHaveAttribute('lang','hi');await page.reload();await expect(toggle(page,'hi')).toHaveAttribute('aria-pressed','true');await page.goto(base+'/contact');await expect(toggle(page,'hi')).toHaveAttribute('aria-pressed','true');await expect(page.locator('.synapse-help-nav')).toContainText('सहयोग करें');await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('[data-language-help]')).toBeVisible();
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}}
 await page.setViewportSize({width:390,height:900});await page.locator('.synapse-legal-footer').screenshot({path:'test-results/footer-language-hi-dark.png'});await toggle(page,'en').click();await expect(page.locator('.synapse-legal-footer')).toContainText('Privacy');await expect(page.locator('[data-language-help]')).toBeHidden();await page.goto(base+'/');await expect(page.locator('.public-hero h1')).toContainText('A little clarity.');expect(errors).toEqual([]);
});
test('Ritual footer/native selector preserve inputs, results and pack checks',async({page})=>{
 await page.goto(base+'/ritual-assist?guide=shraddha');await page.locator('[data-item=water]').check();await toggle(page,'hi').click();await expect(page.locator('#language')).toHaveValue('hi');await expect(page.locator('#guide-title')).toContainText('श्राद्ध');await expect(page.locator('[data-item=water]')).toBeChecked();await page.locator('#language').selectOption('en');await expect(toggle(page,'en')).toHaveAttribute('aria-pressed','true');await toggle(page,'hi').click();await page.goto(base+'/ritual-assist/calendar');await expect(page.locator('#language')).toHaveValue('hi');await page.locator('#date').fill('2025-10-01');await page.locator('#time').fill('12:00');await page.locator('#pincode').fill('110001');await page.locator('#calculate').click();await expect(page.locator('.future-plan tbody tr')).toHaveCount(11);await page.locator('#open-preparation-pack').click();await page.locator('[data-pack-item="shraddha:water"]').check();await page.locator('[data-pack-task="0"]').fill('Aakanksha');await toggle(page,'en').click();await expect(page.locator('#headline')).toHaveText('Shraddha & Barsi Calendar');await expect(page.locator('#date')).toHaveValue('2025-10-01');await expect(page.locator('#pincode')).toHaveValue('110001');await expect(page.locator('.future-plan tbody tr')).toHaveCount(11);await expect(page.locator('[data-pack-item="shraddha:water"]')).toBeChecked();await expect(page.locator('[data-pack-task="0"]')).toHaveValue('Aakanksha');await page.locator('#language').selectOption('hi');await expect(toggle(page,'hi')).toHaveAttribute('aria-pressed','true');await page.emulateMedia({media:'print'});await expect(page.locator('.synapse-legal-footer')).toBeHidden();
});
test('footer preference preserves Moment Studio wording selection and custom artwork input',async({page})=>{
 await page.goto(base+'/moment-studio');await page.locator('[name=title]').fill('Contact');await expect(page.locator('#language')).toHaveValue('en');await toggle(page,'hi').click();await expect(page.locator('#language')).toHaveValue('en');await expect(page.locator('[name=title]')).toHaveValue('Contact');await expect(page.locator('[data-language-help]')).toBeVisible();await toggle(page,'en').click();await expect(page.locator('[name=title]')).toHaveValue('Contact');
});
test('DIGITAL SAMAJ bridge respects disabled native controls',async({page})=>{
 await page.goto(base+'/digital-samaj');await toggle(page,'hi').click();await expect(page.locator('#language')).toHaveValue('hi');await expect(page.locator('html')).toHaveAttribute('lang','hi');await page.evaluate(()=>document.getElementById('language').disabled=true);await expect(toggle(page,'en')).toBeDisabled();await page.evaluate(()=>document.getElementById('language').disabled=false);await expect(toggle(page,'en')).toBeEnabled();await toggle(page,'en').click();await expect(page.locator('#language')).toHaveValue('en');await expect(page.locator('html')).toHaveAttribute('lang','en');
});
test('storage-blocked switching and no-JavaScript footer links remain usable',async({page,browser})=>{
 await page.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('Storage blocked');};Storage.prototype.setItem=()=>{throw Error('Storage blocked');};});await page.goto(base+'/');await toggle(page,'hi').click();await expect(page.locator('.public-hero h1')).toContainText('थोड़ी स्पष्टता');await toggle(page,'en').click();await expect(page.locator('.public-hero h1')).toContainText('A little clarity.');const context=await browser.newContext({javaScriptEnabled:false});try{const nojs=await context.newPage();await nojs.goto(base+'/ritual-assist');await expect(nojs.locator('[data-language-control]')).toBeHidden();await expect(nojs.locator('.synapse-legal-footer a[href="/privacy"]')).toBeVisible();}finally{await context.close();}
});
