// App definitions are code-reviewed. Do not accept launch URLs from user input.
const apps = [
  {id:'ritual-assist',public:true,name:'Ritual Assist',subtitle:'Prepare with clarity. Observe with care.',category:'Community',status:'Available',path:'/ritual-assist',icon:'knowledge',accent:'amber',description:'Hindu Shubh ceremonies and Ashubh mourning/remembrance preparation in English and Hindi. Suggested steps, item checklists, family-custom notes and references.',features:['15 Hindu guides','Steps & materials','Print & share']},
  {id:'pocket-pause',public:true,catalogueParent:'daily-spark',name:'Pocket Pause',subtitle:'A little space in a busy day.',category:'Play',status:'Available',path:'/pocket-pause',icon:'star',accent:'green',description:'Eight playful breaks: cartoon computer and TV smashing, crockery crash, inbox shredder, bubbles, sand and a gentle circle.',features:['Smash & rebuild','Inbox confetti','Eight modes']},
  { id: 'team-mixer', public: true, name: 'Team Mixer', subtitle: 'Good people. Fresh combinations.', category: 'Community', status: 'Available', path: '/team-mixer', icon: 'team', accent: 'green', description: 'Split 2-100 names into randomly assigned teams with balanced sizes, animated reveals, a downloadable team card and explicit sharing. Free, no login.', features: ['Balanced team sizes', 'Animated reveal', 'PNG & team list'] },
  {id:'moment-studio',public:true,name:'Moment Studio',subtitle:'Words for every kind of moment.',category:'Community',status:'Available',path:'/moment-studio',icon:'star',accent:'blue',description:'Create appreciation certificates, celebrations, invitations and thoughtful condolence cards in English or Hindi. Free branded PNG/PDF exports.',features:['Cards & certificates','Condolences & remembrance','Branded PNG/PDF']},
  { id: 'decision-wheel', public: true, name: 'Decision Wheel', subtitle: 'Less debate. More doing.', category: 'Productivity', status: 'Available', path: '/decision-wheel', icon: 'grid', accent: 'blue', description: 'Spin to choose lunch, tasks or a name. Equal chances, removable winners and shareable results. Free, no login.', features: ['Random picker', 'Remove winners', 'Share results'] },
  { id: 'daily-spark', public: true, name: 'Take a Break', subtitle: 'Seven ways to reset.', category: 'Play', status: 'Available', path: '/take-a-break', icon: 'grid', accent: 'blue', description: 'Make 24, Oddly Different, Memory Minute, Clue Club, Face-Off, Decision Wheel and Pocket Pause in one free play hub.', features: ['Daily & practice games', 'Choose or unwind', 'Challenge a friend'] },
  { id: 'digital-samaj', name: 'DIGITAL SAMAJ', subtitle: 'Families, roots and community', category: 'Community', status: 'Available', path: '/digital-samaj', icon: 'team', accent: 'green', description: 'Private family registry, verified directory, Vanshavali and member messaging. Requires platform access and a Samaj role.', features: ['Family registry', 'Vanshavali', 'Samaj Connect'] },
  { id: 'tournament-lite', name: 'Tournament Lite', subtitle: 'Less admin. More play.', category: 'Community', status: 'Available', path: '/tournament-lite', icon: 'projects', accent: 'green', description: 'Six sports, automatic fixtures, scoring and public results. Organizers sign in; viewers need no account.', features: ['Six sports', 'Fixtures & brackets', 'Share results'] },
  { id: 'batchfee-lite', name: 'BatchFee Lite', subtitle: 'Less chasing. More teaching.', category: 'Education', status: 'Available', path: '/batchfee-lite', icon: 'finance', accent: 'green', description: 'Batches, students, recurring fees, receipts and WhatsApp reminders. Private academy workspace with owner-delegated staff roles.', features: ['Fee tracking', 'Receipts', 'WhatsApp drafts'] },
  { id: 'timetable-lite', public: true, name: 'Timetable Lite', subtitle: 'A well-planned week starts here', category: 'Education', status: 'Available', path: '/timetable-lite', icon: 'projects', accent: 'blue', description: 'Generate conflict-free weekly timetables for schools, coaching classes and training institutes. No login required.', features: ['Automatic scheduling', 'PDF & image', 'Device-local backups'] },
  { id: 'news', public: true, name: 'Sushant Synapse Times', subtitle: 'Daily newspaper by Aakanksha', category: 'News', status: 'Available', path: '/news', icon: 'knowledge', accent: 'green', description: 'Dated news from credited publishers, fictional satire, shared archives and temporary editions.', features: ['Daily newspaper', 'Satire', 'Date archives'] },
  { id: 'fund-overlap', public: true, name: 'Fund Lens', subtitle: 'Mutual fund overlap analyzer', category: 'Investing', status: 'Available', path: '/fund-overlap', icon: 'lens', accent: 'blue', description: 'See what your funds have in common. Compare equity holdings, industries and unique contributions using dated official examples and verified secondary sources.', features: ['Holdings overlap', 'Industry comparison', 'What-if analysis'] },
  { id: 'advocate', name: 'Chambers', subtitle: 'Advocate workspace', category: 'Legal', status: 'Available', path: '/advocate', icon: 'scales', accent: 'green', description: 'Cases, clients, hearings and professional fees. Your entire legal practice, in good order.', features: ['Case management', 'Hearing diary', 'Fees & payments'] },
  { id: 'projects', name: 'Projects', subtitle: 'Plan the work ahead', category: 'Productivity', status: 'Planned', icon: 'projects', accent: 'violet', description: 'A future workspace for projects, milestones and team tasks.', features: ['Projects', 'Milestones'] },
  { id: 'finance', name: 'Finance', subtitle: 'Clarity for your business', category: 'Business', status: 'Planned', icon: 'finance', accent: 'amber', description: 'A future app for business income, expenses and financial reporting.', features: ['Income & expenses', 'Reports'] },
  { id: 'knowledge', name: 'Knowledge', subtitle: 'Keep good ideas together', category: 'Productivity', status: 'Planned', icon: 'knowledge', accent: 'blue', description: 'A future home for notes, references and shared knowledge.', features: ['Notes', 'Collections'] },
];
const appAliases={certificates:'moment-studio','celebration-studio':'moment-studio'};
const resolveAppId=id=>Object.hasOwn(appAliases,id)?appAliases[id]:id;
module.exports = { apps, resolveAppId };
