// App definitions are code-reviewed. Do not accept launch URLs from user input.
const apps = [
  { id: 'decision-wheel', public: true, name: 'Decision Wheel', subtitle: 'Less debate. More doing.', category: 'Productivity', status: 'Available', path: '/decision-wheel', icon: 'grid', accent: 'blue', description: 'Spin to choose lunch, tasks or a name. Equal chances, removable winners and shareable results. Free, no login.', features: ['Random picker', 'Remove winners', 'Share results'] },
  { id: 'daily-spark', public: true, name: 'Daily Spark', subtitle: 'Your daily brain break', category: 'Play', status: 'Available', path: '/daily-spark', icon: 'grid', accent: 'blue', description: 'Four numbers, one goal: make 24. A free daily puzzle with hints, practice and shareable results. No sign-in required.', features: ['Daily challenge', 'Practice puzzles', 'Share results'] },
  { id: 'digital-samaj', name: 'DIGITAL SAMAJ', subtitle: 'Families, roots and community', category: 'Community', status: 'Available', path: '/digital-samaj', icon: 'team', accent: 'green', description: 'Private family registry, verified directory, Vanshavali and member messaging. Requires platform access and a Samaj role.', features: ['Family registry', 'Vanshavali', 'Samaj Connect'] },
  { id: 'tournament-lite', name: 'Tournament Lite', subtitle: 'Less admin. More play.', category: 'Community', status: 'Available', path: '/tournament-lite', icon: 'projects', accent: 'green', description: 'Six sports, automatic fixtures, scoring and public results. Organizers sign in; viewers need no account.', features: ['Six sports', 'Fixtures & brackets', 'Share results'] },
  { id: 'batchfee-lite', ownerOnly: true, name: 'BatchFee Lite', subtitle: 'Less chasing. More teaching.', category: 'Education', status: 'Available', path: '/batchfee-lite', icon: 'finance', accent: 'green', description: 'Batches, students, recurring fees, receipts and WhatsApp reminders. Private academy workspace for the platform owner.', features: ['Fee tracking', 'Receipts', 'WhatsApp drafts'] },
  { id: 'timetable-lite', public: true, name: 'Timetable Lite', subtitle: 'A well-planned week starts here', category: 'Education', status: 'Available', path: '/timetable-lite', icon: 'projects', accent: 'blue', description: 'Generate conflict-free weekly timetables for schools, coaching classes and training institutes. No login required.', features: ['Automatic scheduling', 'PDF & image', 'Device-local backups'] },
  { id: 'certificates', public: true, name: 'Appreciation Certificate Generator', subtitle: 'Make appreciation beautiful', category: 'Community', status: 'Available', path: '/certificates', icon: 'knowledge', accent: 'blue', description: 'Create professional appreciation certificates privately in your browser. No account required.', features: ['Six templates', 'PDF & PNG', 'Local processing'] },
  { id: 'news', public: true, name: 'Sushant Synapse Times', subtitle: 'Daily newspaper by Bhavik', category: 'News', status: 'Available', path: '/news', icon: 'knowledge', accent: 'green', description: 'Ten recent India public-affairs releases and fictional satire, saved as a daily newspaper.', features: ['Daily newspaper', 'Satire', 'Date archives'] },
  { id: 'fund-overlap', public: true, name: 'Fund Lens', subtitle: 'Mutual fund overlap analyzer', category: 'Investing', status: 'Available', path: '/fund-overlap', icon: 'lens', accent: 'blue', description: 'See what your funds have in common. Compare equity holdings, industries and unique contributions using official portfolio disclosures.', features: ['Holdings overlap', 'Industry comparison', 'What-if analysis'] },
  { id: 'advocate', name: 'Chambers', subtitle: 'Advocate workspace', category: 'Legal', status: 'Available', path: '/advocate', icon: 'scales', accent: 'green', description: 'Cases, clients, hearings and professional fees. Your entire legal practice, in good order.', features: ['Case management', 'Hearing diary', 'Fees & payments'] },
  { id: 'projects', name: 'Projects', subtitle: 'Plan the work ahead', category: 'Productivity', status: 'Planned', icon: 'projects', accent: 'violet', description: 'A future workspace for projects, milestones and team tasks.', features: ['Projects', 'Milestones'] },
  { id: 'finance', name: 'Finance', subtitle: 'Clarity for your business', category: 'Business', status: 'Planned', icon: 'finance', accent: 'amber', description: 'A future app for business income, expenses and financial reporting.', features: ['Income & expenses', 'Reports'] },
  { id: 'knowledge', name: 'Knowledge', subtitle: 'Keep good ideas together', category: 'Productivity', status: 'Planned', icon: 'knowledge', accent: 'blue', description: 'A future home for notes, references and shared knowledge.', features: ['Notes', 'Collections'] },
];
module.exports = { apps };
