const {test,expect}=require('@playwright/test'),{spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{setTheme}=require('../../../tests/browser-theme');let child,base,dir;
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-break-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});base=await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timeout')),15000);child.stdout.on('data',c=>{out+=c;const match=out.match(/localhost:(\d+)/);if(match){clearTimeout(timer);resolve('http://127.0.0.1:'+match[1]);}});child.once('error',reject);});});test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});fs.rmSync(dir,{recursive:true,force:true});});
async function oddFinish(page,seed){const {oddRound}=await import('../frontend/engine.mjs');for(let round=0;round<5;round++)await page.locator('.odd-board button').nth(oddRound(seed,round).oddIndex).click();}
test('older backend groups the play hub while preserving favourite and launch identifiers',async({page})=>{
 const user={id:'owner',name:'Play Owner',email:'owner@example.com',role:'Owner'},apps=require('../../../packages/app-registry').apps.filter(a=>['daily-spark','decision-wheel','pocket-pause'].includes(a.id)).map(a=>({...a,accessible:true}));const hub=apps.find(a=>a.id==='daily-spark');hub.name='Daily Spark';hub.path='/daily-spark';apps.forEach(a=>delete a.catalogueParent);let launch='';
 await page.route('**/api/auth/status',r=>r.fulfill({json:{user,setupRequired:false}}));await page.route('**/api/platform',r=>r.fulfill({json:{user,apps,preferences:{favorites:['daily-spark','decision-wheel','pocket-pause'],recent:[]},team:[]}}));await page.route('**/api/platform/apps/*/launch',r=>{launch=r.request().url();return r.fulfill({json:{path:'/daily-spark'}});});await page.goto(base+'/signin');await expect(page.locator('.app-card')).toHaveCount(1);await expect(page.getByRole('heading',{name:'Take a Break',exact:true})).toBeVisible();await expect(page.locator('.favorite')).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Favourites',exact:true}).click();await expect(page.locator('.app-card')).toHaveCount(3);await page.getByRole('button',{name:'Open Take a Break',exact:false}).click();await expect(page).toHaveURL(base+'/take-a-break');expect(launch).toContain('/daily-spark/launch');await expect(page.locator('.break-card')).toHaveCount(7);
});
test('one mobile entry opens all seven breaks and preserves in-tab progress and Make 24',async({page})=>{
 const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))api.push(r.url());});await page.setViewportSize({width:320,height:700});await page.goto(base+'/take-a-break');await expect(page.locator('.break-card')).toHaveCount(7);await page.locator('[data-filter=choose]').click();await expect(page.locator('.break-card:visible')).toHaveCount(2);await page.locator('[data-filter=challenge]').click();
 await page.locator('[data-game="24"]').click();await expect(page.locator('[data-pane="24"] #numbers button')).toHaveCount(4);const numbers=await page.locator('[data-pane="24"] #numbers').innerText();await page.locator('[data-pane="24"] #numbers button').first().click();await page.locator('#all-breaks').click();await page.locator('[data-game=odd]').click();await page.locator('.odd-hint').click();await expect(page.locator('.odd-tile.candidate')).toHaveCount(3);await page.locator('#all-breaks').click();await page.locator('[data-game="24"]').click();expect(await page.locator('[data-pane="24"] #numbers').innerText()).toContain(numbers.split('\n')[0]);await expect(page.locator('[data-pane="24"] #numbers button').first()).toHaveAttribute('aria-pressed','true');
 await page.locator('[data-pane="24"] .spark-details').first().locator('summary').click();await page.locator('[data-pane="24"] #reveal').click();await expect(page.locator('[data-pane="24"] #result-copy')).toContainText('24');await page.getByRole('button',{name:'Try Oddly Different'}).click();await expect(page.locator('.odd-tile.candidate')).toHaveCount(3);
 await page.locator('#all-breaks').click();await page.locator('[data-filter=choose]').click();await page.getByRole('link',{name:/Decision Wheel/}).click();await expect(page.locator('#spin')).toBeVisible();await page.getByRole('link',{name:'All breaks ↗',exact:true}).click();await page.locator('[data-filter=unwind]').click();await page.getByRole('link',{name:/Pocket Pause/}).click();await expect(page.locator('.modes')).toBeVisible();await page.getByRole('link',{name:'All breaks ↗',exact:true}).click();await expect(page.locator('.break-card')).toHaveCount(7);expect(api).toEqual([]);expect(errors).toEqual([]);
});
test('daily visual puzzle completes honestly and reopens the same shared board',async({page})=>{
 const seed='2026-10-01';await page.goto(base+'/take-a-break?game=odd&day='+seed+'&v=1');await page.locator('.odd-hint').click();const {oddRound}=await import('../frontend/engine.mjs');await page.locator('.odd-board button').nth((oddRound(seed,0).oddIndex+1)%9).click();await expect(page.locator('.mistakes')).toContainText('1 extra try');await oddFinish(page,seed);await expect(page.locator('[data-pane=odd] .result-card')).toContainText('1 hints');await page.addInitScript(()=>{Object.defineProperty(navigator,'share',{value:undefined});Object.defineProperty(navigator,'clipboard',{value:undefined});});await page.reload();const first=await page.locator('.odd-board').innerHTML();await page.getByRole('button',{name:'Challenge a friend'}).click();await expect(page.locator('#share-message')).toHaveValue(new RegExp('day='+seed));await page.reload();expect(await page.locator('.odd-board').innerHTML()).toBe(first);await page.locator('#practice-mode').click();await expect(page.locator('#hub-edition')).toContainText('PRACTICE');await page.locator('#daily-mode').click();expect(await page.locator('.odd-board').innerHTML()).toBe(first);
});
test('memory handles mismatch without timers and solves six pairs',async({page})=>{
 const seed='2026-10-02',{memoryGame}=await import('../frontend/engine.mjs'),cards=memoryGame(seed).cards;await page.goto(base+'/take-a-break?game=memory&day='+seed);const other=cards.findIndex(v=>v!==cards[0]);await page.locator('.memory-tile').nth(0).click();await page.locator('.memory-tile').nth(other).click();await expect(page.locator('.continue-pair')).toBeVisible();await expect(page.locator('.memory-tile[aria-pressed=true]')).toHaveCount(2);await page.locator('.continue-pair').click();for(let value=0;value<6;value++)for(const index of cards.flatMap((v,i)=>v===value?[i]:[]))await page.locator('.memory-tile').nth(index).click();await expect(page.locator('.memory-tile.matched')).toHaveCount(12);await expect(page.locator('[data-pane=memory] .result-card')).toContainText('7 moves');await page.getByRole('button',{name:'Try Clue Club'}).click();await expect(page.locator('.clue-list li')).toHaveCount(1);
});
test('Clue Club accepts Hindi answers, tracks clues and reveals without a false win',async({page})=>{
 const seed='2026-10-03',{clueFor}=await import('../frontend/engine.mjs'),clue=clueFor(seed);await page.goto(base+'/take-a-break?game=clue&day='+seed+'&lang=hi');await page.getByLabel('Clue language').selectOption('hi');await expect(page.locator('.clue-list li')).toHaveText(clue.hi[0]);await page.getByLabel('Your guess').fill('not this');await page.getByRole('button',{name:'Check guess'}).click();await expect(page.locator('[data-pane=clue] .status')).toContainText('Not this one');await page.getByRole('button',{name:'Show next clue'}).click();await page.getByLabel('Your guess').fill(clue.answers.at(-1));await page.getByRole('button',{name:'Check guess'}).click();await expect(page.locator('[data-pane=clue] .result-card')).toContainText('2 of 3 clues · 2 guesses');await page.locator('#practice-mode').click();await page.getByRole('button',{name:'Reveal answer'}).click();await expect(page.locator('[data-pane=clue] .result-card')).toContainText('answer revealed');
});
test('Face-Off validates, keeps safe custom choices, handles byes and undoes the final pick',async({page})=>{
 await page.goto(base+'/take-a-break?game=face');await page.getByLabel('Choices, one per line').fill('A\na');await page.getByRole('button',{name:'Start Face-Off'}).click();await expect(page.locator('.face-error')).toContainText('different name');await page.getByLabel('Choices, one per line').fill('<img src=x>\nहिन्दी\nOption C\nOption D\nOption E');await page.getByLabel('Face-Off title').fill('My safe choices');await page.getByRole('button',{name:'Start Face-Off'}).click();for(let i=0;i<4;i++)await page.locator('.face-pair button').first().click();await expect(page.locator('[data-pane=face] .result-card')).toContainText('4 comparisons');await expect(page.locator('.face-layout img')).toHaveCount(0);await page.getByRole('button',{name:'Undo last choice'}).click();await expect(page.locator('.face-pair button')).toHaveCount(2);await expect(page.locator('[data-pane=face] .result-card')).toBeHidden();
});
test('hub and every game fit small phones, desktop themes and keyboard focus',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const [width,height,theme] of [[320,568,'light'],[390,844,'dark'],[1440,900,'light']]){await page.setViewportSize({width,height});await page.goto(base+'/take-a-break');await setTheme(page,theme);await page.screenshot({path:`test-results/break-hub-${width}.png`,fullPage:true});for(const id of ['24','odd','memory','clue','face']){await page.locator(id==='face'?'[data-filter=choose]':'[data-filter=challenge]').click();await page.locator(`[data-game="${id}"]`).click();await expect(page.locator('#play-title')).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/break-${id}-${width}.png`});await page.locator('#all-breaks').click();await expect(page.locator(`[data-game="${id}"]`)).toBeFocused();}}await page.goto(base+'/take-a-break?game=odd&day=2026-02-30&v=9');await expect(page.locator('.quiet-note').first()).toContainText('unavailable');expect(errors).toEqual([]);
});
