const {test,expect}=require('@playwright/test');const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');let child,base,dir;
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-celebration-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timed out')),15000);child.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve();}});child.once('error',reject);});});test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});
test('all occasions, Hindi, designs, sizes, fitting, privacy and PNG exports',async({page})=>{
 const api=[],errors=[];page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{value:undefined});});await page.goto(base+'/celebration-studio');await expect(page.locator('#download')).toBeEnabled();
 for(const language of ['en','hi'])for(const occasion of ['birthday','invitation','anniversary','festival','thanks','fun']){await page.getByLabel('Occasion',{exact:true}).selectOption(occasion);await page.getByLabel('Suggested wording',{exact:true}).selectOption(language);await page.locator('#suggest').click();await expect(page.locator('#download')).toBeEnabled();}
 await expect(page.getByLabel('Headline',{exact:true})).toHaveValue('आज के सुपरस्टार!');await page.getByLabel('Name or recipient',{exact:false}).fill('अनन्या');for(const design of ['Confetti','Elegant','Bloom','Bold']){await page.getByRole('radio',{name:design,exact:true}).check();await expect(page.locator('#download')).toBeEnabled();}
 for(const palette of ['peach','lavender','ocean','forest','sunshine','rose']){await page.getByLabel('Colour palette').selectOption(palette);await expect(page.locator('#download')).toBeEnabled();}
 for(const [format,width,height]of [['square',1080,1080],['story',1080,1920]]){await page.getByLabel('Card size').selectOption(format);const event=page.waitForEvent('download');await page.locator('#download').click();const download=await event,file=path.join('test-results','celebration-'+format+'.png');await download.saveAs(file);const bytes=fs.readFileSync(file);expect(bytes.readUInt32BE(16)).toBe(width);expect(bytes.readUInt32BE(20)).toBe(height);}
 await page.getByLabel('Card size').selectOption('square');await page.getByLabel('Your message',{exact:true}).fill('W'.repeat(600));await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#fit-status')).toContainText('does not fit');await page.locator('#suggest').click();await expect(page.locator('#download')).toBeEnabled();
 await page.getByLabel('Headline',{exact:true}).fill('');await expect(page.locator('#download')).toBeDisabled();await page.locator('#suggest').click();const shareDownload=page.waitForEvent('download');await page.locator('#share').click();await shareDownload;await expect(page.locator('#status')).toContainText('Attach it');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.getByLabel('Suggested wording',{exact:true}).selectOption('en');await page.getByLabel('Occasion',{exact:true}).selectOption('invitation');await page.locator('#suggest').click();await page.getByLabel('Name or recipient',{exact:false}).fill('Aarav & Ananya');await page.getByLabel('Event date, time & venue',{exact:false}).fill('18 October | 6 pm | Community Hall');await page.getByRole('radio',{name:'Confetti',exact:true}).check();await page.getByLabel('Colour palette').selectOption('peach');await page.screenshot({path:'test-results/celebration-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('#theme').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:'test-results/celebration-mobile.png',fullPage:true});expect(api).toEqual([]);expect(errors).toEqual([]);await page.reload();await expect(page.getByLabel('Name or recipient',{exact:false})).toHaveValue('');
});
test('photo validation, removal and native sharing cancellation preserve the card',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{value:()=>true});Object.defineProperty(navigator,'share',{value:async data=>{window.sharedFiles=data.files.map(f=>({type:f.type,size:f.size,name:f.name}));throw new DOMException('Cancelled','AbortError');}});});await page.goto(base+'/celebration-studio');const png=await page.locator('#card').screenshot();await page.locator('#photo').setInputFiles({name:'portrait.png',mimeType:'image/png',buffer:png});await expect(page.locator('#photo-status')).toContainText('added locally');await expect(page.locator('#download')).toBeEnabled();await page.locator('#share').click();await expect(page.locator('#status')).toContainText('cancelled');expect((await page.evaluate(()=>window.sharedFiles))[0].type).toBe('image/png');await expect(page.locator('#download')).toBeEnabled();await page.locator('#remove-photo').click();await expect(page.locator('#photo-status')).toContainText('removed');await expect(page.locator('#remove-photo')).toBeDisabled();
 await page.locator('#photo').setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await expect(page.locator('#photo-status')).not.toContainText('Loading');await expect(page.locator('#download')).toBeEnabled();await page.locator('#photo').setInputFiles({name:'big.jpg',mimeType:'image/jpeg',buffer:Buffer.alloc(5*1024*1024+1)});await expect(page.locator('#photo-status')).toContainText('5 MB');
 await page.locator('#photo').setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});await expect(page.locator('#photo-status')).toContainText('PNG, JPEG or WebP');const huge=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=5000;canvas.height=5000;return canvas.toDataURL('image/png').split(',')[1];});await page.locator('#photo').setInputFiles({name:'many-pixels.png',mimeType:'image/png',buffer:Buffer.from(huge,'base64')});await expect(page.locator('#photo-status')).toContainText('24 megapixels');await page.getByLabel('Headline',{exact:true}).fill('<img src=x onerror=alert(1)>');await expect(page.locator('#download')).toBeEnabled();await expect(page.locator('main img')).toHaveCount(0);
});
