export const occasions={
 birthday:{name:'Birthday',en:{title:'Happy Birthday!',message:'Another year of stories, laughter and wonderful memories. Wishing you a day as special as you are.'},hi:{title:'जन्मदिन मुबारक!',message:'खुशियों, हँसी और खूबसूरत यादों से भरा एक नया साल। आपका दिन आपके जैसा ही खास हो।'}},
 invitation:{name:'Invitation',en:{title:"You're invited!",message:'Good company, happy moments and a reason to celebrate. Come join us!'},hi:{title:'आप सादर आमंत्रित हैं!',message:'अपनों का साथ और खुशियों के कुछ पल। आइए, मिलकर इस खास मौके को यादगार बनाएँ।'}},
 anniversary:{name:'Anniversary',en:{title:'To many more together.',message:'Celebrating your shared stories, little adventures and a love that keeps growing.'},hi:{title:'सालगिरह की शुभकामनाएँ!',message:'साथ बिताए खूबसूरत पलों और बढ़ते प्यार का जश्न। आपका साथ यूँ ही बना रहे।'}},
 festival:{name:'Festival greeting',en:{title:'A little light. A lot of joy.',message:'Wishing you and your loved ones a beautiful celebration filled with warmth, kindness and new beginnings.'},hi:{title:'त्योहार की शुभकामनाएँ!',message:'आपको और आपके परिवार को खुशियों, स्नेह और नई उम्मीदों से भरे त्योहार की हार्दिक शुभकामनाएँ।'}},
 thanks:{name:'Thank you',en:{title:'You made a difference.',message:'For your kindness, your time and all the little things you do. Thank you, from the heart.'},hi:{title:'दिल से धन्यवाद!',message:'आपके समय, सहयोग और छोटी-छोटी कोशिशों के लिए। आपने इस पल को खास बना दिया।'}},
 fun:{name:'Fun poster',en:{title:'Officially the main character.',message:'Big energy. Excellent snack choices. Questionable dance moves. A true original.'},hi:{title:'आज के सुपरस्टार!',message:'शानदार अंदाज़, बेहतरीन नाश्ते की पसंद और मजेदार डांस। आप जैसा कोई नहीं।'}}
};
export const designs={confetti:'Confetti',elegant:'Elegant',bloom:'Bloom',bold:'Bold'};
export const palettes={peach:{name:'Peach',bg:'#fff0e5',ink:'#553029',accent:'#bd513b',soft:'#f7c6b3'},lavender:{name:'Lavender',bg:'#f0eafb',ink:'#3c2e60',accent:'#7056aa',soft:'#d3c2ed'},ocean:{name:'Ocean',bg:'#e8f4f7',ink:'#193d4c',accent:'#28798f',soft:'#b4dce5'},forest:{name:'Forest',bg:'#ecf3e9',ink:'#29452e',accent:'#547d42',soft:'#c8deba'},sunshine:{name:'Sunshine',bg:'#fff7d9',ink:'#59451c',accent:'#a36b12',soft:'#f1d58a'},rose:{name:'Rose',bg:'#fcebf0',ink:'#602a42',accent:'#a74570',soft:'#eabbd0'}};
export const sizes={square:{width:1080,height:1080,name:'Square post'},story:{width:1080,height:1920,name:'Vertical status'}};
export function validate(raw){const data={};for(const [key,max]of Object.entries({title:100,name:80,message:600,details:200,from:80})){data[key]=String(raw[key]??'').trim();if([...data[key]].length>max)throw Error(`${key} is too long (maximum ${max} characters).`);}if(!data.title)throw Error('Add a headline before downloading.');for(const [key,values]of Object.entries({occasion:occasions,design:designs,palette:palettes,format:sizes})){if(!Object.hasOwn(values,raw[key]))throw Error('Choose a valid '+key+'.');data[key]=raw[key];}if(!['en','hi'].includes(raw.language))throw Error('Choose English or Hindi.');data.language=raw.language;return data;}
export function filename(data){const safe=data.title.normalize('NFKC').replace(/[^\p{L}\p{M}\p{N}]+/gu,'-').replace(/^-|-$/g,'').slice(0,64)||'celebration';return `${safe}-${data.format}.png`;}
const font='"Segoe UI", "Nirmala UI", Arial, sans-serif';
function lines(ctx,text,width){const output=[];const segmenter=new Intl.Segmenter(undefined,{granularity:'grapheme'});for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/).filter(Boolean)){const candidate=line?line+' '+word:word;if(ctx.measureText(candidate).width<=width){line=candidate;continue;}if(line){output.push(line);line='';}if(ctx.measureText(word).width<=width){line=word;continue;}for(const {segment}of segmenter.segment(word)){if(line&&ctx.measureText(line+segment).width>width){output.push(line);line='';}line+=segment;}}output.push(line);}return output;}
function textBlock(ctx,text,{x,y,width,height,max=44,min=24,bold=false,color}){if(!text)return true;let wrapped,size;for(size=max;size>=min;size--){ctx.font=`${bold?700:400} ${size}px ${font}`;wrapped=lines(ctx,text,width);if(wrapped.length*size*1.45<=height)break;}if(size<min)return false;ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';const step=size*1.45,top=y+(height-wrapped.length*step)/2;wrapped.forEach((line,i)=>ctx.fillText(line,x+width/2,top+step*(i+.5)));return true;}
export function render(canvas,raw,image=null){
 const d=validate(raw),size=sizes[d.format],p=palettes[d.palette];canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext('2d'),w=size.width,h=size.height,story=d.format==='story';ctx.fillStyle=p.bg;ctx.fillRect(0,0,w,h);
 ctx.fillStyle=p.soft;ctx.strokeStyle=p.accent;ctx.lineWidth=3;
 if(d.design==='confetti'){for(let i=0;i<46;i++){const x=(i*137+31)%w,y=(i*197+47)%h;if(x>140&&x<w-140&&y>120&&y<h-140)continue;ctx.save();ctx.translate(x,y);ctx.rotate(i*.71);ctx.fillStyle=i%2?p.accent:p.soft;ctx.fillRect(-7,-7,14,24);ctx.restore();}}
 if(d.design==='elegant'){ctx.strokeRect(36,36,w-72,h-72);ctx.strokeRect(50,50,w-100,h-100);for(const y of [110,h-100]){ctx.beginPath();ctx.moveTo(w/2-90,y);ctx.lineTo(w/2+90,y);ctx.stroke();}}
 if(d.design==='bloom'){for(const [x,y]of [[52,66],[w-52,h-66]]){for(let i=0;i<7;i++){const angle=i*Math.PI*2/7;ctx.beginPath();ctx.ellipse(x+55*Math.cos(angle),y+55*Math.sin(angle),24,54,angle,0,Math.PI*2);ctx.fill();}ctx.fillStyle=p.accent;ctx.beginPath();ctx.arc(x,y,28,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.soft;}}
 if(d.design==='bold'){ctx.fillStyle=p.accent;ctx.fillRect(0,0,w,28);ctx.fillRect(0,h-28,w,28);ctx.fillStyle=p.soft;ctx.beginPath();ctx.arc(w,0,270,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(0,h,210,0,Math.PI*2);ctx.fill();}
 const margin=112,content=w-2*margin;let ok=true;
 const block=(text,y,height,max,min,bold=false)=>{ok=textBlock(ctx,text,{x:margin,y,width:content,height,max,min,bold,color:p.ink})&&ok;};
 block(d.language==='hi'?'एक खास पल':'A MOMENT TO CELEBRATE',story?155:85,48,24,20);
 let titleY=story?260:170;
 if(image){const side=story?460:240,x=(w-side)/2,y=story?275:165;ctx.save();ctx.beginPath();ctx.roundRect(x,y,side,side,d.design==='elegant'?8:38);ctx.clip();const scale=Math.max(side/image.width,side/image.height),iw=image.width*scale,ih=image.height*scale;ctx.drawImage(image,x+(side-iw)/2,y+(side-ih)/2,iw,ih);ctx.restore();titleY=y+side+24;}
 const titleH=story?250:image?132:200;block(d.title,titleY,titleH,story?90:76,34,true);
 const nameY=titleY+titleH+8;block(d.name,nameY,story?90:60,story?54:42,24,true);
 const messageY=nameY+(story?110:78),messageH=story?330:image?150:210;block(d.message,messageY,messageH,story?44:36,24);
 const detailsY=messageY+messageH+16;block(d.details,detailsY,story?140:95,30,21);block(d.from,story?h-240:h-140,70,30,22,true);
 ctx.font=`18px ${font}`;ctx.fillStyle=p.accent;ctx.textAlign='center';ctx.fillText('Made with Sushant Synapse',w/2,h-65);
 return {fits:ok,width:w,height:h};
}
