'use strict';
const {fail}=require('../../../server/http');
const frequencies=['Monthly','Quarterly','Course','One-time','Per-class','Custom'];
const modes=['Cash','UPI','Bank Transfer','Card','Cheque','Other'];
const text=(v,label,required=false,max=200)=>{if(v==null)v='';if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail(400,`${label} is required / too long`);return v.trim();};
const integer=(v,min,max,label)=>{const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)fail(400,`Invalid ${label}`);return n;};
const money=v=>{if(!/^(0|[1-9]\d{0,7})(\.\d{1,2})?$/.test(String(v)))fail(400,'Use an amount with up to two decimal places');return Math.round(Number(v)*100);};
const choice=(v,values)=>{if(!values.includes(v))fail(400,'Invalid choice');return v;};
const phone=(v,label,required=false)=>{const value=text(v,label,required);if(value&&(!/^\+?[\d -]+$/.test(value)||!/^\d{10,15}$/.test(value.replace(/\D/g,''))))fail(400,`Invalid ${label} number`);return value;};
const time=v=>{const value=text(v,'Time');if(value&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))fail(400,'Invalid batch time');return value;};
const boolean=(v,fallback)=>{if(v===undefined)return fallback;if(![true,false,'true','false'].includes(v))fail(400,'Invalid status choice');return v===true||v==='true';};
function date(v){if(typeof v!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail(400,'Invalid date (2000–2099)');return v;}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function monthAdd(v,n){const d=new Date(v.slice(0,7)+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,7);}
function due(month,day){const [y,m]=month.split('-').map(Number);return `${month}-${String(Math.min(day,new Date(Date.UTC(y,m,0)).getUTCDate())).padStart(2,'0')}`;}
const empty=()=>({profile:null,batches:[],students:[],fees:[],payments:[],allocations:[],expenses:[],template:"Hello {{ParentName}}, {{StudentName}}'s fee of {{Amount}} for {{Month}} is pending. Kindly make the payment when convenient. Thank you, {{ClassName}}"});
const get=(rows,id)=>{const r=rows.find(x=>x.id===id);if(!r)fail(404,'Record not found');return r;};
const paid=(s,f)=>s.allocations.filter(a=>a.feeId===f.id&&!get(s.payments,a.paymentId).reversed).reduce((n,a)=>n+a.amount,0);
const balance=(s,f)=>f.amount-f.waived-paid(s,f);
const credit=(s,p)=>p.reversed?0:p.amount-s.allocations.filter(a=>a.paymentId===p.id).reduce((n,a)=>n+a.amount,0);
function totals(s){const payments=new Map(s.payments.map(p=>[p.id,p])),fees=new Map(),allocated=new Map();for(const a of s.allocations){allocated.set(a.paymentId,(allocated.get(a.paymentId)||0)+a.amount);if(!payments.get(a.paymentId).reversed)fees.set(a.feeId,(fees.get(a.feeId)||0)+a.amount);}return {fees,allocated};}
function allocate(s){const t=totals(s),groups=new Map();for(const f of s.fees){const left=f.amount-f.waived-(t.fees.get(f.id)||0);if(left>0){if(!groups.has(f.studentId))groups.set(f.studentId,[]);groups.get(f.studentId).push({fee:f,left});}}for(const list of groups.values())list.sort((a,b)=>a.fee.due.localeCompare(b.fee.due)||a.fee.id.localeCompare(b.fee.id));for(const p of s.payments){if(p.reversed)continue;let left=p.amount-(t.allocated.get(p.id)||0);if(!left)continue;for(const item of groups.get(p.studentId)||[]){const amount=Math.min(left,item.left);if(amount>0){s.allocations.push({paymentId:p.id,feeId:item.fee.id,amount});left-=amount;item.left-=amount;}if(!left)break;}}}
function generate(s,day){for(const st of s.students)for(const e of st.enrolments){const b=get(s.batches,e.batchId);if(e.start>day)continue;if(['Custom','Per-class'].includes(e.frequency))continue;let period=e.next||e.start.slice(0,7);let count=0;while(period<=day.slice(0,7)&&!e.finished){if(++count>1200)fail(400,'Too many periods');const active=st.status==='Active'||(st.status==='Paused'&&st.continueFees);if(active&&b.active&&e.start<=day){const id=`${e.id}:${period}`;if(!s.fees.some(f=>f.id===id))s.fees.push({id,studentId:st.id,batchId:b.id,batchName:b.name,period,due:[due(period,e.dueDay),e.start].sort().at(-1),amount:e.amount-e.discount,waived:0,waiverReason:'',label:e.frequency});}if(['Course','One-time'].includes(e.frequency)){e.finished=true;break;}period=monthAdd(period+'-01',e.frequency==='Quarterly'?3:1);e.next=period;}}allocate(s);}
function batch(i,id){return {id,name:text(i.name,'Batch name',true),subject:text(i.subject,'Course'),teacher:text(i.teacher,'Teacher'),days:text(i.days,'Days'),startTime:time(i.startTime),endTime:time(i.endTime),amount:money(i.fee),frequency:choice(i.frequency,frequencies),dueDay:integer(i.dueDay,1,31,'due day'),active:boolean(i.active,true)};}
function student(s,i,id,old,day,requestId=id){const mobile=phone(i.mobile,'mobile',true);const enrolments=i.enrolments;if(!Array.isArray(enrolments)||enrolments.length<1||enrolments.length>10)fail(400,'Choose one to ten batches');const seen=new Set();const list=enrolments.map((e,index)=>{const b=get(s.batches,e.batchId);if(seen.has(b.id))fail(400,'Batch repeated');seen.add(b.id);const prev=old?.enrolments.find(x=>x.batchId===b.id);const start=prev?.start||date(e.start||(old?monthAdd(day,1)+'-01':i.joining));const amount=e.fee===''||e.fee==null?b.amount:money(e.fee),discount=money(e.discount||0);if(discount>amount)fail(400,'Concession exceeds fee');return {id:prev?.id||`${requestId}:${index}`,batchId:b.id,amount,discount,frequency:choice(e.frequency||b.frequency,frequencies),dueDay:integer(e.dueDay||b.dueDay,1,31,'due day'),start,next:prev&&prev.frequency!==(e.frequency||b.frequency)?monthAdd(day,1):prev?.next,finished:prev?.frequency===(e.frequency||b.frequency)?prev.finished:false};});return {id,name:text(i.name,'Student name',true),parent:text(i.parent,'Parent'),mobile,whatsapp:phone(i.whatsapp,'WhatsApp'),secondary:phone(i.secondary,'Secondary mobile'),family:text(i.family,'Family key'),joining:old?.joining||date(i.joining),notes:text(i.notes,'Notes',false,2000),status:choice(i.status||'Active',['Active','Paused','Inactive']),continueFees:boolean(i.continueFees,false),enrolments:list};}
function apply(s,c,day){date(day);if(!c||typeof c!=='object')fail(400,'Invalid command');const i=c.input||{},id=c.id; if(typeof id!=='string'||id.length>150)fail(400,'Invalid request ID');generate(s,day);
 switch(c.type){
 case 'sync':break;
 case 'profile':{const logo=text(i.logo,'Logo',false,300000);if(logo&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(logo))fail(400,'Use a PNG, JPEG or WebP logo');s.profile={name:text(i.name,'Academy name',true),owner:text(i.owner,'Teacher name',true),mobile:phone(i.mobile,'Mobile',true),address:text(i.address,'Address',false,1000),whatsapp:phone(i.whatsapp,'WhatsApp'),dueDay:integer(i.dueDay,1,31,'due day'),currency:choice(i.currency||'INR',['INR']),sessionMonth:integer(i.sessionMonth,1,12,'session month'),logo};break;}
 case 'batch':{const value=batch(i,i.id||id);if(i.id)Object.assign(get(s.batches,i.id),value);else s.batches.push(value);break;}
 case 'student':{const old=i.id?get(s.students,i.id):null;const value=student(s,i,i.id||id,old,day,id);if(old)Object.assign(old,value);else s.students.push(value);break;}
 case 'import':{if(!Array.isArray(i.students)||!i.students.length||i.students.length>1000)fail(400,'Import 1–1000 students');i.students.forEach((row,n)=>{if(s.students.some(x=>x.name.toLowerCase()===String(row.name).toLowerCase()&&x.mobile===row.mobile))fail(409,`Duplicate student: ${row.name}`);s.students.push(student(s,row,`${id}:${n}`,null,day));});break;}
 case 'charge':{const st=get(s.students,i.studentId),b=get(s.batches,i.batchId);if(!st.enrolments.some(e=>e.batchId===b.id))fail(400,'Student is not in this batch');const amount=money(i.amount);if(!amount)fail(400,'Amount must be positive');s.fees.push({id,studentId:st.id,batchId:b.id,batchName:b.name,amount,waived:0,waiverReason:'',period:date(i.due).slice(0,7),due:i.due,label:text(i.label,'Fee description',true)});break;}
 case 'payment':{const st=get(s.students,i.studentId),amount=money(i.amount);if(!amount)fail(400,'Amount must be positive');if(date(i.date)>day)fail(400,'Payment date cannot be in the future');if(s.payments.some(p=>!p.reversed&&p.studentId===st.id&&p.amount===amount&&p.date===i.date&&p.mode===i.mode)&&i.confirmDuplicate!==true)fail(409,'A matching payment exists. Review history and explicitly confirm if this is another payment.');const p={id,studentId:st.id,amount,date:i.date,mode:choice(i.mode,modes),note:text(i.note,'Reference'),number:`BF-${String(s.payments.length+1).padStart(6,'0')}`,reversed:null,receipt:null};s.payments.push(p);allocate(s);p.receipt={profile:structuredClone(s.profile),student:structuredClone(st),batchNames:st.enrolments.map(e=>get(s.batches,e.batchId).name),allocations:s.allocations.filter(a=>a.paymentId===id).map(a=>({...a,fee:structuredClone(get(s.fees,a.feeId))})),remaining:s.fees.filter(f=>f.studentId===st.id).reduce((n,f)=>n+balance(s,f),0),advance:credit(s,p)};break;}
 case 'reverse':{const p=get(s.payments,i.id);if(p.reversed)fail(409,'Payment already reversed');p.reversed={reason:text(i.reason,'Correction reason',true),date:day};allocate(s);break;}
 case 'waive':{const f=get(s.fees,i.id);if(f.waived)fail(409,'Fee already waived');const left=balance(s,f);if(!left)fail(400,'No remaining balance');f.waived=left;f.waiverReason=text(i.reason,'Waiver reason',true);break;}
 case 'expense':{const amount=money(i.amount);if(!amount)fail(400,'Amount must be positive');if(date(i.date)>day)fail(400,'Expense cannot be future dated');s.expenses.push({id,date:i.date,category:choice(i.category,['Rent','Electricity','Teacher payment','Stationery','Marketing','Miscellaneous']),amount,note:text(i.note,'Note'),reversed:null});break;}
 case 'reverseExpense':{const e=get(s.expenses,i.id);if(e.reversed)fail(409,'Expense already reversed');e.reversed={date:day,reason:text(i.reason,'Reason',true)};break;}
 case 'template':s.template=text(i.template,'Reminder template',true,3000);break;
 default:fail(400,'Unknown action');
 }generate(s,day);return s;
}
function view(s,day=today()){const t=totals(s);return {...s,today:day,fees:s.fees.map(f=>{const p=t.fees.get(f.id)||0,left=f.amount-f.waived-p;return {...f,paid:p,balance:left,status:!left?(f.waived?'Waived':'Paid'):p?'Partially Paid':f.due<day?'Overdue':f.due===day?'Due':'Upcoming'};}),payments:s.payments.map(p=>({...p,credit:p.reversed?0:p.amount-(t.allocated.get(p.id)||0)}))};}
module.exports={empty,apply,view,today,date,frequencies,modes};
