import {istDate,puzzle,levelPuzzle,tokens,calculate,solve,display,solutionSteps} from './engine.mjs';
export function mountSpark(root,{day=null,challengeUrl=date=>`${location.origin}/daily-spark?day=${date}`,onComplete}={}){
const $=selector=>root.querySelector(selector);
let date,mode='daily',original,items,selected=[],op=null,history=[],assisted=false,finished=false,revealed=false,hintStep=0;
const symbols={'+':'+','-':'−','*':'×','/':'÷'};
const params=new URLSearchParams(location.search),difficulty=$('#practice-difficulty');
let legacyRound=params.has('day')&&!params.has('level');
difficulty.value=['warmup','challenge','expert'].includes(params.get('level'))?params.get('level'):'challenge';
difficulty.onchange=()=>{legacyRound=false;start(mode==='practice');};
const descriptions={warmup:'A gentle start: no division needed.',challenge:'Division is required; whole-number steps are possible.',expert:'A tougher spark: a fractional step is required.'};
function start(practice=false){date=day||istDate();mode=practice?'practice':'daily';original=!practice&&legacyRound?puzzle(date):levelPuzzle(practice?String(crypto.getRandomValues(new Uint32Array(1))[0]):date,difficulty.value);reset();if(!practice&&!legacyRound){const u=new URL(location.href);u.searchParams.set('day',date);u.searchParams.set('level',difficulty.value);window.history.replaceState(null,'',u.href);}}
function reset(){items=tokens(original);selected=[];op=null;history=[];hintStep=0;assisted=false;finished=false;revealed=false;$('#status').textContent='';$('#result').hidden=true;$('#share-fallback').hidden=true;render();}
function render(){
 root.dataset.sparkLegacy=String(legacyRound&&mode==='daily');
 $('#difficulty-note').textContent=legacyRound&&mode==='daily'?'Original shared puzzle · difficulty varies.':descriptions[difficulty.value];
 $('#edition').textContent=mode==='daily'?`DAILY · ${date} · IST`:'PRACTICE · JUST FOR FUN';$('#daily').setAttribute('aria-pressed',String(mode==='daily'));$('#practice').setAttribute('aria-pressed',String(mode==='practice'));
 $('#numbers').replaceChildren(...items.map((item,index)=>{const b=document.createElement('button');b.type='button';b.className='tile';b.textContent=display(item.value);b.disabled=finished;b.setAttribute('aria-label',`Number ${index+1}: ${display(item.value)}`);b.setAttribute('aria-pressed',String(selected.includes(index)));if(selected.includes(index)){const order=document.createElement('small');order.textContent=selected.indexOf(index)===0?'FIRST':'SECOND';b.append(order);}b.onclick=()=>{if(selected.includes(index))selected=selected.filter(n=>n!==index);else if(selected.length<2)selected.push(index);else selected=[index];render();$('#numbers').children[index]?.focus();};return b;}));
 root.querySelectorAll('[data-op]').forEach(b=>{b.setAttribute('aria-pressed',String(op===b.dataset.op));b.disabled=finished;});$('#combine').disabled=finished||selected.length!==2||!op;$('#undo').disabled=!history.length||finished;$('#hint').disabled=finished;$('#reveal').disabled=finished;
 $('#move').textContent=finished?'Round complete.':selected.length===2?`${display(items[selected[0]].value)} ${symbols[op]||'?'} ${display(items[selected[1]].value)}`:selected.length===1?'Select your second number.':'Select your first number.';
 $('#history').replaceChildren(...history.map(step=>{const li=document.createElement('li');li.textContent=step.label;return li;}));
}
root.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{op=b.dataset.op;render();});
$('#combine').onclick=()=>{const [a,b]=selected.map(index=>items[index]);try{const value=calculate(a.value,op,b.value);history.push({items:structuredClone(items),label:`${display(a.value)} ${symbols[op]} ${display(b.value)} = ${display(value)}`});items=[...items.filter((_,index)=>!selected.includes(index)),{value,expression:`(${a.expression} ${op} ${b.expression})`}];selected=[];op=null;hintStep=0;$('#status').textContent='';if(items.length===1){if(Math.abs(items[0].value-24)<1e-8)complete(false);else $('#status').textContent=`You made ${display(items[0].value)}. Undo a move or start again.`;}render();$('#numbers').querySelector('button:not(:disabled)')?.focus();}catch(error){$('#status').textContent=error.message;}};
$('#undo').onclick=()=>{items=history.pop().items;selected=[];op=null;hintStep=0;$('#status').textContent='';render();};$('#reset').onclick=reset;$('#daily').onclick=()=>start();$('#practice').onclick=()=>start(true);$('#another').onclick=()=>start(true);
$('#hint').onclick=()=>{assisted=true;const steps=solutionSteps(items);if(!steps){$('#status').textContent='No route to 24 remains. Undo or start again.';return;}const step=steps[0];hintStep++;const names={'+':'addition','-':'subtraction','*':'multiplication','/':'division'};$('#status').textContent=hintStep===1?`A nudge: try ${names[step.op]}.`:hintStep===2?`Try combining ${display(step.a)} ${symbols[step.op]} ${display(step.b)} first.`:`First move: ${display(step.a)} ${symbols[step.op]} ${display(step.b)} = ${display(step.value)}. Use Show solution for the full route.`;};
function complete(show){finished=true;revealed=show;$('#result').hidden=false;$('#result').classList.toggle('spark-solved',!show);$('#result-title').textContent=show?'One way to make 24.':'You made it. A spark well spent!';$('#result-copy').textContent=show?`${solve(tokens(original))} = 24`:`${assisted?'Solved with hints.':'Solved independently — without hints.'} ${mode==='daily'?'Challenge a friend with the same four numbers.':'Try another practice round.'}`;$('#status').textContent=show?'Solution revealed. Start again to try it yourself.':'All four numbers used. Nicely done.';onComplete?.();}
$('#reveal').onclick=()=>{assisted=true;complete(true);render();};
$('#share').onclick=async()=>{const text=`Daily Spark${mode==='daily'?` · ${date} (IST)`:''}\n${original.join(' · ')} → 24\n${revealed?'Can you make 24?':assisted?'Solved with a hint':'Solved without hints'}\n${mode==='practice'?'Try the daily challenge: ':''}${shareUrl()}`;try{if(navigator.share){await navigator.share({title:'Daily Spark',text});return;}if(navigator.clipboard){await navigator.clipboard.writeText(text);$('#status').textContent='Result copied. Paste it to challenge a friend.';return;}}catch(error){if(error.name==='AbortError')return;}$('#share-fallback').hidden=false;$('#share-text').value=text;$('#share-text').focus();$('#share-text').select();$('#status').textContent='Copy the message below to share your result.';};
function shareUrl(){const u=new URL(challengeUrl(mode==='daily'?date:istDate()),location.origin);if(!(legacyRound&&mode==='daily'))u.searchParams.set('level',difficulty.value);return u.href;}
// Preserve dated v1 links; new links include their selected v2 level.
const sharedDay=day||params.get('day');
if(sharedDay&&/^\d{4}-\d{2}-\d{2}$/.test(sharedDay)&&!Number.isNaN(Date.parse(sharedDay))&&new Date(sharedDay).toISOString().slice(0,10)===sharedDay&&sharedDay<=istDate())day=sharedDay;
start();
}
