const {test,expect}=require('@playwright/test');const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');let child,base,dir;
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-mixer-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timed out')),15000);child.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve();}});child.once('error',reject);});});test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});
test('animated complete teams, PNG and private copy/share fallbacks, editing and refresh',async({page})=>{
 const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:undefined});Object.defineProperty(navigator,'canShare',{value:undefined});});await page.goto(base+'/team-mixer');const names=(await page.locator('#names').inputValue()).split('\n');await page.locator('#mix').click();await expect(page.locator('#mix')).toBeDisabled();await expect(page.locator('#names')).toBeDisabled();await expect(page.locator('#exports')).toBeVisible();await expect(page.locator('#teams article')).toHaveCount(3);expect((await page.locator('#teams li').allTextContents()).sort()).toEqual(names.sort());for(const team of await page.locator('#teams article').all())await expect(team.locator('li')).toHaveCount(4);
 await page.locator('#copy').click();await expect(page.locator('#copy-text')).toHaveValue(/Team 1/);for(const name of names)expect(await page.locator('#copy-text').inputValue()).toContain(name);
 const event=page.waitForEvent('download');await page.locator('#download').click();const download=await event;await download.saveAs('test-results/team-mixer-card.png');const bytes=fs.readFileSync('test-results/team-mixer-card.png');expect(bytes.readUInt32BE(16)).toBe(1200);expect(bytes.readUInt32BE(20)).toBeGreaterThan(350);const fallback=page.waitForEvent('download');await page.locator('#share').click();await fallback;await expect(page.locator('#export-status')).toContainText('Attach it');
 await page.locator('#title').fill('Sunday cricket');await expect(page.locator('#exports')).toBeHidden();await expect(page.locator('#teams article')).toHaveCount(0);await page.locator('#mix').click();await expect(page.locator('#exports')).toBeVisible();await expect(page.locator('#results-title')).toHaveText('Sunday cricket');
 await page.screenshot({path:'test-results/team-mixer-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('#theme').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:'test-results/team-mixer-mobile.png',fullPage:true});for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}expect(errors).toEqual([]);expect(api).toEqual([]);await page.reload();await expect(page.locator('#exports')).toBeHidden();await expect(page.locator('#title')).toHaveValue('Our teams');
});
test('uneven sizes, validation, safe Hindi labels, large exports and native share cancellation',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce',colorScheme:'dark'});await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{value:()=>true});Object.defineProperty(navigator,'share',{value:async data=>{window.shared=data.files.map(f=>({name:f.name,type:f.type,size:f.size}));throw new DOMException('Cancelled','AbortError');}});});await page.goto(base+'/team-mixer/');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.locator('#names').fill('A\na');await page.locator('#team-count').fill('2');await page.locator('#mix').click();await expect(page.locator('#status')).toContainText('unique');await page.locator('#names').fill('A\nB');await page.locator('#team-count').fill('3');await page.locator('#mix').click();await expect(page.locator('#status')).toContainText('one participant');
 const names=['अनन्या','आरव','भविक','दिया','ईशान','<img src=x onerror=alert(1)>','Meera'];await page.locator('#names').fill(names.join('\n'));await page.locator('#title').fill('हमारी टीम');await page.locator('#mix').click();await expect(page.locator('#exports')).toBeVisible();expect((await page.locator('#teams li').allTextContents()).sort()).toEqual(names.sort());await expect(page.locator('#teams img')).toHaveCount(0);const sizes=await page.locator('#teams article').evaluateAll(teams=>teams.map(t=>t.querySelectorAll('li').length));expect([...sizes].sort()).toEqual([2,2,3]);await page.locator('#share').click();await expect(page.locator('#export-status')).toContainText('cancelled');expect((await page.evaluate(()=>window.shared))[0].type).toBe('image/png');await expect(page.locator('#mix')).toBeEnabled();
 const bounds=await page.evaluate(async()=>{const {mix}=await import('/team-mixer/engine.mjs'),{renderCard}=await import('/team-mixer/export.mjs');const names=Array.from({length:100},(_,i)=>'W'.repeat(57)+String(i));const result=mix(names.join('\n'),20,'W'.repeat(100)),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),bad=[];const original=ctx.fillText;ctx.fillText=function(text,x,y){if(x+this.measureText(text).width>1200||y>canvas.height)bad.push(text);return original.call(this,text,x,y);};const size=renderCard(canvas,result);return {...size,bad};});expect(bounds.width).toBe(1200);expect(bounds.height).toBeGreaterThan(1500);expect(bounds.bad).toEqual([]);
 await page.locator('#names').fill(Array.from({length:100},(_,i)=>'Participant '+i).join('\n'));await page.locator('#team-count').fill('20');await page.locator('#mix').click();await expect(page.locator('#teams article')).toHaveCount(20);await expect(page.locator('#exports')).toBeVisible();await expect(page.locator('#teams li')).toHaveCount(100);await page.locator('#sample').click();await expect(page.locator('#team-count')).toHaveValue('3');await expect(page.locator('#exports')).toBeHidden();
});
