const en={
 brief:['Thinking of you and your family. Please accept my heartfelt condolences.','With heartfelt sympathy. Wishing you care and support in the days ahead.','I am so sorry for your loss. You are in my thoughts.'],
 warm:['There are no perfect words for a loss like this. I am thinking of you, and I am here to listen whenever you need.','May the memories you hold close bring moments of comfort. Sending you love and heartfelt sympathy.','Your loss matters, and so do you. Take each day at your own pace. I am here for you.'],
 formal:['Please accept our sincere condolences. Our thoughts are with you and your family during this difficult time.','We extend our deepest sympathy to you and your loved ones. Wishing you strength and support in the days ahead.','With sincere sympathy and respect, we offer our heartfelt condolences to you and your family.']};
const hi={
 brief:['इस कठिन समय में हमारी संवेदनाएँ आपके और आपके परिवार के साथ हैं।','आपके दुःख में हम आपके साथ हैं। हमारी हार्दिक संवेदनाएँ स्वीकार करें।','आपकी क्षति का हमें गहरा दुःख है। हम आपके बारे में सोच रहे हैं।'],
 warm:['ऐसी क्षति के लिए शब्द कम पड़ जाते हैं। जब भी आप बात करना चाहें, हम आपकी बात सुनने के लिए साथ हैं।','अपनों की यादें आपके मन को कुछ सुकून दें। इस कठिन समय में हमारा स्नेह और संवेदनाएँ आपके साथ हैं।','आपका दुःख हमारे लिए मायने रखता है। अपना समय लें; जब भी ज़रूरत हो, हम आपके साथ हैं।'],
 formal:['कृपया हमारी हार्दिक संवेदनाएँ स्वीकार करें। इस कठिन समय में हम आपके और आपके परिवार के साथ हैं।','आपको और आपके प्रियजनों को हमारी गहरी संवेदनाएँ। आने वाले दिनों में आपको अपनों का सहारा मिले।','सादर, हम आपके और आपके परिवार के प्रति अपनी हार्दिक संवेदनाएँ व्यक्त करते हैं।']};
export function condolenceMessage({language='en',tone='warm',connection='general',variant=0}={}){if(!['en','hi'].includes(language)||!['brief','warm','formal'].includes(tone)||!['general','friend','colleague'].includes(connection)||!Number.isInteger(variant)||variant<0)throw Error('Choose valid message options.');let text=(language==='hi'?hi:en)[tone][variant%3];if(connection==='friend'&&tone!=='brief')text+=language==='hi'?' एक मित्र के रूप में, मैं आपके साथ हूँ।':' As your friend, I am here for you.';if(connection==='colleague'&&tone!=='brief')text+=language==='hi'?' काम की चिंता छोड़कर अपना समय लें।':' Please take the time you need away from work.';return {title:language==='hi'?'हार्दिक संवेदनाएँ':'With heartfelt sympathy',message:text};}
