import {sample,mix,resultText,safeFilename} from './engine.mjs';
import {renderCard,pngBlob,download} from './export.mjs';
const $=s=>document.querySelector(s),media=matchMedia('(prefers-color-scheme: dark)'),motion=matchMedia('(prefers-reduced-motion: reduce)');
$('#theme').outerHTML=window.SynapseTheme.control('id="theme"');function theme(){const p=window.SynapseTheme.read();document.documentElement.dataset.theme=p==='system'?(media.matches?'dark':'light'):p;}$('#theme').addEventListener('change',theme);media.addEventListener('change',theme);theme();
let result=null,busy=false;
function lock(value){busy=value;document.querySelectorAll('#setup input,#setup textarea,#setup button,#exports button').forEach(control=>control.disabled=value);$('#teams').setAttribute('aria-busy',String(value));}
function clear(){result=null;$('#teams').replaceChildren();$('#empty').hidden=false;$('#exports').hidden=true;$('#export-help').hidden=true;$('#copy-fallback').hidden=true;$('#summary').textContent='';$('#results-title').textContent='A fresh mix awaits.';$('#export-status').textContent='';}
$('#setup').addEventListener('input',()=>{if(!busy){clear();$('#status').textContent='Mix to use your updated names and settings.';}});
$('#sample').onclick=()=>{if(busy)return;$('#names').value=sample.join('\n');$('#team-count').value='3';$('#title').value='Our teams';clear();$('#status').textContent='Sample names loaded. Mix to try them.';};
$('#setup').onsubmit=async event=>{event.preventDefault();if(busy)return;try{const next=mix($('#names').value,Number($('#team-count').value),$('#title').value);clear();lock(true);$('#empty').hidden=true;$('#results-title').textContent=next.title;$('#status').textContent='Mixing your teams...';
 const cards=next.teams.map(team=>{const article=document.createElement('article');article.className='team';const header=document.createElement('header'),title=document.createElement('h3'),count=document.createElement('span');title.textContent=team.name;count.textContent=team.members.length+' '+(team.members.length===1?'person':'people');header.append(title,count);const list=document.createElement('ol');team.members.forEach(name=>{const li=document.createElement('li');li.textContent=name;list.append(li);});article.append(header,list);return article;});$('#teams').append(...cards);
 await Promise.all(cards.map(async(card,index)=>{const animation=card.animate([{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:motion.matches?0:350,delay:motion.matches?0:index*90,easing:'ease-out',fill:'both'});try{await animation.finished;}finally{animation.cancel();}}));
 result=next;$('#summary').textContent=next.total+' people | '+next.teams.length+' teams';$('#exports').hidden=false;$('#export-help').hidden=false;$('#status').textContent='Teams ready. Everyone is included once. Mix again for another assignment.';$('#results-title').setAttribute('tabindex','-1');$('#results-title').focus();
 }catch(error){$('#status').textContent=error.message;}finally{lock(false);}
};
$('#copy').onclick=async()=>{if(!result||busy)return;const text=resultText(result);try{if(navigator.clipboard){await navigator.clipboard.writeText(text);$('#export-status').textContent='Team list copied. Paste it into your group chat.';return;}}catch{}$('#copy-text').value=text;$('#copy-fallback').hidden=false;$('#copy-text').focus();$('#copy-text').select();$('#export-status').textContent='Copy the team list below.';};
async function exportTeams(share){if(!result||busy)return;const snapshot=result;lock(true);try{const canvas=document.createElement('canvas');renderCard(canvas,snapshot);const png=await pngBlob(canvas),name=safeFilename(snapshot.title),file=new File([png],name,{type:'image/png'});if(share&&navigator.canShare?.({files:[file]})&&navigator.share){try{await navigator.share({title:'Team Mixer',files:[file]});$('#export-status').textContent='Team card shared.';return;}catch(error){if(error.name==='AbortError'){$('#export-status').textContent='Sharing cancelled. Your teams are still here.';return;}}}download(png,name);$('#export-status').textContent=share?'Team card downloaded. Attach it in your group chat.':'Team card downloaded.';}catch(error){$('#export-status').textContent=error.message;}finally{lock(false);}}
$('#download').onclick=()=>exportTeams(false);$('#share').onclick=()=>exportTeams(true);$('#names').value=sample.join('\n');
