export const sample=['Aarav','Ananya','Bhavik','Diya','Ishaan','Kavya','Meera','Neel','Priya','Rohan','Sana','Vihaan'];
export function parseNames(text){if(typeof text!=='string'||text.length>16000)throw Error('Keep the list under 16,000 characters.');const names=text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(names.length<2||names.length>100)throw Error('Enter 2 to 100 participants, one per line.');if(names.some(s=>[...s].length>60))throw Error('Keep each name to 60 characters or fewer.');const unique=new Set(names.map(s=>s.normalize('NFKC').toLocaleLowerCase('en-IN')));if(unique.size!==names.length)throw Error('Names must be unique. Add initials or surnames for people with the same name.');return names;}
export function randomIndex(count,read=()=>crypto.getRandomValues(new Uint32Array(1))[0]){if(!Number.isInteger(count)||count<1||count>100)throw Error('Invalid random range.');const limit=4294967296-(4294967296%count);for(let attempt=0;attempt<128;attempt++){const value=read();if(!Number.isInteger(value)||value<0||value>4294967295)throw Error('Invalid random value.');if(value<limit)return value%count;}throw Error('Random selection failed. Try again.');}
export function shuffle(values,read){const result=[...values];for(let i=result.length-1;i>0;i--){const j=randomIndex(i+1,read);[result[i],result[j]]=[result[j],result[i]];}return result;}
export function mix(namesText,count,title='',read){const names=parseNames(namesText);if(!Number.isInteger(count)||count<2||count>20||count>names.length)throw Error('Choose 2 to 20 teams, with at least one participant per team.');title=String(title).trim()||'Our teams';if([...title].length>100)throw Error('Keep the title to 100 characters or fewer.');const teams=Array.from({length:count},(_,i)=>({name:'Team '+(i+1),members:[]})),order=shuffle(teams.map((_,i)=>i),read);shuffle(names,read).forEach((name,i)=>teams[order[i%count]].members.push(name));return {title,teams,total:names.length};}
export function resultText(result){return `${result.title}\n${result.total} participants | ${result.teams.length} teams\n\n${result.teams.map(team=>team.name+'\n'+team.members.join('\n')).join('\n\n')}\n\nMade with Team Mixer\n${location.origin}/team-mixer`;}
export function constrainedMix(text,count,title='',rules={},read){
 if(!rules.together?.trim()&&!rules.apart?.trim())return mix(text,count,title,read);const names=parseNames(text);mix(text,count,title,read);const key=n=>n.normalize('NFKC').toLocaleLowerCase('en-IN'),ids=new Map(names.map((n,i)=>[key(n),i])),parent=names.map((_,i)=>i),root=i=>parent[i]===i?i:(parent[i]=root(parent[i]));
 function rows(value){if(typeof value!=='string'||value.length>16000)throw Error('Keep constraints under 16,000 characters.');const lines=value.split(/\r?\n/).filter(l=>l.trim());if(lines.length>100)throw Error('Use at most 100 constraint rows.');return lines.map(l=>{const result=l.split('|').map(n=>ids.get(key(n.trim())));if(result.length<2||result.some(i=>i===undefined)||new Set(result).size!==result.length)throw Error('Each constraint needs distinct participant names separated by |.');return result;});}
 for(const row of rows(rules.together||''))for(const i of row.slice(1))parent[root(i)]=root(row[0]);
 const edges=new Map();for(const row of rows(rules.apart||''))for(let i=0;i<row.length;i++)for(let j=i+1;j<row.length;j++){const a=root(row[i]),b=root(row[j]);if(a===b)throw Error('These rules keep the same people together and apart.');if(!edges.has(a))edges.set(a,new Set());if(!edges.has(b))edges.set(b,new Set());edges.get(a).add(b);edges.get(b).add(a);}
 const groups=new Map();names.forEach((n,i)=>{const r=root(i);if(!groups.has(r))groups.set(r,[]);groups.get(r).push(n);});const ordered=shuffle([...groups],read).sort((a,b)=>b[1].length-a[1].length),capacities=shuffle(Array.from({length:count},(_,i)=>Math.floor(names.length/count)+(i<names.length%count?1:0)),read),teams=Array.from({length:count},(_,i)=>({name:'Team '+(i+1),members:[]})),assigned=new Map();let visits=0;
 function place(index){if(++visits>20000)return false;if(index===ordered.length)return true;const [id,members]=ordered[index];for(const t of shuffle(teams.map((_,i)=>i),read)){if(teams[t].members.length+members.length>capacities[t]||[...(edges.get(id)||[])].some(other=>assigned.get(other)===t))continue;assigned.set(id,t);teams[t].members.push(...members);if(place(index+1))return true;teams[t].members.splice(-members.length);assigned.delete(id);}return false;}
 if(!place(0))throw Error('No balanced mix found within the search limit. Relax a rule or change the team count.');return {title:String(title).trim()||'Our teams',teams,total:names.length};
}
export function safeFilename(title){return (String(title).normalize('NFKC').replace(/[^\p{L}\p{M}\p{N}]+/gu,'-').replace(/^-|-$/g,'').slice(0,64)||'teams')+'-teams.png';}
