const {test,expect}=require('@playwright/test');const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');let child,base,dir;
test.beforeAll(async()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'synapse-celebration-'));child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'0',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timed out')),15000);child.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/localhost:(\d+)/);if(match){base='http://127.0.0.1:'+match[1];clearTimeout(timer);resolve();}});child.once('error',reject);});});test.afterAll(async()=>{if(child?.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});if(dir)fs.rmSync(dir,{recursive:true,force:true});});

test('all studio sections are discoverable on mobile with exactly one current section',async({page})=>{
 await page.setViewportSize({width:320,height:850});await page.goto(base+'/moment-studio');
 const nav=page.getByRole('navigation',{name:'Moment Studio sections'});
 for(const link of await nav.getByRole('link').all()){await expect(link).toBeVisible();const box=await link.boundingBox();expect(box.y+box.height).toBeLessThan(850);}
 await expect(nav.locator('[aria-current=page]')).toHaveCount(1);
 await expect(nav.locator('[aria-current=page]')).toHaveAttribute('data-studio-section','cards');
 await nav.getByRole('link',{name:'Condolences & remembrance',exact:true}).click();
 await expect(page.locator('#condolence-tools')).toBeVisible();
 await expect(nav.locator('[aria-current=page]')).toHaveCount(1);
 await expect(nav.locator('[aria-current=page]')).toHaveAttribute('data-studio-section','condolences');
 await page.screenshot({path:'test-results/moment-navigation-mobile.png'});
 await page.locator('#occasion').selectOption('birthday');
 await expect(nav.locator('[aria-current=page]')).toHaveCount(1);
 await expect(nav.locator('[aria-current=page]')).toHaveAttribute('data-studio-section','cards');
 await nav.getByRole('link',{name:'Certificates & awards',exact:true}).click();
 await expect(nav.locator('[aria-current=page]')).toHaveAttribute('data-studio-section','certificates');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('respectful bilingual generation, all branded card designs and real PNG export, merged navigation and private copying',async({page})=>{
const api=[],errors=[];page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',r=>r.abort());await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:undefined}));await page.goto(base+'/moment-studio?occasion=condolence');await expect(page).toHaveTitle(/Moment Studio/);await expect(page.locator('#occasion')).toHaveValue('condolence');await expect(page.getByRole('radio',{name:'Quiet remembrance',exact:true})).toBeChecked();await expect(page.locator('#palette')).toHaveValue('slate');
for(const language of ['en','hi'])for(const tone of ['brief','warm','formal'])for(const connection of ['general','friend','colleague']){await page.locator('#language').selectOption(language);await page.locator('#message-tone').selectOption(tone);await page.locator('#connection').selectOption(connection);await page.locator('#generate-message').click();await expect(page.locator('#download')).toBeEnabled();}await page.locator('#copy-message').click();await expect(page.locator('#message-copy')).toHaveValue(/Sushant Synapse/);await expect(page.locator('#message-copy')).toHaveValue(/Moment Studio/);await page.locator('[name=name]').fill('आदरणीय अनन्या');
const branded=await page.evaluate(async()=>{const {render,occasions,designs,palettes}=await import('/moment-studio/card-renderer.mjs'),{brandReady}=await import('/moment-studio/branding.mjs');const result=[];for(const occasion of Object.keys(occasions))for(const design of Object.keys(designs))for(const format of ['square','story']){const c=document.createElement('canvas'),ctx=c.getContext('2d'),draw=ctx.drawImage.bind(ctx),fill=ctx.fillText.bind(ctx),logos=[],credits=[];ctx.drawImage=(image,...args)=>{if(image.src?.endsWith('/logo-adaptive-192.png'))logos.push(args);return draw(image,...args);};ctx.fillText=(text,...args)=>{if(text.includes('Sushant Synapse'))credits.push(text);return fill(text,...args);};const d={...occasions[occasion].hi,occasion,language:'hi',design,palette:'slate',format,name:'अनन्या',from:'आपके मित्र'};const r=render(c,d);result.push({occasion,design,format,fits:r.fits,logos:logos.length,credits:credits.length});}return {brandReady,result};});expect(branded.brandReady).toBe(true);for(const row of branded.result){expect(row.fits).toBe(true);expect(row.logos).toBe(1);expect(row.credits).toBe(1);}expect(branded.result).toHaveLength(90);
for(const [format,height] of [['square',1080],['story',1920]]){await page.getByLabel('Card size').selectOption(format);const event=page.waitForEvent('download');await page.locator('#download').click();const download=await event,file='test-results/moment-condolence-'+format+'.png';await download.saveAs(file);const bytes=fs.readFileSync(file);expect(bytes.readUInt32BE(16)).toBe(1080);expect(bytes.readUInt32BE(20)).toBe(height);const match=await page.evaluate(async b64=>{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),bitmap=await createImageBitmap(new Blob([bytes],{type:'image/png'})),c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;c.getContext('2d').drawImage(bitmap,0,0);bitmap.close();const current=document.querySelector('#card'),y=c.height-104,a=current.getContext('2d').getImageData(60,y,960,64).data,b=c.getContext('2d').getImageData(60,y,960,64).data;return a.every((v,i)=>v===b[i]);},bytes.toString('base64'));expect(match).toBe(true);}
await page.getByLabel('Card size').selectOption('square');await page.setViewportSize({width:390,height:844});await page.locator('#theme').click();await page.screenshot({path:'test-results/moment-condolence-mobile.png',fullPage:true});for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.getByRole('link',{name:'Certificates & awards',exact:true}).click();await expect(page).toHaveURL(base+'/moment-studio/certificates');await expect(page.locator('[name=type] option')).toHaveCount(17);await page.getByRole('link',{name:'Condolences & remembrance',exact:true}).click();await expect(page.locator('#occasion')).toHaveValue('condolence');await page.reload();await expect(page.locator('[name=name]')).toHaveValue('');expect(errors).toEqual([]);expect(api).toEqual([]);
});
test('certificates brand every template, PDF/PNG/print and preserved organisations; missing logo blocks outputs',async({page,browser})=>{
await page.goto(base+'/moment-studio/certificates');await page.getByLabel('Recipient Name',{exact:true}).fill('Priya Sharma');await page.getByLabel('Certificate Type').selectOption('Best Friend');const brand=await page.evaluate(async()=>{const {render,templates}=await import('/moment-studio/certificate-renderer.mjs');return templates.map(template=>{const c=document.createElement('canvas'),ctx=c.getContext('2d'),draw=ctx.drawImage.bind(ctx),fill=ctx.fillText.bind(ctx);let logos=0,credits=0;ctx.drawImage=(img,...args)=>{if(img.src?.endsWith('/logo-adaptive-192.png'))logos++;return draw(img,...args);};ctx.fillText=(t,...args)=>{if(t.includes('Sushant Synapse')&&t.includes('Moment Studio'))credits++;return fill(t,...args);};render(c,{template,recipient:'Priya',description:'being a wonderful friend'},{});return {logos,credits};});});for(const row of brand){expect(row.logos).toBe(1);expect(row.credits).toBe(1);}await page.getByRole('button',{name:'Generate certificate'}).click();await page.getByLabel('PNG quality').selectOption('300');for(const [button,format]of [['Download PNG','png'],['Download PDF','pdf']]){const event=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const d=await event,p='test-results/moment-award.'+format;await d.saveAs(p);const b=fs.readFileSync(p);if(format==='png'){expect(b.readUInt32BE(16)).toBe(3508);expect(b.readUInt32BE(20)).toBe(2480);}else expect(b.subarray(0,8).toString()).toContain('%PDF-1.4');}await page.getByLabel('Organization Name').fill('Kindness Foundation');await page.locator('#save-organisation').click();await page.getByRole('link',{name:'Cards & greetings',exact:true}).click();await page.getByRole('link',{name:'Certificates & awards',exact:true}).click();await expect(page.getByLabel('Organization Name')).toHaveValue('Kindness Foundation');await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));await expect(page.locator('#certificate')).toHaveAttribute('width','3508');
const blocked=await browser.newContext(),bp=await blocked.newPage();await bp.route('**/logo-adaptive-192.png',r=>r.abort());await bp.goto(base+'/moment-studio');await expect(bp.locator('#fit-status')).toContainText('logo could not load');await expect(bp.locator('#download')).toBeDisabled();await expect(bp.locator('#share')).toBeDisabled();await bp.goto(base+'/moment-studio/certificates');await bp.getByLabel('Recipient Name',{exact:true}).fill('Priya');await bp.getByLabel('Certificate Type').selectOption('Best Friend');await bp.getByRole('button',{name:'Generate certificate'}).click();await expect(bp.locator('#downloads')).toBeHidden();await expect(bp.locator('#status')).toContainText('logo could not load');await bp.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));await expect(bp.locator('body')).toHaveClass('brand-unavailable');await blocked.close();
});

test('older backend catalogue still shows one Moment Studio and preserves legacy launches',async({page})=>{const user={id:'owner',name:'Studio Owner',email:'owner@example.com',role:'Owner'},catalog=require('../../../packages/app-registry').apps.find(a=>a.id==='moment-studio'),old={...catalog,id:'certificates',name:'Appreciation Certificate Generator',path:'/certificates',accessible:true};let launch='';await page.route('**/api/auth/status',r=>r.fulfill({json:{user,setupRequired:false}}));await page.route('**/api/platform',r=>r.fulfill({json:{user,apps:[old,{...old,id:'celebration-studio',name:'Celebration Studio',path:'/celebration-studio'}],preferences:{favorites:['certificates','celebration-studio'],recent:[{id:'certificates',at:'2026-10-09'},{id:'celebration-studio',at:'2026-10-08'}]},team:[]}}));await page.route('**/api/platform/apps/*/launch',r=>{launch=r.request().url();return r.fulfill({json:{path:'/certificates'}});});await page.goto(base+'/signin');await expect(page.locator('.app-card')).toHaveCount(1);await expect(page.getByRole('heading',{name:'Moment Studio',exact:true})).toBeVisible();await expect(page.locator('.favorite')).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Open Moment Studio',exact:false}).click();await expect(page).toHaveURL(base+'/moment-studio');expect(launch).toContain('/certificates/launch');await expect(page.locator('#download')).toBeEnabled();});
